import type { LeisureRanking } from "@/lib/types";

const collectedAt = "2026-06-08";

export const niigataLeisureRankings: LeisureRanking[] = [
  {
    slug: "niigata-leisure-best",
    title: "新潟でまず候補に入れたいおすすめレジャースポット",
    description: "県外観光、日帰り、家族利用のどれにも転用しやすい代表スポットを、公式情報の確認しやすさと体験の分かりやすさで整理しました。",
    conclusion: "初回の新潟レジャーなら、絶景は清津峡、市内の雨の日はマリンピア日本海、上越方面はうみがたり、公共系の自然学習ならビュー福島潟や県立植物園が選びやすいです。",
    quickTableLabel: "新潟レジャー主要スポット早見表",
    criteria: [
      "公式・自治体・観光協会ページで基本情報を確認できること",
      "屋外・屋内・複合型のバランスが取れること",
      "県外観光客にも体験内容を説明しやすいこと",
      "家族、カップル、雨の日、車なしなど複数の検索軸に展開できること",
      "営業時間や予約条件の注意点を明記できること",
    ],
    lastUpdatedAt: collectedAt,
    items: [
      { rank: 1, itemSlug: "kiyotsu-gorge-tunnel", score: 94, reason: "新潟の絶景・アート体験として訴求力が強く、県外観光の目的地になりやすい。", isPr: false },
      { rank: 2, itemSlug: "marinepia-nihonkai", score: 91, reason: "新潟市内で屋内・家族・雨の日の検索意図を広く拾える定番施設。", isPr: false },
      { rank: 3, itemSlug: "yuzawa-kogen-panorama-park", score: 89, reason: "越後湯沢駅周辺の旅行導線に組み込みやすく、高原とロープウェイの体験が明確。", isPr: false },
      { rank: 4, itemSlug: "shinano-river-water-shuttle", score: 87, reason: "新潟市中心部の移動と体験を兼ねられ、車なし観光にも使いやすい。", isPr: false },
      { rank: 5, itemSlug: "yahiko-ropeway", score: 86, reason: "彌彦神社や温泉とセットにしやすく、半日から1日の回遊導線を作れる。", isPr: false },
      { rank: 6, itemSlug: "umigatari-joetsu", score: 85, reason: "上越方面の屋内レジャーとして強く、日本海テーマの大型水族博物館を紹介できる。", isPr: false },
      { rank: 7, itemSlug: "niigata-furusato-mura", score: 84, reason: "観光情報、展示、物産、飲食を一か所で回れ、旅程の前後に置きやすい。", isPr: false },
      { rank: 8, itemSlug: "view-fukushimagata", score: 83, reason: "公共系の自然学習スポットとして、屋内展示と福島潟の展望を組み合わせられる。", isPr: false },
    ],
    sources: [
      { title: "清津峡 公式サイト", url: "https://nakasato-kiyotsu.com/", sourceType: "official", collectedAt, note: "清津峡の基本情報確認。" },
      { title: "マリンピア日本海 ご利用案内", url: "https://www.marinepia.or.jp/info/", sourceType: "official", collectedAt, note: "水族館の基本情報確認。" },
      { title: "湯沢高原 料金・営業時間", url: "https://www.yuzawakogen.com/green/tickets/", sourceType: "official", collectedAt, note: "湯沢高原の営業期間・料金確認。" },
      { title: "新潟市観光ガイド 信濃川ウォーターシャトル", url: "https://www.nvcb.or.jp/spot/detail_1158.html", sourceType: "tourism", collectedAt, note: "水上バスの料金・乗船場確認。" },
      { title: "うみがたり 公式サイト", url: "https://www.umigatari.jp/joetsu/", sourceType: "official", collectedAt, note: "上越市立水族博物館の基本情報確認。" },
    ],
    faqs: [
      { question: "このランキングは広告ですか？", answer: "現時点ではPR掲載なしです。公式・自治体・観光協会等の公開情報を元に編集部が整理しています。" },
      { question: "営業時間は保証されていますか？", answer: "営業時間、運行、休館日、予約条件は変更される可能性があります。各スポット詳細の参照元から最新情報を確認してください。" },
    ],
  },
  {
    slug: "niigata-outdoor-leisure",
    title: "新潟のアウトドアレジャーで選びたいスポット",
    description: "渓谷、高原、ロープウェイ、水上バス、公園など、外で過ごす体験を中心に、季節と天候の影響も踏まえて整理します。",
    conclusion: "写真映えと絶景なら清津峡、駅近の高原体験なら湯沢高原、弥彦周辺の半日観光なら弥彦山ロープウェイと弥彦公園、日常的な外遊びなら鳥屋野潟公園が候補です。",
    quickTableLabel: "アウトドアレジャー早見表",
    criteria: ["自然・展望・乗り物など屋外体験が明確", "季節性を説明できる", "移動手段と組み合わせやすい", "家族・カップルどちらにも展開できる"],
    lastUpdatedAt: collectedAt,
    items: [
      { rank: 1, itemSlug: "kiyotsu-gorge-tunnel", score: 94, reason: "自然景観とアートの組み合わせが強く、目的地としての魅力が明確。", isPr: false },
      { rank: 2, itemSlug: "yuzawa-kogen-panorama-park", score: 90, reason: "ロープウェイと高原散策で、越後湯沢旅行に組み込みやすい。", isPr: false },
      { rank: 3, itemSlug: "yahiko-ropeway", score: 88, reason: "弥彦エリアの回遊拠点として使いやすく、展望体験が分かりやすい。", isPr: false },
      { rank: 4, itemSlug: "yahiko-park", score: 87, reason: "駅近で桜・ホタル・紅葉の季節導線を作りやすく、弥彦観光に組み込みやすい。", isPr: false },
      { rank: 5, itemSlug: "echigo-hillside-park", score: 86, reason: "花、遊具、芝生広場、季節イベントがあり、家族の外遊びに向く。", isPr: false },
      { rank: 6, itemSlug: "toyano-sports-park", score: 85, reason: "新潟市中心部で芝生・遊具・自然生態園・スポーツ施設を使い分けられる。", isPr: false },
      { rank: 7, itemSlug: "kodomo-shizen-okoku", score: 84, reason: "子ども向け自然体験、工作、キャンプまで広く、公共系の体験施設として強い。", isPr: false },
      { rank: 8, itemSlug: "shinano-river-water-shuttle", score: 83, reason: "新潟市中心部で水上移動そのものをレジャー化できる。", isPr: false },
    ],
    sources: [
      { title: "清津峡 公式サイト", url: "https://nakasato-kiyotsu.com/", sourceType: "official", collectedAt, note: "屋外・渓谷スポット確認。" },
      { title: "湯沢高原 料金・営業時間", url: "https://www.yuzawakogen.com/green/tickets/", sourceType: "official", collectedAt, note: "高原・ロープウェイ営業情報確認。" },
      { title: "国営越後丘陵公園 公式", url: "https://echigo-park.jp/", sourceType: "official", collectedAt, note: "公園公式情報確認。" },
      { title: "にいがた観光ナビ 弥彦公園", url: "https://niigata-kankou.or.jp/spot/7482", sourceType: "tourism", collectedAt, note: "弥彦公園の基本情報確認。" },
      { title: "新潟県 鳥屋野潟公園", url: "https://www.pref.niigata.lg.jp/sec/toshiseibi/1220551354997.html", sourceType: "government", collectedAt, note: "鳥屋野潟公園の施設概要確認。" },
    ],
    faqs: [
      { question: "アウトドアスポットは冬でも同じように楽しめますか？", answer: "施設により季節営業、整備休業、積雪・天候の影響があります。公式情報の確認が必要です。" },
      { question: "車なしでも行きやすいスポットはありますか？", answer: "湯沢高原や信濃川ウォーターシャトルは、公共交通と組み合わせた導線を作りやすい候補です。" },
    ],
  },
  {
    slug: "niigata-indoor-leisure",
    title: "新潟のインドア・雨の日レジャースポット",
    description: "水族館、科学館、鉄道資料館、物産・展示施設など、天候に左右されにくい屋内中心のスポットを整理します。",
    conclusion: "家族の定番ならマリンピア日本海、上越方面ならうみがたり、学習要素なら自然科学館や県立植物園、日常の雨の日運動ならアクアパークにいがたが選びやすいです。",
    quickTableLabel: "インドアレジャー早見表",
    criteria: ["屋内展示や屋内滞在が中心", "雨の日でも計画しやすい", "料金・休館日を確認しやすい", "子ども連れや短時間利用にも向く"],
    lastUpdatedAt: collectedAt,
    items: [
      { rank: 1, itemSlug: "marinepia-nihonkai", score: 92, reason: "屋内展示が中心で、家族・雨の日・新潟市観光の検索意図を広く拾える。", isPr: false },
      { rank: 2, itemSlug: "umigatari-joetsu", score: 90, reason: "上越方面の大型水族博物館で、雨の日や家族旅行の目的地にしやすい。", isPr: false },
      { rank: 3, itemSlug: "niigata-science-museum", score: 89, reason: "体験型展示とプラネタリウムがあり、学習系レジャーとして強い。", isPr: false },
      { rank: 4, itemSlug: "niigata-botanical-garden", score: 87, reason: "観賞温室と企画展示があり、雨の日でも植物観察をしやすい。", isPr: false },
      { rank: 5, itemSlug: "niitsu-railway-museum", score: 86, reason: "鉄道文化と車両展示で、親子や鉄道好きに刺さるテーマ性がある。", isPr: false },
      { rank: 6, itemSlug: "teradomari-aquarium", score: 85, reason: "寺泊観光と組み合わせやすい公共系の水族博物館として補完性が高い。", isPr: false },
      { rank: 7, itemSlug: "niigata-furusato-mura", score: 84, reason: "展示、物産、飲食がまとまり、旅行前後の立ち寄りにも使いやすい。", isPr: false },
      { rank: 8, itemSlug: "aqua-park-niigata", score: 83, reason: "屋内温水施設として、日常的な雨の日レジャーや運動目的に向く。", isPr: false },
    ],
    sources: [
      { title: "マリンピア日本海 ご利用案内", url: "https://www.marinepia.or.jp/info/", sourceType: "official", collectedAt, note: "水族館の屋内施設・料金・休館日確認。" },
      { title: "新潟県立自然科学館 ご利用案内", url: "https://www.sciencemuseum.jp/guide/", sourceType: "official", collectedAt, note: "科学館の開館時間・料金確認。" },
      { title: "にいがた観光ナビ 新津鉄道資料館", url: "https://niigata-kankou.or.jp/spot/5615", sourceType: "tourism", collectedAt, note: "鉄道資料館の基本情報確認。" },
      { title: "うみがたり 開館時間・料金", url: "https://www.umigatari.jp/en/joetsu/info/", sourceType: "official", collectedAt, note: "上越市立水族博物館の開館時間・料金確認。" },
      { title: "にいがた観光ナビ 新潟県立植物園", url: "https://niigata-kankou.or.jp/spot/5621", sourceType: "tourism", collectedAt, note: "県立植物園の基本情報確認。" },
    ],
    faqs: [
      { question: "雨の日でも完全に濡れずに回れますか？", answer: "屋内中心の施設でも、駐車場から入口、屋外展示、移動時に雨の影響を受ける場合があります。" },
      { question: "小さい子ども連れでも使いやすいですか？", answer: "マリンピア日本海、自然科学館、いくとぴあ食花は子ども連れの候補として整理しやすい施設です。" },
    ],
  },
  {
    slug: "niigata-family-rainyday",
    title: "子連れ・雨の日で選ぶ新潟レジャースポット",
    description: "天候が読みにくい日や、未就学児から小学生までを連れて行きやすいスポットを、屋内比率と滞在しやすさで整理します。",
    conclusion: "雨の日の安定感ならマリンピア日本海・うみがたり・自然科学館、無料入館や短時間利用なら新潟ふるさと村、体を動かすならアクアパークにいがたが候補です。",
    quickTableLabel: "子連れ・雨の日早見表",
    criteria: ["屋内滞在しやすい", "子どもの年齢に合わせて選びやすい", "駐車場情報を確認しやすい", "半日程度の予定に組み込みやすい"],
    lastUpdatedAt: collectedAt,
    items: [
      { rank: 1, itemSlug: "marinepia-nihonkai", score: 92, reason: "水族館は年齢を問わず使いやすく、雨の日でも計画しやすい。", isPr: false },
      { rank: 2, itemSlug: "umigatari-joetsu", score: 91, reason: "上越方面の水族博物館として、親子旅行と雨の日の両方に対応しやすい。", isPr: false },
      { rank: 3, itemSlug: "niigata-science-museum", score: 90, reason: "体験展示とプラネタリウムで、小学生の学習系おでかけに向く。", isPr: false },
      { rank: 4, itemSlug: "ikutopia-shoku-hana", score: 87, reason: "複数施設を年齢や天候に合わせて選べるため、子連れの調整余地が大きい。", isPr: false },
      { rank: 5, itemSlug: "niigata-botanical-garden", score: 86, reason: "観賞温室があり、植物観察や自由研究の目的を作りやすい。", isPr: false },
      { rank: 6, itemSlug: "niigata-furusato-mura", score: 85, reason: "入館無料で、展示・物産・飲食をまとめられるため短時間でも使いやすい。", isPr: false },
      { rank: 7, itemSlug: "aqua-park-niigata", score: 84, reason: "屋内温水施設として、雨の日に体を動かす候補になる。", isPr: false },
      { rank: 8, itemSlug: "niitsu-railway-museum", score: 83, reason: "鉄道好きの子どもには目的性が高く、屋内外展示の組み合わせもある。", isPr: false },
      { rank: 9, itemSlug: "view-fukushimagata", score: 82, reason: "展望・映像展示で自然学習ができ、福島潟の屋外観察にもつなげやすい。", isPr: false },
    ],
    sources: [
      { title: "マリンピア日本海 ご利用案内", url: "https://www.marinepia.or.jp/info/", sourceType: "official", collectedAt, note: "家族向け料金・開館情報確認。" },
      { title: "新潟県立自然科学館 ご利用案内", url: "https://www.sciencemuseum.jp/guide/", sourceType: "official", collectedAt, note: "料金、駐車場、開館情報確認。" },
      { title: "いくとぴあ食花 公式", url: "https://www.ikutopia.com/", sourceType: "official", collectedAt, note: "複合施設の営業時間・駐車場確認。" },
      { title: "うみがたり 開館時間・料金", url: "https://www.umigatari.jp/en/joetsu/info/", sourceType: "official", collectedAt, note: "上越市立水族博物館の開館時間・料金確認。" },
      { title: "アクアパークにいがた", url: "https://niigata-kankou.or.jp/spot/11337", sourceType: "tourism", collectedAt, note: "屋内温水施設の基本情報確認。" },
    ],
    faqs: [
      { question: "未就学児でも楽しめる候補はありますか？", answer: "マリンピア日本海、いくとぴあ食花、新潟ふるさと村は未就学児連れでも検討しやすい候補です。" },
      { question: "雨の日だけでなく晴れの日も使えますか？", answer: "屋内中心の施設に加え、いくとぴあ食花や越後丘陵公園のように屋外要素を持つ施設もあります。" },
    ],
  },
];
