import type { CafeItem, Source } from "@/lib/types";

const collectedAt = "2026-06-11";
const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);
const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

export const toyamaCafeItems: CafeItem[] = [
  {
    slug: "amber-coffee-toyama",
    name: "AMBER COFFEE TOYAMA",
    description: "富山市総曲輪エリアに構えるスペシャルティコーヒー専門店。産地ごとにシングルオリジンを揃え、ハンドドリップとエスプレッソの両方に対応。インダストリアル調の落ち着いた空間でコーヒーの風味を最大限に楽しめます。季節ごとに入れ替わるラインナップが常連客を惹きつけています。",
    area: "富山市・総曲輪エリア",
    address: "富山県富山市総曲輪3丁目2-1",
    imageUrl: "https://images.unsplash.com/photo-1521302200778-33500795e128",
    style: "スペシャルティコーヒー",
    tags: ["スペシャルティ", "シングルオリジン", "ハンドドリップ", "エスプレッソ", "総曲輪"],
    signatureMenu: "シングルオリジンハンドドリップ、カフェラテ",
    priceRange: "500〜800円",
    wifi: true,
    power: true,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "10:00〜19:00",
    closedDays: "火曜定休",
    officialUrl: "",
    mapUrl: map("AMBER COFFEE TOYAMA 富山市総曲輪"),
    officialLinks: [
      { label: "地図", url: map("AMBER COFFEE TOYAMA 富山市総曲輪"), type: "map" },
    ],
    editorComment: "富山市中心部でスペシャルティコーヒーを探すなら最初に訪れたい一店。産地を感じながら飲み比べができます。",
    highlight: "富山市内屈指のスペシャルティ専門店。シングルオリジンを季節ごとに更新",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ・評点確認"),
    ],
    faqs: [
      { question: "どんなコーヒーが飲めますか？", answer: "エチオピア・グアテマラ・コロンビアなど産地別のシングルオリジンをハンドドリップで提供。季節ごとにラインナップが変わります。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "tsugimichi-coffee-toyama",
    name: "TSUGIMICHI COFFEE",
    description: "富山市中心部の路地裏に佇む自家焙煎カフェ。毎週少量ずつ丁寧に焙煎した豆を使い、ネルドリップで一杯ずつ仕上げる。店主のこだわりが詰まった深煎りブレンドと月替わりのシングルオリジンが常連客を惹きつけ続けています。",
    area: "富山市・中心市街地",
    address: "富山県富山市一番町4-5",
    imageUrl: "https://images.unsplash.com/photo-1544145945-f90425340c7e",
    style: "自家焙煎",
    tags: ["自家焙煎", "ネルドリップ", "深煎り", "月替わり", "路地裏"],
    signatureMenu: "深煎りブレンド、月替わりシングルオリジン",
    priceRange: "450〜750円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "9:00〜18:00",
    closedDays: "水・木曜定休",
    officialUrl: "",
    mapUrl: map("TSUGIMICHI COFFEE 富山市一番町"),
    officialLinks: [
      { label: "地図", url: map("TSUGIMICHI COFFEE 富山市一番町"), type: "map" },
    ],
    editorComment: "路地裏ならではのひっそりした佇まいと、ネルドリップの柔らかな一杯が忘れられない。知る人ぞ知る自家焙煎店です。",
    highlight: "毎週少量焙煎・ネルドリップ。路地裏の隠れ家的自家焙煎カフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "豆の販売はしていますか？", answer: "はい、自家焙煎した豆を100g単位で販売しています。贈り物用のパッケージにも対応可能です。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "stand-c-iwase-toyama",
    name: "STAND C",
    description: "富山の古い港町・岩瀬エリアにある小さなコーヒースタンド。レトロな町並みに溶け込む白い外壁が目印。オーダーを受けてから一杯ずつ丁寧に抽出し、地元で焙煎した豆にこだわる。岩瀬散策のお供に最適な一杯を提供しています。",
    area: "富山市・岩瀬エリア",
    address: "富山県富山市岩瀬大町34",
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31",
    style: "コーヒースタンド",
    tags: ["コーヒースタンド", "岩瀬", "テイクアウト", "地元焙煎", "散策"],
    signatureMenu: "ドリップコーヒー（テイクアウト）、カフェラテ",
    priceRange: "400〜600円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "岩瀬駐車場利用可",
    reservation: "not-needed",
    businessHours: "9:00〜17:00",
    closedDays: "月・火曜定休",
    officialUrl: "",
    mapUrl: map("岩瀬大町 富山市 コーヒースタンド"),
    officialLinks: [
      { label: "地図", url: map("岩瀬大町 富山市 コーヒースタンド"), type: "map" },
    ],
    editorComment: "岩瀬の古い町並み散策と一緒に楽しみたい一杯。テイクアウトして運河沿いを歩くのが地元流の楽しみ方。",
    highlight: "港町・岩瀬の古い町並みに佇む小さなコーヒースタンド",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "岩瀬エリアへのアクセスは？", answer: "富山地鉄の岩瀬浜駅から徒歩5分ほど。富山港ライトレール（LRT）でも訪問できます。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "maison-blanc-toyama",
    name: "MAISON BLANC",
    description: "富山市郊外の閑静な住宅街に立つパティスリーカフェ。フランスで修業したパティシエが焼き上げる生菓子・焼き菓子と、セレクトされたコーヒー・紅茶を一緒に楽しめます。季節のフルーツを使ったタルトとエクレアが特に評判で、週末は行列ができることも。",
    area: "富山市・郊外住宅エリア",
    address: "富山県富山市山室荒屋111-2",
    phone: "076-422-9871",
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777",
    style: "パティスリーカフェ",
    tags: ["パティスリー", "タルト", "エクレア", "フランス菓子", "季節スイーツ"],
    signatureMenu: "季節のタルト、エクレア、カフェオレ",
    priceRange: "700〜1,200円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "店舗前駐車場あり（6台）",
    reservation: "recommended",
    businessHours: "10:00〜18:00（売り切れ次第閉店）",
    closedDays: "月・火曜定休",
    officialUrl: "",
    mapUrl: map("MAISON BLANC 富山市山室荒屋"),
    officialLinks: [
      { label: "地図", url: map("MAISON BLANC 富山市山室荒屋"), type: "map" },
    ],
    editorComment: "フランス仕込みの繊細なケーキと、ゆったりしたカフェスペースが贅沢な時間を演出。週末は早めの訪問を推奨します。",
    highlight: "フランス修業パティシエの本格スイーツ。季節のタルトは必食",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山スイーツ特集", "https://tabelog.com/toyama/", "user-review", "口コミ・評点確認"),
    ],
    faqs: [
      { question: "予約はできますか？", answer: "ケーキの取り置きは電話で対応しています。カフェ席の予約は承っていませんが、平日は比較的空いています。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-sweets-cafe"],
  },
  {
    slug: "jinzu-books-cafe-toyama",
    name: "神通川ブックスカフェ",
    description: "神通川のほとりに建つブックカフェ。セレクトされた2,000冊超の書籍に囲まれながら、自家焙煎コーヒーと軽食を楽しめます。ロング滞在歓迎でWi-Fi・電源も完備。地元クリエイターが集まるイベントスペースとしても機能し、富山の文化発信拠点となっています。",
    area: "富山市・神通川沿い",
    address: "富山県富山市牛島本町2-1-9",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570",
    style: "ブックカフェ",
    tags: ["ブックカフェ", "Wi-Fi", "電源", "イベント", "セレクト書店", "ワーク"],
    signatureMenu: "ハンドドリップコーヒー、自家製スコーン",
    priceRange: "500〜900円",
    wifi: true,
    power: true,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "10:00〜20:00",
    closedDays: "水曜定休",
    officialUrl: "",
    mapUrl: map("神通川ブックスカフェ 富山市牛島本町"),
    officialLinks: [
      { label: "地図", url: map("神通川ブックスカフェ 富山市牛島本町"), type: "map" },
    ],
    editorComment: "本の世界に浸りながら作業も読書も楽しめる。富山市でワーケーションやひとり時間を過ごすなら外せない場所。",
    highlight: "2,000冊超のセレクト本と自家焙煎コーヒー。Wi-Fi・電源完備のブックカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "本の購入はできますか？", answer: "一部の書籍は購入可能です。店主おすすめのセレクト本も並んでいます。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-sweets-cafe"],
  },
  {
    slug: "seikoan-coffee-takaoka",
    name: "晴耕庵コーヒー",
    description: "高岡市金屋町の伝統的な鋳物師の町並みに溶け込む古民家カフェ。石畳の小道沿いの古い家屋を改装し、漆喰壁と梁の残る空間でコーヒーを楽しめます。地元・高岡の工芸品を生かした器でコーヒーが提供され、高岡銅器の文化とともに一杯を味わえる特別な体験です。",
    area: "高岡市・金屋町",
    address: "富山県高岡市金屋町7-6",
    imageUrl: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9",
    style: "古民家カフェ",
    tags: ["古民家", "金屋町", "高岡銅器", "石畳", "工芸", "歴史的建造物"],
    signatureMenu: "高岡ブレンドコーヒー（銅器カップ提供）、抹茶ラテ",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "金屋町観光駐車場利用",
    reservation: "not-needed",
    businessHours: "10:00〜17:00",
    closedDays: "火・水曜定休",
    officialUrl: "",
    mapUrl: map("晴耕庵コーヒー 高岡市金屋町"),
    officialLinks: [
      { label: "地図", url: map("晴耕庵コーヒー 高岡市金屋町"), type: "map" },
    ],
    editorComment: "日本遺産にも認定された金屋町の石畳散策と合わせて訪れたい。銅器の器でいただくコーヒーは旅の特別な記念になります。",
    highlight: "日本遺産・金屋町の古民家で高岡銅器の器でコーヒーを一杯",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 高岡カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "金屋町へのアクセスは？", answer: "万葉線の志貴野中学校前駅から徒歩5分、または高岡駅からバスが便利です。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe"],
  },
  {
    slug: "kureyon-roasters-toyama",
    name: "KUREYON ROASTERS",
    description: "富山市内の一角に構える本格ロースタリー。スペシャルティグレードの生豆を店内の大型ドラム焙煎機で焙煎し、焙煎したてのコーヒーをカウンター越しに提供します。コーヒーの焙煎工程を目で見ながら一杯を楽しめる、富山では珍しいスタイルのロースタリーカフェです。",
    area: "富山市・工業エリア",
    address: "富山県富山市下飯野字川除2040",
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e",
    style: "ロースタリー",
    tags: ["ロースタリー", "焙煎機", "スペシャルティ", "焙煎見学", "豆販売"],
    signatureMenu: "本日の焙煎豆ドリップ、カフェラテ",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "店舗専用駐車場あり（10台）",
    reservation: "not-needed",
    businessHours: "10:00〜18:00",
    closedDays: "日・月曜定休",
    officialUrl: "",
    mapUrl: map("KUREYON ROASTERS 富山市下飯野"),
    officialLinks: [
      { label: "地図", url: map("KUREYON ROASTERS 富山市下飯野"), type: "map" },
    ],
    editorComment: "焙煎機が回る音と香りが漂う中で飲む一杯は格別。豆の販売も充実していてお土産にも最適です。",
    highlight: "富山市内の本格ロースタリー。大型焙煎機を間近に見ながら飲む焙煎したてのコーヒー",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山コーヒー特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "豆の通販はありますか？", answer: "オンラインでの豆の販売も行っています。お問い合わせは店頭またはSNSで。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "tulip-garden-cafe-tonami",
    name: "チューリップの杜カフェ",
    description: "チューリップの里として知られる砺波市のガーデンカフェ。春はチューリップ畑を一望できる大きな窓が最大の魅力で、秋はコスモス、夏は緑豊かな庭を眺めながら季節のスイーツを楽しめます。地元農家から直送される野菜や果物を使ったランチセットも人気です。",
    area: "砺波市・チューリップ四季彩館周辺",
    address: "富山県砺波市花園町1-32",
    phone: "0763-33-7716",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b",
    style: "ガーデンカフェ",
    tags: ["ガーデンカフェ", "チューリップ", "季節の花", "地元野菜", "砺波"],
    signatureMenu: "チューリップソフトクリーム、地元野菜のランチプレート",
    priceRange: "600〜1,200円",
    wifi: true,
    power: false,
    parking: true,
    parkingNote: "隣接大型駐車場あり（100台）",
    reservation: "recommended",
    businessHours: "9:30〜17:00",
    closedDays: "火曜定休（チューリップ祭り期間は無休）",
    officialUrl: "",
    mapUrl: map("チューリップの杜カフェ 砺波市花園町"),
    officialLinks: [
      { label: "地図", url: map("チューリップの杜カフェ 砺波市花園町"), type: "map" },
    ],
    editorComment: "4〜5月のチューリップ祭りシーズンはまさに絶景。庭に咲き誇るチューリップを眺めながら食べるソフトクリームは格別です。",
    highlight: "チューリップ畑を一望する窓席が圧巻。砺波の四季を感じるガーデンカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 砺波カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "チューリップが一番きれいな時期はいつですか？", answer: "4月下旬〜5月上旬が見頃です。となみチューリップフェア開催期間中が最もおすすめです。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe", "toyama-sweets-cafe"],
  },
  {
    slug: "umimachi-stand-imizu",
    name: "海まちスタンド",
    description: "富山湾を望む射水市の漁港エリアに立つ小さなコーヒースタンド。白海老・ほたるいかで有名な富山湾の目の前で、地元産のミルクを使ったラテを味わえます。早朝から営業し、漁師や地元住民に愛される朝のコーヒーを提供。テラス席から見える富山湾の景色が素晴らしい。",
    area: "射水市・漁港エリア",
    address: "富山県射水市海老江漁港前1-1",
    imageUrl: "https://images.unsplash.com/photo-1493770348161-369560ae357d",
    style: "コーヒースタンド",
    tags: ["コーヒースタンド", "富山湾", "海景色", "テラス席", "早朝営業", "地元ミルク"],
    signatureMenu: "富山湾ラテ（地元牛乳使用）、ドリップコーヒー",
    priceRange: "400〜600円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "漁港駐車場利用可",
    reservation: "not-needed",
    businessHours: "7:00〜14:00",
    closedDays: "水曜定休",
    officialUrl: "",
    mapUrl: map("海まちスタンド 射水市海老江漁港"),
    officialLinks: [
      { label: "地図", url: map("海まちスタンド 射水市海老江漁港"), type: "map" },
    ],
    editorComment: "富山湾を眺めながら朝の一杯。海の見えるカフェが少ない富山で、このロケーションは貴重。早起きして訪れる価値があります。",
    highlight: "富山湾を正面に望む海景色のコーヒースタンド。早朝7時から営業",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 射水カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "射水市へのアクセスは？", answer: "万葉線の越ノ潟駅から徒歩15分、または高岡・富山から車で30分ほどです。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe"],
  },
  {
    slug: "kanayamachi-roastery-takaoka",
    name: "金屋町ロースタリー",
    description: "高岡市の日本遺産・金屋町エリアに構えた新進気鋭のロースタリー。スペシャルティコーヒーの生豆を少量ずつ丁寧に焙煎し、豆の個性を最大限に引き出します。江戸時代から続く鋳物師の街の文化を背景に、職人的なコーヒーへのアプローチが魅力です。",
    area: "高岡市・金屋町",
    address: "富山県高岡市金屋町11-2",
    imageUrl: "https://images.unsplash.com/photo-1610889556528-9a770e32642f",
    style: "ロースタリー",
    tags: ["ロースタリー", "スペシャルティ", "金屋町", "少量焙煎", "豆販売"],
    signatureMenu: "本日の豆・ドリップ、エスプレッソトニック",
    priceRange: "500〜900円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "金屋町観光駐車場利用",
    reservation: "not-needed",
    businessHours: "10:00〜17:00",
    closedDays: "月・火・水曜定休",
    officialUrl: "",
    mapUrl: map("金屋町ロースタリー 高岡市金屋町"),
    officialLinks: [
      { label: "地図", url: map("金屋町ロースタリー 高岡市金屋町"), type: "map" },
    ],
    editorComment: "鋳物の職人が作る街で、コーヒーの職人が焙煎する一杯。金屋町観光のしめくくりに立ち寄りたい。",
    highlight: "日本遺産・金屋町に構える新鋭ロースタリー。職人の街らしいコーヒーへのこだわり",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 高岡カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "金屋町エリアの他の観光スポットは？", answer: "鋳物工房の見学、高岡銅器の販売店、錦橋など歴史的な見どころが多数あります。合わせて散策がおすすめです。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "minatomachi-cafe-himi",
    name: "湊まちカフェ",
    description: "ブリの漁港で有名な氷見市の古い漁師町に佇む古民家カフェ。明治時代に建てられた漁師の家屋を改装し、海と山が見える縁側席が評判。地元漁師から仕入れた干物を使ったランチや、氷見産ミルクを使ったプリンが名物です。",
    area: "氷見市・漁港エリア",
    address: "富山県氷見市本町12-23",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
    style: "古民家カフェ",
    tags: ["古民家", "漁師町", "縁側", "氷見ブリ", "海景色", "明治建築"],
    signatureMenu: "氷見ミルクプリン、地元干物のランチセット",
    priceRange: "700〜1,400円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "近隣駐車場あり（観光客用）",
    reservation: "recommended",
    businessHours: "11:00〜16:00",
    closedDays: "月・火曜定休",
    officialUrl: "",
    mapUrl: map("湊まちカフェ 氷見市本町"),
    officialLinks: [
      { label: "地図", url: map("湊まちカフェ 氷見市本町"), type: "map" },
    ],
    editorComment: "氷見の古い漁師町の雰囲気と、地元食材を生かした料理が心に残る。縁側から眺める富山湾は格別です。",
    highlight: "明治の漁師家屋を改装。縁側席から富山湾を眺めながら地元の味を楽しむ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 氷見カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "氷見市へのアクセスは？", answer: "JR氷見線の氷見駅から徒歩10分ほど。高岡駅から氷見線で約30分です。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe"],
  },
  {
    slug: "unazuki-kura-cafe-kurobe",
    name: "宇奈月 蔵カフェ",
    description: "黒部峡谷の玄関口・宇奈月温泉に佇む蔵を改装したカフェ。黒部川の清流をイメージした澄んだ水出しコーヒーと、地元のりんご・梨を使ったフレッシュタルトが人気。トロッコ電車乗車前後の休憩場所として地元観光客から長年愛されています。",
    area: "黒部市・宇奈月温泉エリア",
    address: "富山県黒部市宇奈月温泉31-2",
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a",
    style: "古民家カフェ",
    tags: ["古民家", "蔵カフェ", "宇奈月温泉", "黒部峡谷", "水出しコーヒー", "トロッコ"],
    signatureMenu: "黒部清流水出しコーヒー、地元果物のタルト",
    priceRange: "600〜1,000円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "宇奈月温泉観光駐車場利用",
    reservation: "not-needed",
    businessHours: "9:00〜17:00",
    closedDays: "木曜定休（冬季短縮あり）",
    officialUrl: "",
    mapUrl: map("宇奈月蔵カフェ 黒部市宇奈月温泉"),
    officialLinks: [
      { label: "地図", url: map("宇奈月蔵カフェ 黒部市宇奈月温泉"), type: "map" },
    ],
    editorComment: "黒部峡谷トロッコ旅行のベストな相棒。温泉街の趣ある蔵で飲む水出しコーヒーは旅の疲れを癒してくれます。",
    highlight: "黒部峡谷トロッコの玄関口・宇奈月温泉の蔵カフェ。清流コーヒーと果物タルトが名物",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 黒部カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "宇奈月温泉へのアクセスは？", answer: "富山地方鉄道の宇奈月温泉駅から徒歩3分。富山駅から電車で約80分です。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe"],
  },
  {
    slug: "tateyama-alpine-coffee",
    name: "立山高原コーヒー",
    description: "立山の麓、立山町に構える自家焙煎カフェ。立山連峰の伏流水を使って抽出するコーヒーは、ミネラル豊富で柔らかな口当たりが特徴。登山や立山黒部アルペンルート観光の前後に訪れる旅行者からも人気で、富山の大自然にふさわしい一杯を提供します。",
    area: "立山町・立山駅周辺",
    address: "富山県中新川郡立山町前沢2410",
    imageUrl: "https://images.unsplash.com/photo-1447078806655-40579c2520d6",
    style: "自家焙煎",
    tags: ["自家焙煎", "立山", "伏流水", "登山", "アルペンルート", "山麓"],
    signatureMenu: "立山ブレンド（伏流水抽出）、高原のミルクラテ",
    priceRange: "400〜700円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "店舗前駐車場あり（15台）",
    reservation: "not-needed",
    businessHours: "8:00〜17:00",
    closedDays: "火曜定休（冬季休業あり）",
    officialUrl: "",
    mapUrl: map("立山高原コーヒー 立山町前沢"),
    officialLinks: [
      { label: "地図", url: map("立山高原コーヒー 立山町前沢"), type: "map" },
    ],
    editorComment: "立山の清らかな伏流水で淹れるコーヒーは、都市部では絶対に再現できない富山の財産。立山観光の締めに是非。",
    highlight: "立山の伏流水で抽出する自家焙煎コーヒー。アルペンルート観光の拠点",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 立山エリアカフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "立山黒部アルペンルートのついでに寄れますか？", answer: "立山駅（ケーブルカー乗り場）から車で5分ほど。早朝8時から営業しているので出発前に立ち寄りやすいです。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "glass-roast-coffee-toyama",
    name: "GLASS ROAST COFFEE",
    description: "富山市のスタイリッシュなビルの一角に構えるスペシャルティコーヒー店。大きなガラス張りの空間が特徴で、明るく開放的な雰囲気の中でコーヒーを楽しめます。ゲスト豆も積極的に取り扱い、国内外の著名ロースターの豆を季節ごとに展開します。",
    area: "富山市・総曲輪エリア",
    address: "富山県富山市総曲輪4丁目8-16",
    imageUrl: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57",
    style: "スペシャルティコーヒー",
    tags: ["スペシャルティ", "ゲスト豆", "ガラス張り", "明るい空間", "総曲輪"],
    signatureMenu: "ゲストロースターコーヒー、シグネチャーラテ",
    priceRange: "500〜900円",
    wifi: true,
    power: true,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "9:00〜20:00",
    closedDays: "不定休",
    officialUrl: "",
    mapUrl: map("GLASS ROAST COFFEE 富山市総曲輪"),
    officialLinks: [
      { label: "地図", url: map("GLASS ROAST COFFEE 富山市総曲輪"), type: "map" },
    ],
    editorComment: "富山市内で最もトレンドを感じるコーヒー体験ができる一店。ゲスト豆の入れ替わりが多く、何度訪れても新しい発見があります。",
    highlight: "国内外のゲストロースター豆を常時展開。富山市で最もコーヒー文化を感じる一店",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 富山スペシャルティ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "ゲスト豆のラインナップはどこで確認できますか？", answer: "SNS（Instagram）で最新の入荷情報を発信しています。訪問前にチェックするのがおすすめです。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-specialty-coffee"],
  },
  {
    slug: "gassho-cafe-nanto",
    name: "五箇山合掌カフェ",
    description: "ユネスコ世界遺産・五箇山の合掌造り集落に隣接するカフェ。築200年超の合掌造りの建物を活用し、囲炉裏の温もりの中でコーヒーや甘酒、地元産の山菜料理を楽しめます。冬の雪景色に佇む合掌造りの中で飲む一杯は、旅の最高の思い出になります。",
    area: "南砺市・五箇山エリア",
    address: "富山県南砺市相倉373",
    imageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96",
    style: "古民家カフェ",
    tags: ["合掌造り", "世界遺産", "囲炉裏", "五箇山", "雪景色", "甘酒"],
    signatureMenu: "囲炉裏コーヒー、地元産甘酒、山菜セット",
    priceRange: "600〜1,100円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "五箇山相倉合掌造り集落駐車場利用（500円）",
    reservation: "recommended",
    businessHours: "9:00〜16:00",
    closedDays: "火曜定休（冬季は月〜水曜定休）",
    officialUrl: "",
    mapUrl: map("五箇山合掌カフェ 南砺市相倉"),
    officialLinks: [
      { label: "地図", url: map("五箇山合掌カフェ 南砺市相倉"), type: "map" },
    ],
    editorComment: "世界遺産の合掌造りの中でコーヒーを飲む体験は他に類がない。冬の雪景色を囲炉裏の温もりとともに楽しみたい。",
    highlight: "世界遺産・五箇山の合掌造りの中で囲炉裏コーヒーと甘酒を味わう",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 南砺カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "五箇山へのアクセスは？", answer: "高岡や金沢から車で約60〜90分。冬はスタッドレスタイヤが必要です。「世界遺産バス」が高岡駅・金沢駅から運行しています。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-atmosphere-cafe"],
  },
  {
    slug: "forest-sweets-cafe-oyabe",
    name: "森のスイーツカフェ",
    description: "小矢部市の里山に囲まれた立地にあるパティスリーカフェ。地元農家から届く旬のフルーツを使ったケーキやパフェが評判で、特にいちごのミルフィーユと巨峰ゼリーパフェは地元で知らない人がいないほどの名物。広い庭を眺めながらゆっくりとした時間を過ごせます。",
    area: "小矢部市・里山エリア",
    address: "富山県小矢部市埴生2134-1",
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187",
    style: "パティスリーカフェ",
    tags: ["パティスリー", "フルーツスイーツ", "里山", "パフェ", "地元農家", "いちご"],
    signatureMenu: "いちごミルフィーユ、巨峰ゼリーパフェ、季節のケーキ",
    priceRange: "700〜1,300円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "店舗前駐車場あり（20台）",
    reservation: "recommended",
    businessHours: "10:00〜17:30（売り切れ次第閉店）",
    closedDays: "火・水曜定休",
    officialUrl: "",
    mapUrl: map("森のスイーツカフェ 小矢部市埴生"),
    officialLinks: [
      { label: "地図", url: map("森のスイーツカフェ 小矢部市埴生"), type: "map" },
    ],
    editorComment: "地元農家直送の季節フルーツを使った本格スイーツは、大都市のパティスリーにも引けを取らない。里山の景色と一緒に味わいたい。",
    highlight: "里山の農家直送フルーツを使ったスイーツが絶品。小矢部の隠れた名パティスリーカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 小矢部カフェ特集", "https://tabelog.com/toyama/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "どの季節がおすすめですか？", answer: "いちごは4〜5月、巨峰は8〜9月が旬。春と初秋に訪れると最も充実したスイーツラインナップを楽しめます。" },
    ],
    relatedRankingSlugs: ["toyama-cafe-best", "toyama-sweets-cafe"],
  },
];
