import type { ProteinTargetInfo } from "@/lib/types";

export const proteinTargets: ProteinTargetInfo[] = [
  {
    slug: "women",
    name: "女性向け",
    description: "ダイエット・美容・健康維持を目的とした女性のためのプロテイン選び。低カロリー・飲みやすさ・人工甘味料不使用を重視した選定。",
    tagline: "ダイエット・美容・健康維持に。女性が選ぶプロテインガイド",
    imageUrl: "https://images.unsplash.com/photo-1571019613576-2b22c76fd955?w=800&q=80",
    keyNeeds: ["低カロリー・低脂質", "飲みやすい味", "人工甘味料が気になる", "美容・肌ケアとの両立", "置き換えダイエットに使いたい"],
    proteinPerDay: "体重×0.8〜1.2g（運動している場合は体重×1.2〜1.6g）",
    recommendedTypes: ["whey-wpc", "whey-wpi", "soy"],
    status: "live",
  },
  {
    slug: "men",
    name: "男性向け",
    description: "筋肥大・体力向上を目的とした男性のためのプロテイン選び。タンパク質量・コスパ・飲みやすさを総合評価。",
    tagline: "筋肥大・体力向上に。男性が選ぶプロテインガイド",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
    keyNeeds: ["1食あたりのタンパク質量が多い", "コスパが良い", "トレーニング後すぐ飲める溶けやすさ", "毎日継続できる味", "大容量で買いやすい"],
    proteinPerDay: "体重×1.2〜2.0g（筋トレ強度によって変動）",
    recommendedTypes: ["whey-wpc", "whey-wpi"],
    status: "live",
  },
  {
    slug: "trainer",
    name: "トレーナー・上級者向け",
    description: "競技パフォーマンス・体組成管理を追求するトレーナー・アスリートのためのプロテイン選び。成分の純度・WPI配合を重視。",
    tagline: "競技パフォーマンスと体組成管理に。上級者が選ぶプロテインガイド",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80",
    keyNeeds: ["WPI（アイソレート）で高純度", "脂質・炭水化物を極限まで抑えたい", "大量摂取でもコスト管理できる", "成分の透明性・信頼性", "BCAAs含有量が高い"],
    proteinPerDay: "体重×1.8〜2.2g（競技・目的により個人差大）",
    recommendedTypes: ["whey-wpi", "whey-wpc"],
    status: "live",
  },
  {
    slug: "student",
    name: "大学生向け",
    description: "コスパ最優先で毎日続けたい学生のためのプロテイン選び。大容量・低価格・入手しやすさで選定。",
    tagline: "コスパ重視で毎日続ける。学生が選ぶプロテインガイド",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    keyNeeds: ["1kgあたりの価格が安い", "大容量で長持ち", "ネット・コンビニで手軽に買える", "飲みやすい味", "初めてでも選びやすい"],
    proteinPerDay: "体重×1.2〜1.6g（運動習慣のある場合）",
    recommendedTypes: ["whey-wpc"],
    status: "live",
  },
  {
    slug: "diet",
    name: "ダイエット向け",
    description: "脂質・糖質を抑えながら筋肉を維持したい方のためのプロテイン選び。低カロリー・満腹感・置き換えに特化。",
    tagline: "脂質・糖質を抑えて筋肉を守る。ダイエットに選ぶプロテインガイド",
    imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    keyNeeds: ["低カロリー（100kcal以下/食が理想）", "低脂質・低糖質", "満腹感が続く", "置き換え食として使える", "美味しく継続できる"],
    proteinPerDay: "体重×1.0〜1.5g（減量中は筋肉維持のため十分に摂取）",
    recommendedTypes: ["whey-wpi", "whey-wpc"],
    status: "live",
  },
  {
    slug: "beginner",
    name: "初心者向け",
    description: "プロテイン初体験の方のための選び方ガイド。失敗しにくい選び方・飲み方・量の目安を整理。",
    tagline: "はじめてのプロテインを失敗なく選ぶガイド",
    imageUrl: "https://images.unsplash.com/photo-1544991936-9464fa430d54?w=800&q=80",
    keyNeeds: ["どれを選べばいいかわからない", "まず試せる少量・安価なものから", "飲みやすい・溶けやすい", "コンビニ・ドラッグストアで買える", "添加物が少ないと安心"],
    proteinPerDay: "まずは1日1回（20〜30g程度）から始める",
    recommendedTypes: ["whey-wpc"],
    status: "live",
  },
];
