import type { TravelAgency } from "@/lib/types";

const verifiedAt = "2026-06-14";

export const niigataTravelAgencies: TravelAgency[] = [
  {
    slug: "niigata-travel",
    name: "新潟トラベル",
    tagline: "県内複数拠点で個人旅行から団体旅行まで相談しやすい総合型",
    description: "新潟市に本社を置き、三条・長岡・上越にも拠点を持つ旅行会社。国内外の個人・家族旅行、団体旅行、JR券・航空券、宿泊、バス手配まで幅広く扱います。",
    area: "新潟市・三条・長岡・上越",
    address: "新潟県新潟市中央区笹口2-12-3",
    phone: "025-243-6543",
    services: ["国内旅行", "海外旅行", "団体旅行", "宿泊手配", "航空券", "JR券", "バスツアー"],
    bestFor: ["新潟県内で対面相談したい", "家族旅行と団体旅行を同じ窓口で相談したい", "JR券・航空券も含めてまとめたい"],
    tags: ["総合旅行会社", "県内複数拠点", "団体旅行", "個人旅行", "JATA"],
    priceRange: "相談内容により見積もり",
    consultationStyle: "店舗・電話で相談。県内複数営業所あり。",
    businessHours: "店舗により異なるため公式サイトで確認",
    closedDays: "店舗により異なるため公式サイトで確認",
    registeredTravelAgency: "観光庁長官登録旅行業第207号",
    officialUrl: "https://www.nts-kij.co.jp/",
    mapUrl: "https://maps.google.com/?q=新潟県新潟市中央区笹口2-12-3",
    officialLinks: [
      { label: "公式サイト", url: "https://www.nts-kij.co.jp/", type: "website" },
      { label: "会社概要", url: "https://www.nts-kij.co.jp/company/", type: "website" },
      { label: "店舗案内", url: "https://www.nts-kij.co.jp/office/", type: "website" },
      { label: "ツアー検索", url: "https://www.nts-kij.co.jp/tour/", type: "website" },
    ],
    editorComment: "県内の営業所網と旅行業登録の強さがあり、初めて地元旅行会社に相談する人にも入りやすい。個人旅行から団体旅行まで守備範囲が広いのが強み。",
    highlight: "新潟・三条・長岡・上越の相談導線があり、旅行手配をまとめたい人に向く。",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "新潟トラベル 公式サイト", url: "https://www.nts-kij.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行商品・会社導線を確認。" },
      { title: "新潟トラベル 会社概要", url: "https://www.nts-kij.co.jp/company/", sourceType: "official", collectedAt: verifiedAt, note: "所在地・電話・旅行業登録・加盟団体を確認。" },
      { title: "新潟トラベル 店舗案内", url: "https://www.nts-kij.co.jp/office/", sourceType: "official", collectedAt: verifiedAt, note: "新潟、三条、長岡、上越などの拠点を確認。" },
    ],
    faqs: [
      { question: "新潟トラベルはどんな相談に向いていますか？", answer: "県内で対面相談しながら、国内旅行・海外旅行・団体旅行・JR券・航空券・宿泊をまとめたい場合に向いています。" },
      { question: "県内のどこで相談できますか？", answer: "公式サイト上では新潟、三条、長岡、上越などの営業所導線が確認できます。来店前に各店舗の営業時間を確認してください。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "humming-tour",
    name: "ハミングツアー",
    tagline: "花旅・山旅・クルーズなどテーマ型ツアーが見つけやすい",
    description: "新潟発着の国内旅行、海外旅行、クルーズ、山旅、花旅などテーマ性のあるツアーを展開。公式サイトでおすすめコースや特集が継続的に更新されています。",
    area: "新潟市・下越",
    address: "新潟県新潟市周辺",
    services: ["国内旅行", "海外旅行", "バスツアー", "団体旅行"],
    bestFor: ["テーマのある募集型ツアーを探したい", "山旅・花旅・クルーズを見たい", "新潟発着の企画旅行を比較したい"],
    tags: ["募集型ツアー", "花旅", "山旅", "クルーズ", "新潟発着"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイト・電話・営業所で相談。",
    businessHours: "営業所により異なるため公式サイトで確認",
    closedDays: "営業所により異なるため公式サイトで確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.humming-tour.jp/",
    mapUrl: "https://maps.google.com/?q=ハミングツアー 新潟",
    officialLinks: [
      { label: "公式サイト", url: "https://www.humming-tour.jp/", type: "website" },
      { label: "旅ナビ・お問い合わせ", url: "https://www.humming-tour.jp/%E6%97%85%E3%83%8A%E3%83%93/", type: "website" },
    ],
    editorComment: "募集型ツアーの見せ方が分かりやすく、花・山・クルーズなど目的から選びやすい。単なる手配窓口ではなく、旅のテーマを探す入口として使いやすい。",
    highlight: "新潟発着のテーマ型ツアーを探すなら候補に入れたい旅行会社。",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "ハミングツアー 公式サイト", url: "https://www.humming-tour.jp/", sourceType: "official", collectedAt: verifiedAt, note: "国内旅行、クルーズ、海外、山旅、花旅などのツアー導線を確認。" },
      { title: "ハミングツアー 旅ナビ", url: "https://www.humming-tour.jp/%E6%97%85%E3%83%8A%E3%83%93/", sourceType: "official", collectedAt: verifiedAt, note: "問い合わせ・営業所導線を確認。" },
    ],
    faqs: [
      { question: "ハミングツアーはどんなツアーが探しやすいですか？", answer: "花旅、山旅、クルーズ、国内外の募集型ツアーなど、目的やテーマがはっきりした旅行を探しやすい構成です。" },
      { question: "個人旅行の相談もできますか？", answer: "ツアー商品が中心ですが、相談可否や手配範囲は内容により異なります。公式サイトまたは営業所へ確認してください。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "chuetsu-travel",
    name: "中越トラベル",
    tagline: "燕市発、食と貸切バスを組み合わせたオーダーメイド旅行",
    description: "朝日交通株式会社の観光部として、燕市を拠点にオーダーメイド旅行を提案。地元の隠れた食や貸切バスを組み合わせた旅行相談に特色があります。",
    area: "燕・三条",
    address: "新潟県燕市佐渡5262",
    phone: "0256-46-0122",
    services: ["国内旅行", "海外旅行", "団体旅行", "貸切バス", "宿泊手配"],
    bestFor: ["貸切バス込みで相談したい", "食を軸にした旅行を組みたい", "燕・三条周辺から団体旅行を出したい"],
    tags: ["オーダーメイド旅行", "貸切バス", "燕市", "食の旅", "ANTA"],
    priceRange: "相談内容により見積もり",
    consultationStyle: "電話・問い合わせでオーダーメイド相談。",
    businessHours: "公式サイトで要確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "新潟県知事登録旅行業第2-393号",
    officialUrl: "https://chuetsu-travel.com/",
    mapUrl: "https://maps.google.com/?q=新潟県燕市佐渡5262",
    officialLinks: [
      { label: "公式サイト", url: "https://chuetsu-travel.com/", type: "website" },
    ],
    editorComment: "中越交通グループの貸切バスと組み合わせられる点が強い。既成ツアーよりも、地域団体・職場・自治会などの旅行相談で力を発揮しやすい。",
    highlight: "燕・三条周辺で団体旅行や貸切バスを相談するなら見たい一社。",
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "中越トラベル 公式サイト", url: "https://chuetsu-travel.com/", sourceType: "official", collectedAt: verifiedAt, note: "所在地・電話・旅行業登録・オーダーメイド旅行・貸切バス連携を確認。" },
    ],
    faqs: [
      { question: "中越トラベルは団体旅行に向いていますか？", answer: "貸切バス手配と旅行企画を組み合わせられるため、地域団体や職場旅行などの相談に向いています。" },
      { question: "既成ツアーだけでなく個別相談できますか？", answer: "公式サイトではオーダーメイド旅行を打ち出しています。人数、出発地、目的地を整理して問い合わせると相談しやすいです。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "sado-kisen",
    name: "佐渡汽船 旅行・ツアー",
    tagline: "佐渡旅行の移動と滞在をまとめて考えやすい公式導線",
    description: "新潟港・直江津港と佐渡を結ぶ交通会社。フェリー・ジェットフォイルの移動に加え、旅行・ツアー、レンタカー、佐渡滞在の導線がまとまっています。",
    area: "佐渡・新潟港・直江津港",
    address: "新潟県佐渡市両津湊353",
    services: ["佐渡旅行", "国内旅行", "着地型ツアー", "宿泊手配"],
    bestFor: ["佐渡旅行を計画している", "船と現地移動をまとめたい", "佐渡の観光導線を公式情報で確認したい"],
    tags: ["佐渡", "フェリー", "ジェットフォイル", "レンタカー", "着地型"],
    priceRange: "航路・ツアー・手配内容により異なる",
    consultationStyle: "公式サイトで航路・ツアー・旅行商品を確認。",
    businessHours: "窓口・予約センターにより異なるため公式サイトで確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.sadokisen.co.jp/",
    mapUrl: "https://maps.google.com/?q=新潟県佐渡市両津湊353",
    officialLinks: [
      { label: "公式サイト", url: "https://www.sadokisen.co.jp/", type: "website" },
      { label: "旅行・ツアー", url: "https://www.sadokisen.co.jp/trip-top/", type: "website" },
    ],
    editorComment: "純粋な旅行会社というより佐渡旅行の基幹導線。佐渡に行く旅では船・現地交通・宿泊を別々に考える負担があるため、最初に確認する価値が高い。",
    highlight: "佐渡旅行では、船と現地滞在を同時に考える入口として使いやすい。",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "佐渡汽船 公式サイト", url: "https://www.sadokisen.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "航路・旅行導線・佐渡コンテンツを確認。" },
      { title: "佐渡汽船 旅行・ツアー", url: "https://www.sadokisen.co.jp/trip-top/", sourceType: "official", collectedAt: verifiedAt, note: "旅行商品、レンタカー、滞在導線を確認。" },
    ],
    faqs: [
      { question: "佐渡汽船は旅行会社として使えますか？", answer: "フェリー会社ですが、公式サイトに旅行・ツアー導線があります。佐渡旅行では移動と現地滞在をまとめて確認しやすい入口です。" },
      { question: "佐渡旅行では何を先に確認すべきですか？", answer: "船の時刻・運航状況・港までの移動・佐渡内のレンタカーや宿泊を先に確認すると、旅程が組みやすくなります。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "kubiki-motor-green-tour",
    name: "頸城自動車 マルケーグリーンツアー",
    tagline: "上越発のバス・団体旅行相談に強い地域交通系",
    description: "上越市の交通会社。路線・高速・貸切バスに加えて、団体・個人旅行、マルケーグリーンツアー、ホテル・旅館手配などの相談導線があります。",
    area: "上越",
    address: "新潟県上越市石橋2-12-52",
    services: ["バスツアー", "団体旅行", "貸切バス", "宿泊手配", "国内旅行"],
    bestFor: ["上越発の旅行を探したい", "貸切バスと宿をまとめたい", "地域団体の旅行を相談したい"],
    tags: ["上越", "交通会社", "貸切バス", "団体旅行", "バスツアー"],
    priceRange: "ツアー・見積もり内容により異なる",
    consultationStyle: "店舗・電話で相談。旅行取扱店舗あり。",
    businessHours: "店舗により異なるため公式サイトで確認",
    closedDays: "店舗により異なるため公式サイトで確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.marukei-g.com/",
    mapUrl: "https://maps.google.com/?q=新潟県上越市石橋2-12-52",
    officialLinks: [
      { label: "公式サイト", url: "https://www.marukei-g.com/", type: "website" },
      { label: "団体・個人旅行", url: "https://www.marukei-g.com/pages/199/", type: "website" },
    ],
    editorComment: "上越エリアの旅行相談先として地域性が明確。貸切・観光バスの会社なので、移動手段込みの団体旅行で検討しやすい。",
    highlight: "上越発のバス旅行・団体旅行なら確認したい地域交通系の相談先。",
    imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "頸城自動車 公式サイト", url: "https://www.marukei-g.com/", sourceType: "official", collectedAt: verifiedAt, note: "会社所在地、路線・高速・貸切バス、旅行導線を確認。" },
      { title: "頸城自動車 団体・個人旅行", url: "https://www.marukei-g.com/pages/199/", sourceType: "official", collectedAt: verifiedAt, note: "マルケーグリーンツアー、旅行相談、ホテル・旅館手配を確認。" },
    ],
    faqs: [
      { question: "頸城自動車は個人旅行も相談できますか？", answer: "公式サイトでは団体・個人旅行の導線があり、マルケーグリーンツアーなどの旅行商品も確認できます。" },
      { question: "上越からの団体旅行に向いていますか？", answer: "貸切・観光バスを持つ地域交通会社のため、上越発着の団体旅行や移動込みの相談に向いています。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "echigo-kotsu-golden-tour",
    name: "越後交通 ゴールデンツアー",
    tagline: "長岡・中越エリア発着のバスツアーを探しやすい",
    description: "越後交通グループが展開する旅行商品。ゴールデンツアーの一覧、Web申込、チラシ、相談窓口、集合場所などが公式サイトで確認できます。",
    area: "長岡・中越",
    address: "新潟県長岡市周辺",
    services: ["バスツアー", "国内旅行", "団体旅行", "貸切バス"],
    bestFor: ["長岡・中越発のバスツアーを探したい", "日帰りや季節ツアーを比較したい", "交通会社系の旅行商品を見たい"],
    tags: ["長岡", "中越", "ゴールデンツアー", "バスツアー", "Web申込"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイト、Web申込、窓口で確認。",
    businessHours: "窓口により異なるため公式サイトで確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.echigo-kotsu.co.jp/gt/",
    mapUrl: "https://maps.google.com/?q=越後交通 長岡",
    officialLinks: [
      { label: "ゴールデンツアー", url: "https://www.echigo-kotsu.co.jp/gt/", type: "website" },
      { label: "越後交通 公式サイト", url: "https://www.echigo-kotsu.co.jp/", type: "website" },
      { label: "貸切バス", url: "https://www.echigo-kotsu.co.jp/kashikiri/", type: "website" },
    ],
    editorComment: "長岡・中越発着で季節イベントや日帰り旅行を探すときに便利。交通会社系なので集合場所やバス利用の導線が分かりやすい。",
    highlight: "長岡・中越エリアからバスツアーを探すなら候補に入れたい。",
    imageUrl: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "越後交通 ゴールデンツアー", url: "https://www.echigo-kotsu.co.jp/gt/", sourceType: "official", collectedAt: verifiedAt, note: "ツアー一覧、Web申込、チラシ、相談窓口を確認。" },
      { title: "越後交通 公式サイト", url: "https://www.echigo-kotsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行・貸切バス導線を確認。" },
    ],
    faqs: [
      { question: "越後交通ゴールデンツアーはどんな人に向いていますか？", answer: "長岡・中越エリアから、日帰りや季節イベントのバスツアーを探したい人に向いています。" },
      { question: "Web申込はできますか？", answer: "公式サイトにツアー一覧とWeb申込導線があります。空席や催行状況は申込前に公式情報を確認してください。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
  {
    slug: "niigata-kotsu-travel",
    name: "新潟交通 旅行情報",
    tagline: "新潟市発着の交通導線と旅行情報をまとめて確認できる",
    description: "新潟交通グループの公式サイトには旅行情報の独立導線があり、新潟発着の国内・海外旅行、路線バス・高速バスなどの交通情報と合わせて確認できます。",
    area: "新潟市・下越",
    address: "新潟県新潟市中央区万代周辺",
    services: ["国内旅行", "海外旅行", "バスツアー", "団体旅行"],
    bestFor: ["新潟市発着の旅行情報を確認したい", "バス移動と旅行情報を合わせて見たい", "下越エリアの交通会社系導線を使いたい"],
    tags: ["新潟市", "交通会社", "旅行情報", "高速バス", "下越"],
    priceRange: "旅行商品・手配内容により異なる",
    consultationStyle: "公式サイトの旅行情報導線から確認。",
    businessHours: "窓口により異なるため公式サイトで確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www1.niigata-kotsu.co.jp/",
    mapUrl: "https://maps.google.com/?q=新潟交通 新潟市",
    officialLinks: [
      { label: "新潟交通 公式サイト", url: "https://www.niigata-kotsu.co.jp/", type: "website" },
      { label: "旅行情報", url: "https://www1.niigata-kotsu.co.jp/", type: "website" },
    ],
    editorComment: "新潟市内・近郊の交通導線を押さえたうえで旅行情報を確認できる点が特徴。旅行会社単体というより、交通会社グループの入口として扱うのが自然。",
    highlight: "新潟市発着の交通と旅行情報をまとめて確認する入口。",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "新潟交通 公式サイト", url: "https://www.niigata-kotsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行情報、路線バス、高速バス、グループ導線を確認。" },
      { title: "新潟交通 旅行情報", url: "https://www1.niigata-kotsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行情報サイトの存在を確認。" },
    ],
    faqs: [
      { question: "新潟交通は旅行会社として掲載していますか？", answer: "公式サイトに旅行情報の独立導線があるため、地域交通会社系の旅行情報入口として掲載しています。旅行商品の詳細は公式サイトで確認してください。" },
      { question: "新潟市内の移動情報も同時に確認できますか？", answer: "新潟交通公式サイトでは路線バス・高速バスなどの交通情報も確認できます。旅行計画と移動手段を合わせて見たい場合に便利です。" },
    ],
    relatedRankingSlugs: ["niigata-local-travel-agencies"],
  },
];
