import type { Salon, Source } from "@/lib/types";

const collectedAt = "2026-06-08";

const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);

export const beautySalons: Salon[] = [
  {
    slug: "sea-luvism-bandai",
    name: "Sea by LUVISM 万代店",
    tagline: "イルミナカラー・ブリーチ・ダブルカラーが得意な万代の実力サロン",
    description: "新潟万代ビル8Fに構えるLUVISMグループのプレミアムライン。イルミナカラー・ブリーチ・ダブルカラーを得意とし、20〜30代のカラー重視層から高い支持を集める。新潟駅万代口から徒歩約10分とアクセスも良好。年中無休で夜22時まで営業しており、仕事帰りや週末でも通いやすい環境が整っている。",
    area: "新潟市中央区・万代",
    address: "新潟県新潟市中央区万代1-3-10 新潟万代ビル8F",
    phone: "025-278-8332",
    access: "新潟駅（万代口）徒歩約10分",
    treatments: ["cut", "color", "highlight", "hairQuality", "straightening"],
    ageGroups: ["twenties", "thirties"],
    priceRange: "カット+カラーセット ¥7,950〜",
    cutPrice: "要確認（公式サイト・予約サイトで確認）",
    colorPrice: "カット+カラーセット ¥7,950〜",
    parking: false,
    parkingNote: "万代エリア周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜22:00",
    closedDays: "年中無休",
    officialUrl: "https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/",
    mapUrl: map("新潟県新潟市中央区万代1-3-10 新潟万代ビル Sea by LUVISM"),
    officialLinks: [
      { label: "公式サイト", url: "https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000624907/", type: "website" },
      { label: "Google マップ", url: map("新潟県新潟市中央区万代1-3-10 新潟万代ビル Sea by LUVISM"), type: "map" },
    ],
    editorComment: "万代エリアでイルミナカラー・ダブルカラーを得意とするLUVISMグループの上位ライン。20〜30代でカラー重視の読者への最有力候補のひとつ。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Sea by LUVISM 万代店 公式サイト", "https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/", "official", "店舗名・住所・電話・営業時間・得意施術を確認。"),
      src("Sea by LUVISM 万代店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000624907/", "local-media", "料金・メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "Sea by LUVISMはどんな人に向いていますか？", answer: "イルミナカラー・ブリーチを使ったハイライトやダブルカラーなど透明感のあるカラーを求める20〜30代の方に向いています。予約はホットペッパービューティーまたは公式サイトから可能です。" },
      { question: "万代店の場所はどこですか？", answer: "新潟万代ビル8Fにあります。新潟駅万代口から徒歩約10分です。電話番号は025-278-8332です。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
  },
  {
    slug: "cloe-luvism-furumachi",
    name: "CLOE by LUVISM 古町6番店",
    tagline: "オーガニックカラーとデザインカラーを得意とする古町のサロン",
    description: "古町通六番町に位置するLUVISMグループのサロン。デザインカラー・オーガニックカラー・髪質改善を中心にメニューを展開し、20〜40代の幅広い層に対応。年中無休で夜22時まで営業と仕事帰りの利用にも便利。カット¥2,500〜とコスパも良好で、古町エリアでの定番サロンとして定着している。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区古町通六番町982-1 ロンドベル古町6番町",
    phone: "025-201-9922",
    access: "古町モール6番町入口・国際調理製菓専門学校向かい",
    treatments: ["cut", "color", "highlight", "hairQuality", "treatment"],
    ageGroups: ["twenties", "thirties", "forties"],
    priceRange: "カット¥2,500〜 / カット+オーガニックフルカラー¥5,400〜",
    cutPrice: "¥2,500〜",
    colorPrice: "カット+オーガニックフルカラー ¥5,400〜",
    parking: false,
    parkingNote: "古町エリア周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜22:00",
    closedDays: "年中無休",
    officialUrl: "https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/",
    mapUrl: map("新潟県新潟市中央区古町通六番町982-1 CLOE by LUVISM"),
    instagram: "https://www.instagram.com/cloebyluvism/",
    officialLinks: [
      { label: "公式サイト", url: "https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000577647/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/cloebyluvism/", type: "instagram" },
      { label: "Google マップ", url: map("新潟県新潟市中央区古町通六番町982-1 CLOE by LUVISM"), type: "map" },
    ],
    editorComment: "古町エリアでオーガニックカラーを試したい方への第一候補。コスパと立地の良さが20〜40代から支持される。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("CLOE by LUVISM 古町6番店 公式サイト", "https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/", "official", "住所・電話・営業時間・料金を確認。"),
      src("クロエ バイ ラヴィズム 古町6番店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000577647/", "local-media", "メニュー・料金・口コミを確認。"),
    ],
    faqs: [
      { question: "古町6番店のカラー料金はどのくらいですか？", answer: "カット+オーガニックフルカラーが¥5,400〜です。詳細メニューはホットペッパービューティーの公式ページでご確認ください。" },
      { question: "オーガニックカラーとは何ですか？", answer: "天然由来成分を配合したカラー剤を使用する施術です。頭皮への刺激が少なく、敏感肌の方や薬剤が気になる方に向いています。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
  },
  {
    slug: "cloe-luvism-niigataeki",
    name: "CLOE by LUVISM 新潟駅前店",
    tagline: "新潟駅徒歩2分・デザインカラーと縮毛矯正が得意な駅前サロン",
    description: "新潟駅万代口から徒歩2分のアルファビル2Fに構えるCLOEの駅前店。デザインカラー・オーガニックカラー・縮毛矯正を中心に、10〜30代の学生から社会人まで幅広く対応。カット¥2,400〜と価格の入りやすさも強み。夜22時まで年中無休で営業しており、新潟駅を利用する通勤・通学者の定番サロンとして定着している。",
    area: "新潟市中央区・新潟駅前",
    address: "新潟県新潟市中央区花園1-3-23 アルファビル2階",
    phone: "025-282-7335",
    access: "新潟駅（万代口）徒歩2分",
    treatments: ["cut", "color", "highlight", "hairQuality", "straightening"],
    ageGroups: ["teens", "twenties", "thirties"],
    priceRange: "デザインカット¥2,400〜 / カット+オーガニックフルカラー¥4,900〜",
    cutPrice: "¥2,400〜",
    colorPrice: "カット+オーガニックフルカラー ¥4,900〜",
    parking: false,
    parkingNote: "駅近のため公共交通機関利用推奨",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜22:00",
    closedDays: "年中無休",
    officialUrl: "https://cloebyluvism.jp/salon/niigata_ekimae/",
    mapUrl: map("新潟県新潟市中央区花園1-3-23 アルファビル CLOE by LUVISM"),
    instagram: "https://www.instagram.com/cloebyluvism/",
    officialLinks: [
      { label: "公式サイト", url: "https://cloebyluvism.jp/salon/niigata_ekimae/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000316018/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/cloebyluvism/", type: "instagram" },
      { label: "Google マップ", url: map("新潟県新潟市中央区花園1-3-23 アルファビル CLOE by LUVISM"), type: "map" },
    ],
    editorComment: "新潟駅徒歩2分という立地と入りやすい価格帯が10〜20代への強み。初めてデザインカラーや縮毛矯正を試す読者への提案先として使いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("CLOE by LUVISM 新潟駅前店 公式サイト", "https://cloebyluvism.jp/salon/niigata_ekimae/", "official", "住所・電話・営業時間・料金を確認。"),
      src("クロエ バイ ラヴィズム 新潟駅前店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000316018/", "local-media", "メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "新潟駅前店は駅からどのくらいですか？", answer: "新潟駅万代口から徒歩2分、アルファビル2Fです。電話番号は025-282-7335です。" },
      { question: "学生でも利用できますか？", answer: "はい。各種クーポンや割引メニューをホットペッパービューティーで確認できます。最新情報は予約サイトまたは電話でご確認ください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80",
  },
  {
    slug: "delight-designers-works",
    name: "Delight Designer's Works",
    tagline: "新潟駅前に構えるメンズ専門ヘアサロン",
    description: "新潟市中央区東大通の東陽ビル2Fに構えるメンズ専門ヘアサロン。フェードカット・ツーブロック・メンズパーマなどメンズスタイリング全般を高い技術力で提供。新潟駅（花園・沼垂方面出口）から徒歩2分のアクセスも良好。旧東区店から移転後も固定客が多く、新潟市内のメンズサロンとして定評がある。",
    area: "新潟市中央区・新潟駅前",
    address: "新潟県新潟市中央区東大通1丁目5番2号 東陽ビル2F",
    phone: "025-384-4559",
    access: "新潟駅（花園・沼垂方面出口）徒歩2分",
    treatments: ["cut", "color", "perm"],
    ageGroups: ["teens", "twenties", "thirties", "forties"],
    priceRange: "要確認（公式サイト・予約サイトで確認）",
    cutPrice: "要確認（公式サイトで確認）",
    parking: false,
    parkingNote: "駅近のため公共交通機関利用推奨",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "11:00〜20:00（最終受付19:00）",
    closedDays: "毎週月曜日（臨時休業あり）",
    officialUrl: "https://delightdesignersworks.com/",
    mapUrl: map("新潟県新潟市中央区東大通1丁目5番2号 東陽ビル Delight Designers Works"),
    instagram: "https://www.instagram.com/delightdesignersworks/",
    officialLinks: [
      { label: "公式サイト", url: "https://delightdesignersworks.com/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000563316/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/delightdesignersworks/", type: "instagram" },
      { label: "Google マップ", url: map("新潟県新潟市中央区東大通1丁目5番2号 東陽ビル Delight Designers Works"), type: "map" },
    ],
    editorComment: "新潟市内でメンズ専門の技術力に定評があるサロン。料金は公式サイトまたはInstagram（@delightdesignersworks）で要確認。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Delight Designer's Works 公式サイト", "https://delightdesignersworks.com/", "official", "移転後の店舗情報・営業時間を確認。"),
      src("ディライト ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000563316/", "local-media", "メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "女性も利用できますか？", answer: "メンズ専門サロンです。詳細は公式サイト（delightdesignersworks.com）またはInstagramでご確認ください。" },
      { question: "場所はどこですか？", answer: "新潟市中央区東大通1丁目5番2号 東陽ビル2Fです。新潟駅（花園・沼垂方面出口）から徒歩2分です。電話番号は025-384-4559です。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
  },
  {
    slug: "ursus-headlight-sakaihi",
    name: "Ursus hair Design by HEADLIGHT 坂井東店",
    tagline: "髪質改善・ヘッドスパ・縮毛矯正が揃う駐車場完備の西区サロン",
    description: "新潟市西区坂井東に立地するHEADLIGHTグループのサロン。髪質改善・ヘッドスパ・縮毛矯正・デジタルパーマなど幅広いメニューを提供し、車移動が多い西区・西蒲区の利用者に支持されている。専用駐車場5台完備で、郊外在住者でも通いやすい。カット¥2,700〜とリーズナブルな価格帯も魅力で、年中無休夜21時まで営業。",
    area: "新潟市西区",
    address: "新潟県新潟市西区坂井東1-3-15",
    phone: "025-378-3447",
    access: "JR小針駅から車約10分 / 大堀幹線沿い・ブックオフ斜め前",
    treatments: ["cut", "color", "hairQuality", "straightening", "treatment", "headSpa", "perm"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "カット¥2,700〜",
    cutPrice: "¥2,700〜",
    parking: true,
    parkingNote: "専用駐車場5台あり",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜21:00",
    closedDays: "年中無休",
    officialUrl: "https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/",
    mapUrl: map("新潟県新潟市西区坂井東1-3-15 Ursus hair Design HEADLIGHT"),
    officialLinks: [
      { label: "公式サイト（HEADLIGHT）", url: "https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000362060/", type: "website" },
      { label: "Google マップ", url: map("新潟県新潟市西区坂井東1-3-15 Ursus hair Design HEADLIGHT"), type: "map" },
    ],
    editorComment: "新潟市西区で髪質改善・ヘッドスパを求める読者への最有力候補。駐車場完備で車移動派にも使いやすく、豊富なメニューで幅広い悩みに対応できる。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Ursus hair Design by HEADLIGHT 坂井東店 HEADLIGHT公式", "https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/", "official", "住所・電話・営業時間・駐車場・得意施術を確認。"),
      src("アーサス ヘアー デザイン 坂井東店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000362060/", "local-media", "料金・メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "ヘッドスパの予約はできますか？", answer: "はい。ホットペッパービューティーまたは電話（025-378-3447）でご予約いただけます。" },
      { question: "駐車場はありますか？", answer: "専用駐車場が5台あります。大堀幹線沿い、ブックオフ斜め前が目印です。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-headspa", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
  },
  {
    slug: "cloe-luvism-nagaoka",
    name: "CLOE by LUVISM 長岡古正寺店",
    tagline: "キッズスペースあり・駐車場15台完備の長岡ファミリーサロン",
    description: "長岡市古正寺に立地するCLOE by LUVISMの長岡店。15台の広い駐車場とキッズスペースを完備し、子連れ家族でも安心して利用できる。イルミナカラー・インナーカラー・ブリーチ・ハイライトなどカラーメニューも充実しており、長岡市内では数少ない「カラー技術とファミリー対応を両立」するサロン。年中無休で夜22時まで営業。",
    area: "長岡市",
    address: "新潟県長岡市古正寺2-57",
    phone: "0258-86-8755",
    access: "JR長岡駅から車約10分 / 国道351号・新潟トヨペット左隣",
    treatments: ["cut", "color", "highlight", "hairQuality", "perm"],
    ageGroups: ["teens", "twenties", "thirties", "forties"],
    priceRange: "カット¥2,800〜 / イルミナフルカラー+カット¥7,400〜",
    cutPrice: "¥2,800〜（メンズカット¥2,400〜）",
    colorPrice: "イルミナフルカラー+カット ¥7,400〜 / カット+フルカラー ¥5,400〜",
    parking: true,
    parkingNote: "専用駐車場15台完備",
    childrenWelcome: true,
    menWelcome: true,
    businessHours: "9:00〜22:00",
    closedDays: "年中無休",
    officialUrl: "https://cloebyluvism.jp/salon/kosyoji/",
    mapUrl: map("新潟県長岡市古正寺2-57 CLOE by LUVISM"),
    instagram: "https://www.instagram.com/cloebyluvism/",
    officialLinks: [
      { label: "公式サイト", url: "https://cloebyluvism.jp/salon/kosyoji/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000375435/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/cloebyluvism/", type: "instagram" },
      { label: "Google マップ", url: map("新潟県長岡市古正寺2-57 CLOE by LUVISM"), type: "map" },
    ],
    editorComment: "長岡市内で「子連れOK」かつ「カラー技術も妥協したくない」読者への最優先提案先。駐車場15台は長岡郊外での利便性として大きな強み。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("CLOE by LUVISM 長岡古正寺店 公式サイト", "https://cloebyluvism.jp/salon/kosyoji/", "official", "住所・電話・営業時間・駐車場・キッズスペース・料金を確認。"),
      src("クロエ バイ ラヴィズム 長岡古正寺店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000375435/", "local-media", "メニュー・口コミ・子連れ対応を確認。"),
    ],
    faqs: [
      { question: "子連れで利用できますか？", answer: "はい。キッズスペースを完備しています。専用駐車場も15台あるため、お子様連れでも安心してご来店いただけます。" },
      { question: "長岡駅からのアクセスは？", answer: "JR長岡駅から車約10分です。国道351号沿い、新潟トヨペットの左隣が目印です。電話番号は0258-86-8755です。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80",
  },
];
