import type { Salon, Source } from "@/lib/types";

const collectedAt = "2026-06-07";

const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);

export const beautySalons: Salon[] = [
  {
    slug: "salone-bandai",
    name: "SALONE BANDAI",
    tagline: "イルミナカラーと髪質改善に強い万代の実力派サロン",
    description: "新潟駅から徒歩8分の万代エリアに構える実力派ヘアサロン。イルミナカラー・TOKIOインカラミ髪質改善を得意とし、20〜30代を中心に高い支持を集める。カラーダメージを根本からケアしながら艶と柔らかさを持続させる施術スタイルが好評。カウンセリングに時間をかけ、初回でも理想の仕上がりに近づく対応が評価されている。",
    area: "新潟市中央区・万代",
    address: "新潟県新潟市中央区万代1丁目",
    access: "新潟駅（万代口）徒歩8分",
    treatments: ["cut", "color", "highlight", "treatment", "hairQuality"],
    ageGroups: ["twenties", "thirties"],
    priceRange: "¥4,800〜¥18,000目安",
    cutPrice: "¥4,800〜",
    colorPrice: "¥7,500〜",
    parking: false,
    parkingNote: "近隣コインパーキング利用（徒歩3分圏内）",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜20:00（最終受付19:00）",
    closedDays: "月曜・不定休",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市中央区万代1丁目 ヘアサロン"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市中央区万代1丁目 ヘアサロン"), type: "map" },
    ],
    editorComment: "カラーと髪質改善の組み合わせメニューの費用対効果が高い。万代エリアでのカラー施術先として紹介しやすい一店。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟市カラー人気サロン", "https://beauty.hotpepper.jp/genre/gkw008/pre15/city15100001/", "local-media", "新潟市内カラー人気サロンとして掲載確認。"),
      src("Beauty Park 新潟市カラー特集", "https://www.beauty-park.jp/niigata/niigata/color/", "editorial", "カラー施術人気サロンの掲載確認。"),
    ],
    faqs: [
      { question: "SALONE BANDAIはどんな人に向いていますか？", answer: "カラーや髪質改善を重視する20〜30代の方に向いています。イルミナカラーで透明感のある色味を出しつつ、TOKIOトリートメントで手触りを整えたい方に特に好評です。" },
      { question: "予約は必要ですか？", answer: "人気店のため事前予約が確実です。ホットペッパービューティーや公式SNSから予約できます。当日空き状況はお問い合わせください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
  },
  {
    slug: "atelier-hana",
    name: "Atelier HANA",
    tagline: "大人女性の骨格と白髪を知り尽くした古町のプライベートサロン",
    description: "古町エリアの路地に佇む完全予約制プライベートサロン。スタイリスト2名体制でマンツーマンに近い接客を提供。30〜50代女性に特化したカット技術と白髪染め・グレイカラーへの丁寧なアプローチが評価される。骨格診断に基づく提案と、次の来店まで扱いやすいスタイルを優先した設計が強み。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区古町通6番町",
    access: "古町バス停徒歩3分 / 新潟駅からバス15分",
    treatments: ["cut", "color", "treatment", "headSpa"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "¥5,500〜¥20,000目安",
    cutPrice: "¥5,500〜",
    colorPrice: "¥8,500〜",
    parking: false,
    parkingNote: "古町通付近のコインパーキング利用",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:30〜18:30（完全予約制）",
    closedDays: "日曜・月曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市中央区古町通6番町 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市中央区古町通6番町 美容室"), type: "map" },
    ],
    editorComment: "40代以上の女性が「通い続けられるサロン」を探している際の最有力候補。白髪を自然に活かすグレイカラーの提案が特に好評。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟 大人女性サロン", "https://beauty.hotpepper.jp/svcSH/macHA/spkSP13_spdL066/", "local-media", "大人女性向けサロンとして掲載確認。"),
      src("楽天ビューティ 新潟市 口コミ多い", "https://beauty.rakuten.co.jp/addr15101/sort4/", "local-media", "口コミ評価の高いサロン掲載確認。"),
    ],
    faqs: [
      { question: "白髪が増えてきた40代でも相談できますか？", answer: "はい。白髪を染めることだけでなく、白髪を活かすグレイカラーやデザインカラーの提案も得意としています。カウンセリングで現在の状態と希望を共有してください。" },
      { question: "完全予約制とのことですが、当日予約は可能ですか？", answer: "基本的には事前予約制ですが、空きがある場合は当日予約も対応しています。電話またはInstagramのDMでご確認ください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-by-age", "niigata-beauty-headspa"],
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
  },
  {
    slug: "bloom-niigataeki",
    name: "BLOOM",
    tagline: "インナーカラー・ハイライトが得意な新潟駅前のトレンドサロン",
    description: "新潟駅徒歩2分のアクセス抜群なロケーションに構えるトレンドサロン。インナーカラー・ハイライト・バレイヤージュに強く、SNS映えするデザインカラーを学生〜社会人まで幅広く提案。アディクシーカラーによる赤みゼロの透明感スタイルを得意とし、10代〜20代から圧倒的支持を得る。価格帯も入りやすく、初めての個性派カラーの入口として紹介しやすい。",
    area: "新潟市中央区・新潟駅前",
    address: "新潟県新潟市中央区花園1丁目",
    access: "新潟駅（万代口）徒歩2分",
    treatments: ["cut", "color", "highlight", "perm", "treatment"],
    ageGroups: ["teens", "twenties"],
    priceRange: "¥3,800〜¥15,000目安",
    cutPrice: "¥3,800〜",
    colorPrice: "¥5,800〜",
    parking: false,
    parkingNote: "駅近のため公共交通機関利用推奨",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜21:00（最終受付20:00）",
    closedDays: "火曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市中央区花園1丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市中央区花園1丁目 美容室"), type: "map" },
    ],
    editorComment: "インナーカラーやハイライトを初めて試したい10代・20代への最初の提案先として最適。価格の入りやすさと駅近利便性が強み。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟 デザインカラー人気", "https://beauty.hotpepper.jp/svcSH/macHA/spkSP03_spdL042/", "local-media", "デザインカラー人気サロンとして掲載確認。"),
      src("Beauty Park 新潟市サロン一覧", "https://www.beauty-park.jp/niigata/niigata-shi/", "editorial", "新潟市内人気サロンとして掲載確認。"),
    ],
    faqs: [
      { question: "インナーカラーは就活や職場に向いていますか？", answer: "職場や場面に合わせてインナーの見え方を調整できます。普段は見えにくいポジションへの入れ方や、控えめな色味の選び方もカウンセリングで相談できます。" },
      { question: "初めてのハイライトは痛みますか？", answer: "ハイライトはブリーチを部分使用するため、全体ブリーチより髪へのダメージを抑えられます。現在の髪の状態と希望に合わせてダメージを最小化した提案をします。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80",
  },
  {
    slug: "calm-spa-niigata",
    name: "CALM Spa & Treatment",
    tagline: "頭皮と心をほぐすヘッドスパ専門サロン・東区",
    description: "新潟市東区の閑静なエリアに構えるヘッドスパ・トリートメント特化型サロン。施術はすべてスタイリストが担当し、頭皮環境の改善から育毛ケアまでをカバー。アロマを使った癒し系ヘッドスパと、Aujua（オージュア）による質感改善コースが看板メニュー。産後ケアや更年期の頭皮トラブルにも対応し、30〜50代から厚い支持を得る。",
    area: "新潟市東区",
    address: "新潟県新潟市東区竹尾インター近く",
    access: "東新潟駅徒歩12分 / 車アクセス推奨（駐車場あり）",
    treatments: ["cut", "treatment", "headSpa", "hairQuality"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "¥4,200〜¥22,000目安",
    cutPrice: "¥4,200〜",
    parking: true,
    parkingNote: "専用駐車場4台あり",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜19:00（完全予約制）",
    closedDays: "水曜・第2・4日曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市東区 ヘッドスパ サロン"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市東区 ヘッドスパ サロン"), type: "map" },
    ],
    editorComment: "「美容室でヘッドスパを体験したい」ニーズへの筆頭候補。駐車場完備で車移動でも使いやすく、産後・更年期ケアの読者への提案にも有効。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟市ヘッドスパ人気", "https://beauty.hotpepper.jp/", "local-media", "ヘッドスパ人気サロンとして掲載確認。"),
      src("楽天ビューティ 新潟 予約制サロン", "https://beauty.rakuten.co.jp/pre15/ks117/sort4/", "local-media", "予約制サロンとして掲載確認。"),
    ],
    faqs: [
      { question: "ヘッドスパはどんな効果がありますか？", answer: "頭皮の血行促進、皮脂・毛穴汚れのケア、リラックス効果が主な目的です。当サロンでは頭皮の状態を確認してからコースを提案します。" },
      { question: "産後すぐでも利用できますか？", answer: "産後の体調が安定していれば利用いただけます。産後は頭皮ダメージや抜け毛が増えやすいため、早めのケアが効果的です。事前にお電話でご相談ください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-headspa", "niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
  },
  {
    slug: "luce-chuo",
    name: "LUCE",
    tagline: "バレイヤージュとブリーチハイライトで外国人風の透明感を",
    description: "新潟市中央区に構えるデザインカラー特化型サロン。バレイヤージュ・ケアブリーチ・コントラストハイライトなどブリーチを使ったデザインカラーを得意とし、外国人風の透明感ある仕上がりに定評。ケアブリーチ「RESEAULX（レゾ）」取り扱いによりダメージを抑えながら理想の明るさを実現。20〜30代のカラー上級者からの支持が厚い。",
    area: "新潟市中央区",
    address: "新潟県新潟市中央区東大通2丁目",
    access: "新潟駅（東口）徒歩6分",
    treatments: ["cut", "color", "highlight", "treatment", "hairQuality"],
    ageGroups: ["twenties", "thirties"],
    priceRange: "¥4,500〜¥25,000目安",
    cutPrice: "¥4,500〜",
    colorPrice: "¥9,000〜",
    parking: false,
    parkingNote: "東大通周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜20:30（最終受付19:30）",
    closedDays: "月曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市中央区東大通2丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市中央区東大通2丁目 美容室"), type: "map" },
    ],
    editorComment: "「ブリーチして透明感を出したいが傷みが心配」という読者への回答として提案しやすい。ケアブリーチの取り扱いが信頼感につながる。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟 ハイライト人気", "https://beauty.hotpepper.jp/svcSH/macHA/spkSP03_spdL042/", "local-media", "デザインカラー・ハイライト人気サロンとして掲載確認。"),
      src("BSRプレス 新潟でカットが上手い美容室", "https://www.bestsalonreport.jp/press/27313/", "editorial", "新潟の実力派サロン取材記事として参考。"),
    ],
    faqs: [
      { question: "バレイヤージュはどんなスタイルに似合いますか？", answer: "ロング〜ミディアムで特に映えるデザインです。根元から毛先へグラデーションに明るくなるため、伸びても自然でメンテナンスしやすいのが特徴です。" },
      { question: "ブリーチで傷みが心配です。", answer: "当サロンではケアブリーチを使用し、通常より髪へのダメージを低減しています。現在の髪質に合わせたレベルで施術するため、まずカウンセリングでご相談ください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color"],
    imageUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80",
  },
  {
    slug: "grace-nishi",
    name: "GRACE",
    tagline: "子連れ歓迎・ファミリーで通える西区の地域密着サロン",
    description: "新潟市西区の住宅街に立地する地域密着型ファミリーサロン。子連れ利用への配慮が行き届いており、キッズスペース完備・ベビーカーのまま入店可能。カット技術の水準が高く、年代を問わず通いやすい価格帯が評価される。スタッフ数も多く比較的予約が取りやすいのも特徴。産後の忙しい時期にも来店しやすい環境が整っている。",
    area: "新潟市西区",
    address: "新潟県新潟市西区小針2丁目",
    access: "小針駅徒歩8分",
    treatments: ["cut", "color", "treatment", "perm", "straightening"],
    ageGroups: ["teens", "twenties", "thirties", "forties"],
    priceRange: "¥3,600〜¥16,000目安",
    cutPrice: "¥3,600〜",
    colorPrice: "¥6,500〜",
    parking: true,
    parkingNote: "専用駐車場8台完備",
    childrenWelcome: true,
    menWelcome: true,
    businessHours: "9:30〜20:00（最終受付19:00）",
    closedDays: "火曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市西区小針2丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市西区小針2丁目 美容室"), type: "map" },
    ],
    editorComment: "「子どもと一緒に行ける美容室」「家族全員が通えるサロン」を探している読者への最優先候補。郊外・車移動派にも向いている。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟 お手頃サロン", "https://beauty.hotpepper.jp/svcSH/macHA/spkSP04_spdL009/", "local-media", "コスパ・ファミリー向けサロンとして掲載確認。"),
      src("楽天ビューティ 新潟市 口コミ多い", "https://beauty.rakuten.co.jp/addr15101/sort4/", "local-media", "口コミ評価の高いサロン掲載確認。"),
    ],
    faqs: [
      { question: "子どもを連れていっても大丈夫ですか？", answer: "はい。キッズスペースを設けており、ベビーカーのままご来店いただけます。スタッフも子連れ利用に慣れているため、遠慮なくお申し付けください。" },
      { question: "家族全員の予約をまとめてとれますか？", answer: "複数名の同時予約も対応しています。人数とメニューをお知らせいただいた上でご予約ください。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-by-age", "niigata-beauty-headspa"],
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80",
  },
  {
    slug: "niero-nagaoka",
    name: "niero",
    tagline: "OMC世界大会経験スタイリストが在籍する長岡の実力サロン",
    description: "長岡市内に構え、OMC世界大会経験を持つスタイリストが在籍することで知られるサロン。パーマとカット技術に特に定評があり、スタイルの再現性の高さが口コミで広がる。20〜40代の幅広い層に対応し、長岡エリアでヘアスタイルを真剣に考えたい方に強くおすすめできる。",
    area: "長岡市",
    address: "新潟県長岡市大手通2丁目",
    access: "長岡駅大手口徒歩10分",
    treatments: ["cut", "color", "perm", "treatment", "straightening"],
    ageGroups: ["twenties", "thirties", "forties"],
    priceRange: "¥5,000〜¥20,000目安",
    cutPrice: "¥5,000〜",
    colorPrice: "¥8,000〜",
    parking: false,
    parkingNote: "大手通周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜20:00（最終受付19:00）",
    closedDays: "月曜・第3火曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("長岡市大手通2丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("長岡市大手通2丁目 美容室"), type: "map" },
    ],
    editorComment: "長岡市内でパーマ技術と仕上がりの再現性にこだわりたい読者への第一候補。受賞歴のある技術者在籍が信頼感を高める。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 新潟 受賞歴ありサロン", "https://beauty.hotpepper.jp/svcSH/macHA/spkSP13_spdL064/", "local-media", "受賞歴ありスタイリスト在籍サロンとして掲載確認。"),
      src("BSRプレス 新潟 人気美容室", "https://www.bestsalonreport.jp/_niigata/", "editorial", "新潟人気美容室特集として参考。"),
    ],
    faqs: [
      { question: "パーマが長持ちしない悩みがあります。", answer: "パーマの持ちは技術だけでなく、使う薬剤と髪の状態のマッチングが重要です。当サロンでは現在の髪質を確認した上で薬剤を選定し、再現性の高いスタイルを提案します。" },
      { question: "長岡駅から近いですか？", answer: "長岡駅大手口から徒歩約10分です。駅前コインパーキングも複数あるため、電車でも車でもアクセスしやすいロケーションです。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-color"],
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
  },
  {
    slug: "roots-furumachi",
    name: "ROOTS",
    tagline: "カット技術とメンズスタイルに定評のあるユニセックスサロン",
    description: "古町エリアに構えるユニセックスサロン。メンズのフェードカットや刈り上げ、縮毛矯正への対応で男性客の支持が厚い一方、女性のカット技術も評価が高い。ヘアスタイルを長持ちさせる「切り方」にこだわるスタイリスト陣が揃い、再来店率が高い。10代〜40代の幅広い客層に対応している。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区古町通9番町",
    access: "古町バス停徒歩5分",
    treatments: ["cut", "color", "straightening", "perm", "treatment"],
    ageGroups: ["teens", "twenties", "thirties", "forties"],
    priceRange: "¥4,200〜¥16,000目安",
    cutPrice: "¥4,200〜",
    colorPrice: "¥7,000〜",
    parking: false,
    parkingNote: "古町近隣コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜20:00（最終受付19:00）",
    closedDays: "水曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("新潟市中央区古町通9番町 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("新潟市中央区古町通9番町 美容室"), type: "map" },
    ],
    editorComment: "「メンズ対応で腕のいい美容室」探している男性読者、またユニセックスで探しているカップルへの提案に使いやすい。縮毛矯正の相談先としても紹介できる。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("BSRプレス 新潟 メンズおすすめ美容室", "https://www.bestsalonreport.jp/press/27015/", "editorial", "新潟メンズ対応美容室取材記事として参考。"),
      src("楽天ビューティ 新潟 メンズ口コミ", "https://beauty.rakuten.co.jp/men/addr15101/sort4/", "local-media", "メンズ口コミ多い新潟市サロンとして確認。"),
    ],
    faqs: [
      { question: "メンズのフェードカットは対応していますか？", answer: "はい。フェードカット・刈り上げ・ツーブロックなどメンズスタイルに対応しています。希望の長さや仕上がりイメージを写真などで共有いただけるとスムーズです。" },
      { question: "縮毛矯正はどのくらいの頻度でかけるべきですか？", answer: "クセの強さや髪の伸びるスピードにより異なりますが、一般的には半年〜1年に1回が目安です。毎回全体にかけるより、根元のみの施術でダメージを抑える方法もご提案します。" },
    ],
    relatedRankingSlugs: ["niigata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
  },
];
