import type { TravelServiceRegion } from "@/lib/types";

export const travelServiceRegions: TravelServiceRegion[] = [
  {
    slug: "niigata",
    name: "新潟県",
    shortName: "新潟",
    description: "新潟県内発着のバスツアー、佐渡旅行、団体手配、貸切バス相談などに強い地域密着型の旅行会社・交通会社を整理します。",
    tagline: "地元発着ツアーと団体手配に強い、新潟の旅行相談先",
    seoTitle: "新潟県のおすすめ旅行会社・地域密着型旅行会社ガイド",
    seoDescription: "新潟県の地域密着型旅行会社を7件に絞って比較。新潟トラベル、ハミングツアー、中越トラベル、佐渡汽船、頸城自動車、越後交通、新潟交通グループの特徴を整理。",
    seoKeywords: ["新潟 旅行会社", "新潟 バスツアー", "新潟 団体旅行", "新潟 貸切バス", "佐渡 旅行", "地元 旅行会社"],
    status: "live",
    headline: "新潟県の旅行会社を、地元発着・団体手配・佐渡旅行で選ぶ。",
    subtext: "大手予約サイトでは拾いにくい、地元発着ツアーや団体旅行の相談先を公式情報ベースで整理。初回は新潟県内の地域密着型7件に絞っています。",
    heroBadge: "Niigata Travel Services",
    heroCtaSlug: "niigata-local-travel-agencies",
    heroCtaLabel: "旅行会社ランキングを見る",
    statsNote: "旅行業登録、公式サイトの更新状況、県内拠点、ツアー実体、団体・貸切相談のしやすさを確認して掲載しています。",
    areas: ["新潟市", "三条・燕", "長岡", "上越", "佐渡", "中越", "下越"],
    featuredSlugs: ["niigata-travel", "humming-tour", "sado-kisen", "echigo-kotsu-golden-tour"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828", alt: "旅行計画とスマートフォン" },
      { key: "region", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", alt: "旅先へ向かう道路と風景" },
    ],
  },
  {
    slug: "shizuoka",
    name: "静岡県",
    shortName: "静岡",
    description: "静岡県内発着のバスツアー、伊豆・富士山周辺の着地型旅行、団体旅行、貸切バス相談に強い地域密着型の旅行会社・交通会社を整理します。",
    tagline: "伊豆・富士山・浜松発着。地域交通と旅行手配に強い静岡の相談先",
    seoTitle: "静岡県のおすすめ旅行会社・地域密着型旅行会社ガイド",
    seoDescription: "静岡県の地域密着型旅行会社を7件に絞って比較。静岡鉄道、遠鉄トラベル、バンビツアー、東海バストラベル、伊豆箱根トラベル、静鉄ジョイステップバス、富士急トラベルの特徴を整理。",
    seoKeywords: ["静岡 旅行会社", "静岡 バスツアー", "静岡 団体旅行", "浜松 バスツアー", "伊豆 旅行会社", "静岡 貸切バス"],
    status: "live",
    headline: "静岡県の旅行会社を、伊豆・富士山・浜松発着で選ぶ。",
    subtext: "静岡県は東西に広く、伊豆・静岡市・浜松・富士山周辺で旅行導線が分かれます。地域交通会社系のツアー、団体旅行、貸切バス相談先を7件に絞って整理します。",
    heroBadge: "Shizuoka Travel Services",
    heroCtaSlug: "shizuoka-local-travel-agencies",
    heroCtaLabel: "旅行会社ランキングを見る",
    statsNote: "旅行業登録、公式サイトの更新状況、県内発着ツアー、団体旅行・貸切バスの相談導線、伊豆・富士山周辺の地域性を確認して掲載しています。",
    areas: ["静岡市", "焼津・中部", "浜松・遠州", "伊豆", "三島・東部", "富士山周辺", "熱海・初島"],
    featuredSlugs: ["shizutetsu-tourism", "entetsu-travel", "tokai-bus-travel", "izuhakone-travel"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9", alt: "日本の山と旅の風景" },
      { key: "region", url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee", alt: "旅先へ向かう道路と風景" },
    ],
  },
  {
    slug: "yamagata",
    name: "山形県",
    shortName: "山形",
    description: "山形県内の庄内発着ツアー、天童・上山の温泉地体験、置賜の着地型旅行、最上川・蔵王の現地観光に強い地域密着型の旅行会社・交通/観光事業者を整理します。",
    tagline: "庄内・天童・上山・置賜・最上・蔵王。山形らしい旅の相談先",
    seoTitle: "山形県のおすすめ旅行会社・地域密着型旅行相談先ガイド",
    seoDescription: "山形県の地域密着型旅行会社・旅行相談先を7件に絞って比較。庄交トラベル、庄内交通、TENDODAYS、やまがたアルカディア観光局、上山ラプソディ、最上峡芭蕉ライン観光、蔵王ロープウェイの特徴を整理。",
    seoKeywords: ["山形 旅行会社", "山形 バスツアー", "山形 団体旅行", "庄内 旅行会社", "天童 体験ツアー", "蔵王 旅行"],
    status: "live",
    headline: "山形県の旅行会社を、庄内発着・温泉地体験・現地観光で選ぶ。",
    subtext: "山形県は、庄内の募集型ツアー、天童・上山の温泉地体験、置賜の着地型旅行、最上川・蔵王の現地観光で相談先が分かれます。公式情報を確認し、7件に絞って整理します。",
    heroBadge: "Yamagata Travel Services",
    heroCtaSlug: "yamagata-local-travel-agencies",
    heroCtaLabel: "旅行会社ランキングを見る",
    statsNote: "旅行業登録・約款導線、公式サイトの更新状況、地域発着ツアー、体験プラン、団体移動・貸切相談、現地観光での使いやすさを確認して掲載しています。",
    areas: ["鶴岡・酒田", "庄内", "天童", "上山", "長井・南陽", "最上", "蔵王温泉"],
    featuredSlugs: ["shoko-travel", "tendodays-dmc-tendo", "arcadia-tourism-bureau", "kaminoyama-rhapsody"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b", alt: "山岳と旅行風景" },
      { key: "region", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e", alt: "水辺と旅の風景" },
    ],
  },
];
