import type { CafeItem, Source } from "@/lib/types";

const collectedAt = "2026-06-09";
const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);
const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

export const niigataCafeItems: CafeItem[] = [
  {
    slug: "chamonix-niigata",
    name: "珈琲工房 シャモニー 古町店",
    description: "1970年代創業の老舗自家焙煎純喫茶。毎朝店内で豆を焙煎し、一杯ずつサイフォンで丁寧に淹れる。ブレンド5種・ストレート7種・エスプレッソ6種・水出し4種と豊富なラインナップを誇り、昭和の喫茶文化を今に伝える古町の名所です。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区古町通五番町591（古町モール5・2F）",
    phone: "025-228-7189",
    imageUrl: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb",
    style: "自家焙煎",
    tags: ["老舗", "古町", "サイフォン", "純喫茶", "自家焙煎", "モーニング"],
    signatureMenu: "シャモニーブレンド珈琲、Bセット（コーヒー＋ハーフピザトースト＋サラダ）",
    priceRange: "400〜700円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "8:00〜19:00",
    closedDays: "年中無休",
    officialUrl: "https://chamonix-niigata.com/",
    mapUrl: map("珈琲工房シャモニー古町 新潟市中央区古町通五番町591"),
    officialLinks: [
      { label: "公式サイト", url: "https://chamonix-niigata.com/", type: "website" },
      { label: "地図", url: map("珈琲工房シャモニー古町 新潟市中央区古町通五番町591"), type: "map" },
    ],
    editorComment: "古町観光のついでに寄れる老舗中の老舗。サイフォン式の丁寧な一杯を、昭和喫茶の空気とともに味わう体験は唯一無二です。",
    highlight: "毎朝店内焙煎・サイフォン式、50年以上愛される古町の純喫茶",
    lastVerifiedAt: collectedAt,
    sources: [
      src("シャモニー 公式サイト", "https://chamonix-niigata.com/", "official", "営業時間・メニュー・焙煎スタイル確認"),
      src("食べログ 珈琲工房シャモニー", "https://tabelog.com/niigata/A1501/A150102/15001134/", "user-review", "口コミ・評点確認"),
    ],
    faqs: [
      { question: "シャモニーのコーヒーはどんな特徴ですか？", answer: "毎朝自家焙煎した豆をサイフォンで一杯ずつ丁寧に淹れます。ブレンド5種・ストレート7種など豊富なラインナップから好みの一杯を選べます。" },
      { question: "古町モールからのアクセスは？", answer: "古町通五番町591、古町モール5の2Fにあります。古町アーケードを歩きながら立ち寄れる好立地です。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "harumachi-coffee",
    name: "HARUMACHI coffee",
    description: "地域工務店「ノモトホームズ」が直営するカフェ。木の香り・庭の緑・暖炉の音が五感を包む空間で、地元新潟のロースターが厳選した豆を一杯ずつハンドドリップで提供。素材にこだわった手作りスイーツと、HARUMACHIプリンが人気です。",
    area: "新潟市中央区・鳥屋野",
    address: "新潟県新潟市中央区鳥屋野南3-8-24",
    phone: "025-278-8667",
    imageUrl: "https://images.unsplash.com/photo-1445116572489-8890e5d91968",
    style: "ガーデンカフェ",
    tags: ["木造り", "手作りスイーツ", "プリン", "フルーツパフェ", "ハンドドリップ", "暖炉"],
    signatureMenu: "HARUMACHIプリン、旬のフルーツパフェ、ハンドドリップコーヒー",
    priceRange: "600〜900円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "住宅展示場併設の広い駐車場あり",
    reservation: "recommended",
    businessHours: "平日 10:00〜16:00（LO 15:30）、土日祝 10:00〜17:00（LO 16:30）",
    closedDays: "木曜日",
    officialUrl: "https://www.harumachi-coffee.com/",
    mapUrl: map("HARUMACHI coffee 新潟市中央区鳥屋野南3-8-24"),
    officialLinks: [
      { label: "公式サイト", url: "https://www.harumachi-coffee.com/", type: "website" },
      { label: "地図", url: map("HARUMACHI coffee 新潟市中央区鳥屋野南3-8-24"), type: "map" },
    ],
    editorComment: "車で行ける広い駐車場と、木の温もりに包まれた空間が魅力。週替わりのスイーツと季節のパフェは早めに売り切れることも多いので午前中の来店がおすすめです。",
    highlight: "工務店直営・自然素材の空間で味わう手作りプリンとフルーツパフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("HARUMACHI coffee 公式サイト", "https://www.harumachi-coffee.com/", "official", "営業時間・メニュー・アクセス確認"),
      src("新潟おでかけメディア025 HARUMACHI coffee紹介", "https://025niigata.jp/", "local-media", "口コミ・雰囲気確認"),
    ],
    faqs: [
      { question: "HARUMACHIプリンはいつでも食べられますか？", answer: "数量限定のため、人気時期（週末・連休）は午前中に売り切れる場合があります。早めの来店または公式SNSで在庫状況を確認することをおすすめします。" },
      { question: "子連れでも利用できますか？", answer: "駐車場が広く、木のぬくもりある空間で比較的ゆっくりできます。ただし小さいお子様連れの場合は席の混雑状況に応じてご利用ください。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-sweets-cafe"],
  },
  {
    slug: "innovative-co-niigata",
    name: "innovative Co.",
    description: "古町エリアのスペシャルティコーヒー専門店。まず豆の種類を選び、次に抽出方法（ハンドドリップ／カフェラテ／エスプレッソ／アメリカーノ）を選ぶというユニークな注文スタイルが特徴。コーヒーを深く楽しみたい人向けの一杯を提供します。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区西堀通4-259-58 西堀青藍館1F",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
    style: "スペシャルティコーヒー",
    tags: ["スペシャルティ", "豆選び", "古町", "ハンドドリップ", "エスプレッソ"],
    signatureMenu: "豆×抽出方法を選ぶスペシャルティコーヒー（ハンドドリップ・カフェラテ等）",
    priceRange: "500〜700円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "10:00〜17:00",
    closedDays: "不定休（Instagram要確認）",
    officialUrl: "#",
    mapUrl: map("innovative Co. 新潟市中央区西堀通4-259-58"),
    officialLinks: [
      { label: "地図", url: map("innovative Co. 新潟市中央区西堀通4-259-58"), type: "map" },
    ],
    editorComment: "「豆の種類を選んでから抽出方法を決める」という体験型の注文スタイルが新鮮。コーヒーの個性と抽出の違いを学びながら飲める、古町の穴場的スペシャルティカフェです。",
    highlight: "豆×抽出方法を自分で選ぶ体験型スペシャルティコーヒー専門店",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ innovative Co.", "https://tabelog.com/niigata/A1501/A150102/15013600/", "user-review", "店舗情報・口コミ確認"),
    ],
    faqs: [
      { question: "コーヒーに詳しくなくても楽しめますか？", answer: "スタッフが豆の特徴や抽出方法の違いを丁寧に説明してくれるので、コーヒー初心者でも安心して楽しめます。" },
      { question: "営業日の確認方法は？", answer: "不定休のため、訪問前に公式SNSや電話で確認することをおすすめします。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "shibui-matsushiro",
    name: "カールベンクス古民家カフェ『澁い -SHIBUI-』",
    description: "ドイツ人建築家カール・ベンクス氏が手がけた築100年超の古民家再生カフェ。豪雪地帯・越後妻有の雪国文化と、モダンな空間デザインが融合。大地の芸術祭エリアにあり、アート観光と組み合わせて訪れる旅行者にも人気の一軒です。",
    area: "十日町市・松代",
    address: "新潟県十日町市松代2074-1",
    phone: "025-594-7944",
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735",
    style: "古民家カフェ",
    tags: ["古民家", "大地の芸術祭", "越後妻有", "雪国", "カールベンクス", "ランチ"],
    signatureMenu: "季節の地元食材を使ったランチプレート、コーヒー",
    priceRange: "600〜1,800円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "11:00〜16:00（ランチLO 15:00、ドリンクLO 15:30）",
    closedDays: "月〜水（木金土日祝営業）",
    officialUrl: "https://karl-bengs.jp/shibui/",
    mapUrl: map("澁い SHIBUI 十日町市松代2074-1"),
    officialLinks: [
      { label: "公式サイト", url: "https://karl-bengs.jp/shibui/", type: "website" },
      { label: "地図", url: map("澁い SHIBUI 十日町市松代2074-1"), type: "map" },
    ],
    editorComment: "大地の芸術祭エリアの中でも特に印象に残るカフェ。梁を生かしたダイナミックな空間と、地元食材のランチのクオリティが高く、遠方からわざわざ訪れる価値があります。",
    highlight: "ドイツ人建築家が再生した築100年超の古民家、大地の芸術祭エリア",
    lastVerifiedAt: collectedAt,
    sources: [
      src("カールベンクス澁い -SHIBUI- 公式", "https://karl-bengs.jp/shibui/", "official", "営業時間・アクセス・コンセプト確認"),
      src("大地の芸術祭公式サイト", "https://www.echigo-tsumari.jp/", "tourism", "エリア情報確認"),
    ],
    faqs: [
      { question: "大地の芸術祭の会期外でも営業していますか？", answer: "芸術祭の会期外でも営業しています。ただし貸切や特別イベントで臨時休業となる場合があるため、事前に公式サイトで確認してください。" },
      { question: "アクセス方法は？", answer: "まつだい駅（ほくほく線）から徒歩圏内です。車の場合は専用駐車場があります。積雪期は道路状況を事前に確認してください。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "mizuya-yuzawa",
    name: "温泉珈琲 水屋",
    description: "越後湯沢駅すぐの旅館HATAGO井仙1Fにある、温泉水を使ったカフェ。神立地方で湧く「飲める温泉水」で仕立てた水出し温泉珈琲が名物。魚沼産コシヒカリの米粉ロールケーキ「湯澤るうろ」も絶品で、スキーや温泉旅行のついでに立ち寄れます。",
    area: "南魚沼郡・越後湯沢",
    address: "新潟県南魚沼郡湯沢町湯沢2455-1（HATAGO井仙1F）",
    phone: "025-784-3361",
    imageUrl: "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff",
    style: "古民家カフェ",
    tags: ["温泉珈琲", "越後湯沢", "足湯", "米粉", "スキーリゾート", "お土産"],
    signatureMenu: "温泉珈琲、湯澤るうろ（米粉ロールケーキ）、温泉プリン",
    priceRange: "600〜900円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "越後湯沢駅から徒歩2分。旅館駐車場利用（宿泊客以外は確認要）",
    reservation: "not-needed",
    businessHours: "9:00〜18:00（LO 17:30）",
    closedDays: "無休",
    officialUrl: "https://www.hatago-isen.jp/mizuya/",
    mapUrl: map("水屋 越後湯沢 HATAGO井仙"),
    officialLinks: [
      { label: "公式サイト（HATAGO井仙）", url: "https://www.hatago-isen.jp/mizuya/", type: "website" },
      { label: "地図", url: map("水屋 越後湯沢 HATAGO井仙"), type: "map" },
    ],
    editorComment: "スキー・温泉旅行のついでに越後湯沢駅近で立ち寄れる好立地。入り口の足湯でひと休みしながら飲む温泉珈琲は、旅の特別な記憶になります。",
    highlight: "「飲める温泉水」で仕立てた水出し珈琲、越後湯沢駅徒歩2分",
    lastVerifiedAt: collectedAt,
    sources: [
      src("HATAGO井仙 水屋 食べログ", "https://tabelog.com/niigata/A1504/A150404/15001180/", "user-review", "営業時間・メニュー・口コミ確認"),
      src("越後湯沢観光協会", "https://www.e-yuzawa.gr.jp/", "tourism", "エリア情報確認"),
    ],
    faqs: [
      { question: "温泉珈琲とは何ですか？", answer: "越後湯沢・神立地方で湧く飲用可能な温泉水を使って淹れたコーヒーです。温泉水ならではのまろやかな風味が特徴で、水屋のオリジナルメニューです。" },
      { question: "足湯は誰でも利用できますか？", answer: "水屋の入り口付近に足湯があり、カフェ利用者も楽しめます。冬季は特に旅の疲れを癒すのにおすすめです。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "pepe-nagaoka",
    name: "COFFEE & SNACK PePe",
    description: "レンガ造りの外観が印象的な長岡の老舗純喫茶。昭和の雰囲気を残す店内で、まかないから生まれた名物のピザ風ナポリタンが常連客に長く愛されている。長岡駅から徒歩5分というアクセスの良さも魅力。",
    area: "長岡市",
    address: "新潟県長岡市東坂之上町2-2-9",
    imageUrl: "https://images.unsplash.com/photo-1554118811-1e0d58224f24",
    style: "古民家カフェ",
    tags: ["老舗", "純喫茶", "長岡", "レトロ", "ナポリタン", "夜営業"],
    signatureMenu: "ピザ風ナポリタン、アイスコーヒー",
    priceRange: "400〜1,000円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "9:00〜22:00",
    closedDays: "毎週水曜日",
    officialUrl: "#",
    mapUrl: map("COFFEE SNACK PePe 長岡市東坂之上町2-2-9"),
    officialLinks: [
      { label: "地図", url: map("COFFEE SNACK PePe 長岡市東坂之上町2-2-9"), type: "map" },
    ],
    editorComment: "「Things新潟」でも紹介された長岡の純喫茶名所。昭和レトロな外観と内装はノスタルジーを感じさせ、夜22時まで営業しているため長岡観光後の一杯にも最適です。",
    highlight: "レンガ造りが印象的、まかない発祥のナポリタンが名物の長岡老舗純喫茶",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Things新潟 PePe紹介記事", "https://things-niigata.jp/other/pepe/", "local-media", "店舗情報・名物メニュー確認"),
      src("食べログ PePe 長岡", "https://tabelog.com/niigata/A1502/A150201/15003059/", "user-review", "口コミ・評点確認"),
    ],
    faqs: [
      { question: "ピザ風ナポリタンとはどんな料理ですか？", answer: "まかない料理として生まれたPePeオリジナルのナポリタンです。チーズやトマトソースが乗ったボリューム感のある一皿で、長年通う常連客に愛されています。" },
      { question: "夜も営業していますか？", answer: "22時まで営業しています（水曜定休）。長岡市内での夕食後や観光の締めに立ち寄れる数少ない純喫茶です。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "west-cafe-nagaoka",
    name: "WEST CAFE 長岡店",
    description: "アウトドアライフストア「WEST」の長岡店内に併設されたカフェ。山形・長岡のコーヒー豆専門店「山倉」のオリジナルブレンド豆を使用し、アウトドアの雰囲気の中でこだわりの一杯を楽しめる。週替わりのフードメニューも人気。",
    area: "長岡市",
    address: "新潟県長岡市花園南1丁目71（アウトドアショップWEST内）",
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187",
    style: "コーヒースタンド",
    tags: ["アウトドア", "長岡", "スペシャルティ", "テイクアウト可", "セレクトショップ"],
    signatureMenu: "山倉オリジナルブレンドコーヒー、ラテ",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "WEST駐車場あり",
    reservation: "not-needed",
    businessHours: "平日 11:30〜18:00（LO 17:00）、土日祝 10:30〜18:00（LO 17:00）",
    closedDays: "毎週火曜日",
    officialUrl: "https://www.west-shop.co.jp/info/store/nagaokacafe",
    mapUrl: map("WEST CAFE 長岡 花園南1丁目71"),
    instagramUrl: "https://www.instagram.com/westcafenagaoka",
    officialLinks: [
      { label: "公式サイト", url: "https://www.west-shop.co.jp/info/store/nagaokacafe", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/westcafenagaoka", type: "instagram" },
      { label: "地図", url: map("WEST CAFE 長岡 花園南1丁目71"), type: "map" },
    ],
    editorComment: "アウトドアショップ内というユニークな立地ながら、コーヒーの質は本格派。駐車場が広いため車でのアクセスもしやすく、アウトドア用品を見ながらのコーヒータイムが楽しい。",
    highlight: "アウトドアショップ直営、山倉ブレンド豆の本格コーヒーを長岡市で",
    lastVerifiedAt: collectedAt,
    sources: [
      src("WEST CAFE 長岡店 公式", "https://www.west-shop.co.jp/info/store/nagaokacafe", "official", "営業時間・メニュー確認"),
      src("長岡カフェ2025年完全ガイド", "https://mise-repo.com/", "local-media", "口コミ・評判確認"),
    ],
    faqs: [
      { question: "アウトドア用品を見るだけでも入店できますか？", answer: "WEST長岡店はアウトドア用品店で、カフェは店内にあります。商品を見ながらコーヒーを楽しんでいただけます。" },
      { question: "コーヒー豆の購入はできますか？", answer: "使用している山倉のオリジナルブレンド豆は購入可能な場合があります。詳細は店頭でご確認ください。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "book-cafe-antenna",
    name: "ブックカフェ アンテナ",
    description: "絵本と古書が所狭しと並ぶ新潟市内のブックカフェ。豊富な本を自由に読みながらコーヒーやスパイシーなチキンマサラカレーを楽しめる。WiFi・コンセント完備で長居しやすく、本好きのローカルファンに愛される穴場的存在。",
    area: "新潟市中央区・上所",
    address: "新潟県新潟市中央区幸町13-7 幸ビル103",
    imageUrl: "https://images.unsplash.com/photo-1534040385115-33dcb3acba5b",
    style: "ブックカフェ",
    tags: ["ブックカフェ", "古書", "絵本", "WiFi", "電源", "カレー"],
    signatureMenu: "チキンマサラカレー（1,100円）、コーヒー",
    priceRange: "600〜1,100円",
    wifi: true,
    power: true,
    parking: true,
    reservation: "not-needed",
    businessHours: "変動あり（公式Instagram要確認）",
    closedDays: "不定休（公式Instagram要確認）",
    officialUrl: "#",
    mapUrl: map("ブックカフェアンテナ 新潟市中央区幸町13-7"),
    instagramUrl: "https://www.instagram.com/book_cafe_antenna",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/book_cafe_antenna", type: "instagram" },
      { label: "地図", url: map("ブックカフェアンテナ 新潟市中央区幸町13-7"), type: "map" },
    ],
    editorComment: "現金のみの営業ですが、WiFi・電源完備で長時間の滞在にも向いています。古書・絵本の蔵書は独特の選書センスがあり、読書好きには特別な空間です。",
    highlight: "絵本・古書に囲まれた穴場的ブックカフェ、WiFi・電源完備",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ブックカフェ アンテナ Instagram", "https://www.instagram.com/book_cafe_antenna", "sns", "営業情報・雰囲気確認"),
    ],
    faqs: [
      { question: "本は購入できますか？", answer: "古書・絵本の一部は購入可能な場合があります。気に入った本があればスタッフにお声がけください。" },
      { question: "支払い方法は？", answer: "現金のみの対応となっています。事前にご準備ください。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "awayuki-coffee-joetsu",
    name: "淡雪coffee",
    description: "新潟県上越市の住宅街に静かに佇むスペシャルティコーヒー専門店。世界各地の生産者から厳選した豆を常時6種以上取り揃え、浅煎りから深煎りまでその日の気分で選べる。バスクチーズケーキなど店内手作りの焼き菓子との組み合わせが人気で、全10席のコンパクトな空間がくつろぎを生み出す。上越エリアのコーヒー文化を牽引する実力派スペシャルティカフェ。",
    area: "上越市",
    address: "新潟県上越市滝寺（番地要確認）",
    imageUrl: "https://images.unsplash.com/photo-1511920170033-f8396924c348",
    style: "スペシャルティコーヒー",
    tags: ["スペシャルティコーヒー", "上越市", "ハンドドリップ", "焼き菓子", "バスクチーズケーキ", "コーヒースタンド"],
    signatureMenu: "ハンドドリップコーヒー（常時6種以上から選択）、バスクチーズケーキ",
    priceRange: "600〜900円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "敷地内2台、徒歩2分に4台",
    reservation: "not-needed",
    businessHours: "平日 11:00〜17:00、土日祝 11:00〜18:00",
    closedDays: "水・木曜",
    officialUrl: "https://awayuki.coffee/",
    mapUrl: map("淡雪coffee 上越市滝寺"),
    officialLinks: [
      { label: "公式サイト", url: "https://awayuki.coffee/", type: "website" },
      { label: "地図", url: map("淡雪coffee 上越市滝寺"), type: "map" },
    ],
    editorComment: "東京・福岡の一流ロースターが焙煎した高品質豆を手の届く価格で提供。上越エリアでコーヒーの聖地として定着しつつある一軒。",
    highlight: "スペシャルティコーヒー常時6種以上、上越住宅街に静かに輝くコーヒー専門店",
    lastVerifiedAt: collectedAt,
    sources: [
      src("淡雪coffee 公式サイト", "https://awayuki.coffee/", "official", "営業時間・メニュー確認"),
      src("タウン情報にいがた 淡雪coffee紹介", "https://tjniigata.jp/gourmet/202406cafeawayuki/", "local-media", "店舗紹介記事確認"),
    ],
    faqs: [
      { question: "どのようなコーヒーが飲めますか？", answer: "浅煎りから深煎りまで常時6種以上のスペシャルティコーヒーを取り揃え、ハンドドリップやエスプレッソなど幅広いスタイルで楽しめます。" },
      { question: "駐車場はありますか？", answer: "敷地内に2台、徒歩約2分の場所に4台の駐車スペースがあります。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "sekai-no-tonari-joetsu",
    name: "世界ノトナリ",
    description: "日本最古級の映画館「高田世界館」の隣に位置する、築90年の町家をリノベーションしたカフェ。アンティーク家具で統一されたレトロな空間は上越・高田の歴史的な街並みと調和する。地元焙煎所の新鮮な豆をハンドドリップで丁寧に淹れたコーヒーと、手作りハムが薫るサンドイッチが看板メニュー。歴史ある高田の街歩きの休憩スポットとして地元に愛される。",
    area: "上越市・高田",
    address: "新潟県上越市本町6-4-19",
    phone: "025-512-4982",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    style: "古民家カフェ",
    tags: ["古民家カフェ", "上越市", "高田", "町家リノベ", "レトロ", "ハンドドリップ", "観光"],
    signatureMenu: "ハンドドリップコーヒー、手作りハムのサンドイッチ",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "10:00〜17:00",
    closedDays: "月・火曜",
    officialUrl: "#",
    mapUrl: map("世界ノトナリ 上越市本町6-4-19"),
    officialLinks: [
      { label: "地図", url: map("世界ノトナリ 上越市本町6-4-19"), type: "map" },
    ],
    editorComment: "国の登録有形文化財「高田世界館」の隣という立地は唯一無二。地域の歴史的資産を活かしたカフェとして、高田観光の際に必ず立ち寄りたい一軒。",
    highlight: "日本最古級映画館の隣・築90年の町家カフェ、上越・高田の歴史と溶け込む",
    lastVerifiedAt: collectedAt,
    sources: [
      src("上越妙高タウン情報 世界ノトナリ紹介", "https://joetsu.yukiguni.town/gourmet/230598/", "local-media", "店舗紹介記事確認"),
      src("ヒトサラ 世界ノトナリ", "https://hitosara.com/0031367893/", "editorial", "店舗詳細確認"),
    ],
    faqs: [
      { question: "高田世界館とはどんな建物ですか？", answer: "日本最古級の映画館のひとつで、国の登録有形文化財にも指定されています。世界ノトナリはその隣の築90年の建物をリノベーションして開かれたカフェです。" },
      { question: "徒歩圏内に観光スポットはありますか？", answer: "高田城跡公園や高田の雁木通りなどが徒歩圏内にあり、カフェを起点とした街歩きを楽しめます。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "cafe-hayashi-joetsu",
    name: "CAFE HAYASHI",
    description: "上越市三和区の田園地帯に佇む、国の登録有形文化財「林富永邸」を活用した古民家カフェ。「文化財カフェ・発酵スイーツカフェ」をコンセプトに、塩麹・味噌・醤油麹などを使ったメニューを提供。NHK「ふるカフェ系 ハルさんの休日」にも登場した注目店で、週末限定の開店が一層の希少価値を生む。",
    area: "上越市・三和区",
    address: "新潟県上越市三和区神田2245-24",
    phone: "025-532-2602",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f",
    style: "古民家カフェ",
    tags: ["古民家カフェ", "上越市", "文化財", "発酵", "スイーツ", "塩麹", "週末限定", "NHK"],
    signatureMenu: "塩麹鶏ハムプレート、けんさん焼き（クルミ味噌）、発酵スイーツセット",
    priceRange: "800〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "金・土・日・祝のみ営業",
    closedDays: "月〜木曜（要事前確認）",
    officialUrl: "https://cafe-hayashi.com/",
    mapUrl: map("CAFE HAYASHI 上越市三和区神田2245-24"),
    officialLinks: [
      { label: "公式サイト", url: "https://cafe-hayashi.com/", type: "website" },
      { label: "地図", url: map("CAFE HAYASHI 上越市三和区神田2245-24"), type: "map" },
    ],
    editorComment: "NHKのカフェ番組に取り上げられた実績が示すとおり、建築・食・発酵文化が三位一体となった唯一無二の体験ができる。上越の農村エリアに足を伸ばす価値がある。",
    highlight: "国登録有形文化財の農家でNHK取材済み・週末限定の発酵スイーツカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("CAFE HAYASHI 公式サイト", "https://cafe-hayashi.com/", "official", "コンセプト・メニュー確認"),
      src("新潟観光ナビ CAFE HAYASHI紹介", "https://niigata-kankou.or.jp/blog/815", "tourism", "店舗紹介記事確認"),
    ],
    faqs: [
      { question: "予約は必要ですか？", answer: "週末・祝日限定の営業のため、確実に訪問したい場合は電話（025-532-2602）での事前予約が推奨です。" },
      { question: "発酵メニューとはどんな料理ですか？", answer: "塩麹を使った鶏ハムや、クルミ味噌のけんさん焼き、レモンと麹のドレッシングなど、発酵食材をふんだんに使ったメニューが揃います。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "rucchi-coffee-roaster-myoko",
    name: "Rucchi Coffee Roaster",
    description: "妙高市の新井駅前に2025年オープンした自家焙煎コーヒー専門店。店内に焙煎機を備え常時5種類の豆を取り揃えており、訪問者が試飲しながら好みの豆を選べる体験型スタイルが特徴。駅前という好立地で妙高・上越エリアを訪れるコーヒー愛好家の間で急速に注目が集まっている。",
    area: "妙高市",
    address: "新潟県妙高市朝日町1-1-1（新井駅前）",
    imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e",
    style: "ロースタリー",
    tags: ["ロースタリー", "妙高市", "自家焙煎", "試飲体験", "駅前", "コーヒー豆販売", "2025年新店"],
    signatureMenu: "5種の自家焙煎コーヒー豆から選ぶドリップコーヒー（試飲あり）",
    priceRange: "400〜700円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "5台あり",
    reservation: "not-needed",
    businessHours: "10:00〜18:00（変動あり、要確認）",
    closedDays: "日曜",
    officialUrl: "#",
    mapUrl: map("Rucchi Coffee Roaster 妙高市朝日町1-1-1"),
    officialLinks: [
      { label: "地図", url: map("Rucchi Coffee Roaster 妙高市朝日町1-1-1"), type: "map" },
    ],
    editorComment: "2025年オープンの新鋭ながら、駅前という抜群の立地と試飲体験できるスタイルで急速に支持を集めている。妙高への旅の出発点として訪れたい一軒。",
    highlight: "妙高・新井駅前の自家焙煎ロースタリー、5種の豆を試飲しながら選べる体験型",
    lastVerifiedAt: collectedAt,
    sources: [
      src("上越妙高タウン情報 Rucchi紹介", "https://joetsu.yukiguni.town/gourmet/311813/", "local-media", "オープン情報・店舗詳細確認"),
      src("web cocola Rucchi Coffee Roaster", "https://cocola.jp/rucchicoffeeroaster/", "local-media", "店舗詳細確認"),
    ],
    faqs: [
      { question: "コーヒー豆のお土産購入はできますか？", answer: "はい、店内で焙煎したコーヒー豆をお土産としてご購入いただけます。5種類以上の豆から選べます。" },
      { question: "JR新井駅からのアクセスは？", answer: "JR信越本線・新井駅の駅前に位置しており、電車でのアクセスも便利です。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "tsubame-coffee-tsubame",
    name: "ツバメコーヒー",
    description: "燕市吉田駅から徒歩圏内に位置する、壁一面に本が並ぶ書斎のような自家焙煎カフェ。ヘアサロンや無人書店を併設したユニークな複合施設として、燕三条エリアのカフェシーンをリードする存在。ものづくりの街・燕市らしく一杯ずつ丁寧に淹れたコーヒーと焼き菓子が人気。中川政七商店のメディアでも紹介されたローカル名店。",
    area: "燕市・吉田",
    address: "新潟県燕市吉田2760-1",
    phone: "0256-77-8781",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570",
    style: "自家焙煎",
    tags: ["自家焙煎", "燕三条", "ブックカフェ", "焼き菓子", "燕市", "ものづくり", "複合施設"],
    signatureMenu: "ツバメブレンド（500円）、スコーン・焼き菓子、クロックムッシュ",
    priceRange: "500〜900円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "11:00〜17:00",
    closedDays: "月・火・水曜",
    officialUrl: "https://tsubamecoffee.com/",
    mapUrl: map("ツバメコーヒー 燕市吉田2760-1"),
    instagramUrl: "https://www.instagram.com/tsubamecoffee/",
    officialLinks: [
      { label: "公式サイト", url: "https://tsubamecoffee.com/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/tsubamecoffee/", type: "instagram" },
      { label: "地図", url: map("ツバメコーヒー 燕市吉田2760-1"), type: "map" },
    ],
    editorComment: "中川政七商店の読みものにも紹介された、燕三条を代表するカフェ。ものづくりの街・燕市らしく、コーヒーの一杯にも職人気質が感じられる。",
    highlight: "壁一面の本に囲まれた書斎風自家焙煎カフェ、燕三条のものづくり精神が宿る名店",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ツバメコーヒー 公式サイト", "https://tsubamecoffee.com/", "official", "営業時間・メニュー確認"),
      src("中川政七商店の読みもの ツバメコーヒー紹介", "https://story.nakagawa-masashichi.jp/6240", "editorial", "店舗紹介記事確認"),
    ],
    faqs: [
      { question: "本や雑貨の購入もできますか？", answer: "同施設に無人書店が併設されており、本の購入が可能です。ヘアサロンも入居しています。" },
      { question: "燕三条駅からのアクセスは？", answer: "JR吉田駅から徒歩圏内にあります。車での来店も便利です。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
  {
    slug: "mother-cafe-tsubame",
    name: "Mother",
    description: "2024年春にオープンした、燕市吉田の2階に広がる観葉植物カフェ。緑あふれる店内は海外のボタニカルインテリアを彷彿とさせ、オーガニック食品も販売するセレクトショップを兼ねる。自家製プリンやコーヒーとともに植物に囲まれたゆったりとした時間を過ごせると、オープン直後から地元の若い女性を中心に支持を集めている。",
    area: "燕市・吉田",
    address: "新潟県燕市吉田幸町6-12 2F",
    imageUrl: "https://images.unsplash.com/photo-1490750967868-88df5691cc4e",
    style: "ガーデンカフェ",
    tags: ["植物カフェ", "オーガニック", "燕市", "2024年新店", "ボタニカル", "観葉植物", "インスタ映え"],
    signatureMenu: "ドリップコーヒー、自家製手作りプリン、トースト",
    priceRange: "600〜1,000円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "10:30〜18:00",
    closedDays: "火・水曜",
    officialUrl: "https://www.mayrow.jp/en/mother",
    mapUrl: map("Mother cafe 燕市吉田幸町6-12"),
    instagramUrl: "https://www.instagram.com/mother_cafe_art/",
    officialLinks: [
      { label: "公式サイト", url: "https://www.mayrow.jp/en/mother", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/mother_cafe_art/", type: "instagram" },
      { label: "地図", url: map("Mother cafe 燕市吉田幸町6-12"), type: "map" },
    ],
    editorComment: "2024年春オープンと新しいながら、インスタ映えする植物空間が話題を呼んでいる。燕三条エリアでボタニカルカフェ体験ができる貴重な存在。",
    highlight: "観葉植物に囲まれた非日常のボタニカル空間、オーガニックショップ併設の燕市新スポット",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Mother 公式サイト", "https://www.mayrow.jp/en/mother", "official", "コンセプト・メニュー確認"),
      src("ガタチラ Mother紹介", "https://gatachira.com/local/97939/", "local-media", "オープン情報確認"),
    ],
    faqs: [
      { question: "オーガニック商品の購入はできますか？", answer: "カフェに併設したオーガニックショップで、海外のオーガニック食品や雑貨を購入できます。" },
      { question: "混雑しやすい時間帯はいつですか？", answer: "週末の午後が特に混雑しやすい傾向があります。平日の午前〜昼前が比較的ゆっくり過ごせます。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-sweets-cafe"],
  },
  {
    slug: "camoco-cafe-ko-asobi-sado",
    name: "caMoco cafe 湖ASOBi",
    description: "築70年の舟小屋をリノベーションした、佐渡島の加茂湖に面したロケーションカフェ。加茂湖産の牡蠣を育てる漁師が手がける6次産業型カフェとして地元食材への深いこだわりが光る。大佐渡山脈と加茂湖を一望できる大きな窓から差し込む光の中で、牡蠣のパスタや旬魚のポキ丼を楽しむひとときは佐渡旅の白眉。両津港から車で5分というアクセスの良さも魅力。",
    area: "佐渡市・加茂湖畔",
    address: "新潟県佐渡市原黒553-28",
    phone: "0259-67-7467",
    imageUrl: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606",
    style: "ガーデンカフェ",
    tags: ["佐渡島", "湖畔", "漁師直営", "牡蠣", "ロケーションカフェ", "舟小屋リノベ", "地産地消", "絶景"],
    signatureMenu: "加茂湖産牡蠣のパスタ、旬魚のポキ丼、佐渡の地場食材プレート",
    priceRange: "1,000〜2,500円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "ランチ 11:30〜16:00 / ディナー 18:00〜21:00",
    closedDays: "水・木曜（祝日の場合は営業）",
    officialUrl: "https://camoco.cafe/",
    mapUrl: map("caMoco cafe 湖ASOBi 佐渡市原黒553-28"),
    instagramUrl: "https://www.instagram.com/camoco_cafe/",
    officialLinks: [
      { label: "公式サイト", url: "https://camoco.cafe/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/camoco_cafe/", type: "instagram" },
      { label: "地図", url: map("caMoco cafe 湖ASOBi 佐渡市原黒553-28"), type: "map" },
    ],
    editorComment: "佐渡観光の玄関口・両津港から車5分という好立地に加え、漁師直営ならではの鮮度抜群の加茂湖産牡蠣料理が食べられる唯一無二の存在。島旅の初日に訪れたい。",
    highlight: "牡蠣漁師が手がける湖畔の舟小屋カフェ、佐渡の食と絶景が一体となった特別体験",
    lastVerifiedAt: collectedAt,
    sources: [
      src("caMoco cafe 湖ASOBi 公式サイト", "https://camoco.cafe/", "official", "メニュー・営業時間確認"),
      src("新潟観光ナビ caMoco紹介", "https://niigata-kankou.or.jp/blog/874", "tourism", "取材記事確認"),
    ],
    faqs: [
      { question: "牡蠣料理は年中食べられますか？", answer: "加茂湖産の牡蠣は通年提供していますが、旬の時期（秋〜春）が特に身が大きく濃厚です。" },
      { question: "両津港からのアクセスは？", answer: "両津港から車で約5分と便利な場所にあります。フェリー到着後すぐに立ち寄れます。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-atmosphere-cafe"],
  },
  {
    slug: "lindbergh-coffee-roastery-murakami",
    name: "LINDBERGH COFFEE ROASTERY",
    description: "2025年5月に岩船駅前にオープンした、村上市初の本格コーヒーロースタリー。世界10か国から厳選した11種類のプレミアムコーヒー豆に加えオリジナルブレンド2種を取り揃え、直火式焙煎機で丁寧に仕上げた芳醇な一杯を提供する。Things新潟をはじめ地元メディアで話題のニューカマー。焙煎豆の購入も可能でお土産にも最適。",
    area: "村上市・岩船",
    address: "新潟県村上市岩船駅前29-8",
    phone: "0254-56-6014",
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd",
    style: "ロースタリー",
    tags: ["ロースタリー", "村上市", "自家焙煎", "直火式焙煎", "2025年新店", "コーヒー豆販売", "岩船"],
    signatureMenu: "世界10か国厳選豆のドリップコーヒー（11種）、オリジナルブレンド2種",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "5台あり",
    reservation: "not-needed",
    businessHours: "月・水・金 12:00〜18:00 / 日 10:00〜17:00",
    closedDays: "火・木・土曜",
    officialUrl: "#",
    mapUrl: map("LINDBERGH COFFEE ROASTERY 村上市岩船駅前29-8"),
    instagramUrl: "https://www.instagram.com/lindbergh_coffee/",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/lindbergh_coffee/", type: "instagram" },
      { label: "地図", url: map("LINDBERGH COFFEE ROASTERY 村上市岩船駅前29-8"), type: "map" },
    ],
    editorComment: "村上市はサーモンや地酒で知られるが、コーヒー文化も着実に育っている。2025年オープンのこの店はThings新潟で紹介されるなど早くも注目を集める村上のコーヒー界のホープ。",
    highlight: "2025年5月開業・岩船駅前の直火式ロースタリー、10か国以上の豆を揃える村上の新拠点",
    lastVerifiedAt: collectedAt,
    sources: [
      src("まいぷれ村上 LINDBERGH紹介", "https://murakami.mypl.net/shop/00000379680/", "local-media", "店舗情報確認"),
      src("Things新潟 LINDBERGH紹介", "https://things-niigata.jp/other/lindbergh-coffee-roastery/", "local-media", "店舗紹介記事確認"),
    ],
    faqs: [
      { question: "コーヒー豆のお土産購入はできますか？", answer: "はい、店内で焙煎したコーヒー豆をお土産としてご購入いただけます。世界10か国以上の豆から選べます。" },
      { question: "JR岩船駅からのアクセスは？", answer: "JR羽越本線・岩船駅の駅前に位置しており、電車でのアクセスも便利です。" },
    ],
    relatedRankingSlugs: ["niigata-cafe-best", "niigata-specialty-coffee"],
  },
];
