import type { Category } from "@/lib/types";
import { routes } from "@/lib/routes";

export const categories: Category[] = [
  {
    slug: "food",
    name: "グルメ",
    href: routes.food,
    description: "ラーメン、カフェなどの外食情報を地域、目的、移動手段から探せるカテゴリ。",
    tagline: "地域、味、雰囲気で選ぶ外食ガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "店舗カード"],
    searchFacets: ["地域", "ジャンル", "駐車場", "営業時間", "カフェ", "ラーメン"],
    plannedTopics: ["定食", "スイーツ", "居酒屋", "ランチ", "テイクアウト"],
    theme: { primary: "#a64019", accent: "#e5a126", background: "#fff6ea" },
    images: [{ key: "hero", url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", alt: "ラーメンと外食" }],
  },
  {
    slug: "health",
    name: "健康",
    href: routes.health,
    description: "プロテインを中心に、目的別・成分別・価格帯別で健康関連の商品を比較するカテゴリ。",
    tagline: "目的と成分で選ぶ健康ガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "商品カード"],
    searchFacets: ["目的", "種類", "価格帯", "栄養成分", "プロテイン"],
    plannedTopics: ["EAA・BCAA比較", "プロテインバー", "植物性プロテイン", "コンビニで買える健康食品"],
    theme: { primary: "#1e3a5f", accent: "#f97316", background: "#eff6ff" },
    images: [{ key: "hero", url: "https://images.unsplash.com/photo-1622818426197-d54f85b88690", alt: "プロテイン・フィットネス" }],
  },
  {
    slug: "beauty",
    name: "美容",
    href: routes.beauty,
    description: "美容室を年代・施術・エリアで選べるカテゴリ。カラー、髪質改善、ヘッドスパなどを整理。",
    tagline: "年代・施術・エリアで選ぶ美容ガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "サロンカード"],
    searchFacets: ["エリア", "年代", "施術", "価格帯", "子連れ", "メンズ"],
    plannedTopics: ["メンズ特化", "縮毛矯正", "頭皮ケア", "ブライダル", "長岡・三条"],
    theme: { primary: "#8b3a7e", accent: "#d4819e", background: "#fef0f6" },
    images: [{ key: "hero", url: "https://images.unsplash.com/photo-1746723378067-83a345ff3160", alt: "美容室・サロン" }],
  },
  {
    slug: "travel",
    name: "旅行",
    href: routes.travel,
    description: "宿泊施設、温泉、旅行会社、旅行アプリを旅の目的別に比較するカテゴリ。",
    tagline: "宿・移動・手配先で選ぶ旅行ガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "宿カード", "旅行会社カード"],
    searchFacets: ["エリア", "温泉", "食事", "駐車場", "旅行会社", "アプリ"],
    plannedTopics: ["宮城県", "秋田県", "福島県", "岩手県", "青森県"],
    theme: { primary: "#2d5a3d", accent: "#c8973a", background: "#f5f0e6" },
    images: [{ key: "hero", url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828", alt: "旅行計画とスマートフォン" }],
  },
  {
    slug: "leisure",
    name: "レジャー",
    href: routes.leisure,
    description: "アウトドア、インドア、雨の日、子連れ、車なしで選べるレジャースポットを整理するカテゴリ。",
    tagline: "天候、同行者、移動手段で選ぶおでかけガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "スポットカード"],
    searchFacets: ["エリア", "屋外", "屋内", "雨の日", "子連れ", "車なし"],
    plannedTopics: ["季節イベント", "温泉", "道の駅", "キャンプ", "半日モデルコース"],
    theme: { primary: "#176b87", accent: "#f4a261", background: "#edf9f8" },
    images: [{ key: "hero", url: "https://images.unsplash.com/photo-1766585464570-abb62d6cf7da", alt: "日本の庭園・レジャー" }],
  },
];
