import type { Category } from "@/lib/types";

export const categories: Category[] = [
  {
    slug: "protein",
    name: "プロテイン",
    href: "/protein",
    description: "女性・男性・ダイエット・初心者など目的別にプロテインを比較。栄養成分・価格・味・溶けやすさを実データで整理。",
    tagline: "目的・年代・価格帯で選ぶプロテインガイド",
    status: "live",
    contentTypes: ["ランキング", "商品カード", "栄養成分比較"],
    searchFacets: ["目的", "種類", "価格帯", "フレーバー", "国産・海外"],
    plannedTopics: ["EAA・BCAA比較", "プロテインバー", "植物性プロテイン", "プロテイン飲み方", "コンビニで買える"],
    theme: { primary: "#1e3a5f", accent: "#f97316", background: "#eff6ff" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1622818426197-d54f85b88690", alt: "プロテイン・フィットネス" },
    ],
  },
  {
    slug: "beauty",
    name: "美容室",
    href: "/beauty",
    description: "新潟の美容室を年代・施術・エリアで選べるカテゴリ。カラー・髪質改善・ヘッドスパ・パーマなど施術ごとの特徴と費用感を整理。",
    tagline: "年代・施術・エリアで選ぶ美容室ガイド",
    status: "live",
    contentTypes: ["ランキング", "サロンカード", "ガイド記事"],
    searchFacets: ["エリア", "年代", "施術", "価格帯", "子連れ", "メンズ"],
    plannedTopics: ["メンズ特化", "縮毛矯正", "頭皮ケア", "ブライダル", "長岡・三条"],
    theme: { primary: "#8b3a7e", accent: "#d4819e", background: "#fef0f6" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1746723378067-83a345ff3160", alt: "美容室・サロン" },
    ],
  },
  {
    slug: "ramen",
    name: "ラーメン",
    href: "/ramen",
    description: "新潟を中心に、エリア別・ジャンル別・目的別でラーメン店を探せるカテゴリ。",
    tagline: "地域、味、移動手段で選ぶ外食ガイド",
    status: "live",
    contentTypes: ["記事", "ランキング", "店舗カード"],
    searchFacets: ["エリア", "ジャンル", "駐車場", "営業時間", "個店", "夜営業"],
    plannedTopics: ["県内全域", "非チェーン個店", "深夜営業", "子連れ", "駅近", "観光ルート"],
    theme: { primary: "#a64019", accent: "#e5a126", background: "#fff6ea" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", alt: "ラーメン" },
    ],
  },
  {
    slug: "leisure",
    name: "レジャー",
    href: "/leisure",
    description: "新潟を中心に、アウトドア・インドア・雨の日・子連れ・車なしで選べるレジャースポットを整理するカテゴリ。",
    tagline: "天候、同行者、移動手段で選ぶおでかけガイド",
    status: "live",
    contentTypes: ["地域ページ", "ランキング", "スポットカード"],
    searchFacets: ["エリア", "屋外", "屋内", "雨の日", "子連れ", "車なし"],
    plannedTopics: ["季節イベント", "温泉", "道の駅", "キャンプ", "半日モデルコース"],
    theme: { primary: "#176b87", accent: "#f4a261", background: "#edf9f8" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1766585464570-abb62d6cf7da", alt: "日本の庭園・レジャー" },
    ],
  },
  {
    slug: "travel",
    name: "旅行",
    href: "/travel",
    description: "新潟・山形など各県の温泉旅館・宿泊施設を泉質・景観・旅スタイルで比較。ランキングと宿カードで整理しています。",
    tagline: "宿・温泉・旅スタイルで選ぶ旅行ガイド",
    status: "live",
    contentTypes: ["宿カード", "ランキング", "温泉エリア"],
    searchFacets: ["エリア", "温泉", "食事", "駐車場", "旅スタイル", "ひとり旅"],
    plannedTopics: ["宮城県", "秋田県", "福島県", "岩手県", "青森県"],
    theme: { primary: "#2d5a3d", accent: "#c8973a", background: "#f5f0e6" },
  },
  {
    slug: "travel-services",
    name: "旅行アプリ・旅行会社",
    href: "/travel-services",
    description: "旅行計画に使えるアプリと、県ごとの地域密着型旅行会社を比較。大手だけでは拾いにくい地元発着ツアー、団体手配、着地型の相談先を整理します。",
    tagline: "旅の計画、移動、手配先を実用目線で選ぶ",
    status: "live",
    contentTypes: ["アプリ比較", "旅行会社カード", "地域別ランキング", "調査ガイド"],
    searchFacets: ["旅行計画", "乗換", "予約", "地元旅行会社", "着地型ツアー", "団体旅行"],
    plannedTopics: ["新潟県の旅行会社", "旅行アプリ比較", "県別ローカル旅行会社", "バスツアー", "旅程管理"],
    theme: { primary: "#285a6f", accent: "#e08f3e", background: "#eef7f6" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828", alt: "旅行計画とスマートフォン" },
    ],
  },
  {
    slug: "cafe",
    name: "カフェ",
    href: "/cafe",
    description: "新潟・山形のカフェをスタイル・エリア・こだわりで選べるカテゴリ。スペシャルティコーヒー、古民家カフェ、スイーツ、WiFi環境など目的別に整理。",
    tagline: "コーヒーとスタイルで選ぶカフェガイド",
    status: "live",
    contentTypes: ["ランキング", "カフェカード", "ガイド記事"],
    searchFacets: ["エリア", "スタイル", "コーヒー", "スイーツ", "WiFi", "駐車場"],
    plannedTopics: ["テイクアウト専門", "モーニング", "読書カフェ", "ワーケーション", "ペット可"],
    theme: { primary: "#5c3317", accent: "#d4a853", background: "#fdf7ef" },
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93", alt: "カフェ・コーヒー" },
    ],
  },
  {
    slug: "gadget",
    name: "ガジェット",
    href: "/#categories",
    description: "使い勝手、価格、用途別の違いを整理するデジタル製品比較。",
    tagline: "用途と価格で迷いを減らす製品比較",
    status: "planned",
    contentTypes: ["比較表", "レビュー", "買い替えガイド"],
    searchFacets: ["用途", "価格帯", "サイズ", "互換性", "購入時期"],
    plannedTopics: ["スマホ周辺機器", "在宅ワーク", "撮影機材", "AI端末", "充電環境"],
    theme: { primary: "#344e6c", accent: "#8ecae6", background: "#eef5fb" },
  },
  {
    slug: "life",
    name: "暮らし",
    href: "/#categories",
    description: "毎日の選択を少し楽にする生活用品、サービス、地域情報。",
    tagline: "生活用品と地域サービスを実用目線で整理",
    status: "planned",
    contentTypes: ["選び方", "サービス比較", "地域情報"],
    searchFacets: ["目的", "価格", "地域", "家族構成", "手間"],
    plannedTopics: ["家事効率", "防災", "引越し", "サブスク", "地域手続き"],
    theme: { primary: "#4f6f52", accent: "#d2a24c", background: "#f3f7ef" },
  },
  {
    slug: "tools",
    name: "ツール比較",
    href: "/#categories",
    description: "SaaS、業務ツール、AIツールを目的別に比較するカテゴリ。",
    tagline: "仕事の導入判断に使えるツール比較",
    status: "planned",
    contentTypes: ["比較表", "導入ガイド", "料金整理"],
    searchFacets: ["職種", "規模", "料金", "連携", "AI対応"],
    plannedTopics: ["AIライティング", "予約管理", "CRM", "会計", "ノーコード"],
    theme: { primary: "#3f4f96", accent: "#f08a5d", background: "#f2f3ff" },
  },
];
