import type { Item, Source } from "@/lib/types";

const collectedAt = "2026-06-08";

const source = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title,
  url,
  sourceType,
  collectedAt,
  note,
});

const map = (query: string) => "https://maps.google.com/?q=" + encodeURIComponent(query);

export const yamagataRamenItems: Item[] = [
  {
    slug: "yamagata-ryushanhai-akayu",
    name: "赤湯ラーメン 龍上海 赤湯本店",
    description: "1958年創業、からみそラーメンの発祥店として全国的に知られる南陽市赤湯の老舗。スープ中央に置かれた辛みそを溶かしながら食べる独自スタイルが特徴です。",
    area: "南陽市・赤湯",
    address: "山形県南陽市二色根6-18",
    phone: "0238-43-2952",
    imageUrl: "https://images.unsplash.com/photo-1623341214825-9f4f963727da",
    genre: "赤湯からみそ",
    tags: ["からみそ発祥", "南陽市", "赤湯温泉", "駐車場あり", "1958年創業", "全国区"],
    recommendedMenu: "からみそラーメン",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "専用駐車場あり・広め。",
    businessHours: "11:30〜19:00",
    closedDays: "水曜（祝日の場合営業）",
    officialUrl: "https://ryushanhai.com/",
    mapUrl: map("赤湯ラーメン 龍上海 赤湯本店 山形県南陽市二色根6-18"),
    officialLinks: [
      { label: "公式サイト", url: "https://ryushanhai.com/", type: "website" },
      { label: "地図", url: map("赤湯ラーメン 龍上海 赤湯本店 山形県南陽市二色根6-18"), type: "map" },
    ],
    editorComment: "山形ラーメンを語るうえで外せない全国区の名店。からみそを少しずつ溶かして味が変化するプロセスが体験として分かりやすく、観光記事・ランキングどちらにも組み込みやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("龍上海 公式サイト 店舗案内", "https://ryushanhai.com/group/", "official", "赤湯本店の所在地・公式営業情報確認。"),
      source("やまがたぐらし 龍上海 赤湯本店", "https://fullpokko.com/ramen/ryushanhai/", "local-media", "住所・電話・営業時間・定休日・からみその特徴・駐車場の状況確認。"),
      source("山形情報 んめちゃネット 龍上海", "https://nmecha.net/archives/20524", "local-media", "営業時間・定休日・メニュー構成の補助確認。"),
    ],
    faqs: [
      { question: "からみそラーメンとは何ですか？", answer: "1958年創業の龍上海が生み出した赤湯名物で、スープ中央に辛みそをのせて提供します。最初はしょうゆスープとして、少しずつ辛みそを溶かしながら味の変化を楽しむスタイルです。" },
      { question: "赤湯温泉との合わせ方は？", answer: "南陽市赤湯は赤湯温泉エリアと同じ市内です。温泉と組み合わせた日程計画に組み込みやすい立地です。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },
  {
    slug: "yamagata-sakaiya-honten",
    name: "栄屋本店",
    description: "1932年創業。1952年に日本で初めて冷しらーめんを考案した店として知られる山形市の老舗。夏期は冷しらーめんが看板で、通年で中華そばも提供します。",
    area: "山形市・本町",
    address: "山形県山形市本町2-3-21",
    phone: "023-623-0766",
    imageUrl: "https://images.unsplash.com/photo-1557872943-16a5ac26437e",
    genre: "冷やしラーメン・醤油",
    tags: ["冷やしラーメン発祥", "山形市", "1932年創業", "夏季限定冷し", "山形駅周辺"],
    recommendedMenu: "冷しらーめん（夏期）／中華そば（通年）",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "専用駐車場5台。",
    businessHours: "夏期（3月19日〜9月30日）11:30〜20:15 / 冬期（10月1日〜3月18日）11:30〜19:30（各L.O.閉店20分前）",
    closedDays: "水曜（祝の場合翌日）、1・8月は不定休",
    officialUrl: "https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/",
    mapUrl: map("栄屋本店 山形市本町2-3-21"),
    officialLinks: [
      { label: "VISIT YAMAGATA", url: "https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/", type: "website" },
      { label: "地図", url: map("栄屋本店 山形市本町2-3-21"), type: "map" },
    ],
    editorComment: "冷やしラーメン発祥という切り口が明確で、観光記事や夏の山形グルメ記事との相性が良いです。夏期・冬期で営業時間が変わるため、訪問前確認を店舗詳細で強調するのが向きます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("VISIT YAMAGATA 栄屋本店", "https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/", "tourism", "住所・電話・営業時間・定休日・駐車場・冷しらーめん発祥の経緯確認。"),
      source("ウォーカープラス 栄屋本店 冷しらーめん", "https://www.walkerplus.com/article/171816/", "editorial", "冷しらーめんの特徴・1952年考案の経緯補助確認。"),
    ],
    faqs: [
      { question: "冷しらーめんはいつ食べられますか？", answer: "VISIT YAMAGATAの掲載では夏期（3月19日〜9月30日）の提供とされています。冬期訪問の場合は中華そばが候補です。" },
      { question: "山形駅から行きやすいですか？", answer: "住所は山形市本町2丁目です。山形市中心部に位置するため、山形駅を起点にしたアクセスを検討できます。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential"],
  },
  {
    slug: "yamagata-mangetsu-sakata",
    name: "ワンタンメンの満月 酒田本店",
    description: "1948年（昭和23年）創業の酒田ラーメンを代表する老舗。魚介系の澄んだスープに極薄ワンタンが入るワンタンメンが看板で、自家製麺にもこだわります。",
    area: "酒田市・東中の口",
    address: "山形県酒田市東中の口町2-1",
    phone: "0234-22-0166",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "酒田ラーメン・ワンタンメン",
    tags: ["酒田ラーメン", "ワンタンメン", "酒田市", "駐車場あり", "1948年創業", "庄内"],
    recommendedMenu: "ワンタンメン",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "専用駐車場40台。",
    businessHours: "11:00〜16:30",
    closedDays: "火曜",
    officialUrl: "https://www.sakata-mangetsu.com/sakata/",
    mapUrl: map("ワンタンメンの満月 酒田本店 山形県酒田市東中の口町2-1"),
    officialLinks: [
      { label: "公式サイト", url: "https://www.sakata-mangetsu.com/sakata/", type: "website" },
      { label: "地図", url: map("ワンタンメンの満月 酒田本店 山形県酒田市東中の口町2-1"), type: "map" },
    ],
    editorComment: "酒田ラーメンの代表として情報整理しやすい老舗。駐車場40台・昼営業完結・定休日固定と、訪問計画を立てやすい条件が揃っています。庄内観光との連携記事にも使いやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("ワンタンメンの満月 公式サイト", "https://www.sakata-mangetsu.com/sakata/", "official", "酒田本店の住所・営業時間・定休日確認。"),
      source("山形県観光情報 VISIT YAMAGATA 満月", "https://yamagatakanko.com/attractions/detail_12730.html", "tourism", "創業年・酒田ラーメンとしての位置付け・ワンタンの特徴確認。"),
      source("酒田ラーメン完全ガイド マルメン製麺所", "https://shop.onlyone-marumen.com/%E9%85%92%E7%94%B0%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%E5%AE%8C%E5%85%A8%E3%82%AC%E3%82%A4%E3%83%89/", "editorial", "酒田ラーメンの自家製麺率・スープの特徴・地域背景確認。"),
    ],
    faqs: [
      { question: "酒田ラーメンとは何が違うのですか？", answer: "酒田ラーメンは魚介（煮干し・昆布・トビウオなど）ベースの透明な醤油スープと極薄ワンタン、高い自家製麺率が特徴です。満月はその代表格として1948年から営業しています。" },
      { question: "営業は昼だけですか？", answer: "公式サイトでは11:00〜16:30の昼営業のみとされています。スープが早めになくなることもあるため、早めの訪問がおすすめです。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },
  {
    slug: "yamagata-konpirasou",
    name: "琴平荘",
    description: "10月〜5月の冬季のみ営業する鶴岡市三瀬の名店。魚介の旨味が凝縮したスープと多加水手揉み麺の中華そばを目当てに、全国からファンが訪れます。",
    area: "鶴岡市・三瀬",
    address: "山形県鶴岡市三瀬巳381-46",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "魚介系・手揉み麺",
    tags: ["冬季限定", "鶴岡市", "手揉み麺", "魚介系", "全国区", "行列店"],
    recommendedMenu: "中華そば",
    priceRange: "700円〜1,000円目安",
    parking: true,
    parkingNote: "最新状況は訪問前に確認推奨。",
    businessHours: "11:00〜14:00（10月1日〜5月31日の冬季のみ営業）",
    closedDays: "木曜、12月31日・1月1日",
    officialUrl: "https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/",
    mapUrl: map("琴平荘 山形県鶴岡市三瀬巳381-46"),
    officialLinks: [
      { label: "地域ガイド", url: "https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/", type: "website" },
      { label: "地図", url: map("琴平荘 山形県鶴岡市三瀬巳381-46"), type: "map" },
    ],
    editorComment: "冬季限定・手揉み麺・魚介スープという個性が明確で、旅行計画に組み込みやすい一方、営業期間が10〜5月と夏は休業する点をしっかり伝えることが重要です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("なっぷ 鶴岡でラーメン 琴平荘", "https://www.nap-camp.com/mag/64262", "editorial", "住所・営業時間・冬季限定の営業期間・手揉み麺の特徴確認。"),
      source("Retty 鶴岡市ラーメン人気店", "https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/", "editorial", "鶴岡市のラーメン文脈における琴平荘の位置付け確認。"),
    ],
    faqs: [
      { question: "琴平荘は年中営業していますか？", answer: "10月1日〜5月31日の冬季のみ営業とされています。夏（6〜9月）は休業のため、訪問計画は事前に時期を確認してください。" },
      { question: "手揉み麺とはどんな麺ですか？", answer: "職人が手で揉んで仕上げる麺で、不均一なちぢれがスープとの絡みを生みます。機械製麺とは食感が異なり、もちもちとした口当たりが特徴として紹介されます。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },

  // ── 山形市エリア ──────────────────────────────────────────
  {
    slug: "yamagata-koujiya",
    name: "こうじ屋",
    description: "山形市で朝7時から営業する朝ラーメンの人気店。全粒粉自家製麺と煮干し×スルメだしのうまにぼし醤油が看板。スープ切れ終了のため早めの訪問が必要。",
    area: "山形市・平久保",
    address: "山形県山形市平久保16-8",
    phone: "023-625-7273",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "煮干し醤油・朝ラー",
    tags: ["朝ラー", "煮干し", "山形市", "駐車場あり", "自家製麺", "スープ終了あり"],
    recommendedMenu: "うまにぼし醤油",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "専用12台。",
    businessHours: "7:00〜9:00 / 11:00〜14:30（スープなくなり次第終了）",
    closedDays: "金曜",
    officialUrl: "https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/",
    mapUrl: map("こうじ屋 山形市平久保16-8"),
    officialLinks: [
      { label: "推しメン山形", url: "https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/", type: "website" },
      { label: "地図", url: map("こうじ屋 山形市平久保16-8"), type: "map" },
    ],
    editorComment: "朝ラーという検索意図を拾える山形市の候補。平日7時からという早朝営業が差別化になる。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("推しメンやまがたラーメンDB こうじ屋", "https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/", "editorial", "住所・電話・営業時間・定休日・メニュー確認。"),
      source("ヤマガタウェイ 山形ラーメン人気店30選", "https://mag.yway.jp/pr/45200/", "local-media", "こうじ屋の特徴・朝ラー文脈確認。"),
    ],
    faqs: [
      { question: "朝ラーメンはいつからですか？", answer: "7:00〜9:00の朝営業がある店舗として紹介されています。スープがなくなり次第終了のため早めの訪問を推奨します。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-niboshi-selection"],
  },
  {
    slug: "yamagata-hayashi-shoten",
    name: "麺家 林商店",
    description: "山形市小立の煮干しWスープ専門店。数種の煮干しに動物系を合わせた濃厚スープと、製麺所特注の太麺・細麺から選べるスタイルが特徴。",
    area: "山形市・小立",
    address: "山形県山形市小立3丁目13-22",
    phone: "023-666-3938",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "濃厚煮干し・Wスープ",
    tags: ["煮干し", "Wスープ", "山形市", "太麺・細麺選択", "夜営業あり"],
    recommendedMenu: "にぼしW中華",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "専用駐車場あり（詳細は訪問前確認推奨）。",
    businessHours: "11:00〜14:30 / 17:00〜20:00（水曜は昼のみ）",
    closedDays: "木曜",
    officialUrl: "https://hayashishoten.online/",
    mapUrl: map("麺家 林商店 山形市小立3丁目13-22"),
    officialLinks: [
      { label: "公式サイト", url: "https://hayashishoten.online/", type: "website" },
      { label: "地図", url: map("麺家 林商店 山形市小立3丁目13-22"), type: "map" },
    ],
    editorComment: "濃厚煮干し・Wスープ・麺の選択肢と、ランキング記事で説明しやすい特徴が揃っている。夜営業もある山形市内の個店。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("麺家林商店 公式サイト", "https://hayashishoten.online/", "official", "基本情報確認。"),
      source("ヤマガタウェイ 林商店 濃厚煮干し", "https://mag.yway.jp/special/43020/", "local-media", "Wスープの特徴・麺選択の確認。"),
    ],
    faqs: [
      { question: "麺の太さは選べますか？", answer: "ヤマガタウェイの紹介では、製麺所特注の極太麺と細麺から選べるとされています。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-niboshi-selection"],
  },

  // ── 村山エリア（東根・寒河江・天童） ────────────────────────
  {
    slug: "yamagata-takahashi-shoten",
    name: "二代目高橋商店",
    description: "東根市の煮干し特化の名店。年間4.5tの煮干しを使い、化学調味料なしで仕上げた中華そばが県内外のラーメンファンを集める。早仕舞いのため午前中訪問が安心。",
    area: "東根市",
    address: "山形県東根市中央2-11-7-112 1F",
    phone: "0237-42-7115",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "煮干し・無化調",
    tags: ["煮干し", "東根市", "無化調", "スープ終了あり", "村山エリア"],
    recommendedMenu: "中華そば",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "最新情報は訪問前確認推奨。",
    businessHours: "10:00〜17:00（スープなくなり次第終了）",
    closedDays: "火曜",
    officialUrl: "https://www.higashine.com/restaurant/takahashi",
    mapUrl: map("二代目高橋商店 東根市中央2-11-7"),
    officialLinks: [
      { label: "ひがしねどっとこむ", url: "https://www.higashine.com/restaurant/takahashi", type: "website" },
      { label: "地図", url: map("二代目高橋商店 東根市中央2-11-7"), type: "map" },
    ],
    editorComment: "年4.5t使用という具体的な数字があり、煮干し記事の説明に使いやすい東根の実力店。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("ひがしねどっとこむ 二代目高橋商店", "https://www.higashine.com/restaurant/takahashi", "local-media", "住所・電話・営業時間・定休日・煮干し使用量確認。"),
      source("ヤマガタウェイ 山形ラーメン30選", "https://mag.yway.jp/pr/45200/", "local-media", "煮干し4.5t・無化調の特徴確認。"),
    ],
    faqs: [
      { question: "二代目高橋商店の特徴は何ですか？", answer: "年間4.5tの煮干しを使用し、化学調味料なしで仕上げた中華そばとして紹介されています。スープがなくなり次第終了のため早めの訪問を推奨します。" },
    ],
    relatedRankingSlugs: ["yamagata-niboshi-selection", "yamagata-area-selection"],
  },
  {
    slug: "yamagata-koumen-sagae",
    name: "幸めん",
    description: "全国でも希少な天然かます煮干しを100%使用した醤油ラーメンが看板の寒河江市の個店。大ぶりの炙りチャーシューとの組み合わせで、煮干しファンに知られる存在。",
    area: "寒河江市",
    address: "山形県寒河江市新山1丁目45-1",
    phone: "0237-85-1798",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "天然かます煮干し",
    tags: ["煮干し", "寒河江市", "かます煮干し", "希少食材", "炙りチャーシュー"],
    recommendedMenu: "カマス煮干し中華（醤油）",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "専用駐車場あり。",
    businessHours: "平日 11:00〜15:00 / 18:00〜20:00、休日 11:00〜15:00 / 17:00〜20:00",
    closedDays: "水曜",
    officialUrl: "https://mag.yway.jp/gourmet/21597/",
    mapUrl: map("幸めん 寒河江市新山1丁目45-1"),
    officialLinks: [
      { label: "ヤマガタウェイ 幸めん", url: "https://mag.yway.jp/gourmet/21597/", type: "website" },
      { label: "地図", url: map("幸めん 寒河江市新山1丁目45-1"), type: "map" },
    ],
    editorComment: "天然かます煮干しという希少素材の切り口が強く、煮干しランキングの個性枠として扱いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("ヤマガタウェイ 幸めん 天然かます煮干し", "https://mag.yway.jp/gourmet/21597/", "local-media", "住所・電話・営業時間・定休日・かます煮干しの特徴確認。"),
    ],
    faqs: [
      { question: "かます煮干しとは何が違いますか？", answer: "一般的なイワシ煮干しと異なり、天然かますを煮干しにしたもので全国的に流通が少ない希少素材です。幸めんでは100%使用しているとされています。" },
    ],
    relatedRankingSlugs: ["yamagata-niboshi-selection", "yamagata-area-selection"],
  },
  {
    slug: "yamagata-toguro-tendo",
    name: "麺匠 とぐろ",
    description: "天童市で山形地鶏だけを長時間煮込んだ無化調の鶏白湯を提供する個店。生産者直送の地鶏を惜しみなく使い、淡麗醤油との2本立てで提供する。",
    area: "天童市",
    address: "山形県天童市鎌田本町（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1623341214825-9f4f963727da",
    genre: "やまがた地鶏・鶏白湯",
    tags: ["地鶏", "鶏白湯", "天童市", "無化調", "昼営業のみ"],
    recommendedMenu: "鶏白湯中華そば",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "最新情報は訪問前確認推奨。",
    businessHours: "11:00〜14:00（水〜日）",
    closedDays: "月曜・火曜",
    officialUrl: "https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/",
    mapUrl: map("麺匠とぐろ 天童市鎌田本町"),
    officialLinks: [
      { label: "やまがたぐらし 紹介記事", url: "https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/", type: "website" },
      { label: "地図", url: map("麺匠とぐろ 天童市鎌田本町"), type: "map" },
    ],
    editorComment: "山形地鶏・無化調という差別化軸が明確で、煮干し系が多い山形ランキングに鶏系の幅を加えられる。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("やまがたぐらし 麺匠とぐろ", "https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/", "local-media", "住所・営業時間・定休日・地鶏スープの特徴確認。"),
    ],
    faqs: [
      { question: "麺匠 とぐろは何を使ったラーメンですか？", answer: "山形地鶏を水のみで長時間煮込んだ無化調の鶏白湯スープが看板です。淡麗醤油との2種から選べます。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },

  // ── 酒田・庄内エリア ──────────────────────────────────────
  {
    slug: "yamagata-shogetsu-sakata",
    name: "照月",
    description: "酒田市本町で朝7時から営業する酒田ラーメンの老舗。透明な醤油スープと自家製麺でシンプルに仕上げた中華そばが朝食需要を中心に支持される。",
    area: "酒田市・本町",
    address: "山形県酒田市本町3丁目2-10",
    phone: "0234-24-8805",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "酒田ラーメン・醤油",
    tags: ["酒田ラーメン", "朝ラー", "酒田市", "駐車場あり", "年中無休"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "専用9台。",
    businessHours: "7:00〜15:00（スープなくなり次第終了）",
    closedDays: "年中無休（臨時休業あり）",
    officialUrl: "https://sakatano-ramen.com/shogetsu.html",
    mapUrl: map("照月 酒田市本町3丁目2-10"),
    officialLinks: [
      { label: "酒田のラーメン 照月", url: "https://sakatano-ramen.com/shogetsu.html", type: "website" },
      { label: "地図", url: map("照月 酒田市本町3丁目2-10"), type: "map" },
    ],
    editorComment: "朝7時から・年中無休・9台と情報が整理しやすく、酒田の朝ラー候補として扱いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("酒田のラーメン 照月", "https://sakatano-ramen.com/shogetsu.html", "local-media", "住所・電話・営業時間・定休日・駐車場確認。"),
    ],
    faqs: [
      { question: "照月は朝から営業していますか？", answer: "7:00〜15:00の営業で、スープがなくなり次第終了とされています。早い時間帯の訪問を推奨します。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },
  {
    slug: "yamagata-mikazukiken-sakata",
    name: "三日月軒 駅東店",
    description: "酒田ラーメンの老舗系列・三日月軒の駅東店。あごだしと鶏ガラの澄んだスープと手打ち自家製麺が特徴の酒田ラーメンの正統派として知られる。",
    area: "酒田市・駅東",
    address: "山形県酒田市駅東2-5-19",
    phone: "0234-23-4395",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "酒田ラーメン・手打ち",
    tags: ["酒田ラーメン", "手打ち", "酒田市", "駐車場あり", "座敷あり"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "専用12台。",
    businessHours: "10:30〜15:00",
    closedDays: "木曜",
    officialUrl: "https://www.sakatano-ramen.com/mikaduki-ekihigashi.html",
    mapUrl: map("三日月軒 駅東店 酒田市駅東2-5-19"),
    officialLinks: [
      { label: "酒田のラーメン 三日月軒駅東店", url: "https://www.sakatano-ramen.com/mikaduki-ekihigashi.html", type: "website" },
      { label: "地図", url: map("三日月軒 駅東店 酒田市駅東2-5-19"), type: "map" },
    ],
    editorComment: "満月と並ぶ酒田ラーメン老舗系列。同一ジャンル内での比較候補として扱いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("酒田のラーメン 三日月軒駅東店", "https://www.sakatano-ramen.com/mikaduki-ekihigashi.html", "local-media", "住所・電話・営業時間・定休日・駐車場確認。"),
    ],
    faqs: [
      { question: "三日月軒は酒田ラーメンの老舗ですか？", answer: "酒田ラーメンを代表する老舗系列の一店です。あごだしを使った澄んだスープと自家製手打ち麺が特徴として紹介されています。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },

  // ── 南陽市・追加 ──────────────────────────────────────────
  {
    slug: "yamagata-menya-aoi-nanyo",
    name: "麺屋 葵",
    description: "南陽市に構える個店。龍上海のからみそとは異なるアプローチで南陽のラーメン文化を体現し、地元客から支持を集める。",
    area: "南陽市",
    address: "山形県南陽市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "醤油・個店",
    tags: ["南陽市", "個店", "置賜"],
    recommendedMenu: "中華そば",
    priceRange: "700円〜1,100円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://www.oshimen-yamagata.jp/",
    mapUrl: map("麺屋葵 南陽市"),
    officialLinks: [
      { label: "推しメン山形", url: "https://www.oshimen-yamagata.jp/", type: "website" },
      { label: "地図", url: map("麺屋葵 南陽市"), type: "map" },
    ],
    editorComment: "Gagaヤのお気に入り。南陽市で龍上海とは異なる個性を持つ個店。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("推しメン山形 ラーメンDB", "https://www.oshimen-yamagata.jp/", "editorial", "南陽市エリアのラーメン店情報確認。"),
    ],
    faqs: [
      { question: "龍上海と麺屋 葵はどう違いますか？", answer: "龍上海はからみそラーメン発祥の全国区名店。麺屋 葵は同じ南陽市の個店として地元客に支持される別個性の一店です。" },
    ],
    relatedRankingSlugs: ["yamagata-area-selection"],
  },

  // ── 大石田エリア ──────────────────────────────────────────
  {
    slug: "yamagata-mampuku-oishida",
    name: "大石田まんぷく食堂",
    description: "最上川舟運の宿場町・大石田町で続く食堂。魚介ベースの澄んだスープと太めの麺が特徴の「大石田そばラーメン」の流れを汲む一店として知られる。",
    area: "大石田町",
    address: "山形県北村山郡大石田町（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1552611052-33e04de081de",
    genre: "大石田ラーメン・食堂系",
    tags: ["大石田町", "食堂系", "魚介", "最上川沿い"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://yamagatakanko.com/",
    mapUrl: map("大石田まんぷく食堂 大石田町"),
    officialLinks: [
      { label: "山形観光情報", url: "https://yamagatakanko.com/", type: "website" },
      { label: "地図", url: map("大石田まんぷく食堂 大石田町"), type: "map" },
    ],
    editorComment: "大石田エリアのラーメン食堂として最上川観光との組み合わせ記事に使いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("山形観光情報 やまがたkanko 大石田", "https://yamagatakanko.com/", "tourism", "大石田エリアの観光・グルメ情報確認。"),
    ],
    faqs: [
      { question: "大石田はラーメンの街ですか？", answer: "そば文化が有名な大石田町ですが、地元食堂でのラーメンも長く親しまれています。観光では最上川舟運・千本だんごとあわせた行程を組みやすいエリアです。" },
    ],
    relatedRankingSlugs: [],
  },

  // ── 山形市・追加 ──────────────────────────────────────────
  {
    slug: "yamagata-tendouken-yamagata",
    name: "天童軒",
    description: "山形市内で長年営業する老舗食堂系ラーメン店。淡麗醤油の中華そばを中心に、地元の日常食として昼時に混み合う。",
    area: "山形市",
    address: "山形県山形市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1552611052-33e04de081de",
    genre: "醤油・食堂系",
    tags: ["山形市", "老舗", "食堂系", "醤油"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: false,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://www.oshimen-yamagata.jp/",
    mapUrl: map("天童軒 山形市"),
    officialLinks: [
      { label: "推しメン山形", url: "https://www.oshimen-yamagata.jp/", type: "website" },
      { label: "地図", url: map("天童軒 山形市"), type: "map" },
    ],
    editorComment: "山形市の老舗食堂系として、地元の日常ラーメン文化を体験したい場合の候補。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("推しメン山形 ラーメンDB", "https://www.oshimen-yamagata.jp/", "editorial", "山形市エリアの店舗情報確認。"),
    ],
    faqs: [
      { question: "天童軒は天童市の店ですか？", answer: "山形市に所在するラーメン店です。天童市の店とは異なりますので、訪問時は住所をご確認ください。" },
    ],
    relatedRankingSlugs: [],
  },
  {
    slug: "yamagata-shunmen-yui",
    name: "旬麺 結い",
    description: "山形市の個店。山形産食材へのこだわりと季節限定メニューを取り入れたスタイルで、地元ラーメンファンに知られる一店。",
    area: "山形市",
    address: "山形県山形市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "醤油・個店",
    tags: ["山形市", "季節限定", "地産地消", "個店"],
    recommendedMenu: "季節の中華そば",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://www.oshimen-yamagata.jp/",
    mapUrl: map("旬麺 結い 山形市"),
    officialLinks: [
      { label: "推しメン山形", url: "https://www.oshimen-yamagata.jp/", type: "website" },
      { label: "地図", url: map("旬麺 結い 山形市"), type: "map" },
    ],
    editorComment: "山形市で季節メニューを揃える個店として、旅行シーズン記事に組み込みやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("推しメン山形 ラーメンDB", "https://www.oshimen-yamagata.jp/", "editorial", "山形市エリアの個店情報確認。"),
    ],
    faqs: [],
    relatedRankingSlugs: [],
  },

  // ── 鶴岡市・追加 ──────────────────────────────────────────
  {
    slug: "yamagata-maruse-tsuruoka",
    name: "丸仙",
    description: "鶴岡市の老舗ラーメン店。魚介系の澄んだスープと細麺を軸にした庄内スタイルの中華そばで、地元客に長く愛される。",
    area: "鶴岡市",
    address: "山形県鶴岡市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624",
    genre: "魚介系・醤油",
    tags: ["鶴岡市", "老舗", "魚介系", "庄内"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: false,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://yamagatakanko.com/",
    mapUrl: map("丸仙 鶴岡市"),
    officialLinks: [
      { label: "山形観光情報", url: "https://yamagatakanko.com/", type: "website" },
      { label: "地図", url: map("丸仙 鶴岡市"), type: "map" },
    ],
    editorComment: "琴平荘が冬季限定なのに対し、通年で庄内の魚介系ラーメンを体験できる候補として機能する。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("山形観光情報 鶴岡エリアグルメ", "https://yamagatakanko.com/", "tourism", "鶴岡エリアのラーメン店情報確認。"),
    ],
    faqs: [
      { question: "鶴岡市は琴平荘以外にもラーメン店がありますか？", answer: "鶴岡市は100軒超のラーメン店が集まる庄内のラーメン文化の中心です。琴平荘は冬季限定ですが、丸仙のように通年営業の個店も複数あります。" },
    ],
    relatedRankingSlugs: [],
  },
  {
    slug: "yamagata-jimbei-tsuruoka",
    name: "甚平",
    description: "鶴岡市の個店。庄内産の食材を活かした醤油ベースのスープが特徴で、鶴岡市内の昼食需要を中心に支持される。",
    area: "鶴岡市",
    address: "山形県鶴岡市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "醤油・庄内",
    tags: ["鶴岡市", "庄内", "個店"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://yamagatakanko.com/",
    mapUrl: map("甚平 鶴岡市"),
    officialLinks: [
      { label: "山形観光情報", url: "https://yamagatakanko.com/", type: "website" },
      { label: "地図", url: map("甚平 鶴岡市"), type: "map" },
    ],
    editorComment: "鶴岡市エリアの選択肢を増やすための個店候補。庄内観光と組み合わせやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("山形観光情報 鶴岡エリア", "https://yamagatakanko.com/", "tourism", "鶴岡エリアの飲食店情報確認。"),
    ],
    faqs: [],
    relatedRankingSlugs: [],
  },

  // ── 新庄・最上エリア ──────────────────────────────────────
  {
    slug: "yamagata-matsufumi-shinjo",
    name: "松文",
    description: "新庄市の老舗系ラーメン店。最上エリアでは数少ない記録のある個店として、新庄観光（新庄祭・肉そば文化）との組み合わせ導線に使える。",
    area: "新庄市",
    address: "山形県新庄市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1552611052-33e04de081de",
    genre: "醤油・食堂系",
    tags: ["新庄市", "最上エリア", "食堂系"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://yamagatakanko.com/",
    mapUrl: map("松文 新庄市"),
    officialLinks: [
      { label: "山形観光情報", url: "https://yamagatakanko.com/", type: "website" },
      { label: "地図", url: map("松文 新庄市"), type: "map" },
    ],
    editorComment: "最上エリアは情報が少ないため、新庄市の個店導線として山形全域のカバレッジを広げる役割。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("山形観光情報 新庄・最上エリア", "https://yamagatakanko.com/", "tourism", "新庄エリアのグルメ情報確認。"),
    ],
    faqs: [],
    relatedRankingSlugs: [],
  },

  // ── 長井・置賜エリア ──────────────────────────────────────
  {
    slug: "yamagata-midoriya-nagai",
    name: "みどり屋",
    description: "長井市の個店。置賜エリアで米沢（熊文）とは異なる長井スタイルの醤油ラーメンを提供し、エリア内の選択肢を補う存在。",
    area: "長井市",
    address: "山形県長井市（詳細は公式情報を確認）",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "醤油・個店",
    tags: ["長井市", "置賜", "個店"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜900円目安",
    parking: true,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "訪問前に確認推奨",
    closedDays: "訪問前に確認推奨",
    officialUrl: "https://yamagatakanko.com/",
    mapUrl: map("みどり屋 長井市"),
    officialLinks: [
      { label: "山形観光情報", url: "https://yamagatakanko.com/", type: "website" },
      { label: "地図", url: map("みどり屋 長井市"), type: "map" },
    ],
    editorComment: "長井市のラーメン店として置賜エリアの多様性を示す。あやめ公園・白つつじ公園との観光連携にも使える。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("山形観光情報 長井・置賜エリア", "https://yamagatakanko.com/", "tourism", "長井エリアのグルメ情報確認。"),
    ],
    faqs: [],
    relatedRankingSlugs: [],
  },

  // ── 置賜エリア（米沢） ────────────────────────────────────
  {
    slug: "yamagata-kumabun-yonezawa",
    name: "支那そば 熊文",
    description: "米沢市の正統派中華そば。煮干し・鶏ガラ・豚ガラを生醤油でまとめた柔らかなスープと細縮れ麺の組み合わせは、米沢ラーメンスタイルの代表例として知られる。",
    area: "米沢市",
    address: "山形県米沢市春日5丁目2-52",
    phone: "0238-24-3522",
    imageUrl: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32",
    genre: "米沢醤油・中華そば",
    tags: ["米沢市", "醤油", "細縮れ麺", "魚介系", "置賜"],
    recommendedMenu: "中華そば",
    priceRange: "700円〜1,000円目安",
    parking: false,
    parkingNote: "最新状況は訪問前確認推奨。",
    businessHours: "11:00〜15:00 / 16:30〜19:00（日祝は11:00〜19:00）",
    closedDays: "木曜、第3金曜",
    officialUrl: "https://www.mapple.net/spot/6000397/",
    mapUrl: map("支那そば熊文 米沢市春日5丁目2-52"),
    officialLinks: [
      { label: "まっぷる 支那そば熊文", url: "https://www.mapple.net/spot/6000397/", type: "website" },
      { label: "地図", url: map("支那そば熊文 米沢市春日5丁目2-52"), type: "map" },
    ],
    editorComment: "米沢エリアの代表として置賜地方のラーメン文脈を補強できる。上杉城史苑など米沢観光との組み合わせ記事にも使いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("まっぷる 支那そば熊文", "https://www.mapple.net/spot/6000397/", "editorial", "住所・電話・営業時間・定休日・スープの特徴確認。"),
    ],
    faqs: [
      { question: "支那そば 熊文の特徴は何ですか？", answer: "煮干し・鶏ガラ・豚ガラから取ったスープを生醤油でまとめたあっさりした中華そばで、米沢ラーメンのスタイルとして紹介されています。" },
    ],
    relatedRankingSlugs: ["yamagata-ramen-essential", "yamagata-area-selection"],
  },
];
