import type { Item, Source } from "@/lib/types";

const collectedAt = "2026-06-15";

const source = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title,
  url,
  sourceType,
  collectedAt,
  note,
});

const map = (query: string) => "https://maps.google.com/?q=" + encodeURIComponent(query);

export const fukushimaRamenItems: Item[] = [
  {
    slug: "fukushima-bannai-kitakata",
    name: "坂内食堂",
    description: "1958年創業の喜多方ラーメンを代表する老舗。あっさりした豚骨清湯と平打ち熟成多加水麺、チャーシューを敷き詰めた肉そばで全国的に知られます。",
    area: "喜多方市・市街地",
    address: "福島県喜多方市細田7230",
    phone: "0241-22-0351",
    imageUrl: "https://www.bannaisyokudou.jp/wp/wp-content/uploads/2025/03/img_store_Inside.jpg",
    genre: "喜多方ラーメン",
    tags: ["喜多方", "老舗", "朝ラー", "駐車場あり", "1958年創業"],
    recommendedMenu: "肉そば",
    priceRange: "800円〜1,400円目安",
    parking: true,
    parkingNote: "公式掲載で第1〜第3駐車場あり。",
    businessHours: "9:00〜18:00（L.O.17:50）",
    closedDays: "水曜・木曜（祝日営業、年末年始・お盆等は変更あり）",
    officialUrl: "https://www.bannaisyokudou.jp/store/",
    mapUrl: map("坂内食堂 福島県喜多方市細田7230"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://www.bannaisyokudou.jp/store/", type: "website" },
      { label: "地図", url: map("坂内食堂 福島県喜多方市細田7230"), type: "map" },
    ],
    editorComment: "福島ラーメンの入口として最も説明しやすい喜多方の代表格。公式情報で住所・営業時間・駐車場まで追えるため、初回ランキングの軸にしやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("坂内食堂 公式 店舗案内", "https://www.bannaisyokudou.jp/store/", "official", "住所・電話・営業時間・定休日・駐車場・開業年確認。"),
      source("喜多方ラーメン坂内 公式", "https://ban-nai.com/", "official", "坂内食堂を本店に持つ喜多方ラーメンブランドとして確認。"),
    ],
    faqs: [
      { question: "坂内食堂は朝ラーできますか？", answer: "公式掲載では9:00から営業です。朝早めに喜多方ラーメンを食べたい読者に向きます。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-kitakata", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-hasegawa-kitakata",
    name: "食堂 はせ川",
    description: "喜多方市大荒井の人気店。喜多方らしい多加水縮れ麺と醤油スープを軸に、老舗系とは違う現代的な喜多方ラーメン候補として比較しやすい一店です。",
    area: "喜多方市・大荒井",
    address: "福島県喜多方市大荒井6",
    phone: "0241-24-5180",
    genre: "喜多方ラーメン",
    tags: ["喜多方", "醤油", "多加水麺", "行列店", "昼営業"],
    recommendedMenu: "醤油らーめん",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "駐車場あり。混雑時は最新案内確認推奨。",
    businessHours: "11:00〜15:00（スープがなくなり次第終了）",
    closedDays: "木曜、第1水曜、冬季は第3水曜も休み目安",
    officialUrl: map("食堂 はせ川 福島県喜多方市大荒井6"),
    mapUrl: map("食堂 はせ川 福島県喜多方市大荒井6"),
    officialLinks: [
      { label: "地図", url: map("食堂 はせ川 福島県喜多方市大荒井6"), type: "map" },
    ],
    editorComment: "坂内食堂だけでは喜多方が老舗寄りに見えるため、現代的な人気店として加える候補。営業時間は変動しやすいので訪問前確認を強調します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("まっぷる 食堂はせ川", "https://www.mapple.net/spot/7001335/", "editorial", "住所・電話・交通・店舗概要の補助確認。"),
      source("毎日がラーメン 食堂はせ川", "https://ramendays.jp/restaurant/iSopRk5gj510Axp1", "user-review", "営業時間・定休日の補助確認。"),
      source("Google Maps 食堂はせ川", map("食堂 はせ川 福島県喜多方市大荒井6"), "map", "所在地確認の補助。"),
    ],
    faqs: [
      { question: "はせ川は遅い時間でも入れますか？", answer: "昼営業中心でスープ切れ終了の案内が多いため、早めの訪問と直前確認をおすすめします。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-kitakata"],
  },
  {
    slug: "fukushima-kiichi-kitakata",
    name: "喜一",
    description: "喜多方で塩ラーメンを選ぶ時に候補にしたい人気店。醤油中心の喜多方ラーメンに、Sio系の選択肢を加えられる一店です。",
    area: "喜多方市・関柴",
    address: "福島県喜多方市関柴町上高額境田635-7",
    genre: "喜多方ラーメン・塩",
    tags: ["喜多方", "塩ラーメン", "朝営業", "駐車場あり", "売切終了"],
    recommendedMenu: "Sioラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "車訪問向き。混雑・売切に注意。",
    businessHours: "朝〜昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("喜一 福島県喜多方市関柴町上高額境田635-7"),
    mapUrl: map("喜一 福島県喜多方市関柴町上高額境田635-7"),
    officialLinks: [
      { label: "地図", url: map("喜一 福島県喜多方市関柴町上高額境田635-7"), type: "map" },
    ],
    editorComment: "喜多方の中でも塩系の需要を拾える候補。営業時間の追跡性は公式サイト型ではないため、地図情報・直近案内確認を前提にします。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 喜一", map("喜一 福島県喜多方市関柴町上高額境田635-7"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 喜一", "https://ramendb.supleks.jp/s/12231.html", "user-review", "喜多方の人気店・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "喜一は醤油以外を食べたい時に向きますか？", answer: "塩ラーメンを目的に喜多方を回る読者に向く候補です。売切・営業変更は訪問前に確認してください。" },
    ],
    relatedRankingSlugs: ["fukushima-kitakata", "fukushima-light-shoyu"],
  },
  {
    slug: "fukushima-ippei-kitakata",
    name: "喜多方ラーメン 一平",
    description: "朝ラー文化を感じたい時に候補にしたい喜多方の店舗。じとじと系など背脂を合わせたメニューもあり、王道だけでない喜多方の幅を出せます。",
    area: "喜多方市・松山町",
    address: "福島県喜多方市松山町村松石田1453",
    genre: "喜多方ラーメン・背脂",
    tags: ["喜多方", "朝ラー", "背脂", "駐車場あり", "車移動"],
    recommendedMenu: "じとじとラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は地図・店舗案内確認推奨。",
    businessHours: "朝〜昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("喜多方ラーメン 一平 福島県喜多方市松山町村松石田1453"),
    mapUrl: map("喜多方ラーメン 一平 福島県喜多方市松山町村松石田1453"),
    officialLinks: [
      { label: "地図", url: map("喜多方ラーメン 一平 福島県喜多方市松山町村松石田1453"), type: "map" },
    ],
    editorComment: "喜多方ラーメンの朝ラー・背脂という切り口を作れる。坂内・はせ川・喜一と並べると喜多方内の幅が出ます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 喜多方ラーメン 一平", map("喜多方ラーメン 一平 福島県喜多方市松山町村松石田1453"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 喜多方ラーメン 一平", "https://ramendb.supleks.jp/s/5703.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "一平は喜多方の王道と違いますか？", answer: "王道の醤油に加え、背脂を合わせたじとじと系の切り口で比較できます。" },
    ],
    relatedRankingSlugs: ["fukushima-kitakata", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-torashokudo-shirakawa",
    name: "とら食堂",
    description: "白河ラーメンの草分けとして知られる全国区の名店。手打ち中華、手揉み麺、醤油スープ、炭焼きチャーシューの文脈で白河ラーメンを説明する核になります。",
    area: "白河市・双石",
    address: "福島県白河市双石滝ノ尻1",
    phone: "0248-22-3426",
    genre: "白河ラーメン",
    tags: ["白河", "手打ち中華", "全国区", "駐車場あり", "売切終了"],
    recommendedMenu: "手打中華",
    priceRange: "900円〜1,500円目安",
    parking: true,
    parkingNote: "車訪問向き。混雑時は待ち時間に注意。",
    businessHours: "11:00〜14:30 / 16:00〜18:00（材料なくなり次第終了、休憩時間変動あり）",
    closedDays: "月曜",
    officialUrl: "https://x.com/torashokudo",
    mapUrl: map("とら食堂 福島県白河市双石滝ノ尻1"),
    officialLinks: [
      { label: "公式X", url: "https://x.com/torashokudo", type: "x" },
      { label: "地図", url: map("とら食堂 福島県白河市双石滝ノ尻1"), type: "map" },
    ],
    editorComment: "白河ラーメンを紹介するうえで最重要。公式Xで直近情報を追えるため、営業変更の多い人気店としても扱いやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("とら食堂 公式X", "https://x.com/torashokudo", "sns", "住所・電話・営業時間・定休日の確認先。"),
      source("るるぶ&more. とら食堂", "https://rurubu.jp/andmore/spot/80005358", "editorial", "白河ラーメン草分け・手打ち中華の特徴確認。"),
    ],
    faqs: [
      { question: "白河ラーメンとは何ですか？", answer: "手打ち・手揉みの縮れ麺と醤油スープを軸にした福島県南部のご当地ラーメンです。とら食堂はその代表格として知られます。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-shirakawa", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-suzuki-shirakawa",
    name: "手打中華 すずき",
    description: "白河市で手打ち中華を比較したい時の有力候補。とら食堂だけでなく、白河ラーメンの層の厚さを示す店舗として整理します。",
    area: "白河市・瀬戸原",
    address: "福島県白河市瀬戸原4-9",
    phone: "0248-22-3392",
    genre: "白河ラーメン",
    tags: ["白河", "手打ち中華", "醤油", "昼営業", "駐車場確認"],
    recommendedMenu: "手打中華",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "駐車場の最新状況は訪問前確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("手打中華 すずき 福島県白河市瀬戸原4-9"),
    mapUrl: map("手打中華 すずき 福島県白河市瀬戸原4-9"),
    officialLinks: [
      { label: "地図", url: map("手打中華 すずき 福島県白河市瀬戸原4-9"), type: "map" },
    ],
    editorComment: "白河ラーメンの比較軸に必要な店。公式サイト型ではないため、営業時間は控えめに掲載します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 手打中華 すずき", map("手打中華 すずき 福島県白河市瀬戸原4-9"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 手打中華 すずき", "https://ramendb.supleks.jp/s/4441.html", "user-review", "白河ラーメン候補としての確認補助。"),
    ],
    faqs: [
      { question: "とら食堂以外の白河ラーメン候補ですか？", answer: "はい。手打ち中華を比較したい時の候補として、とら食堂と合わせて検討できます。" },
    ],
    relatedRankingSlugs: ["fukushima-shirakawa", "fukushima-light-shoyu"],
  },
  {
    slug: "fukushima-kafuutei-shirakawa",
    name: "火風鼎",
    description: "白河ラーメンの流れを汲みつつ、独自の手打ち麺と燻し感のあるチャーシューで知られる人気店。公式Xで定休日・臨時休業を追いやすい点も強みです。",
    area: "白河市・鬼越",
    address: "福島県白河市鬼越44-16",
    genre: "白河ラーメン",
    tags: ["白河", "手打ち麺", "燻製チャーシュー", "公式SNS確認", "昼営業"],
    recommendedMenu: "手打中華",
    priceRange: "800円〜1,400円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は公式X確認推奨。",
    businessHours: "11:00〜15:00目安（最新は公式X確認）",
    closedDays: "火曜",
    officialUrl: "https://x.com/KaFuuTei_RaaMen",
    mapUrl: map("火風鼎 福島県白河市鬼越44-16"),
    officialLinks: [
      { label: "公式X", url: "https://x.com/KaFuuTei_RaaMen", type: "x" },
      { label: "地図", url: map("火風鼎 福島県白河市鬼越44-16"), type: "map" },
    ],
    editorComment: "白河ラーメンの中でも個性が出る候補。公式Xで休業情報を発信しているため、訪問前確認の導線を作りやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("火風鼎 公式X", "https://x.com/KaFuuTei_RaaMen", "sns", "定休日・臨時休業の確認先。"),
      source("ふくラボ 火風鼎", "https://www.fukulabo.net/shop/shop.shtml?s=275", "local-media", "白河ラーメンとしての特徴・チャーシューの補助確認。"),
    ],
    faqs: [
      { question: "火風鼎は白河ラーメンの王道ですか？", answer: "白河ラーメンの文脈にありつつ、手打ち麺やチャーシューの個性が強い比較候補です。" },
    ],
    relatedRankingSlugs: ["fukushima-shirakawa", "fukushima-light-shoyu"],
  },
  {
    slug: "fukushima-azuma-shirakawa",
    name: "あずま食堂",
    description: "白河市鬼越の白河ラーメン候補。とら食堂や火風鼎と近いエリアで比較しやすく、白河ラーメン巡りの厚みを作れます。",
    area: "白河市・鬼越",
    address: "福島県白河市鬼越28-3",
    genre: "白河ラーメン",
    tags: ["白河", "手打ち中華", "醤油", "車移動", "地元店"],
    recommendedMenu: "白味噌タンメン／手打中華",
    priceRange: "800円〜1,400円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は地図・店舗情報確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("あずま食堂 福島県白河市鬼越28-3"),
    mapUrl: map("あずま食堂 福島県白河市鬼越28-3"),
    officialLinks: [
      { label: "地図", url: map("あずま食堂 福島県白河市鬼越28-3"), type: "map" },
    ],
    editorComment: "白河エリアの掲載数を確保するための候補。手打ち中華だけでなく白味噌タンメンのような選択肢もあり、比較軸が作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps あずま食堂", map("あずま食堂 福島県白河市鬼越28-3"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース あずま食堂", "https://ramendb.supleks.jp/s/4434.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "白河で複数店回る候補になりますか？", answer: "鬼越周辺の白河ラーメン候補として、火風鼎などと比較しやすい立地です。" },
    ],
    relatedRankingSlugs: ["fukushima-shirakawa", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-uende-aizu",
    name: "うえんで 本店",
    description: "昭和47年創業の会津若松の老舗。中華そば、焼き鳥、北塩原村産の会津山塩を使う会津山塩らぁ麺が看板で、会津エリアの代表候補になります。",
    area: "会津若松市・大戸町",
    address: "福島県会津若松市大戸町上三寄大豆田11-3",
    phone: "0242-92-3253",
    imageUrl: "https://uende.jp/sys/wp-content/uploads/2023/07/b5c1ec405738f0fa76088e0ba0b3e079-1280x560.jpg",
    genre: "会津山塩ラーメン・中華そば",
    tags: ["会津若松", "会津山塩", "老舗", "駐車場あり", "昼営業"],
    recommendedMenu: "会津山塩らぁ麺",
    priceRange: "800円〜1,400円目安",
    parking: true,
    parkingNote: "郊外型店舗。駐車場の最新状況は公式確認推奨。",
    businessHours: "9:00〜15:00（L.O.14:30）",
    closedDays: "火曜",
    officialUrl: "https://www.uende.jp/",
    mapUrl: map("うえんで 本店 福島県会津若松市大戸町上三寄大豆田11-3"),
    officialLinks: [
      { label: "公式サイト", url: "https://www.uende.jp/", type: "website" },
      { label: "地図", url: map("うえんで 本店 福島県会津若松市大戸町上三寄大豆田11-3"), type: "map" },
    ],
    editorComment: "会津エリアの核。公式サイトで営業時間・店舗住所・会津山塩らぁ麺の情報を追えるため、福島全体の地域バランスを作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("うえんで 公式サイト", "https://www.uende.jp/", "official", "営業時間・店舗住所・会津山塩らぁ麺・創業情報を確認。"),
    ],
    faqs: [
      { question: "会津山塩ラーメンとは何ですか？", answer: "北塩原村産の山塩を使う塩ラーメンとして紹介され、会津エリアの個性を出しやすいメニューです。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-aizu-koriyama", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-gyunyuyashokudo-aizu",
    name: "牛乳屋食堂",
    description: "会津鉄道・芦ノ牧温泉駅近くの老舗食堂。ラーメンとソースカツ丼を組み合わせる会津らしい食堂使いができ、観光導線に入れやすい店です。",
    area: "会津若松市・芦ノ牧温泉駅",
    address: "福島県会津若松市大戸町上三寄香塩343",
    phone: "0242-92-2512",
    genre: "会津中華そば・食堂",
    tags: ["会津若松", "芦ノ牧温泉", "食堂", "ソースカツ丼", "観光導線"],
    recommendedMenu: "ラーメン／ソースカツ丼セット",
    priceRange: "800円〜1,600円目安",
    parking: true,
    parkingNote: "観光・車移動向き。最新状況は確認推奨。",
    businessHours: "昼・夕方営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("牛乳屋食堂 福島県会津若松市大戸町上三寄香塩343"),
    mapUrl: map("牛乳屋食堂 福島県会津若松市大戸町上三寄香塩343"),
    officialLinks: [
      { label: "地図", url: map("牛乳屋食堂 福島県会津若松市大戸町上三寄香塩343"), type: "map" },
    ],
    editorComment: "ラーメン単体より、会津観光・温泉・食堂文化と組み合わせて紹介しやすい店。宿泊/観光カテゴリとの内部導線にも向きます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 牛乳屋食堂", map("牛乳屋食堂 福島県会津若松市大戸町上三寄香塩343"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 牛乳屋食堂", "https://ramendb.supleks.jp/s/15991.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "牛乳屋食堂はラーメン専門店ですか？", answer: "食堂としての利用もでき、ラーメンとソースカツ丼の組み合わせで会津観光に組み込みやすい店です。" },
    ],
    relatedRankingSlugs: ["fukushima-aizu-koriyama", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-masuya-koriyama",
    name: "ますや本店 台新店",
    description: "郡山ブラックの代表候補として知られる店舗。濃い色の醤油スープで、喜多方・白河とは違う郡山のラーメン文化を説明できます。",
    area: "郡山市・台新",
    address: "福島県郡山市台新1-31-10",
    phone: "024-922-8646",
    genre: "郡山ブラック",
    tags: ["郡山", "郡山ブラック", "醤油", "駐車場あり", "地元名物"],
    recommendedMenu: "伝統の醤油ラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("ますや本店 台新店 福島県郡山市台新1-31-10"),
    mapUrl: map("ますや本店 台新店 福島県郡山市台新1-31-10"),
    officialLinks: [
      { label: "地図", url: map("ますや本店 台新店 福島県郡山市台新1-31-10"), type: "map" },
    ],
    editorComment: "郡山ブラックの検索意図を拾うために必要な店。福島ラーメンを喜多方・白河だけにしないための地域代表候補です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps ますや本店 台新店", map("ますや本店 台新店 福島県郡山市台新1-31-10"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース ますや本店 台新店", "https://ramendb.supleks.jp/s/2947.html", "user-review", "郡山ブラック候補としての確認補助。"),
    ],
    faqs: [
      { question: "郡山ブラックとは何ですか？", answer: "濃い色の醤油スープが印象的な郡山のご当地系ラーメンとして紹介されます。味の濃さは店ごとに異なります。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-aizu-koriyama"],
  },
  {
    slug: "fukushima-harukiya-koriyama",
    name: "春木屋 郡山分店",
    description: "荻窪中華そばの流れを郡山で楽しめる人気店。魚介香る醤油スープと自家製麺系の中華そばで、郡山の淡麗寄り候補として整理します。",
    area: "郡山市・桑野",
    address: "福島県郡山市桑野2-16-13",
    phone: "024-922-0141",
    genre: "醤油中華そば",
    tags: ["郡山", "中華そば", "魚介醤油", "自家製麺", "駐車場確認"],
    recommendedMenu: "中華そば",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "駐車場の最新状況は訪問前確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("春木屋 郡山分店 福島県郡山市桑野2-16-13"),
    mapUrl: map("春木屋 郡山分店 福島県郡山市桑野2-16-13"),
    officialLinks: [
      { label: "地図", url: map("春木屋 郡山分店 福島県郡山市桑野2-16-13"), type: "map" },
    ],
    editorComment: "郡山でブラック以外の醤油中華そばを入れるための候補。淡麗・魚介醤油のランキングに使いやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 春木屋 郡山分店", map("春木屋 郡山分店 福島県郡山市桑野2-16-13"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 春木屋 郡山分店", "https://ramendb.supleks.jp/s/5368.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "郡山ブラック以外の郡山候補ですか？", answer: "はい。魚介醤油の中華そばを選びたい時に、ますや本店と比較できます。" },
    ],
    relatedRankingSlugs: ["fukushima-aizu-koriyama", "fukushima-light-shoyu"],
  },
  {
    slug: "fukushima-dateya-fukushima",
    name: "伊達屋",
    description: "福島市で塩ラーメンを探す時の代表候補。鶏の旨味と端正な塩スープで知られ、県北エリアの淡麗・塩枠として入れたい一店です。",
    area: "福島市・南沢又",
    address: "福島県福島市南沢又下番匠田22",
    phone: "024-557-3841",
    genre: "塩ラーメン",
    tags: ["福島市", "塩", "淡麗", "駐車場あり", "行列店"],
    recommendedMenu: "塩ラーメン",
    priceRange: "900円〜1,500円目安",
    parking: true,
    parkingNote: "車訪問向き。混雑・売切に注意。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("伊達屋 福島県福島市南沢又下番匠田22"),
    mapUrl: map("伊達屋 福島県福島市南沢又下番匠田22"),
    officialLinks: [
      { label: "地図", url: map("伊達屋 福島県福島市南沢又下番匠田22"), type: "map" },
    ],
    editorComment: "福島市のラーメン候補として非常に強い。公式追跡性は弱いが、県北エリアの塩・淡麗ランキングには欠かせません。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 伊達屋", map("伊達屋 福島県福島市南沢又下番匠田22"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 伊達屋", "https://ramendb.supleks.jp/s/5372.html", "user-review", "店舗存在・塩ラーメン候補としての確認補助。"),
    ],
    faqs: [
      { question: "福島市で軽めのラーメンを選ぶなら向きますか？", answer: "塩・淡麗系を探す読者に向く候補です。混雑や営業変更は事前確認してください。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-light-shoyu", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-kuon-fukushima",
    name: "自家製麺 くをん",
    description: "福島駅周辺で自家製麺のつけ麺を探す時の候補。県北の駅近・濃厚系需要を拾えるため、喜多方・白河以外の都市部導線を作れます。",
    area: "福島市・福島駅周辺",
    address: "福島県福島市太田町8-1",
    genre: "自家製麺・つけ麺",
    tags: ["福島市", "福島駅", "つけ麺", "自家製麺", "駅近"],
    recommendedMenu: "つけ麺",
    priceRange: "900円〜1,500円目安",
    parking: false,
    parkingNote: "駅周辺店舗。周辺駐車場または公共交通利用を想定。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("自家製麺 くをん 福島県福島市太田町8-1"),
    mapUrl: map("自家製麺 くをん 福島県福島市太田町8-1"),
    officialLinks: [
      { label: "地図", url: map("自家製麺 くをん 福島県福島市太田町8-1"), type: "map" },
    ],
    editorComment: "福島駅周辺の検索導線を作るための店舗。県外旅行者が新幹線・駅周辺で探す用途に向きます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 自家製麺 くをん", map("自家製麺 くをん 福島県福島市太田町8-1"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 自家製麺 くをん", "https://ramendb.supleks.jp/s/23387.html", "user-review", "店舗存在・つけ麺候補としての確認補助。"),
    ],
    faqs: [
      { question: "福島駅から使いやすい候補ですか？", answer: "福島駅周辺でつけ麺・自家製麺を探す際の候補です。営業時間は直前確認してください。" },
    ],
    relatedRankingSlugs: ["fukushima-station-tourism"],
  },
  {
    slug: "fukushima-wakamusha-nihonmatsu",
    name: "麺処 若武者",
    description: "二本松駅周辺で福島鶏白湯や創作系を探す時の代表候補。県北〜中通りのラーメン導線を広げる店舗として整理します。",
    area: "二本松市・二本松駅周辺",
    address: "福島県二本松市本町2-86-1",
    phone: "0243-22-7107",
    genre: "鶏白湯・創作ラーメン",
    tags: ["二本松", "鶏白湯", "駅近", "創作系", "中通り"],
    recommendedMenu: "福島鶏白湯",
    priceRange: "900円〜1,500円目安",
    parking: true,
    parkingNote: "駅周辺・車利用どちらも検討可。最新状況は確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("麺処 若武者 福島県二本松市本町2-86-1"),
    mapUrl: map("麺処 若武者 福島県二本松市本町2-86-1"),
    officialLinks: [
      { label: "地図", url: map("麺処 若武者 福島県二本松市本町2-86-1"), type: "map" },
    ],
    editorComment: "喜多方・白河のご当地系とは違う、創作・鶏白湯の軸を作れる。二本松観光との連携も可能です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 麺処 若武者", map("麺処 若武者 福島県二本松市本町2-86-1"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 麺処 若武者", "https://ramendb.supleks.jp/s/26256.html", "user-review", "店舗存在・鶏白湯候補としての確認補助。"),
    ],
    faqs: [
      { question: "若武者はご当地ラーメンですか？", answer: "喜多方・白河のような伝統ご当地ではなく、鶏白湯や創作系の中通り候補として扱います。" },
    ],
    relatedRankingSlugs: ["fukushima-ramen-essential", "fukushima-station-tourism"],
  },
  {
    slug: "fukushima-chinan-iwaki",
    name: "チーナン食堂",
    description: "いわき市小名浜の老舗食堂系ラーメン候補。港町・小名浜観光と合わせやすく、浜通りのラーメン導線を作るために入れたい店です。",
    area: "いわき市・小名浜",
    address: "福島県いわき市小名浜栄町66-30",
    phone: "0246-92-2940",
    genre: "食堂系中華そば",
    tags: ["いわき", "小名浜", "食堂", "港町", "観光導線"],
    recommendedMenu: "ラーメン",
    priceRange: "700円〜1,200円目安",
    parking: true,
    parkingNote: "小名浜周辺の車移動向き。最新確認推奨。",
    businessHours: "昼・夕方営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("チーナン食堂 福島県いわき市小名浜栄町66-30"),
    mapUrl: map("チーナン食堂 福島県いわき市小名浜栄町66-30"),
    officialLinks: [
      { label: "地図", url: map("チーナン食堂 福島県いわき市小名浜栄町66-30"), type: "map" },
    ],
    editorComment: "浜通りを入れるための小名浜候補。ラーメン専門店というより食堂文化として、観光導線と相性が良いです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps チーナン食堂", map("チーナン食堂 福島県いわき市小名浜栄町66-30"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース チーナン食堂", "https://ramendb.supleks.jp/s/19565.html", "user-review", "店舗存在・食堂系ラーメン候補としての確認補助。"),
    ],
    faqs: [
      { question: "小名浜観光と合わせやすいですか？", answer: "小名浜エリアの食堂系候補として、港町観光やアクアマリンふくしま方面と合わせて検討できます。" },
    ],
    relatedRankingSlugs: ["fukushima-station-tourism", "fukushima-car-friendly"],
  },
  {
    slug: "fukushima-kaizan-iwaki",
    name: "海山",
    description: "いわき市で海沿い・浜通りのラーメン候補を増やす店舗。魚介や塩系のイメージと合わせて、県内の地域バランスを整えます。",
    area: "いわき市・好間",
    address: "福島県いわき市好間町下好間鬼越89-3",
    genre: "魚介・塩系",
    tags: ["いわき", "浜通り", "魚介", "塩", "車移動"],
    recommendedMenu: "塩ラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("海山 ラーメン 福島県いわき市好間町下好間鬼越89-3"),
    mapUrl: map("海山 ラーメン 福島県いわき市好間町下好間鬼越89-3"),
    officialLinks: [
      { label: "地図", url: map("海山 ラーメン 福島県いわき市好間町下好間鬼越89-3"), type: "map" },
    ],
    editorComment: "浜通り側の候補を厚くするための店舗。公式情報が弱いため、詳細は控えめに、車移動向けの候補として扱います。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 海山", map("海山 ラーメン 福島県いわき市好間町下好間鬼越89-3"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 海山", "https://ramendb.supleks.jp/s/21865.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "いわき市内で車移動向きですか？", answer: "好間エリアの車移動候補として扱います。営業状況は地図情報などで確認してください。" },
    ],
    relatedRankingSlugs: ["fukushima-car-friendly"],
  },
  {
    slug: "fukushima-koubou-sukagawa",
    name: "らーめん好房",
    description: "須賀川・県中エリアのラーメン候補。白河・郡山の間に位置するため、車移動で県中を回る読者向けに追加します。",
    area: "須賀川市・小作田",
    address: "福島県須賀川市小作田谷地1-2",
    genre: "醤油・塩",
    tags: ["須賀川", "県中", "醤油", "塩", "車移動"],
    recommendedMenu: "しょうゆらーめん",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "車訪問向き。最新状況は確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("らーめん好房 福島県須賀川市小作田谷地1-2"),
    mapUrl: map("らーめん好房 福島県須賀川市小作田谷地1-2"),
    officialLinks: [
      { label: "地図", url: map("らーめん好房 福島県須賀川市小作田谷地1-2"), type: "map" },
    ],
    editorComment: "県中エリアを郡山だけにしないための候補。白河方面への移動途中に組み込みやすい立地です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps らーめん好房", map("らーめん好房 福島県須賀川市小作田谷地1-2"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース らーめん好房", "https://ramendb.supleks.jp/s/4499.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "郡山・白河移動の途中で使えますか？", answer: "須賀川市の車移動候補として、県中〜県南の移動計画に組み込みやすいです。" },
    ],
    relatedRankingSlugs: ["fukushima-car-friendly", "fukushima-light-shoyu"],
  },
];
