import type { Item, Source } from "@/lib/types";

const collectedAt = "2026-06-15";

const source = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title,
  url,
  sourceType,
  collectedAt,
  note,
});

const map = (query: string) => "https://maps.google.com/?q=" + encodeURIComponent(query);

export const chibaRamenItems: Item[] = [
  {
    slug: "chiba-tomita-matsudo",
    name: "中華蕎麦 とみ田",
    description: "松戸を代表する濃厚豚骨魚介つけ麺の全国区店。20時間以上炊き込む濃厚スープと自家製極太麺を軸に、千葉ラーメンの都市型名店として外せない一店です。",
    area: "松戸市・松戸駅",
    address: "千葉県松戸市松戸1339 高橋ビル1F",
    phone: "047-368-8860",
    imageUrl: "https://www.tomita-cocoro.jp/wp2024/wp-content/themes/tomita/images/store-01.jpg",
    genre: "濃厚豚骨魚介つけ麺",
    tags: ["松戸", "つけ麺", "自家製麺", "全国区", "売切終了"],
    recommendedMenu: "つけ麺",
    priceRange: "1,000円〜2,000円目安",
    parking: false,
    parkingNote: "公式掲載では専用駐車場なし。周辺コインパーキング利用を想定。",
    businessHours: "11:00〜15:00（売り切れ・満枠になり次第終了）",
    closedDays: "水曜",
    officialUrl: "https://www.tomita-cocoro.jp/store/",
    mapUrl: map("中華蕎麦 とみ田 千葉県松戸市松戸1339"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://www.tomita-cocoro.jp/store/", type: "website" },
      { label: "TRY店舗情報", url: "https://tokyoramenoftheyear.com/ja/shop/shop-00346", type: "website" },
      { label: "地図", url: map("中華蕎麦 とみ田 千葉県松戸市松戸1339"), type: "map" },
    ],
    editorComment: "千葉ラーメンの初回候補として最も説明しやすい店。予約・整理・売切の運用が変わりやすいため、訪問前に公式案内を確認する前提で紹介します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("中華蕎麦とみ田 公式 店舗案内", "https://www.tomita-cocoro.jp/store/", "official", "所在地・電話・営業時間・定休日・駐車場情報を確認。"),
      source("Tokyo Ramen of the Year 中華蕎麦 とみ田", "https://tokyoramenoftheyear.com/ja/shop/shop-00346", "editorial", "TRYでの店舗情報とつけ麺文化における位置付けを補助確認。"),
    ],
    faqs: [
      { question: "とみ田は予約が必要ですか？", answer: "営業・受付方法が変わりやすく、売切や満枠終了もあります。訪問前に公式サイトまたは公式SNSで最新案内を確認してください。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-tsukemen-rich", "chiba-train-access"],
  },
  {
    slug: "chiba-tonikaku-matsudo",
    name: "兎に角 松戸店",
    description: "自家製太麺と魚介豚骨を軸に、ラーメン・つけ麺・油そばを展開する松戸の人気店。駅近で夜まで使いやすく、松戸ラーメン巡りの比較候補に向きます。",
    area: "松戸市・松戸駅東口",
    address: "千葉県松戸市根本462 比嘉ビル1F",
    phone: "047-361-4667",
    genre: "魚介豚骨・油そば",
    tags: ["松戸", "油そば", "つけ麺", "自家製太麺", "駅近"],
    recommendedMenu: "油そば／つけ麺",
    priceRange: "900円〜1,400円目安",
    parking: false,
    parkingNote: "駅近店舗。周辺コインパーキング利用を想定。",
    businessHours: "月〜金 11:00〜22:00 / 土日祝 10:00〜22:00",
    closedDays: "なし（年末年始・お盆休みの場合あり）",
    officialUrl: "https://www.tonikaku.co.jp/shop",
    mapUrl: map("兎に角 松戸店 千葉県松戸市根本462"),
    officialLinks: [
      { label: "公式店舗一覧", url: "https://www.tonikaku.co.jp/shop", type: "website" },
      { label: "地図", url: map("兎に角 松戸店 千葉県松戸市根本462"), type: "map" },
    ],
    editorComment: "とみ田と同じ松戸軸で、つけ麺だけでなく油そば需要も拾える。駅から近く夜まで営業するため、観光より日常利用寄りの検索にも対応できます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("兎に角 公式 店舗一覧", "https://www.tonikaku.co.jp/shop", "official", "松戸店の住所・電話・営業時間・定休日・メニューを確認。"),
    ],
    faqs: [
      { question: "兎に角は何を頼むのが分かりやすいですか？", answer: "魚介豚骨と自家製太麺の特徴を感じやすい油そば、つけ麺が初回候補です。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-tsukemen-rich", "chiba-train-access"],
  },
  {
    slug: "chiba-akebi-kashiwa",
    name: "AKEBI",
    description: "柏駅周辺で淡麗醤油とつけ麺を探す読者に入れたい実力店。公式Xで営業案内を出しているため、訪問前確認を前提に柏エリアの代表候補として整理します。",
    area: "柏市・柏駅",
    address: "千葉県柏市柏3丁目6-26",
    genre: "醤油・つけ麺",
    tags: ["柏", "淡麗醤油", "つけ麺", "駅近", "公式SNS確認"],
    recommendedMenu: "中華そば／つけ麺",
    priceRange: "900円〜1,400円目安",
    parking: false,
    parkingNote: "柏駅周辺のため公共交通・周辺駐車場利用を想定。",
    businessHours: "昼・夜営業中心（最新は公式X確認）",
    closedDays: "不定休（公式X確認）",
    officialUrl: "https://x.com/akebimen",
    mapUrl: map("AKEBI 千葉県柏市柏3丁目6-26"),
    officialLinks: [
      { label: "公式X", url: "https://x.com/akebimen", type: "x" },
      { label: "地図", url: map("AKEBI 千葉県柏市柏3丁目6-26"), type: "map" },
    ],
    editorComment: "濃厚つけ麺だけに寄らない柏の候補。公式SNS確認が前提になるため、ランキングでは営業時間の追跡性より味の幅とエリア代表性を評価します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("AKEBI 公式X", "https://x.com/akebimen", "sns", "営業案内・臨時情報の確認先。"),
      source("Google Maps AKEBI", map("AKEBI 千葉県柏市柏3丁目6-26"), "map", "所在地確認の補助。"),
    ],
    faqs: [
      { question: "AKEBIは営業時間をどこで確認すべきですか？", answer: "営業変更が出る可能性があるため、訪問前は公式Xの直近投稿を確認してください。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-tsukemen-rich", "chiba-train-access"],
  },
  {
    slug: "chiba-menya-kouji-kashiwa",
    name: "麺屋こうじ",
    description: "柏で濃厚豚骨魚介のつけ麺を探すときの代表候補。公式SNSで昼夜の営業案内が確認でき、松戸・柏の濃厚つけ麺軸を厚くできます。",
    area: "柏市・柏駅",
    address: "千葉県柏市旭町1丁目4-15",
    genre: "濃厚豚骨魚介・つけ麺",
    tags: ["柏", "つけ麺", "濃厚豚骨魚介", "駅近", "夜営業"],
    recommendedMenu: "つけ麺",
    priceRange: "900円〜1,500円目安",
    parking: false,
    parkingNote: "柏駅周辺のため周辺駐車場利用を想定。",
    businessHours: "昼の部 11:00〜17:00 / 夜の部 17:00〜22:00（公式SNS掲載ベース）",
    closedDays: "最新は公式SNS確認",
    officialUrl: "https://x.com/ko_ji_official",
    mapUrl: map("麺屋こうじ 千葉県柏市旭町1丁目4-15"),
    officialLinks: [
      { label: "公式X", url: "https://x.com/ko_ji_official", type: "x" },
      { label: "地図", url: map("麺屋こうじ 千葉県柏市旭町1丁目4-15"), type: "map" },
    ],
    editorComment: "松戸のとみ田だけでなく、柏にも濃厚魚介豚骨の導線を作るための店舗。駅近・夜営業の軸でランキングに組み込みやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("麺屋こうじ 公式X", "https://x.com/ko_ji_official", "sns", "営業時間・系列店舗案内の確認先。"),
      source("Google Maps 麺屋こうじ", map("麺屋こうじ 千葉県柏市旭町1丁目4-15"), "map", "所在地確認の補助。"),
    ],
    faqs: [
      { question: "柏で濃厚つけ麺を食べたい場合に向いていますか？", answer: "濃厚豚骨魚介を軸にしたつけ麺候補として向いています。混雑や営業変更は公式SNSで確認してください。" },
    ],
    relatedRankingSlugs: ["chiba-tsukemen-rich", "chiba-train-access"],
  },
  {
    slug: "chiba-komuro-ichikawa",
    name: "支那ソバ 小むろ",
    description: "行徳駅近くの淡麗支那そば・ワンタン麺の名店。TRYの店舗情報でも住所・営業時間・駐車場なしが整理されており、市川エリアの淡麗系代表として扱いやすい一店です。",
    area: "市川市・行徳",
    address: "千葉県市川市末広1-18-13 SATOMI四番館",
    phone: "047-359-8106",
    genre: "支那そば・ワンタン麺",
    tags: ["市川", "行徳", "淡麗醤油", "ワンタン麺", "駅近"],
    recommendedMenu: "ワンタンメン",
    priceRange: "900円〜1,500円目安",
    parking: false,
    parkingNote: "TRY掲載では駐車場なし。",
    businessHours: "10:00〜16:00（材料なくなり次第終了）",
    closedDays: "火曜",
    officialUrl: "https://tokyoramenoftheyear.com/ja/shop/shop-00056",
    mapUrl: map("支那ソバ 小むろ 千葉県市川市末広1-18-13"),
    officialLinks: [
      { label: "TRY店舗情報", url: "https://tokyoramenoftheyear.com/ja/shop/shop-00056", type: "website" },
      { label: "地図", url: map("支那ソバ 小むろ 千葉県市川市末広1-18-13"), type: "map" },
    ],
    editorComment: "濃厚系が目立つ千葉ランキングに淡麗・ワンタンの軸を作れる。公共交通で訪れやすい市川エリア候補として強いです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Tokyo Ramen of the Year 支那ソバ 小むろ", "https://tokyoramenoftheyear.com/ja/shop/shop-00056", "editorial", "住所・営業時間・休日・席数・駐車場なしを確認。"),
    ],
    faqs: [
      { question: "小むろは車で行きやすいですか？", answer: "TRY掲載では駐車場なしです。行徳駅からの徒歩アクセスか周辺駐車場の確認をおすすめします。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-light-shoyu", "chiba-train-access"],
  },
  {
    slug: "chiba-konmen-motoyawata",
    name: "魂麺",
    description: "本八幡駅周辺で長く支持される創作系ラーメン店。駅からのアクセスがよく、夜利用の候補にもなるため、市川・船橋周辺の都市部ラーメン枠で整理します。",
    area: "市川市・本八幡",
    address: "千葉県市川市南八幡3丁目6-17",
    phone: "047-370-5300",
    genre: "醤油・創作ラーメン",
    tags: ["本八幡", "市川", "駅近", "夜利用", "創作系"],
    recommendedMenu: "魂麺",
    priceRange: "800円〜1,300円目安",
    parking: false,
    parkingNote: "駅近店舗。公共交通・周辺駐車場利用を想定。",
    businessHours: "昼・夜営業中心（最新は地図・公式情報確認）",
    closedDays: "木曜目安（最新確認推奨）",
    officialUrl: map("魂麺 千葉県市川市南八幡3丁目6-17"),
    mapUrl: map("魂麺 千葉県市川市南八幡3丁目6-17"),
    officialLinks: [
      { label: "地図", url: map("魂麺 千葉県市川市南八幡3丁目6-17"), type: "map" },
    ],
    editorComment: "本八幡駅周辺の検索導線を作るための候補。公式サイトの追跡性は弱いため、営業時間は断定せず、エリアとジャンルの補完として扱います。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 魂麺", map("魂麺 千葉県市川市南八幡3丁目6-17"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 魂麺", "https://ramendb.supleks.jp/s/1237.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "魂麺の営業時間は固定ですか？", answer: "変更される可能性があるため、地図情報や直近の店舗案内を確認してから訪問してください。" },
    ],
    relatedRankingSlugs: ["chiba-light-shoyu", "chiba-train-access"],
  },
  {
    slug: "chiba-sugitaya-yukou",
    name: "ラーメン杉田家 千葉祐光店",
    description: "家系総本山吉村家直系1号店の杉田家が千葉市で展開する店舗。朝5時から営業し、専用・第2駐車場情報も公式に掲載されている車移動向けの有力候補です。",
    area: "千葉市中央区・祐光",
    address: "千葉県千葉市中央区祐光4-17-7",
    phone: "043-441-8008",
    imageUrl: "https://sugitaya.com/ieie/wp-content/uploads/2024/02/x-yuukou.jpg",
    genre: "家系ラーメン",
    tags: ["千葉市", "家系", "朝ラー", "駐車場あり", "吉村家直系"],
    recommendedMenu: "ラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "公式掲載で第2駐車場6台あり。",
    businessHours: "5:00〜23:00（L.O.22:30）",
    closedDays: "月曜",
    officialUrl: "https://sugitaya.com/shop/",
    mapUrl: map("ラーメン杉田家 千葉祐光店 千葉県千葉市中央区祐光4-17-7"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://sugitaya.com/shop/", type: "website" },
      { label: "地図", url: map("ラーメン杉田家 千葉祐光店 千葉県千葉市中央区祐光4-17-7"), type: "map" },
    ],
    editorComment: "朝5時営業と駐車場情報が非常に強い。千葉市内の車移動・朝ラーランキングで核になる店です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("ラーメン杉田家 公式 店舗案内", "https://sugitaya.com/shop/", "official", "千葉祐光店の住所・電話・営業時間・定休日・駐車場を確認。"),
    ],
    faqs: [
      { question: "杉田家 千葉祐光店は朝ラーメンに使えますか？", answer: "公式掲載では5:00から営業です。月曜定休や臨時変更は訪問前に確認してください。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-car-friendly", "chiba-morning-night"],
  },
  {
    slug: "chiba-sugitaya-chibaekimae",
    name: "ラーメン杉田家 千葉駅前店",
    description: "千葉駅・千葉中央周辺から使いやすい杉田家の駅前店舗。家系を公共交通で食べたい読者向けに、祐光店と使い分けて紹介できます。",
    area: "千葉市中央区・千葉駅前",
    address: "千葉県千葉市中央区中央2-2-6 マコトヤビル1F",
    phone: "043-305-4488",
    genre: "家系ラーメン",
    tags: ["千葉駅", "家系", "駅近", "夜営業", "吉村家直系"],
    recommendedMenu: "ラーメン",
    priceRange: "800円〜1,300円目安",
    parking: false,
    parkingNote: "駅前店舗。周辺駐車場利用を想定。",
    businessHours: "11:00〜23:00（L.O.22:30）",
    closedDays: "月曜",
    officialUrl: "https://sugitaya.com/shop/",
    mapUrl: map("ラーメン杉田家 千葉駅前店 千葉市中央区中央2-2-6"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://sugitaya.com/shop/", type: "website" },
      { label: "地図", url: map("ラーメン杉田家 千葉駅前店 千葉市中央区中央2-2-6"), type: "map" },
    ],
    editorComment: "祐光店は車・朝ラー、千葉駅前店は駅近・夜利用という棲み分けができる。千葉市中心部の検索導線に向いています。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("ラーメン杉田家 公式 店舗案内", "https://sugitaya.com/shop/", "official", "千葉駅前店の住所・電話・営業時間・定休日を確認。"),
    ],
    faqs: [
      { question: "祐光店と千葉駅前店はどう選べばよいですか？", answer: "車や朝ラーなら祐光店、千葉駅周辺から徒歩で行くなら千葉駅前店が選びやすいです。" },
    ],
    relatedRankingSlugs: ["chiba-train-access", "chiba-morning-night"],
  },
  {
    slug: "chiba-kaminari-chibaekimae",
    name: "雷 千葉駅前店",
    description: "とみ田グループの濃厚・ガッツリ系ブランド。千葉駅周辺でパンチのある一杯を探す読者に向けて、公式店舗案内で営業時間まで追跡できます。",
    area: "千葉市中央区・千葉駅前",
    address: "千葉県千葉市中央区富士見2-5-18",
    phone: "043-301-3640",
    imageUrl: "https://www.tomita-cocoro.jp/wp2024/wp-content/themes/tomita/images/store-10.jpg",
    genre: "濃厚・ガッツリ系",
    tags: ["千葉駅", "とみ田グループ", "ガッツリ", "夜営業", "駅近"],
    recommendedMenu: "雷そば",
    priceRange: "900円〜1,500円目安",
    parking: false,
    parkingNote: "公式掲載では駐車場なし。",
    businessHours: "11:00〜23:00",
    closedDays: "なし",
    officialUrl: "https://www.tomita-cocoro.jp/store/",
    mapUrl: map("雷 千葉駅前店 千葉県千葉市中央区富士見2-5-18"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://www.tomita-cocoro.jp/store/", type: "website" },
      { label: "地図", url: map("雷 千葉駅前店 千葉県千葉市中央区富士見2-5-18"), type: "map" },
    ],
    editorComment: "千葉駅前で夜まで使えるガッツリ系。とみ田グループの公式情報で追えるため、都市部ランキングに入れやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("中華蕎麦とみ田 公式 店舗案内", "https://www.tomita-cocoro.jp/store/", "official", "雷 千葉駅前店の住所・電話・営業時間・定休日・駐車場情報を確認。"),
    ],
    faqs: [
      { question: "雷 千葉駅前店はとみ田と同じ味ですか？", answer: "とみ田グループの別ブランドで、つけ麺専門というより濃厚・ガッツリ系の一杯を探す時に向きます。" },
    ],
    relatedRankingSlugs: ["chiba-train-access", "chiba-morning-night"],
  },
  {
    slug: "chiba-kaminari-funabashi",
    name: "雷 船橋駅前店",
    description: "船橋駅から徒歩圏で使えるとみ田グループのガッツリ系店舗。船橋エリアの駅近ラーメン候補を厚くするために、千葉駅前店と合わせて整理します。",
    area: "船橋市・船橋駅前",
    address: "千葉県船橋市本町4丁目42-2",
    phone: "047-411-6725",
    genre: "濃厚・ガッツリ系",
    tags: ["船橋", "とみ田グループ", "駅近", "ガッツリ", "夜営業"],
    recommendedMenu: "雷そば",
    priceRange: "900円〜1,500円目安",
    parking: false,
    parkingNote: "公式掲載では駐車場なし。",
    businessHours: "11:00〜22:00",
    closedDays: "なし",
    officialUrl: "https://www.tomita-cocoro.jp/store/",
    mapUrl: map("雷 船橋駅前店 千葉県船橋市本町4丁目42-2"),
    officialLinks: [
      { label: "公式店舗案内", url: "https://www.tomita-cocoro.jp/store/", type: "website" },
      { label: "地図", url: map("雷 船橋駅前店 千葉県船橋市本町4丁目42-2"), type: "map" },
    ],
    editorComment: "船橋駅前の駅近候補。観光色より日常利用が強いが、沿線検索と夜利用のランキングに使えます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("中華蕎麦とみ田 公式 店舗案内", "https://www.tomita-cocoro.jp/store/", "official", "雷 船橋駅前店の住所・電話・営業時間・定休日・駐車場情報を確認。"),
    ],
    faqs: [
      { question: "船橋駅から徒歩で行けますか？", answer: "公式店舗案内ではJR船橋駅より徒歩4分とされています。" },
    ],
    relatedRankingSlugs: ["chiba-train-access", "chiba-morning-night"],
  },
  {
    slug: "chiba-umenoya-takeoka",
    name: "梅乃家",
    description: "富津・竹岡式ラーメンを語るうえで外せない老舗候補。乾麺、濃い醤油だれ、玉ねぎという地域性が強く、内房ドライブの目的地として紹介しやすい店です。",
    area: "富津市・竹岡",
    address: "千葉県富津市竹岡410",
    phone: "0439-67-0920",
    genre: "竹岡式ラーメン",
    tags: ["富津", "竹岡式", "内房", "老舗", "ドライブ"],
    recommendedMenu: "ラーメン",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "店舗周辺駐車場の最新状況は訪問前確認推奨。",
    businessHours: "昼営業中心（売切終了・最新確認推奨）",
    closedDays: "不定休・臨時休業あり（最新確認推奨）",
    officialUrl: map("梅乃家 千葉県富津市竹岡410"),
    mapUrl: map("梅乃家 千葉県富津市竹岡410"),
    officialLinks: [
      { label: "地図", url: map("梅乃家 千葉県富津市竹岡410"), type: "map" },
    ],
    editorComment: "千葉のご当地ラーメンとして最重要級。営業時間の変動を断定しない代わりに、地域性と訪問前確認を強く出します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 梅乃家", map("梅乃家 千葉県富津市竹岡410"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 梅乃家", "https://ramendb.supleks.jp/s/543.html", "user-review", "竹岡式代表店としての確認補助。"),
    ],
    faqs: [
      { question: "竹岡式ラーメンとは何ですか？", answer: "濃い醤油だれ、玉ねぎ、乾麺を使う店が多い内房発祥のご当地ラーメンです。梅乃家はその代表候補として紹介されます。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-local-style", "chiba-car-friendly"],
  },
  {
    slug: "chiba-suzuya-takeoka",
    name: "鈴屋",
    description: "竹岡式ラーメンを梅乃家と比較して楽しみたい富津の候補。内房ドライブでご当地ラーメンを複数候補にしたい読者に向きます。",
    area: "富津市・竹岡",
    address: "千葉県富津市竹岡92",
    phone: "0439-67-8207",
    genre: "竹岡式ラーメン",
    tags: ["富津", "竹岡式", "内房", "ドライブ", "醤油"],
    recommendedMenu: "ラーメン",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "車訪問向き。台数・混雑は訪問前確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("鈴屋 富津市竹岡92"),
    mapUrl: map("鈴屋 富津市竹岡92"),
    officialLinks: [
      { label: "地図", url: map("鈴屋 富津市竹岡92"), type: "map" },
    ],
    editorComment: "竹岡式を1店だけで終わらせず比較軸にできる店。梅乃家とセットで内房エリアの厚みを作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 鈴屋", map("鈴屋 富津市竹岡92"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 鈴屋", "https://ramendb.supleks.jp/s/541.html", "user-review", "竹岡式候補としての確認補助。"),
    ],
    faqs: [
      { question: "梅乃家と鈴屋は同じ竹岡式ですか？", answer: "どちらも竹岡式の文脈で紹介される富津の候補です。味や営業状況は店ごとに異なるため、訪問前確認をおすすめします。" },
    ],
    relatedRankingSlugs: ["chiba-local-style", "chiba-car-friendly"],
  },
  {
    slug: "chiba-ezawa-katsuura",
    name: "元祖勝浦式担々麺 江ざわ",
    description: "勝浦タンタンメンの代表格として外せない店。醤油ベースにラー油、玉ねぎ、ひき肉を合わせる勝浦独自の辛い一杯を目的に訪れる読者向けです。",
    area: "勝浦市",
    address: "千葉県勝浦市白井久保296-8",
    phone: "090-4410-5798",
    genre: "勝浦タンタンメン",
    tags: ["勝浦", "ご当地ラーメン", "辛い", "ラー油", "ドライブ"],
    recommendedMenu: "担々麺",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "車訪問向き。混雑・待ち時間に注意。",
    businessHours: "昼営業中心（売切・臨時休業あり、最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("元祖勝浦式担々麺 江ざわ 千葉県勝浦市白井久保296-8"),
    mapUrl: map("元祖勝浦式担々麺 江ざわ 千葉県勝浦市白井久保296-8"),
    officialLinks: [
      { label: "地図", url: map("元祖勝浦式担々麺 江ざわ 千葉県勝浦市白井久保296-8"), type: "map" },
      { label: "勝浦タンタンメン企業組合", url: "https://katsuura-tantanmen.com/pages/about", type: "website" },
    ],
    editorComment: "勝浦タンタンメンの核として必須。店舗個別の公式情報は弱いため、勝浦タンタンメンの公式説明と地図情報を併用します。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("勝浦タンタンメン企業組合 こだわり", "https://katsuura-tantanmen.com/pages/about", "official", "勝浦タンタンメンの基本スタイル・地域背景を確認。"),
      source("Google Maps 江ざわ", map("元祖勝浦式担々麺 江ざわ 千葉県勝浦市白井久保296-8"), "map", "所在地確認の補助。"),
    ],
    faqs: [
      { question: "勝浦タンタンメンは普通の担々麺と違いますか？", answer: "一般的なごま系担々麺ではなく、醤油ベースにラー油、玉ねぎ、ひき肉を合わせるラー油系のご当地ラーメンです。" },
    ],
    relatedRankingSlugs: ["chiba-ramen-essential", "chiba-local-style", "chiba-car-friendly"],
  },
  {
    slug: "chiba-teppatsuya-katsuura",
    name: "てっぱつ屋",
    description: "勝浦市街地で勝浦タンタンメンを食べる候補。朝市や海沿い観光と合わせやすく、江ざわと比較する外房エリアの二軒目として扱えます。",
    area: "勝浦市・勝浦駅周辺",
    address: "千葉県勝浦市墨名565-103",
    phone: "0470-73-6006",
    genre: "勝浦タンタンメン",
    tags: ["勝浦", "ご当地ラーメン", "辛い", "駅周辺", "観光導線"],
    recommendedMenu: "勝浦タンタンメン",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "店舗・周辺駐車場の最新状況は訪問前確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("てっぱつ屋 千葉県勝浦市墨名565-103"),
    mapUrl: map("てっぱつ屋 千葉県勝浦市墨名565-103"),
    officialLinks: [
      { label: "地図", url: map("てっぱつ屋 千葉県勝浦市墨名565-103"), type: "map" },
      { label: "勝浦タンタンメン企業組合", url: "https://katsuura-tantanmen.com/pages/about", type: "website" },
    ],
    editorComment: "勝浦タンタンメンを市街地・観光導線で紹介するための候補。江ざわだけに偏らないランキングにできます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("勝浦タンタンメン企業組合 こだわり", "https://katsuura-tantanmen.com/pages/about", "official", "勝浦タンタンメンの基本スタイル・地域背景を確認。"),
      source("Google Maps てっぱつ屋", map("てっぱつ屋 千葉県勝浦市墨名565-103"), "map", "所在地確認の補助。"),
    ],
    faqs: [
      { question: "勝浦観光と組み合わせやすいですか？", answer: "勝浦駅・市街地周辺から検討しやすいため、朝市や海沿い観光と合わせる候補になります。" },
    ],
    relatedRankingSlugs: ["chiba-local-style", "chiba-car-friendly"],
  },
  {
    slug: "chiba-menyaaoyama-narita",
    name: "麺屋青山 本店",
    description: "成田エリアで濃厚系・魚介系を探す読者に向けた代表候補。空港・成田山方面の導線を作れるため、北総エリアのラーメン枠として整理します。",
    area: "成田市・成田",
    address: "千葉県成田市ウイング土屋88",
    phone: "0476-23-1231",
    genre: "濃厚魚介・鶏白湯",
    tags: ["成田", "北総", "濃厚魚介", "鶏白湯", "駐車場あり"],
    recommendedMenu: "らーめん／つけ麺",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "郊外型店舗。最新の駐車場状況は確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("麺屋青山 本店 千葉県成田市ウイング土屋88"),
    mapUrl: map("麺屋青山 本店 千葉県成田市ウイング土屋88"),
    officialLinks: [
      { label: "地図", url: map("麺屋青山 本店 千葉県成田市ウイング土屋88"), type: "map" },
    ],
    editorComment: "千葉市・松戸・勝浦・富津だけでなく、成田方面の導線を作るために入れる店舗。成田山や空港利用の文脈にもつなげられます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 麺屋青山 本店", map("麺屋青山 本店 千葉県成田市ウイング土屋88"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 麺屋青山 本店", "https://ramendb.supleks.jp/s/1933.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "成田観光と合わせやすいですか？", answer: "成田市内の郊外型店舗として、車移動なら成田山・空港方面の移動と合わせて検討しやすい候補です。" },
    ],
    relatedRankingSlugs: ["chiba-tsukemen-rich", "chiba-car-friendly"],
  },
  {
    slug: "chiba-naritake-tsudanuma",
    name: "こってりらーめん なりたけ 津田沼店",
    description: "津田沼発祥の背脂チャッチャ系として知られる人気店。千葉北西部の夜利用・駅近需要を拾いやすく、濃厚背脂ジャンルの比較候補になります。",
    area: "習志野市・津田沼",
    address: "千葉県船橋市前原西2-11-7",
    phone: "047-477-7987",
    genre: "背脂醤油・味噌",
    tags: ["津田沼", "背脂", "こってり", "駅近", "夜利用"],
    recommendedMenu: "しょうゆらーめん／みそらーめん",
    priceRange: "800円〜1,300円目安",
    parking: false,
    parkingNote: "駅周辺店舗。公共交通・周辺駐車場利用を想定。",
    businessHours: "昼〜深夜帯中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("こってりらーめん なりたけ 津田沼店 千葉県船橋市前原西2-11-7"),
    mapUrl: map("こってりらーめん なりたけ 津田沼店 千葉県船橋市前原西2-11-7"),
    officialLinks: [
      { label: "地図", url: map("こってりらーめん なりたけ 津田沼店 千葉県船橋市前原西2-11-7"), type: "map" },
    ],
    editorComment: "千葉の背脂・こってり系を語るときに入れたい店舗。公式サイトの取得が不安定だったため、営業時間は断定しません。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps なりたけ 津田沼店", map("こってりらーめん なりたけ 津田沼店 千葉県船橋市前原西2-11-7"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース なりたけ 津田沼店", "https://ramendb.supleks.jp/s/151.html", "user-review", "背脂系店舗としての確認補助。"),
    ],
    faqs: [
      { question: "なりたけはあっさり系ですか？", answer: "背脂を効かせたこってり系として紹介されることが多い店です。軽い一杯を探す場合は小むろなど淡麗系も比較候補にしてください。" },
    ],
    relatedRankingSlugs: ["chiba-morning-night", "chiba-train-access"],
  },
  {
    slug: "chiba-fukutake-sakuragi",
    name: "らーめん福たけ 桜木本店",
    description: "千葉市若葉区で背脂・煮干し系を探す候補。車移動しやすいエリアにあり、千葉市内の郊外型ラーメンを補強できます。",
    area: "千葉市若葉区・桜木",
    address: "千葉県千葉市若葉区桜木6-24-1",
    phone: "043-235-3353",
    genre: "背脂煮干し",
    tags: ["千葉市", "若葉区", "背脂", "煮干し", "駐車場あり"],
    recommendedMenu: "背脂煮干しラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "郊外型店舗。最新の駐車場状況は確認推奨。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("らーめん福たけ 桜木本店 千葉県千葉市若葉区桜木6-24-1"),
    mapUrl: map("らーめん福たけ 桜木本店 千葉県千葉市若葉区桜木6-24-1"),
    officialLinks: [
      { label: "地図", url: map("らーめん福たけ 桜木本店 千葉県千葉市若葉区桜木6-24-1"), type: "map" },
    ],
    editorComment: "千葉市郊外の背脂煮干し候補。杉田家や雷とは違う、煮干し・背脂の文脈を作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 福たけ 桜木本店", map("らーめん福たけ 桜木本店 千葉県千葉市若葉区桜木6-24-1"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 福たけ 桜木本店", "https://ramendb.supleks.jp/s/1770.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "福たけは車で行く店ですか？", answer: "千葉市若葉区の郊外型店舗として、車移動で検討しやすい候補です。駐車場の最新状況は確認してください。" },
    ],
    relatedRankingSlugs: ["chiba-car-friendly"],
  },
  {
    slug: "chiba-boobootaro-chuo",
    name: "ラーメン BooBoo太郎。",
    description: "千葉中央周辺で二郎系・ガッツリ系を探す読者向けの候補。千葉市中心部の若い読者や夜利用の検索に対応できます。",
    area: "千葉市中央区・千葉中央",
    address: "千葉県千葉市中央区中央4-13-21",
    genre: "二郎系・ガッツリ",
    tags: ["千葉中央", "二郎系", "ガッツリ", "駅近", "ボリューム"],
    recommendedMenu: "ラーメン",
    priceRange: "900円〜1,400円目安",
    parking: false,
    parkingNote: "中心部店舗。周辺駐車場利用を想定。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("ラーメン BooBoo太郎。 千葉市中央区中央4-13-21"),
    mapUrl: map("ラーメン BooBoo太郎。 千葉市中央区中央4-13-21"),
    officialLinks: [
      { label: "地図", url: map("ラーメン BooBoo太郎。 千葉市中央区中央4-13-21"), type: "map" },
    ],
    editorComment: "千葉市中心部のガッツリ系枠。雷と比較しつつ、独立店としての選択肢を作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps BooBoo太郎。", map("ラーメン BooBoo太郎。 千葉市中央区中央4-13-21"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース BooBoo太郎。", "https://ramendb.supleks.jp/s/89437.html", "user-review", "二郎系候補としての確認補助。"),
    ],
    faqs: [
      { question: "BooBoo太郎。は量が多いですか？", answer: "二郎系・ガッツリ系として紹介されるため、初回は麺量やトッピングを控えめに確認するのが無難です。" },
    ],
    relatedRankingSlugs: ["chiba-morning-night", "chiba-train-access"],
  },
  {
    slug: "chiba-chibaya-wakaba",
    name: "横浜ラーメン 千葉家",
    description: "千葉市若葉区で長く知られる家系ラーメン候補。杉田家とは違う地元密着型の家系として、千葉市内の比較軸に入れたい店です。",
    area: "千葉市若葉区・みつわ台",
    address: "千葉県千葉市若葉区みつわ台4-17-22",
    phone: "043-284-0069",
    genre: "家系ラーメン",
    tags: ["千葉市", "若葉区", "家系", "地元密着", "駐車場確認"],
    recommendedMenu: "ラーメン",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "駐車場の最新状況は訪問前確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("横浜ラーメン 千葉家 千葉県千葉市若葉区みつわ台4-17-22"),
    mapUrl: map("横浜ラーメン 千葉家 千葉県千葉市若葉区みつわ台4-17-22"),
    officialLinks: [
      { label: "地図", url: map("横浜ラーメン 千葉家 千葉県千葉市若葉区みつわ台4-17-22"), type: "map" },
    ],
    editorComment: "千葉市の家系を杉田家だけにしないための候補。公式追跡性は弱いので、営業詳細は控えめに扱います。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 千葉家", map("横浜ラーメン 千葉家 千葉県千葉市若葉区みつわ台4-17-22"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 千葉家", "https://ramendb.supleks.jp/s/2146.html", "user-review", "家系ラーメン候補としての確認補助。"),
    ],
    faqs: [
      { question: "杉田家と千葉家はどう違いますか？", answer: "杉田家は公式情報が強い吉村家直系店舗、千葉家は地元密着型の家系候補として比較できます。" },
    ],
    relatedRankingSlugs: ["chiba-car-friendly"],
  },
  {
    slug: "chiba-gouramen-togane",
    name: "ぐうらーめん",
    description: "東金エリアで黒い醤油スープと玉ねぎを楽しむ候補。九十九里方面のドライブ導線に入れやすく、内房・外房以外の地域性を補えます。",
    area: "東金市",
    address: "千葉県東金市田間554-3",
    phone: "0475-52-3380",
    genre: "醤油・玉ねぎ",
    tags: ["東金", "九十九里", "醤油", "玉ねぎ", "ドライブ"],
    recommendedMenu: "ぐうらーめん",
    priceRange: "800円〜1,200円目安",
    parking: true,
    parkingNote: "車訪問向き。駐車場・混雑は最新確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("ぐうらーめん 千葉県東金市田間554-3"),
    mapUrl: map("ぐうらーめん 千葉県東金市田間554-3"),
    officialLinks: [
      { label: "地図", url: map("ぐうらーめん 千葉県東金市田間554-3"), type: "map" },
    ],
    editorComment: "九十九里・東金方面のローカル感を出せる店舗。千葉県ページを湾岸・松戸・勝浦だけに偏らせないために有効です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps ぐうらーめん", map("ぐうらーめん 千葉県東金市田間554-3"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース ぐうらーめん", "https://ramendb.supleks.jp/s/2612.html", "user-review", "店舗存在・地域性確認の補助。"),
    ],
    faqs: [
      { question: "東金方面の観光と合わせやすいですか？", answer: "九十九里方面へ車で移動するルート上の候補として検討しやすい店です。" },
    ],
    relatedRankingSlugs: ["chiba-car-friendly", "chiba-local-style"],
  },
  {
    slug: "chiba-yatai-ramen-iss-inage",
    name: "屋台拉麺一's 稲毛本店",
    description: "稲毛で屋台感のある塩・牛骨系を探す候補。千葉市内の駅近・夜利用の選択肢を広げる店舗として整理します。",
    area: "千葉市稲毛区・稲毛",
    address: "千葉県千葉市稲毛区小仲台2-3-3",
    phone: "043-287-5117",
    genre: "塩・牛骨",
    tags: ["稲毛", "駅近", "塩ラーメン", "牛骨", "夜利用"],
    recommendedMenu: "塩らーめん",
    priceRange: "800円〜1,300円目安",
    parking: false,
    parkingNote: "駅近店舗。周辺駐車場利用を想定。",
    businessHours: "昼・夜営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("屋台拉麺一's 稲毛本店 千葉市稲毛区小仲台2-3-3"),
    mapUrl: map("屋台拉麺一's 稲毛本店 千葉市稲毛区小仲台2-3-3"),
    officialLinks: [
      { label: "地図", url: map("屋台拉麺一's 稲毛本店 千葉市稲毛区小仲台2-3-3"), type: "map" },
    ],
    editorComment: "千葉市内の塩・牛骨系として、家系・背脂・ガッツリに偏らない選択肢を作れます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 屋台拉麺一's 稲毛本店", map("屋台拉麺一's 稲毛本店 千葉市稲毛区小仲台2-3-3"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 屋台拉麺一's", "https://ramendb.supleks.jp/s/3201.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "一'sはこってり系ですか？", answer: "塩・牛骨系の候補として扱います。背脂や家系とは違う方向で選びたい時に比較しやすい店です。" },
    ],
    relatedRankingSlugs: ["chiba-light-shoyu", "chiba-train-access"],
  },
  {
    slug: "chiba-yukichi-funabashi",
    name: "麺処ゆきち",
    description: "船橋エリアで淡麗寄りの一杯を探す候補。濃厚つけ麺やガッツリ系だけではない、船橋周辺のラーメン選択肢を補強します。",
    area: "船橋市",
    address: "千葉県船橋市習志野台1-25-14",
    genre: "淡麗醤油・塩",
    tags: ["船橋", "淡麗", "醤油", "塩", "住宅地"],
    recommendedMenu: "醤油らーめん",
    priceRange: "800円〜1,300円目安",
    parking: false,
    parkingNote: "周辺駐車場・公共交通の最新確認推奨。",
    businessHours: "昼営業中心（最新確認推奨）",
    closedDays: "最新確認推奨",
    officialUrl: map("麺処ゆきち 千葉県船橋市習志野台1-25-14"),
    mapUrl: map("麺処ゆきち 千葉県船橋市習志野台1-25-14"),
    officialLinks: [
      { label: "地図", url: map("麺処ゆきち 千葉県船橋市習志野台1-25-14"), type: "map" },
    ],
    editorComment: "船橋周辺の淡麗候補。情報追跡は弱めなので、ランキングでは小むろや一'sの補助として扱います。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("Google Maps 麺処ゆきち", map("麺処ゆきち 千葉県船橋市習志野台1-25-14"), "map", "所在地確認の補助。"),
      source("ラーメンデータベース 麺処ゆきち", "https://ramendb.supleks.jp/s/59575.html", "user-review", "店舗存在・ジャンル確認の補助。"),
    ],
    faqs: [
      { question: "船橋で軽めのラーメンを探す時に向いていますか？", answer: "淡麗醤油・塩の候補として、ガッツリ系や濃厚つけ麺と比較して選べます。" },
    ],
    relatedRankingSlugs: ["chiba-light-shoyu"],
  },
];
