import type { TravelRegion } from "@/lib/types";

export const travelRegions: TravelRegion[] = [
  {
    slug: "niigata",
    name: "新潟県",
    shortName: "新潟",
    description: "越後湯沢・月岡・松之山など多彩な温泉地を擁する新潟県。日本海の幸と雪国の風情が揃う旅館が充実しています。",
    tagline: "雪国・温泉・日本海。多彩な泉質が揃う旅館県",
    seoTitle: "新潟県 おすすめ温泉旅館・宿泊ガイド",
    seoDescription: "越後湯沢・月岡温泉・松之山・栃尾又・咲花・瀬波など新潟県の温泉旅館をランキングと宿カードで比較。泉質・料理・景観別に整理しています。",
    seoKeywords: ["新潟 旅館", "新潟 温泉", "越後湯沢 旅館", "月岡温泉 旅館", "松之山温泉", "新潟 秘湯", "新潟 宿泊"],
    status: "live",
    headline: "新潟県の温泉・旅館を、泉質・景観・旅スタイルで選ぶ。",
    subtext: "ラジウム泉・日本三大薬湯・硫黄泉・日本海夕日など、エリアごとに個性が際立つ宿を参照ソース付きで整理します。",
    heroBadge: "Niigata Travel Guide",
    heroCtaSlug: "niigata-onsen-ryokan-overall",
    heroCtaLabel: "温泉旅館ランキングを見る",
    statsNote: "松之山温泉は有馬・草津と並ぶ「日本三大薬湯」。栃尾又温泉は日本有数のラジウム含有量。越後湯沢は川端康成『雪国』の舞台。",
    onsenAreas: [
      { name: "越後湯沢温泉", feature: "雪国文学ゆかり。ナトリウム塩化物泉。スキーリゾートとの複合滞在が人気。" },
      { name: "松之山温泉", feature: "日本三大薬湯のひとつ。石油と食塩が混じった独特の塩化物泉。棚田の里山が目の前。" },
      { name: "栃尾又温泉", feature: "日本有数のラジウム含有量。放射能泉（微量）として女性の湯治客に人気。" },
      { name: "月岡温泉", feature: "緑がかった硫黄泉。日本有数の含硫黄量。新発田市の温泉街として整備。" },
      { name: "咲花温泉", feature: "阿賀野川沿い。翡翠色の硫黄泉が特徴。川を眺める露天風呂が名物。" },
      { name: "瀬波温泉", feature: "日本海を一望できる高台。夕日の絶景と村上の郷土料理が魅力。" },
      { name: "岩室温泉", feature: "弥彦山麓・弥彦神社近く。塩化物泉。アクセス良好でひとり旅にも向く。" },
      { name: "赤倉温泉", feature: "妙高山麓。硫酸塩泉。スキー・登山の拠点としても機能する老舗温泉地。" },
    ],
    areas: ["越後湯沢・南魚沼", "十日町・松之山", "魚沼・栃尾又", "新発田・月岡", "五泉・咲花", "村上・瀬波", "弥彦・岩室", "妙高・赤倉"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1614301246509-d1fc7d78b6b6", alt: "新潟県の温泉旅館" },
      { key: "region", url: "https://images.unsplash.com/photo-1587151940594-58bd770fdda7", alt: "新潟県の雪景色" },
    ],
  },
  {
    slug: "yamagata",
    name: "山形県",
    shortName: "山形",
    description: "蔵王・銀山・天童・赤湯など多彩な温泉地が点在する山形県。雪景色と山菜・米沢牛など食の魅力も高い。",
    tagline: "蔵王・銀山・雪景色。山深い温泉と食の宝庫",
    seoTitle: "山形県 おすすめ温泉旅館・宿泊ガイド",
    seoDescription: "蔵王温泉・銀山温泉・天童温泉など山形県の温泉旅館をランキングと宿カードで比較。雪見露天・米沢牛・山菜料理など地域の魅力も整理。",
    seoKeywords: ["山形 旅館", "山形 温泉", "銀山温泉 旅館", "蔵王温泉", "山形 宿泊", "山形 秘湯"],
    status: "planned",
    headline: "山形県の温泉・旅館を、雪景色・食・泉質で選ぶ。",
    subtext: "銀山温泉の大正浪漫、蔵王の樹氷、米沢牛の宿など山形ならではの旅館体験を整理します。",
    heroBadge: "Yamagata Travel Guide",
    heroCtaSlug: "yamagata-onsen-overall",
    heroCtaLabel: "山形温泉旅館ランキング",
    statsNote: "銀山温泉は雑誌・映画で繰り返し紹介される昭和・大正レトロの温泉地。蔵王の樹氷は2月〜3月が見頃。",
    onsenAreas: [],
    areas: ["銀山温泉・大石田", "蔵王温泉", "天童温泉", "米沢・赤湯"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1546954892-64c1c0aed544", alt: "山形県の山岳風景" },
    ],
  },
];
