import type { TravelAgency } from "@/lib/types";

const verifiedAt = "2026-06-14";

export const shizuokaTravelAgencies: TravelAgency[] = [
  {
    slug: "shizutetsu-tourism",
    name: "静岡鉄道 ツーリズム課",
    tagline: "静岡鉄道グループの団体旅行・フリープラン相談窓口",
    description: "静岡鉄道グループのツーリズム課。FDAで行くフリープラン、マイカープラン、社員旅行・グループ旅行・教育旅行などの団体旅行相談に対応しています。",
    area: "静岡市・中部",
    address: "静岡県静岡市周辺",
    phone: "054-254-5122",
    services: ["国内旅行", "団体旅行", "宿泊手配", "航空券"],
    bestFor: ["静岡市周辺で団体旅行を相談したい", "FDA利用のフリープランを見たい", "教育旅行・社員旅行を相談したい"],
    tags: ["静鉄グループ", "団体旅行", "FDA", "マイカープラン", "静岡市"],
    priceRange: "プラン・相談内容により異なる",
    consultationStyle: "公式サイト・電話で相談。団体旅行はツーリズム課へ問い合わせ。",
    businessHours: "平日 10:00〜17:00",
    closedDays: "土日祝日",
    registeredTravelAgency: "観光庁長官登録旅行業 第2155号",
    officialUrl: "https://www.shizutetsu.co.jp/tourism/",
    mapUrl: "https://maps.google.com/?q=静岡鉄道 ツーリズム課",
    officialLinks: [
      { label: "ツーリズム課", url: "https://www.shizutetsu.co.jp/tourism/", type: "website" },
      { label: "静鉄グループ", url: "https://www.shizutetsu.co.jp/", type: "website" },
    ],
    editorComment: "旅行業登録、団体旅行相談、フリープランの導線が公式ページで明確。静岡市・中部エリアで法人や学校系の旅行を相談する入口として使いやすい。",
    highlight: "静岡市周辺で団体旅行やFDA利用プランを相談するなら最初に確認したい。",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "静岡鉄道 ツーリズム課", url: "https://www.shizutetsu.co.jp/tourism/", sourceType: "official", collectedAt: verifiedAt, note: "フリープラン、マイカープラン、団体旅行相談、旅行業登録票を確認。" },
      { title: "静鉄グループ 公式サイト", url: "https://www.shizutetsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行・レジャー関連サービスとしてツーリズム課導線を確認。" },
    ],
    faqs: [
      { question: "静岡鉄道ツーリズム課は個人旅行も扱っていますか？", answer: "公式ページではフリープランやマイカープランの導線があります。一方、団体旅行相談は社員旅行・グループ旅行・教育旅行が中心です。" },
      { question: "旅行業登録は確認できますか？", answer: "公式ページの旅行業登録票で、観光庁長官登録旅行業第2155号が確認できます。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "entetsu-travel",
    name: "遠鉄トラベル",
    tagline: "浜松・遠州の団体旅行と貸切バス相談に強い",
    description: "遠鉄グループの旅行部門。個人旅行の受付は停止中ですが、8名以上の団体旅行、社員旅行、教育旅行、MICE、貸切バス相談に対応しています。",
    area: "浜松・遠州",
    address: "静岡県浜松市周辺",
    phone: "053-457-6470",
    services: ["団体旅行", "貸切バス", "国内旅行", "宿泊手配"],
    bestFor: ["浜松・遠州発の団体旅行を相談したい", "貸切バス込みで見積もりたい", "社員旅行や教育旅行を相談したい"],
    tags: ["遠鉄グループ", "団体旅行", "貸切バス", "浜松", "MICE"],
    priceRange: "相談内容により見積もり",
    consultationStyle: "団体旅行センター・中遠旅行営業所へ電話相談。",
    businessHours: "9:00〜18:00",
    closedDays: "土日祝日",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.e-trip.co.jp/",
    mapUrl: "https://maps.google.com/?q=遠鉄トラベル 浜松",
    officialLinks: [
      { label: "遠鉄トラベル", url: "https://www.e-trip.co.jp/", type: "website" },
      { label: "遠鉄グループ", url: "https://www.entetsu.co.jp/", type: "website" },
    ],
    editorComment: "個人旅行より団体旅行に振り切った相談先。浜松・遠州エリアで貸切バスや団体旅行を組むなら実用性が高い。",
    highlight: "浜松・遠州エリアの団体旅行と貸切バス相談に向く。",
    imageUrl: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "遠鉄トラベル 公式サイト", url: "https://www.e-trip.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "個人旅行受付停止、8名以上の団体旅行、貸切バス、問い合わせ先を確認。" },
      { title: "遠鉄グループポータル", url: "https://www.entetsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "国内旅行・海外旅行、バンビツアー、遠鉄トラベル導線を確認。" },
    ],
    faqs: [
      { question: "遠鉄トラベルは個人旅行も申し込めますか？", answer: "公式サイトでは、現在個人旅行の受付を停止していると案内されています。8名以上の団体旅行や貸切バス相談が中心です。" },
      { question: "どの地域からの相談に向いていますか？", answer: "湖西・浜松地区、磐田・袋井〜焼津地区の問い合わせ先が案内されており、遠州・中遠エリアの団体旅行に向いています。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "bambi-tour",
    name: "バンビツアー",
    tagline: "浜松・磐田・掛川発着の募集型バスツアーを探しやすい",
    description: "遠州鉄道のバスツアーブランド。日帰り・宿泊コース、温泉、花火、フルーツ狩り、観劇などテーマ別に探せ、浜松・磐田・掛川などの乗り場導線があります。",
    area: "浜松・磐田・掛川",
    address: "静岡県浜松市周辺",
    phone: "053-454-4101",
    services: ["バスツアー", "国内旅行", "宿泊手配"],
    bestFor: ["浜松周辺発着のバスツアーを探したい", "日帰り・宿泊ツアーを条件で比較したい", "Webで空席やコースを見たい"],
    tags: ["遠州鉄道", "バスツアー", "浜松発", "日帰り", "宿泊"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイト・予約センターで確認。",
    businessHours: "予約センター 10:00〜16:00",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://bambi.entetsu.co.jp/",
    mapUrl: "https://maps.google.com/?q=バンビツアー 浜松",
    officialLinks: [
      { label: "バンビツアー", url: "https://bambi.entetsu.co.jp/", type: "website" },
      { label: "遠鉄グループ", url: "https://www.entetsu.co.jp/", type: "website" },
    ],
    editorComment: "募集型ツアーの検索性が高く、浜松・磐田・掛川発着の旅行を探す入口として便利。団体旅行の遠鉄トラベルとは役割を分けて掲載する価値がある。",
    highlight: "浜松周辺発着の定番バスツアーを条件・テーマから探せる。",
    imageUrl: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "バンビツアー 公式サイト", url: "https://bambi.entetsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "日帰り・宿泊コース、検索条件、乗り場、予約センターを確認。" },
      { title: "遠鉄グループポータル", url: "https://www.entetsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "バンビツアーと遠鉄トラベルのグループ導線を確認。" },
    ],
    faqs: [
      { question: "バンビツアーは団体旅行向けですか？", answer: "主に募集型のバスツアーを探す用途に向いています。団体旅行や貸切バスの相談は遠鉄トラベル側の導線が適しています。" },
      { question: "どこから乗車できますか？", answer: "公式サイトでは浜松駅、浜松西IC、浜松IC、磐田IC、掛川IC、掛川駅南口などの乗り場条件が確認できます。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "tokai-bus-travel",
    name: "東海バストラベル",
    tagline: "伊豆発・伊豆で巡るバスツアーと着地型旅行に強い",
    description: "東海バスの旅行部門。伊豆から出発するオレンジツアー、伊豆で巡る着地型ツアー、オーダーメイド旅行を公式サイトで展開しています。",
    area: "伊豆・東部",
    address: "静岡県伊東市周辺",
    phone: "0557-36-6660",
    services: ["バスツアー", "着地型ツアー", "国内旅行", "団体旅行"],
    bestFor: ["伊豆発着のバスツアーを探したい", "伊豆現地で巡るツアーを見たい", "東部・伊豆の交通会社系旅行商品を使いたい"],
    tags: ["東海バス", "伊豆", "オレンジツアー", "着地型", "バスツアー"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "Web申込・電話で問い合わせ。",
    businessHours: "10:00〜17:00",
    closedDays: "土日祝日",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.tokaibus.jp/travel/",
    mapUrl: "https://maps.google.com/?q=東海バス 伊東",
    officialLinks: [
      { label: "東海バストラベル", url: "https://www.tokaibus.jp/travel/", type: "website" },
      { label: "東海バス", url: "https://www.tokaibus.jp/", type: "website" },
    ],
    editorComment: "伊豆エリアに強い交通会社系の旅行導線。伊豆発のツアーと伊豆で巡る着地型ツアーの両方を持つ点が、県内他エリアとは違う強み。",
    highlight: "伊豆発・伊豆周遊のバスツアーを探すなら優先して確認したい。",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "東海バストラベル", url: "https://www.tokaibus.jp/travel/", sourceType: "official", collectedAt: verifiedAt, note: "伊豆から出発のツアー、着地型、オーダーメイド旅行、問い合わせ先を確認。" },
      { title: "東海バス 公式サイト", url: "https://www.tokaibus.jp/", sourceType: "official", collectedAt: verifiedAt, note: "路線バス、高速バス、貸切バス、旅行導線を確認。" },
    ],
    faqs: [
      { question: "東海バストラベルは伊豆旅行に向いていますか？", answer: "伊豆から出発するツアーと、伊豆で巡る着地型ツアーの導線があるため、伊豆旅行との相性が高いです。" },
      { question: "Web申込はできますか？", answer: "公式サイトの各ツアーから予約サイトへ遷移する導線が確認できます。出発日や乗車地は各コースで確認してください。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "izuhakone-travel",
    name: "伊豆箱根トラベル",
    tagline: "三島発の伊豆箱根グループ系ツアーとバス送迎相談",
    description: "伊豆箱根鉄道グループの旅行導線。グループ旅行、バス送迎、企画旅行、ツアーパンフレットなどを公式サイトで確認できます。",
    area: "三島・伊豆箱根",
    address: "静岡県三島市大場300番地",
    phone: "055-977-0012",
    services: ["バスツアー", "団体旅行", "貸切バス", "着地型ツアー"],
    bestFor: ["三島・伊豆箱根エリアで相談したい", "バス送迎込みで考えたい", "企画旅行やツアーパンフレットを見たい"],
    tags: ["伊豆箱根鉄道グループ", "三島", "バス送迎", "企画旅行", "伊豆"],
    priceRange: "ツアー・相談内容により異なる",
    consultationStyle: "本社旅行センター・Web導線で確認。",
    businessHours: "公式サイトで要確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.izuhakone.co.jp/travel/index.html",
    mapUrl: "https://maps.google.com/?q=静岡県三島市大場300番地",
    officialLinks: [
      { label: "伊豆箱根トラベル", url: "https://www.izuhakone.co.jp/travel/index.html", type: "website" },
      { label: "伊豆箱根鉄道グループ", url: "https://www.izuhakone.co.jp/", type: "website" },
    ],
    editorComment: "三島・伊豆箱根エリアの交通グループ系旅行導線として有力。バス送迎や企画旅行が明確で、地域イベント・ファンツアー系にも強い。",
    highlight: "三島・伊豆箱根エリアでバス送迎や企画旅行を確認しやすい。",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "伊豆箱根トラベル", url: "https://www.izuhakone.co.jp/travel/index.html", sourceType: "official", collectedAt: verifiedAt, note: "グループ旅行、バス送迎、企画旅行、旅行センターを確認。" },
      { title: "伊豆箱根鉄道グループ", url: "https://www.izuhakone.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "伊豆箱根トラベルと交通事業導線を確認。" },
    ],
    faqs: [
      { question: "伊豆箱根トラベルはどのエリアに強いですか？", answer: "三島を拠点に、伊豆箱根鉄道・バスの導線と組み合わせやすい伊豆箱根エリアに強みがあります。" },
      { question: "バス送迎だけでも相談できますか？", answer: "公式サイトにバス送迎の導線があります。人数、出発地、目的地を整理して問い合わせると相談しやすいです。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "shizutetsu-joystep-bus",
    name: "静鉄ジョイステップバス",
    tagline: "静岡県中部の貸切・観光バスに強い静鉄グループ会社",
    description: "焼津市に本社を置く静鉄グループの貸切・観光バス会社。バスツアー、お見積り、貸切バスの種類、ご利用ガイド、安全への取り組みが公式サイトで確認できます。",
    area: "焼津・静岡県中部",
    address: "静岡県焼津市塩津294-5",
    services: ["貸切バス", "バスツアー", "団体旅行"],
    bestFor: ["静岡県中部で貸切バスを手配したい", "観光バス込みの団体移動を相談したい", "安全性評価を重視したい"],
    tags: ["静鉄グループ", "貸切バス", "観光バス", "焼津", "安全性評価"],
    priceRange: "見積もり内容により異なる",
    consultationStyle: "公式サイトのバス見積り・問い合わせから相談。",
    businessHours: "公式サイトで要確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.joystep.co.jp/",
    mapUrl: "https://maps.google.com/?q=静岡県焼津市塩津294-5",
    officialLinks: [
      { label: "公式サイト", url: "https://www.joystep.co.jp/", type: "website" },
      { label: "バス見積り", url: "https://www.joystep.co.jp/", type: "website" },
    ],
    editorComment: "旅行会社というより貸切・観光バスの相談先だが、地域団体の旅行では移動手段の確保が最初の課題になる。静岡県中部の団体移動で候補に入れたい。",
    highlight: "静岡県中部の貸切・観光バス相談に向く。",
    imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "静鉄ジョイステップバス", url: "https://www.joystep.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "貸切・観光バス、バスツアー、見積り、安全への取り組み、所在地を確認。" },
      { title: "静鉄グループ 公式サイト", url: "https://www.shizutetsu.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "旅行・レジャー関連サービスとして貸切バス導線を確認。" },
    ],
    faqs: [
      { question: "静鉄ジョイステップバスは旅行会社ですか？", answer: "主な役割は貸切・観光バス会社です。団体旅行では移動手段の相談先として実用性が高いため掲載しています。" },
      { question: "バスツアーもありますか？", answer: "公式サイトにバスツアー導線があります。募集状況や内容は公式サイトで確認してください。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
  {
    slug: "fujikyu-travel",
    name: "富士急トラベル",
    tagline: "富士山周辺・富士急グループ系の旅行商品を確認できる",
    description: "富士急グループの旅行会社。富士山周辺、富士急ハイランド、バス旅行、法人・団体向け旅行など、富士急グループの交通・レジャー資産と組み合わせた旅行導線を確認できます。",
    area: "富士山周辺・東部",
    address: "山梨県富士吉田市周辺",
    services: ["国内旅行", "バスツアー", "団体旅行", "宿泊手配"],
    bestFor: ["富士山周辺や富士急グループ施設を組み込みたい", "静岡東部から富士山方面の旅行を考えたい", "法人・団体旅行を相談したい"],
    tags: ["富士急グループ", "富士山", "東部", "バス旅行", "団体旅行"],
    priceRange: "旅行商品・相談内容により異なる",
    consultationStyle: "公式サイト・問い合わせフォームで確認。",
    businessHours: "公式サイトで要確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.fujikyu-travel.co.jp/",
    mapUrl: "https://maps.google.com/?q=富士急トラベル",
    officialLinks: [
      { label: "公式サイト", url: "https://www.fujikyu-travel.co.jp/", type: "website" },
      { label: "お問い合わせ", url: "https://www.fujikyu-travel.co.jp/inquiry/", type: "website" },
    ],
    editorComment: "本社エリアは山梨寄りだが、富士山周辺・静岡東部の旅行導線として外せない。県内ローカルだけに限定せず、富士山周辺の実用性で採用。",
    highlight: "富士山周辺や富士急グループ施設を絡めた旅行で確認したい。",
    imageUrl: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "富士急トラベル 公式サイト", url: "https://www.fujikyu-travel.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "公式旅行会社サイトと問い合わせ導線を確認。" },
      { title: "富士急トラベル お問い合わせ", url: "https://www.fujikyu-travel.co.jp/inquiry/", sourceType: "official", collectedAt: verifiedAt, note: "問い合わせフォーム導線を確認。" },
    ],
    faqs: [
      { question: "富士急トラベルは静岡県の会社ですか？", answer: "富士急グループの旅行会社で、富士山周辺・静岡東部の旅行導線として実用性があるため掲載しています。" },
      { question: "富士急ハイランドや富士山周辺旅行に向いていますか？", answer: "富士急グループの交通・レジャー資産と組み合わせやすく、富士山周辺の旅行相談先として候補になります。" },
    ],
    relatedRankingSlugs: ["shizuoka-local-travel-agencies"],
  },
];
