import type { RamenRegion } from "@/lib/types";

export const ramenRegions: RamenRegion[] = [
  {
    slug: "niigata",
    name: "新潟県",
    shortName: "新潟",
    description: "新潟5大ラーメン（あっさり醤油・濃厚味噌・燕背脂・長岡生姜醤油・三条カレー）が有名。エリアごとに異なるスタイルを、実在店舗と営業情報付きで整理しています。",
    tagline: "5大ラーメン・背脂・煮干し、個性豊かな地域スタイル",
    seoTitle: "新潟ラーメン おすすめ店舗・ランキング",
    seoDescription: "新潟5大ラーメン（あっさり醤油・濃厚味噌・燕背脂・長岡生姜醤油・三条カレー）のおすすめ個店をエリア・営業時間・駐車場で比較。公式情報の確認元付きで整理しています。",
    seoKeywords: ["新潟ラーメン", "新潟市ラーメン", "燕ラーメン", "新潟あっさり醤油", "燕背脂ラーメン", "新潟おすすめラーメン店"],
    status: "live",
    headline: "新潟県内のラーメンを、地域・味・移動手段で選ぶ。",
    subtext: "新潟5大ラーメン、実在店舗、営業時間、駐車場、参照ソースを整理。観光でも地元利用でも、条件を絞って比較しやすいカテゴリに育てます。",
    heroBadge: "Niigata Ramen Guide",
    heroCtaSlug: "niigata-independent-selection",
    heroCtaLabel: "個店8店ランキング",
    statsNote: "新潟5大ラーメン（あっさり醤油・濃厚味噌・燕背脂・長岡生姜醤油・三条カレー）に代表される多スタイル県。",
    styles: [
      { name: "新潟あっさり醤油", area: "新潟市・古町", text: "細麺と淡麗スープ。古町の老舗を入口にしやすい。" },
      { name: "新潟濃厚味噌", area: "新潟市", text: "濃い味噌と太麺。割りスープ文化も分かりやすい。" },
      { name: "燕背脂", area: "燕市", text: "煮干し醤油、背脂、極太麺、玉ねぎの県央スタイル。" },
      { name: "長岡生姜醤油", area: "長岡市", text: "今後、長岡市の代表店を追加予定。" },
      { name: "三条カレー", area: "三条市", text: "今後、三条市の店舗情報を調査して追加予定。" },
    ],
    areas: ["新潟市中央区", "古町", "沼垂", "江南区", "西区", "南区", "西蒲区", "燕市"],
    featuredSlugs: ["ishiguro-bentenbashi", "hanasaki-nuttari", "ippongi-konan", "kaisei-kobari"],
    articleTag: "新潟",
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", alt: "新潟ラーメン" },
      { key: "region", url: "https://images.unsplash.com/photo-1587151940594-58bd770fdda7", alt: "新潟県" },
    ],
  },
  {
    slug: "yamagata",
    name: "山形県",
    shortName: "山形",
    description: "消費量日本一の山形県。からみそ（龍上海）・冷やしラーメン（栄屋本店）・酒田ラーメン（満月）・煮干しと、エリアごとに際立ったスタイルが揃います。",
    tagline: "消費量日本一・からみそ・冷やし・酒田・煮干し",
    seoTitle: "山形ラーメン おすすめ店舗・ランキング",
    seoDescription: "消費量日本一の山形県ラーメンを、からみそ・冷やしラーメン・酒田ラーメン・煮干し別に比較。龍上海・栄屋本店・満月・琴平荘など代表店をランキングと店舗カードで整理。",
    seoKeywords: ["山形ラーメン", "山形市ラーメン", "からみそラーメン", "酒田ラーメン", "龍上海", "山形 おすすめラーメン", "冷やしラーメン"],
    status: "live",
    headline: "山形県のラーメンを、エリア・ジャンル・季節で選ぶ。",
    subtext: "ラーメン消費量日本一の山形は、からみそ・冷やしラーメン・酒田ラーメン・手揉み麺系と地域ごとにスタイルが異なります。参照ソースと確認日付きで代表店を整理します。",
    heroBadge: "Yamagata Ramen Guide",
    heroCtaSlug: "yamagata-ramen-essential",
    heroCtaLabel: "山形ラーメン必食選",
    statsNote: "総務省家計調査で山形市が中華そば外食消費額の全国1位を記録。人口10万人あたりのラーメン店数も全国トップクラス。",
    styles: [
      { name: "赤湯からみそ", area: "南陽市", text: "スープ中央の辛みそを溶かして食べる独自スタイル。龍上海が1958年に発祥。" },
      { name: "冷やしラーメン", area: "山形市", text: "1952年に栄屋本店が考案した日本発祥の冷たいラーメン。夏期限定。" },
      { name: "酒田ラーメン", area: "酒田市", text: "魚介系の透明スープと極薄ワンタン・自家製麺が特徴。2023年ご当地総選挙1位。" },
      { name: "手揉み麺・魚介系", area: "鶴岡市", text: "100軒超が集まるラーメンの街。冬季限定の名店も多い。" },
    ],
    areas: ["南陽市・赤湯", "山形市", "東根市", "天童市", "酒田市", "鶴岡市・庄内", "米沢市", "大石田町"],
    featuredSlugs: [],
    articleTag: "山形",
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1546954892-64c1c0aed544", alt: "山形県の山岳風景" },
      { key: "ramen", url: "https://images.unsplash.com/photo-1615341428002-1d4a5f2abb32", alt: "山形ラーメン" },
    ],
  },
  {
    slug: "chiba",
    name: "千葉県",
    shortName: "千葉",
    description: "松戸の濃厚つけ麺、千葉市の家系・ガッツリ系、富津の竹岡式、勝浦タンタンメン、市川・柏の淡麗系まで、都市部とご当地ラーメンの両方を整理します。",
    tagline: "松戸つけ麺・竹岡式・勝浦タンタンメン・千葉市家系",
    seoTitle: "千葉ラーメン おすすめ店舗・ランキング",
    seoDescription: "千葉県のおすすめラーメン店を、松戸の濃厚つけ麺、富津の竹岡式、勝浦タンタンメン、千葉市の家系、柏・市川の淡麗系までランキングと店舗カードで比較。",
    seoKeywords: ["千葉ラーメン", "松戸ラーメン", "千葉市ラーメン", "竹岡式ラーメン", "勝浦タンタンメン", "千葉 おすすめラーメン", "柏ラーメン"],
    status: "live",
    headline: "千葉県のラーメンを、電車・車・ご当地スタイルで選ぶ。",
    subtext: "松戸・柏・市川・千葉市の都市型名店から、富津の竹岡式、勝浦タンタンメン、成田・東金方面のドライブ候補まで、参照ソースと確認日付きで整理します。",
    heroBadge: "Chiba Ramen Guide",
    heroCtaSlug: "chiba-ramen-essential",
    heroCtaLabel: "千葉ラーメン初回10店",
    statsNote: "東京湾岸・常磐線沿線・内房・外房で食文化が分かれ、つけ麺、家系、竹岡式、勝浦タンタンメンを同じ県内で比較できるラーメン密度の高いエリア。",
    styles: [
      { name: "濃厚豚骨魚介つけ麺", area: "松戸市・柏市", text: "とみ田、兎に角、麺屋こうじなど、太麺と魚介豚骨の濃厚系を比較しやすい。" },
      { name: "竹岡式ラーメン", area: "富津市・内房", text: "濃い醤油だれ、玉ねぎ、乾麺の文脈で語られる内房のご当地スタイル。" },
      { name: "勝浦タンタンメン", area: "勝浦市・外房", text: "醤油ベースにラー油、玉ねぎ、ひき肉を合わせる辛いご当地ラーメン。" },
      { name: "千葉市家系・ガッツリ系", area: "千葉市", text: "杉田家、雷、BooBoo太郎。など、駅前・郊外・朝ラーで選び分けられる。" },
      { name: "淡麗醤油・塩", area: "市川・柏・船橋・稲毛", text: "支那ソバ小むろ、AKEBI、一's、麺処ゆきちなど、濃厚系以外の候補も厚い。" },
    ],
    areas: ["松戸市", "柏市", "市川市・本八幡", "船橋市", "千葉市中央区", "千葉市若葉区", "富津市・竹岡", "勝浦市", "成田市", "東金市・九十九里"],
    featuredSlugs: ["chiba-tomita-matsudo", "chiba-sugitaya-yukou", "chiba-umenoya-takeoka", "chiba-ezawa-katsuura"],
    articleTag: "千葉",
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", alt: "千葉ラーメン" },
      { key: "region", url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf", alt: "千葉県の都市風景" },
    ],
  },
  {
    slug: "fukushima",
    name: "福島県",
    shortName: "福島",
    description: "喜多方ラーメン、白河ラーメン、会津山塩、郡山ブラック、福島市の塩、浜通りの食堂系まで、広い県内の地域差を整理します。",
    tagline: "喜多方・白河・会津山塩・郡山ブラック・浜通り",
    seoTitle: "福島ラーメン おすすめ店舗・ランキング",
    seoDescription: "福島県のおすすめラーメン店を、喜多方ラーメン、白河ラーメン、会津山塩、郡山ブラック、福島市の塩、浜通りの食堂系までランキングと店舗カードで比較。",
    seoKeywords: ["福島ラーメン", "喜多方ラーメン", "白河ラーメン", "会津山塩ラーメン", "郡山ブラック", "福島市ラーメン", "福島 おすすめラーメン"],
    status: "live",
    headline: "福島県のラーメンを、地域スタイルと移動手段で選ぶ。",
    subtext: "喜多方・白河という全国区のご当地ラーメンに加え、会津山塩、郡山ブラック、福島市の塩、二本松・いわき・須賀川まで、参照ソースと確認日付きで整理します。",
    heroBadge: "Fukushima Ramen Guide",
    heroCtaSlug: "fukushima-ramen-essential",
    heroCtaLabel: "福島ラーメン初回10店",
    statsNote: "会津・中通り・浜通りで食文化と移動距離が大きく変わる県。喜多方と白河を軸にしながら、会津山塩、郡山ブラック、県北・浜通りの個店まで比較できます。",
    styles: [
      { name: "喜多方ラーメン", area: "喜多方市", text: "平打ち熟成多加水麺と醤油・塩・背脂。朝ラー文化も含めて比較しやすい。" },
      { name: "白河ラーメン", area: "白河市", text: "手打ち・手揉みの縮れ麺と醤油スープ。とら食堂を起点に複数店を比較できる。" },
      { name: "会津山塩ラーメン", area: "会津若松市", text: "北塩原村産の山塩を使う塩ラーメン。会津観光との導線が作りやすい。" },
      { name: "郡山ブラック", area: "郡山市", text: "濃い色の醤油スープで知られる郡山の地域スタイル。" },
      { name: "県北・浜通りの個店", area: "福島市・二本松・いわき", text: "塩、鶏白湯、食堂系など、喜多方・白河以外の選択肢を補える。" },
    ],
    areas: ["喜多方市", "白河市", "会津若松市", "郡山市", "福島市", "二本松市", "いわき市・小名浜", "須賀川市"],
    featuredSlugs: ["fukushima-bannai-kitakata", "fukushima-torashokudo-shirakawa", "fukushima-uende-aizu", "fukushima-dateya-fukushima"],
    articleTag: "福島",
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624", alt: "福島ラーメン" },
      { key: "region", url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf", alt: "福島県の風景" },
    ],
  },
];
