import type { TravelAgency } from "@/lib/types";

const verifiedAt = "2026-06-14";

export const yamagataTravelAgencies: TravelAgency[] = [
  {
    slug: "shoko-travel",
    name: "庄交トラベル",
    tagline: "庄内発着の募集型ツアーと山旅・飛行機旅まで探しやすい",
    description: "鶴岡市の庄交コーポレーションが運営する旅行会社。庄交ミリオンツアー、山旅、飛行機の旅、海外、山形の旅などを公式サイトで検索でき、庄内発着の旅行相談に強みがあります。",
    area: "鶴岡・酒田・庄内",
    address: "山形県鶴岡市錦町2-60",
    phone: "0235-24-2550",
    services: ["国内旅行", "海外旅行", "バスツアー", "団体旅行", "宿泊手配", "航空券"],
    bestFor: ["庄内発着のツアーを探したい", "山旅や飛行機利用の旅行を比較したい", "旅行業登録が明確な地元会社に相談したい"],
    tags: ["庄内発着", "庄交ミリオンツアー", "山旅", "飛行機の旅", "JATA", "鶴岡"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイト・来店予約・電話で相談。Web予約導線あり。",
    businessHours: "Web専用窓口 平日 9:00〜17:30 / 電話受付は公式サイトで確認",
    closedDays: "土日祝の問い合わせは翌営業日対応の案内あり",
    registeredTravelAgency: "観光庁長官登録旅行業 第1677号",
    officialUrl: "https://www.shoko-travel.jp/",
    mapUrl: "https://maps.google.com/?q=山形県鶴岡市錦町2-60",
    officialLinks: [
      { label: "公式サイト", url: "https://www.shoko-travel.jp/", type: "website" },
      { label: "会社案内", url: "https://www.shoko-travel.jp/company/", type: "website" },
      { label: "団体旅行", url: "https://www.shoko-travel.jp/group/", type: "website" },
    ],
    editorComment: "山形県内では最も旅行会社らしい総合力がある候補。庄内発着の募集型ツアー、山旅、飛行機旅を一つのサイトで見られるため、まず比較対象に入れたい。",
    highlight: "庄内発着のツアーと旅行相談なら最初に確認したい地元旅行会社。",
    imageUrl: "https://images.unsplash.com/photo-1494515843206-f3117d3f51b7",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "庄交トラベル 公式サイト", url: "https://www.shoko-travel.jp/", sourceType: "official", collectedAt: verifiedAt, note: "庄交ミリオンツアー、飛行機の旅、山旅、海外、山形の旅、Web予約導線を確認。" },
      { title: "庄交トラベル 会社案内", url: "https://www.shoko-travel.jp/company/", sourceType: "official", collectedAt: verifiedAt, note: "運営会社、所在地、登録旅行業、JATA会員、問い合わせ先を確認。" },
    ],
    faqs: [
      { question: "庄交トラベルはどの地域の旅行に向いていますか？", answer: "鶴岡・酒田を中心とした庄内発着のバス旅、山旅、飛行機利用の旅行を探す人に向いています。" },
      { question: "旅行業登録は確認できますか？", answer: "公式サイト上で、株式会社庄交コーポレーション 庄交トラベルとして観光庁長官登録旅行業第1677号が確認できます。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "shonai-kotsu",
    name: "庄内交通",
    tagline: "庄内の高速バス・貸切バス・観光アクセスをまとめて確認できる",
    description: "鶴岡市に本社を置く庄内エリアの交通会社。高速バス、路線バス、庄内空港連絡バス、貸切バス、バスで巡る庄内観光など、移動手段と観光導線をまとめて確認できます。",
    area: "鶴岡・酒田・庄内",
    address: "山形県鶴岡市錦町2-60",
    phone: "0235-24-5333",
    services: ["貸切バス", "バスツアー", "団体旅行", "着地型ツアー"],
    bestFor: ["庄内で貸切バスを相談したい", "空港・高速バスと観光を組み合わせたい", "出羽三山や庄内観光の交通を確認したい"],
    tags: ["庄内交通", "貸切バス", "庄内観光", "空港連絡バス", "高速バス", "鶴岡"],
    priceRange: "路線・貸切・見積もり内容により異なる",
    consultationStyle: "公式サイトの貸切バス見積り・バス案内所・電話で確認。",
    businessHours: "案内所により異なるため公式サイトで確認",
    closedDays: "案内所により異なるため公式サイトで確認",
    registeredTravelAgency: "旅行業約款・条件書の掲載あり。登録詳細は公式サイトで要確認",
    officialUrl: "https://www.shonaikotsu.jp/",
    mapUrl: "https://maps.google.com/?q=山形県鶴岡市錦町2-60",
    officialLinks: [
      { label: "公式サイト", url: "https://www.shonaikotsu.jp/", type: "website" },
      { label: "貸切バス", url: "https://www.shonaikotsu.jp/charter/", type: "website" },
      { label: "庄内観光", url: "https://www.shonaikotsu.jp/tourism/", type: "website" },
    ],
    editorComment: "純粋な旅行会社というより地域交通の基盤。庄内で団体移動や観光バス、空港連絡を絡める旅行なら、旅行会社と並行して確認する価値が高い。",
    highlight: "庄内の交通と観光アクセスをまとめて確認できる地域交通会社。",
    imageUrl: "https://images.unsplash.com/photo-1570125909232-eb263c188f7e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "庄内交通 公式サイト", url: "https://www.shonaikotsu.jp/", sourceType: "official", collectedAt: verifiedAt, note: "高速バス、路線バス、空港連絡バス、貸切バス、庄内観光導線を確認。" },
      { title: "庄内交通 貸切バス", url: "https://www.shonaikotsu.jp/charter/", sourceType: "official", collectedAt: verifiedAt, note: "貸切バスラインナップ、見積り、安全性評価を確認。" },
    ],
    faqs: [
      { question: "庄内交通は旅行会社として使えますか？", answer: "旅行手配そのものは庄交トラベルが中心ですが、貸切バス・観光アクセス・空港連絡を確認する窓口として実用性があります。" },
      { question: "団体旅行の移動相談に向いていますか？", answer: "貸切バスの見積り導線があるため、学校・職場・地域団体の移動手段を相談したい場合に向いています。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "tendodays-dmc-tendo",
    name: "TENDODAYS / DMC天童温泉",
    tagline: "天童温泉を起点に、山形らしい体験ツアーを予約できる",
    description: "株式会社DMC天童温泉が運営する体験ツアーサイト。天童温泉を起点に、羽黒山巡礼、さくらんぼ狩り、山形の食・歩く・学ぶ体験など、地域と連携した着地型ツアーを展開しています。",
    area: "天童・村山・庄内連携",
    address: "山形県天童市周辺",
    services: ["着地型ツアー", "国内旅行", "団体旅行", "宿泊手配"],
    bestFor: ["天童温泉滞在中に体験を足したい", "山形らしい食や文化を少人数で体験したい", "ユニバーサルツーリズムも意識したい"],
    tags: ["天童温泉", "着地型ツアー", "体験ツアー", "さくらんぼ", "羽黒山", "DMC"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイト・予約サイト・メール・LINEで確認。",
    businessHours: "ツアー等で電話が繋がらない場合はメール・LINE案内あり",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "標識・約款・旅行条件書の掲載あり。登録詳細は公式サイトで確認",
    officialUrl: "https://www.tendodays.com/",
    mapUrl: "https://maps.google.com/?q=DMC天童温泉",
    officialLinks: [
      { label: "公式サイト", url: "https://www.tendodays.com/", type: "website" },
      { label: "体験ツアー", url: "https://www.tendodays.com/tour", type: "website" },
      { label: "会社概要", url: "https://www.tendodays.com/company", type: "website" },
    ],
    editorComment: "山形の地元体験を商品化する力が強い。大型バスツアーではなく、温泉滞在に体験を足したい読者に合う。",
    highlight: "天童温泉発の体験ツアーや山形らしいローカル体験を探せる。",
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "TENDODAYS 公式サイト", url: "https://www.tendodays.com/", sourceType: "official", collectedAt: verifiedAt, note: "体験ツアー、天童温泉起点、ユニバーサルツーリズム、会社概要・標識導線を確認。" },
      { title: "TENDODAYS 体験ツアー", url: "https://www.tendodays.com/tour", sourceType: "official", collectedAt: verifiedAt, note: "羽黒山、さくらんぼ狩り、食・歩く・学ぶ体験のツアー導線を確認。" },
    ],
    faqs: [
      { question: "TENDODAYSは旅行会社ですか？", answer: "株式会社DMC天童温泉が運営する体験ツアーの予約サイトです。標識・約款・旅行条件書への導線も公式サイトにあります。" },
      { question: "どんな旅行に向いていますか？", answer: "天童温泉を拠点に、山形の食・自然・文化体験を旅程に組み込みたい人に向いています。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "arcadia-tourism-bureau",
    name: "やまがたアルカディア観光局",
    tagline: "置賜南部の体験ツアーと地域文化をまとめて探せる",
    description: "長井市・南陽市・白鷹町・飯豊町・小国町の観光を発信する広域観光局。ARCADIA'Sショップで、カヌー、水上自転車、トレッキング、食文化、視察プランなどの体験ツアーを企画販売しています。",
    area: "長井・南陽・白鷹・飯豊・小国",
    address: "山形県置賜地域",
    services: ["着地型ツアー", "国内旅行", "団体旅行"],
    bestFor: ["置賜地域の体験ツアーを探したい", "長井・南陽・白鷹・飯豊・小国を周遊したい", "視察や地域文化体験を組みたい"],
    tags: ["置賜", "長井", "南陽", "体験ツアー", "視察", "広域観光"],
    priceRange: "ツアーごとに設定",
    consultationStyle: "公式サイトの旅プラン・ショップ・問い合わせから確認。",
    businessHours: "公式サイトで要確認",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://arcadia-kanko.jp/",
    mapUrl: "https://maps.google.com/?q=やまがたアルカディア観光局",
    officialLinks: [
      { label: "公式サイト", url: "https://arcadia-kanko.jp/", type: "website" },
      { label: "旅プラン", url: "https://arcadia-kanko.jp/tour/", type: "website" },
      { label: "お問い合わせ", url: "https://arcadia-kanko.jp/contact/", type: "website" },
    ],
    editorComment: "置賜の小規模な体験や視察を探す入口として有用。旅行会社というより地域DMC寄りだが、地元らしい旅を組むには外せない。",
    highlight: "置賜南部の体験・食・文化・視察プランを探しやすい。",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "やまがたアルカディア観光局 公式サイト", url: "https://arcadia-kanko.jp/", sourceType: "official", collectedAt: verifiedAt, note: "対象エリア、旅プラン、アクティビティ、ARCADIA'Sショップのツアー企画販売を確認。" },
      { title: "やまがたアルカディア観光局 旅プラン", url: "https://arcadia-kanko.jp/tour/", sourceType: "official", collectedAt: verifiedAt, note: "食文化、マタギ、街歩き、視察プランなどの掲載を確認。" },
    ],
    faqs: [
      { question: "やまがたアルカディア観光局はどのエリアが対象ですか？", answer: "長井市、南陽市、白鷹町、飯豊町、小国町の2市3町を中心にした置賜地域です。" },
      { question: "団体や視察にも使えますか？", answer: "公式サイトではSDGs未来都市 長井市の視察プランなども確認できます。内容や人数は事前に問い合わせてください。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "kaminoyama-rhapsody",
    name: "上山市観光物産協会 / 上山ラプソディ",
    tagline: "かみのやま温泉の観光プランと旅行業登録導線を持つ地域窓口",
    description: "一般社団法人上山市観光物産協会が運営する観光サイト。観光プラン、宿泊予約、かみのやま温泉の情報に加え、旅行業登録票・約款・旅行条件書の導線があります。",
    area: "上山・かみのやま温泉",
    address: "山形県上山市矢来1-2-1",
    phone: "023-672-0839",
    services: ["着地型ツアー", "国内旅行", "宿泊手配"],
    bestFor: ["かみのやま温泉滞在を組みたい", "地域の観光プランを公式情報で確認したい", "宿泊と周辺体験を合わせて考えたい"],
    tags: ["上山", "かみのやま温泉", "観光プラン", "宿泊予約", "旅行業登録", "温泉"],
    priceRange: "プラン・宿泊内容により異なる",
    consultationStyle: "公式サイト・電話・メールで確認。",
    businessHours: "9:00〜17:00",
    closedDays: "公式サイトで要確認",
    registeredTravelAgency: "旅行業登録票・約款・旅行条件書の掲載あり。登録詳細は公式サイトで確認",
    officialUrl: "https://kaminoyama-spa.com/",
    mapUrl: "https://maps.google.com/?q=山形県上山市矢来1-2-1",
    officialLinks: [
      { label: "公式サイト", url: "https://kaminoyama-spa.com/", type: "website" },
      { label: "観光プラン", url: "https://kaminoyama-spa.com/plan/", type: "website" },
      { label: "旅行業登録票・約款", url: "https://kaminoyama-spa.com/", type: "website" },
    ],
    editorComment: "温泉地の公式観光窓口として、旅行業登録票・約款まで出している点が強い。上山に泊まる旅行なら宿と体験を合わせて確認したい。",
    highlight: "かみのやま温泉の観光プランと宿泊導線を公式に確認できる。",
    imageUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "上山ラプソディ 公式サイト", url: "https://kaminoyama-spa.com/", sourceType: "official", collectedAt: verifiedAt, note: "観光プラン、宿泊予約、問い合わせ、旅行業登録票・約款導線、所在地を確認。" },
    ],
    faqs: [
      { question: "上山ラプソディは旅行会社ですか？", answer: "上山市観光物産協会の公式観光サイトで、旅行業登録票・約款・旅行条件書への導線があります。地域の観光プラン確認に向いています。" },
      { question: "宿泊予約もできますか？", answer: "公式サイトに宿泊予約導線があります。空室や条件は予約前に公式ページで確認してください。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "mogami-basho-line",
    name: "最上峡芭蕉ライン観光",
    tagline: "最上川舟下りと食事・貸切船を公式予約できる",
    description: "戸沢村の最上川舟下り事業者。通常航路、貸切船、食事予約、宿泊施設連携、帰りの路線バスや車回送など、最上峡観光に必要な導線がまとまっています。",
    area: "最上・戸沢",
    address: "山形県最上郡戸沢村大字古口86-1",
    phone: "0233-72-2001",
    services: ["着地型ツアー", "国内旅行", "団体旅行"],
    bestFor: ["最上川舟下りを旅程に入れたい", "貸切船や小団体利用を相談したい", "食事や帰りの移動もまとめて確認したい"],
    tags: ["最上川", "舟下り", "戸沢", "貸切船", "食事予約", "着地型"],
    priceRange: "普通旅客料金 大人3,000円など。貸切・食事は内容により異なる",
    consultationStyle: "公式サイト・Web予約・電話で確認。",
    businessHours: "4月〜11月 8:20〜17:10 / 12月〜3月 9:00〜16:30",
    closedDays: "運航状況により異なるため当日確認推奨",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://www.blf.co.jp/",
    mapUrl: "https://maps.google.com/?q=山形県最上郡戸沢村大字古口86-1",
    officialLinks: [
      { label: "公式サイト", url: "https://www.blf.co.jp/", type: "website" },
      { label: "会社概要", url: "https://www.blf.co.jp/company", type: "website" },
      { label: "Web予約", url: "https://www.blf.co.jp/", type: "website" },
    ],
    editorComment: "旅行会社ではないが、最上峡観光では実質的な旅程の核になる。貸切船や食事予約まで公式に確認できるため、小団体旅行でも使いやすい。",
    highlight: "最上川舟下りを中心に、食事・貸切・戻りの移動まで確認できる。",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "最上峡芭蕉ライン観光 公式サイト", url: "https://www.blf.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "舟下り、貸切船、食事予約、料金、営業時間、所在地、問い合わせ先を確認。" },
    ],
    faqs: [
      { question: "最上峡芭蕉ライン観光は団体旅行に向いていますか？", answer: "貸切船の相談導線があり、小団体や家族・友人グループの旅行に向いています。詳細は電話で確認してください。" },
      { question: "舟下り後の戻り方も確認できますか？", answer: "公式サイトでは路線バス、往復船、車回送の案内があり、旅程全体を組みやすいです。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
  {
    slug: "zao-ropeway",
    name: "蔵王ロープウェイ",
    tagline: "蔵王温泉の山岳観光・トレッキング・ナイトクルージングの入口",
    description: "山形市蔵王温泉のロープウェイ事業者。ロープウェイ、蔵王ガイド、トレッキング、サマーナイトクルージング、蔵王テラスなど、蔵王温泉滞在中の山岳観光を組みやすい公式導線があります。",
    area: "蔵王温泉・山形市",
    address: "山形県山形市蔵王温泉229-3",
    phone: "023-694-9518",
    services: ["着地型ツアー", "国内旅行", "団体旅行"],
    bestFor: ["蔵王温泉で山岳観光を組みたい", "トレッキングや夜間企画を確認したい", "ロープウェイ運行状況を公式情報で見たい"],
    tags: ["蔵王温泉", "ロープウェイ", "トレッキング", "ナイトクルージング", "山岳観光", "山形市"],
    priceRange: "ロープウェイ料金・企画内容により異なる",
    consultationStyle: "公式サイト・電話で運行情報や企画を確認。",
    businessHours: "運行情報・営業案内は公式サイトで確認",
    closedDays: "天候・点検・季節により異なる",
    registeredTravelAgency: "公式サイトで要確認",
    officialUrl: "https://zaoropeway.co.jp/",
    mapUrl: "https://maps.google.com/?q=山形県山形市蔵王温泉229-3",
    officialLinks: [
      { label: "公式サイト", url: "https://zaoropeway.co.jp/", type: "website" },
      { label: "蔵王ガイド", url: "https://zaoropeway.co.jp/summer/index.php", type: "website" },
      { label: "料金・営業案内", url: "https://zaoropeway.co.jp/summer/ropeway.php", type: "website" },
    ],
    editorComment: "旅行会社というより蔵王観光の現地中核。運行状況を見ながら旅程を組む必要があるため、蔵王温泉旅行では必ず確認したい。",
    highlight: "蔵王温泉の山岳観光・トレッキング・ロープウェイ運行を公式に確認できる。",
    imageUrl: "https://images.unsplash.com/photo-1570459027562-4a916cc6113f",
    lastVerifiedAt: verifiedAt,
    sources: [
      { title: "蔵王ロープウェイ 公式サイト", url: "https://zaoropeway.co.jp/", sourceType: "official", collectedAt: verifiedAt, note: "ロープウェイ、運行情報、蔵王ガイド、所在地、問い合わせ先を確認。" },
      { title: "蔵王ロープウェイ 夏サイト", url: "https://zaoropeway.co.jp/summer/index.php", sourceType: "official", collectedAt: verifiedAt, note: "蔵王テラス、トレッキング、サマーナイトクルージング等の導線を確認。" },
    ],
    faqs: [
      { question: "蔵王ロープウェイは旅行会社ですか？", answer: "旅行会社ではなく現地交通・観光事業者です。蔵王温泉旅行ではロープウェイ運行や山岳観光の公式情報源として重要です。" },
      { question: "天候による変更はありますか？", answer: "山岳交通のため、天候や点検で運行状況が変わる可能性があります。出発前に公式サイトの運行情報を確認してください。" },
    ],
    relatedRankingSlugs: ["yamagata-local-travel-agencies"],
  },
];
