import type { ProteinProduct, Source } from "@/lib/types";

const collectedAt = "2026-06-08";

const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

export const proteinProducts: ProteinProduct[] = [
  {
    slug: "myprotein-impact-whey",
    brand: "Myprotein",
    name: "Impact Whey Protein（インパクトホエイプロテイン）",
    description: "ヨーロッパ最大のスポーツ栄養ブランド・Myproteinのベストセラー商品。乳牛の乳から精製・乾燥した100%天然由来ホエイを使用し、50種類以上のフレーバーが揃う。頻繁なセール・クーポンでコスパは国内トップクラス。",
    proteinType: "whey-wpc",
    targets: ["men", "women", "student", "beginner"],
    servingSize: 25,
    protein: 21,
    calories: 111,
    carbs: 4.8,
    fat: 3.2,
    packageWeight: 1000,
    packagePrice: 4000,
    pricePerKg: 4000,
    flavors: ["チョコレートスムージー", "ナチュラルバニラ", "ストロベリークリーム", "抹茶ラテ", "北海道ミルク", "桜ストロベリーミルク", "ミックスジュース", "他40種類以上"],
    features: ["ヨーロッパ最大スポーツ栄養ブランド", "50種類以上のフレーバー展開", "頻繁なセール・クーポンでさらに安く", "1kg・2.5kg・5kgと容量展開が豊富", "天然由来100%ホエイ"],
    pros: ["フレーバーの豊富さは業界最多クラス", "セール時は¥2,000台/kgになることも", "1食25gあたり21gのタンパク質", "国内外で長年の実績・信頼性"],
    cons: ["通常価格はやや高め", "セール時のまとめ買いが前提", "海外ブランドのため日本語サポートが限定的"],
    officialUrl: "https://www.myprotein.jp/p/sports-nutrition/myprotein-impact-whey-protein-jp-edition/15278802/",
    imageUrl: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800&q=80",
    editorNote: "コスパ最優先の学生・男性向けの最有力候補。セール情報をこまめにチェックすることが重要で、30〜40%オフのタイミングでまとめ買いすると最安クラスになる。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Myprotein Impact Whey Protein 公式JP", "https://www.myprotein.jp/p/sports-nutrition/myprotein-impact-whey-protein-jp-edition/15278802/", "official", "栄養成分・価格・フレーバーを確認。"),
      src("Myprotein JP 公式サイト", "https://www.myprotein.jp/", "official", "ブランド情報・セール情報を確認。"),
    ],
    faqs: [
      { question: "Myproteinはどこで買えますか？", answer: "公式サイト（myprotein.jp）での購入が最も価格が安く、フレーバーの選択肢も最多です。Amazonや楽天でも購入可能ですが、公式サイトのセール時が最安になることが多いです。" },
      { question: "セールはどのくらいの頻度で実施されますか？", answer: "ブラックフライデー・年始・季節ごとに大型セールが実施されます。メールマガジン登録やSNSフォローでセール情報を入手できます。30〜40%オフになることも多いです。" },
    ],
  },
  {
    slug: "on-gold-standard-whey",
    brand: "Optimum Nutrition（オプティマムニュートリション）",
    name: "Gold Standard 100% Whey（ゴールドスタンダード100%ホエイ）",
    description: "世界的ベストセラープロテイン。WPI（ホエイプロテインアイソレート）を主体とした高純度配合で、BCAAs 5.5g/食を含む。遺伝子組み換え不使用。品質と実績で世界中のアスリートから支持される。",
    proteinType: "whey-wpi",
    targets: ["trainer", "men"],
    servingSize: 30,
    protein: 24,
    calories: 119,
    carbs: 4,
    fat: 1,
    packageWeight: 908,
    packagePrice: 6280,
    pricePerKg: 6919,
    flavors: ["ダブルリッチチョコレート", "クッキー&クリーム", "ストロベリーバナナ", "バニラアイスクリーム", "エクストリームミルクチョコレート", "他多数"],
    features: ["WPI主体の高純度配合", "BCAA 5.5g/1食含有", "遺伝子組み換え不使用", "世界累計売上No.1クラス", "グルタミン4g/1食含有"],
    pros: ["1食24gと高タンパク質", "脂質わずか1g/食", "WPI主体で消化吸収が早い", "世界的実績による信頼性"],
    cons: ["1kg換算で¥6,919と価格は高め", "大容量サイズは輸入コストが加わる", "味のバリエーションはMyproteinより少ない"],
    officialUrl: "https://www.optimumnutrition.com/ja-jp/",
    imageUrl: "https://images.unsplash.com/photo-1627393047483-e4c81acaf2d4?w=800&q=80",
    editorNote: "品質・純度を最優先するトレーナー・上級者向けの定番。WPI主体の配合は脂質・乳糖が少なく消化吸収に優れる。コスパより品質重視の層に最適。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Optimum Nutrition Gold Standard 公式JP", "https://www.optimumnutrition.com/ja-jp/", "official", "栄養成分・価格・フレーバーを確認。"),
      src("コストコ Gold Standard 2.88kg", "https://www.costco.co.jp/", "local-media", "2.88kg大容量サイズの価格を確認。"),
      src("iHerb Gold Standard 2.17kg", "https://jp.iherb.com/", "other", "海外購入価格の参考として確認。"),
    ],
    faqs: [
      { question: "コストコでも買えますか？", answer: "はい。コストコでは2.88kgの大容量サイズが約¥12,280（税込）で販売されており、1kg換算約¥4,264と公式価格より安くなります。コストコ会員の方は検討の価値があります。" },
      { question: "WPCとWPIの違いは何ですか？", answer: "WPC（ホエイプロテインコンセントレート）は80%前後のタンパク質含有率。WPI（アイソレート）は90%以上で脂質・乳糖がほぼ除去されています。Gold StandardはWPI主体のためタンパク質純度が高く、乳糖不耐症気味の方にも向きます。" },
    ],
  },
  {
    slug: "savas-whey-100",
    brand: "ザバス（SAVAS）／株式会社明治",
    name: "ホエイプロテイン100",
    description: "国内最大手スポーツ栄養ブランド・明治が展開するザバスの代表商品。ドラッグストア・スーパー・コンビニでも入手できる国産プロテイン。4種のビタミンB群＋ビタミンC・Dを配合し、トレーニングサポートに対応。",
    proteinType: "whey-wpc",
    targets: ["beginner", "women", "student"],
    servingSize: 28,
    protein: 19.5,
    calories: 111,
    carbs: 3.7,
    fat: 2.0,
    packageWeight: 980,
    packagePrice: 4500,
    pricePerKg: 4592,
    flavors: ["リッチショコラ", "バニラ", "ストロベリー", "ミルクティー", "バナナ", "バニラアイスクリーム", "ビターショコラ", "抹茶", "すっきりフルーティー"],
    features: ["ドラッグストア・スーパーで入手可能", "国産ブランド・明治グループ", "ビタミンB群・C・D配合", "日本語サポート完備", "初心者に選ばれやすい知名度"],
    pros: ["コンビニ・薬局でもすぐ買える", "日本語の公式サポートが充実", "ビタミン補給も同時にできる", "フレーバーが豊富（9種類）"],
    cons: ["1食あたりのタンパク質量は19.5gとやや少なめ", "1kg換算価格は海外ブランドより割高", "大容量サイズがない（最大980g）"],
    officialUrl: "https://www.meiji.co.jp/sports/savas/products/built_powered/whey100.html",
    imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80",
    editorNote: "「まず試してみたい初心者」「近所のドラッグストアで買いたい」読者への最初の提案先。国産・明治ブランドの安心感が特に初心者・女性に支持される。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ザバス ホエイプロテイン100 明治公式", "https://www.meiji.co.jp/sports/savas/products/built_powered/whey100.html", "official", "栄養成分・フレーバー・ビタミン配合を確認。"),
      src("価格.com ザバス ホエイプロテイン100", "https://kakaku.com/", "local-media", "最安値・価格推移を確認。"),
    ],
    faqs: [
      { question: "ザバスはコンビニで買えますか？", answer: "はい。ローソン・ファミリーマートなど主要コンビニのほか、マツモトキヨシ等のドラッグストア、スーパーでも購入できます。スポーツ用品店ではより多くのフレーバーが揃っています。" },
      { question: "初心者がまず選ぶなら何フレーバーがおすすめですか？", answer: "「リッチショコラ」が最もクセがなく飲みやすいと口コミで評価されています。甘い味が苦手な方は牛乳で割ることでマイルドになります。" },
    ],
  },
  {
    slug: "grong-whey-standard",
    brand: "GronG（グロング）",
    name: "ホエイプロテイン100 スタンダード",
    description: "Amazonホエイプロテインランキング上位の常連・国内製造ブランド。WPC使用でタンパク質含有率75%以上を確保し、11種のビタミン配合。1kg¥4,480・3kgでさらにお得と、価格と品質のバランスで高評価を獲得している。",
    proteinType: "whey-wpc",
    targets: ["men", "women", "student", "diet", "beginner"],
    servingSize: 29,
    protein: 22.3,
    calories: 118,
    carbs: 2.5,
    fat: 2.1,
    packageWeight: 1000,
    packagePrice: 4480,
    pricePerKg: 4480,
    flavors: ["ナチュラル（無味）", "チョコレート", "ストロベリー", "バナナ", "ヨーグルト"],
    features: ["国内製造WPC", "11種のビタミン配合", "タンパク質含有率75%以上", "Amazonランキング上位常連", "1kg・3kg展開"],
    pros: ["1食22.3gのタンパク質でコスパ優秀", "低糖質（2.5g/食）でダイエットにも", "国内製造の安心感", "3kg購入で1kg換算¥3,993とさらにお得"],
    cons: ["フレーバーは5種類と少なめ", "ナチュラル（無味）は慣れが必要", "日本語公式サポートはWebのみ"],
    officialUrl: "https://shop.grong.jp/products/whey-protein-standard",
    imageUrl: "https://images.unsplash.com/photo-1579722820903-4eb93ac8a911?w=800&q=80",
    editorNote: "「コスパを重視しつつ国内製造を選びたい」層への最有力候補。3kgまとめ買いで1kg換算¥3,993は国内製造ブランド中トップクラスのコスパ。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("GronG ホエイプロテイン100 スタンダード 公式", "https://shop.grong.jp/products/whey-protein-standard", "official", "栄養成分・価格・フレーバー・ビタミン配合を確認。"),
      src("my-best.com GronGレビュー", "https://my-best.com/", "editorial", "口コミ・評価情報を参考として確認。"),
    ],
    faqs: [
      { question: "GronGの3kgと1kgどちらがお得ですか？", answer: "3kg（¥11,980）の方が1kg換算で約¥3,993となり、1kg（¥4,480）より約¥487/kg安くなります。長期継続の見込みがある方には3kgの一括購入がおすすめです。" },
      { question: "ナチュラル（無味）フレーバーはどう使いますか？", answer: "牛乳・豆乳・ヨーグルト・スムージーに混ぜると飲みやすくなります。料理（お菓子・パンケーキ等）に加えて食事からタンパク質を補う使い方も人気です。" },
    ],
  },
  {
    slug: "dns-whey-100",
    brand: "DNS（ディーエヌエス）",
    name: "プロテインホエイ100",
    description: "第一三共ヘルスケアグループ傘下のスポーツ栄養ブランドDNSの看板商品。国内食品工場で製造し、合成着色料・遺伝子組み換え原料不使用。1食24.2gのタンパク質と8種類のフレーバーで、品質重視の日本人向けに設計された高品質ホエイプロテイン。",
    proteinType: "whey-wpc",
    targets: ["men", "trainer"],
    servingSize: 35,
    protein: 24.2,
    calories: 142,
    carbs: 4.7,
    fat: 2.9,
    packageWeight: 630,
    packagePrice: 4980,
    pricePerKg: 7905,
    flavors: ["プレミアムチョコレート", "リッチバニラ", "いちごミルク", "カフェオレ", "抹茶", "バナナオレ", "トロピカルマンゴー", "レモン"],
    features: ["国内食品工場製造", "合成着色料・遺伝子組み換え不使用", "水だけで美味しく溶ける", "スポーツ専門店での取り扱いが多い", "第一三共ヘルスケアグループ"],
    pros: ["国内製造・高品質基準", "1食24.2gの高タンパク", "フレーバーが豊富（8種類）", "溶けやすく飲みやすい"],
    cons: ["1kg換算¥7,905と価格は高め", "630gサイズが主力でコスパに限界", "セールが少なく価格変動が小さい"],
    officialUrl: "https://shop.dnszone.jp/",
    imageUrl: "https://images.unsplash.com/photo-1544033527-b192daee1f5b?w=800&q=80",
    editorNote: "「国産・品質最優先で価格は二の次」というトレーニー向けの選択肢。第一三共ヘルスケアグループの品質管理と国内製造の安心感が最大の強み。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("DNS プロテインホエイ100 公式", "https://shop.dnszone.jp/", "official", "栄養成分・価格・フレーバー・製造情報を確認。"),
      src("価格.com DNS プロテインホエイ100", "https://kakaku.com/", "local-media", "価格推移を確認。"),
    ],
    faqs: [
      { question: "DNSは信頼できるブランドですか？", answer: "はい。第一三共ヘルスケアグループ傘下で、国内食品工場での製造・合成着色料不使用・遺伝子組み換え不使用と品質基準が明確です。スポーツ専門店での取り扱いも多く、日本のスポーツ栄養ブランドとして長い実績があります。" },
      { question: "水で溶かしても飲みやすいですか？", answer: "はい。公式でも「水だけで美味しく溶ける」と謳っており、シェイカーで振るだけできれいに溶けます。牛乳で割ると濃厚さが増します。" },
    ],
  },
  {
    slug: "valx-whey-wpc",
    brand: "VALX（バルクス）",
    name: "ホエイプロテイン WPC",
    description: "筋肉博士・山本義徳氏監修のスポーツ栄養ブランドVALXの主力プロテイン。国内生産・WPC使用で飲みやすさと美味しさに定評あり。女性・ダイエット目的にも対応したラインナップで、幅広い層に人気が高まっている。",
    proteinType: "whey-wpc",
    targets: ["women", "men", "diet", "beginner"],
    servingSize: 30,
    protein: 21.2,
    calories: 116,
    carbs: 4.1,
    fat: 1.7,
    packageWeight: 1000,
    packagePrice: 5490,
    pricePerKg: 5490,
    flavors: ["チョコレート", "ベリー", "ヨーグルト", "カフェオレ", "バナナ", "抹茶", "アーモンドとうふ"],
    features: ["山本義徳氏監修", "国内生産", "WPC使用で飲みやすい", "女性・ダイエット向けラインも展開", "420g・1kgと試しやすいサイズ展開"],
    pros: ["「アーモンドとうふ」など個性的フレーバーが好評", "低脂質（1.7g/食）で女性にも", "飲みやすさ・美味しさの評価が高い", "国内生産の安心感"],
    cons: ["1kg換算¥5,490はミドルレンジ", "フレーバー数は7種類", "セールは限定的"],
    officialUrl: "https://shop.valx.jp/",
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee81f0?w=800&q=80",
    editorNote: "「美味しさ・飲みやすさを一番に選びたい」女性や初心者への有力候補。山本義徳氏の監修ブランドとしてトレーニーからの信頼も高い。アーモンドとうふフレーバーは特に高評価。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("VALX ホエイプロテイン WPC 公式", "https://shop.valx.jp/", "official", "栄養成分・価格・フレーバーを確認。"),
      src("楽天市場 VALX公式ストア", "https://www.rakuten.co.jp/", "local-media", "フレーバー・容量・価格を確認。"),
    ],
    faqs: [
      { question: "VALXのアーモンドとうふフレーバーは本当においしいですか？", answer: "口コミでは「他にはない個性的な味」「プロテインらしくない飲みやすさ」と好評価が多いです。甘さは控えめで、豆乳や牛乳で割るとさらに美味しくなるという意見もあります。" },
      { question: "420gサイズは何回分ですか？", answer: "1食30g使用の場合、約14食分です。まず試したい方や複数フレーバーを試したい方に向いたサイズです。" },
    ],
  },
  {
    slug: "ultora-whey-diet",
    brand: "ULTORA（ウルトラ）",
    name: "ホエイダイエットプロテイン",
    description: "楽天総合1位受賞実績を持つダイエット特化型プロテイン。人工甘味料不使用（植物由来ステビア使用）でWPC+WPIのブレンド配合。1食117kcal・脂質1.5gと低カロリー設計で、日本女性の「ダイエット＋美容」ニーズに応えた商品。",
    proteinType: "whey-wpc",
    targets: ["women", "diet"],
    servingSize: 30,
    protein: 22.6,
    calories: 117,
    carbs: 3.1,
    fat: 1.5,
    packageWeight: 810,
    packagePrice: 4401,
    pricePerKg: 5434,
    flavors: ["抹茶ラテ", "チョコレート", "クリアストロベリー", "ミルクティー", "ほうじ茶ラテ", "フルーツオレ", "ヨーグルト", "ココナッツチョコレート", "黒ゴマきな粉", "クッキー&クリーム"],
    features: ["人工甘味料不使用（ステビア使用）", "WPC+WPIブレンド配合", "楽天総合1位受賞実績", "ビタミン複数配合", "ダイエット・置き換えに特化"],
    pros: ["人工甘味料不使用で安心感が高い", "1食1.5gの低脂質設計", "和風フレーバーが豊富（抹茶・ほうじ茶・黒ゴマきな粉）", "楽天での評価が高い"],
    cons: ["1kg換算¥5,434はやや高め", "810g・390gのみで大容量がない", "ステビアの後味が苦手な方も一定いる"],
    officialUrl: "https://ultora.co.jp/",
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80",
    editorNote: "「人工甘味料は避けたい」「ダイエット目的だが美味しいものを飲みたい」女性へのNo.1推薦。和風フレーバーのラインナップは他社にはない強みで、続けやすさに直結する。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ULTORA ホエイダイエットプロテイン 公式", "https://ultora.co.jp/", "official", "栄養成分・価格・フレーバー・人工甘味料不使用を確認。"),
      src("楽天市場 ULTORAランキング実績", "https://www.rakuten.co.jp/", "local-media", "楽天総合1位実績を確認。"),
    ],
    faqs: [
      { question: "人工甘味料不使用とはどういう意味ですか？", answer: "アスパルテーム・スクラロース・アセスルファムKなどの合成甘味料を使用していません。ULTORAは植物由来のステビアを使用しており、天然甘味料のみで甘さを出しています。" },
      { question: "ダイエット中に1日何回飲めばいいですか？", answer: "一般的には1日1〜2回（1食30gあたり22.6gのタンパク質）が目安です。食事で摂れないタンパク質を補う形で使用するのが基本で、置き換えとして使う場合は1食分として活用できます。" },
    ],
  },
  {
    slug: "finelab-whey-wpi",
    brand: "ファイン・ラボ（Fine Lab）",
    name: "ホエイプロテインピュアアイソレート",
    description: "CFM製法（冷水ろ過法）によるWPI（ホエイプロテインアイソレート）使用の高純度プロテイン。脂質0.3g・炭水化物0.1g（1食あたり）と極めて低い数値を実現。乳糖（ラクトース）も少なく、お腹が弱い方にも対応しやすい。",
    proteinType: "whey-wpi",
    targets: ["trainer", "diet", "women"],
    servingSize: 20,
    protein: 18.2,
    calories: 76,
    carbs: 0.1,
    fat: 0.3,
    packageWeight: 1000,
    packagePrice: 7200,
    pricePerKg: 7200,
    flavors: ["プレーン", "ミルクココア", "ストロベリー", "ミックスフルーツ", "メロン"],
    features: ["CFM製法によるWPI使用", "脂質0.3g・炭水化物0.1g/食", "乳糖（ラクトース）が少ない", "1kg・2kg・4.5kg展開", "高純度・高透明性"],
    pros: ["脂質・糖質を徹底的に抑えたい方の最適解", "乳糖不耐症気味の方にも向きやすい", "高純度WPIで筋肉へのアミノ酸供給が早い", "減量期・コンテスト前の使用に最適"],
    cons: ["1kg換算¥7,200と価格は高め（WPIのため）", "フレーバーは5種類と少なめ", "タンパク質量は1食18.2gとやや少なめ（サービングサイズ20gのため）"],
    officialUrl: "https://www.fine-lab.com/wpi-product-page",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80",
    editorNote: "「脂質・炭水化物をとにかく削りたい」コンテスト前のトレーナーやダイエット追い込み期の読者への特化選択肢。WPIとしての純度と乳糖の少なさが他社WPCとの差別化ポイント。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ファイン・ラボ ホエイプロテインピュアアイソレート 公式", "https://www.fine-lab.com/wpi-product-page", "official", "栄養成分・製法・価格を確認。"),
      src("my-best.com WPIプロテインレビュー", "https://my-best.com/", "editorial", "口コミ・評価情報を確認。"),
    ],
    faqs: [
      { question: "WPCとWPIどちらを選べばいいですか？", answer: "ダイエット中・脂質・糖質を徹底的に抑えたい・乳糖が気になる方はWPI。コスパ重視・筋肉増量が目的・特に制限のない方はWPCが向いています。ファイン・ラボのWPIは脂質0.3g/食と国内WPIトップクラスの低さです。" },
      { question: "乳糖不耐症でも飲めますか？", answer: "WPIは製造過程で乳糖がほぼ除去されるため、WPCより乳糖含有量が少なく、乳糖不耐症気味の方でも飲みやすい場合が多いです。ただし完全な乳糖フリーではないため、重度の乳糖不耐症の方は医師にご相談ください。" },
    ],
  },
  {
    slug: "kentai-powerbody-whey",
    brand: "Kentai（健康体力研究所）",
    name: "パワーボディ 100%ホエイプロテイン",
    description: "1973年創業の老舗スポーツサプリブランド・Kentaiの大容量ホエイプロテイン。2.3kgで約¥7,400とコスパが高く、1kg換算約¥3,217は国産ブランド中最安クラス。ビタミンA・B群・C・D・E・ナイアシン等多数のビタミン・ミネラルを配合。",
    proteinType: "whey-wpc",
    targets: ["student", "men", "trainer"],
    servingSize: 20,
    protein: 14.7,
    calories: 79,
    carbs: 2.4,
    fat: 1.2,
    packageWeight: 2300,
    packagePrice: 7400,
    pricePerKg: 3217,
    flavors: ["ミルクチョコ", "ストロベリー", "バナナラテ"],
    features: ["1973年創業の老舗ブランド", "2.3kgで¥7,400（1kg換算¥3,217）", "ビタミン・ミネラル多数配合", "国産スポーツサプリの草分け的存在"],
    pros: ["2.3kgでの1kg換算価格は国産最安クラス", "ビタミン・ミネラル豊富でサプリ要らず", "老舗ブランドの信頼性", "大容量で長期継続できる"],
    cons: ["1食14.7gとタンパク質量は少なめ", "フレーバーが3種類のみ", "単価は高いが容量が大きいため初期費用が多い"],
    officialUrl: "https://kentai.co.jp/product/protein/powerbody100whey.html",
    imageUrl: "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800&q=80",
    editorNote: "コスパと継続性を重視する学生・長期トレーニーへの大容量選択肢。1kg換算¥3,217は国産ブランドで最安クラスで、ビタミン補給まで一元化できる効率性が魅力。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Kentai パワーボディ 100%ホエイプロテイン 公式", "https://kentai.co.jp/product/protein/powerbody100whey.html", "official", "栄養成分・価格・フレーバーを確認。"),
      src("Amazon.co.jp Kentai パワーボディ", "https://www.amazon.co.jp/", "local-media", "価格・口コミを確認。"),
    ],
    faqs: [
      { question: "2.3kgは使い切れますか？", answer: "1日1食（20g）使用で約115食分です。毎日使用すると約3.8ヶ月分。週3〜5回のトレーニングに合わせて飲む場合は半年以上もちます。大容量ですが密閉保存すれば問題なく使い切れます。" },
      { question: "タンパク質量が14.7gと他製品より少なめですが大丈夫ですか？", answer: "1食20gに対して14.7gのタンパク質は含有率73%で、WPCとして一般的な水準です。より多くのタンパク質が必要な場合は1.5スクープ（30g）で使用することも可能です。" },
    ],
  },
];
