import type { Item, Source } from "@/lib/types";

const collectedAt = "2026-06-07";

const source = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title,
  url,
  sourceType,
  collectedAt,
  note,
});

const map = (query: string) => "https://maps.google.com/?q=" + encodeURIComponent(query);

export const ramenItems: Item[] = [
  {
    slug: "sankichiya-nishibori",
    name: "三吉屋 西堀本店",
    description: "昭和32年創業の老舗。新潟あっさり醤油ラーメンの代表格として、細麺と淡麗スープを目当てに訪れる読者へ紹介したい一店です。",
    area: "新潟市中央区・古町",
    address: "新潟県新潟市中央区西堀通5番町829",
    phone: "025-222-8227",
    genre: "新潟あっさり醤油",
    tags: ["新潟5大ラーメン", "老舗", "古町", "細麺", "昼営業"],
    recommendedMenu: "中華そば",
    priceRange: "600円〜1,000円目安",
    parking: false,
    parkingNote: "専用駐車場は確認できないため、周辺コインパーキング利用を想定。",
    businessHours: "11:00〜16:00、17:00〜19:00（スープ・麺がなくなり次第終了）",
    closedDays: "火曜",
    officialUrl: "https://niigata.mypl.net/article/ramen_niigata/30547",
    mapUrl: map("三吉屋 西堀本店 新潟市中央区西堀通5番町829"),
    officialLinks: [
      { label: "店舗紹介", url: "https://niigata.mypl.net/article/ramen_niigata/30547", type: "website" },
      { label: "地図", url: map("三吉屋 西堀本店 新潟市中央区西堀通5番町829"), type: "map" },
    ],
    editorComment: "新潟ラーメンの入口記事や観光向け導線に最適。濃厚系が苦手な読者にも提案しやすく、古町散策との相性も良いです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("まいぷれ 新潟市 三吉屋 西堀本店", "https://niigata.mypl.net/article/ramen_niigata/30547", "local-media", "住所、電話、営業時間、定休日、看板メニュー確認。"),
      source("新潟市ラーメンガイドブック", "https://www.city.niigata.lg.jp/kanko/kanko/oshirase/ramen.files/guidebook.pdf", "government", "新潟5大ラーメンと掲載店舗の確認。"),
    ],
    faqs: [
      { question: "三吉屋 西堀本店はどんなラーメンですか？", answer: "細麺と淡麗スープの新潟あっさり醤油系です。濃厚さよりも昔ながらの中華そばらしさを重視する人に向いています。" },
      { question: "訪問前に確認すべきことはありますか？", answer: "スープや麺がなくなり次第終了とされるため、遅い時間の訪問前は営業状況を確認してください。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-assari-shoyu"],
  },
  {
    slug: "touyoko-shichikuyama",
    name: "元祖新潟濃厚味噌 東横 紫竹山本店",
    description: "割りスープ付きの濃厚味噌で知られる新潟5大ラーメンの代表格。太麺と味噌の強さを楽しみたい読者向けです。",
    area: "新潟市中央区・紫竹山",
    address: "新潟県新潟市中央区紫竹山1-8-20",
    phone: "025-290-4770",
    genre: "新潟濃厚味噌",
    tags: ["新潟5大ラーメン", "濃厚味噌", "割りスープ", "太麺", "駐車場あり"],
    recommendedMenu: "元祖新潟濃厚味噌",
    priceRange: "700円〜1,200円目安",
    parking: true,
    parkingNote: "車利用しやすい郊外型店舗。",
    businessHours: "平日 11:00〜15:00 / 17:00〜21:00、土日祝 11:00〜21:00",
    closedDays: "不定休",
    officialUrl: "https://www.touyoko.jp/stores",
    mapUrl: map("東横 紫竹山本店 新潟市中央区紫竹山1-8-20"),
    officialLinks: [
      { label: "公式サイト", url: "https://www.touyoko.jp/stores", type: "website" },
      { label: "地図", url: map("東横 紫竹山本店 新潟市中央区紫竹山1-8-20"), type: "map" },
    ],
    editorComment: "県外読者に新潟濃厚味噌を説明する時の軸になる店舗。味噌の濃さ、割りスープ、太麺という体験要素が明確です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("東横 公式 店舗情報", "https://www.touyoko.jp/stores", "official", "店舗展開と紫竹山本店の確認。"),
      source("GOOD LUCK TRIP 東横 紫竹山本店", "https://www.gltjp.com/ja/directory/item/11508/", "editorial", "住所、電話、営業時間、濃厚味噌の説明確認。"),
    ],
    faqs: [
      { question: "割りスープとは何ですか？", answer: "濃厚な味噌スープを好みの濃さに調整するためのスープです。まずはそのまま、途中で調整する流れが分かりやすいです。" },
      { question: "観光客にも向いていますか？", answer: "新潟5大ラーメンの一つを分かりやすく体験できるため、初回の新潟ラーメン巡りにも向いています。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-miso"],
  },
  {
    slug: "ittoya-shichikuyama",
    name: "いっとうや 紫竹山本店",
    description: "魚介系と動物系のWスープ、極太メンマ、あぶりチャーシューが印象的な人気店。新潟市内で満足度重視の一杯を探す読者へ。",
    area: "新潟市中央区・紫竹山",
    address: "新潟県新潟市中央区紫竹山3-5-23",
    phone: "025-241-8325",
    genre: "Wスープ醤油",
    tags: ["人気店", "Wスープ", "炙りチャーシュー", "駐車場あり", "通し営業"],
    recommendedMenu: "かさね醤油",
    priceRange: "900円〜1,300円目安",
    parking: true,
    parkingNote: "新潟市ラーメンガイドでは駐車場22台と掲載。",
    businessHours: "11:00〜21:00",
    closedDays: "なし",
    officialUrl: "https://niigatacity-ramen.jp/ramen/ittoya/",
    mapUrl: map("いっとうや 紫竹山本店 新潟市中央区紫竹山3-5-23"),
    officialLinks: [
      { label: "新潟市ラーメンガイド", url: "https://niigatacity-ramen.jp/ramen/ittoya/", type: "website" },
      { label: "地図", url: map("いっとうや 紫竹山本店 新潟市中央区紫竹山3-5-23"), type: "map" },
    ],
    editorComment: "王道のご当地分類ではないものの、観光・地元利用の両方で紹介しやすい実力派。ランキングでは総合満足度枠に入れたい店舗です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("新潟市ラーメンガイド いっとうや 紫竹山本店", "https://niigatacity-ramen.jp/ramen/ittoya/", "official", "住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"),
    ],
    faqs: [
      { question: "いっとうやは何を頼むべきですか？", answer: "初回は新潟市ラーメンガイドでも紹介される、かさね醤油を軸に検討しやすいです。" },
      { question: "駐車場はありますか？", answer: "新潟市ラーメンガイドでは22台と掲載されています。混雑時は余裕を見て訪問してください。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-parking"],
  },
  {
    slug: "menya-shingen",
    name: "麺や真玄",
    description: "朝ラー対応日もある、煮干しのうま味を追求した店舗。ビッグスワン周辺や車移動の読者に提案しやすい一店です。",
    area: "新潟市中央区・長潟",
    address: "新潟県新潟市中央区長潟2-3-7",
    phone: "025-287-3770",
    genre: "煮干し",
    tags: ["煮干し", "朝ラー", "駐車場あり", "中央区", "メニュー豊富"],
    recommendedMenu: "極み煮干らぁ麺",
    priceRange: "900円〜1,300円目安",
    parking: true,
    parkingNote: "新潟市ラーメンガイドでは駐車場15台と掲載。",
    businessHours: "水〜土 7:00〜10:00、11:00〜15:00、17:30〜21:00（曜日・LOにより変動）",
    closedDays: "不定休",
    officialUrl: "https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/",
    mapUrl: map("麺や真玄 新潟市中央区長潟2-3-7"),
    officialLinks: [
      { label: "新潟市ラーメンガイド", url: "https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/", type: "website" },
      { label: "地図", url: map("麺や真玄 新潟市中央区長潟2-3-7"), type: "map" },
    ],
    editorComment: "朝・昼・夜の使い分けを書けるため、単なるランキングよりも利用シーン別ページで強い店舗です。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("新潟市ラーメンガイド 麺や真玄", "https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/", "official", "住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"),
    ],
    faqs: [
      { question: "朝ラーは毎日ありますか？", answer: "新潟市ラーメンガイドでは水〜土曜のみの朝営業として掲載されています。訪問前に最新情報を確認してください。" },
      { question: "どんな味が特徴ですか？", answer: "大量のイワシ煮干しや燻製ウルメを使う煮干し系として整理しています。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-parking"],
  },
  {
    slug: "raimi-ogata",
    name: "麺や来味",
    description: "淡麗から濃厚まで幅広いメニューを持つ東区の実力店。煮干し香る中華そばを軸に、比較記事でも扱いやすい店舗です。",
    area: "新潟市東区・大形",
    address: "新潟県新潟市東区大形本町5-6-6",
    phone: "025-272-4198",
    genre: "煮干し淡麗",
    tags: ["煮干し", "淡麗", "駐車場あり", "東区", "限定麺"],
    recommendedMenu: "中華そば",
    priceRange: "800円〜1,300円目安",
    parking: true,
    parkingNote: "新潟市ラーメンガイドでは駐車場26台と掲載。",
    businessHours: "11:00〜15:00、17:30〜21:00（材料なくなり次第終了）",
    closedDays: "月曜夜、火曜、ほか不定休",
    officialUrl: "https://niigatacity-ramen.jp/ramen/raimi/",
    mapUrl: map("麺や来味 新潟市東区大形本町5-6-6"),
    officialLinks: [
      { label: "新潟市ラーメンガイド", url: "https://niigatacity-ramen.jp/ramen/raimi/", type: "website" },
      { label: "地図", url: map("麺や来味 新潟市東区大形本町5-6-6"), type: "map" },
    ],
    editorComment: "限定麺やメニュー幅の情報を追う価値がある店舗。今後、季節限定・淡麗系まとめで個別記事化しやすいです。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("新潟市ラーメンガイド 麺や来味", "https://niigatacity-ramen.jp/ramen/raimi/", "official", "住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"),
      source("＆Komachi 麺や来味", "https://www.andkomachi.com/spot/gourmet/113037", "local-media", "営業時間、定休日、駐車場、店舗特徴の補助確認。"),
    ],
    faqs: [
      { question: "麺や来味はあっさり系ですか？", answer: "看板として中華そばが紹介され、煮干し香る淡麗系の入口として扱いやすい店舗です。一方でメニュー幅も広いです。" },
      { question: "駐車場はありますか？", answer: "新潟市ラーメンガイドでは26台と掲載されています。" },
    ],
    relatedRankingSlugs: ["niigata-assari-shoyu", "niigata-parking"],
  },
  {
    slug: "naoji-souhonten",
    name: "新潟拉麺なおじ 総本店",
    description: "肉そばや限定メニューなど、力強いラインアップを持つ総本店。公式サイトで店舗情報を追えるため更新運用しやすい店舗です。",
    area: "新潟市中央区・上所",
    address: "新潟県新潟市中央区上所上3丁目1-28",
    phone: "025-250-5501",
    genre: "肉そば・背脂",
    tags: ["公式サイトあり", "肉そば", "限定麺", "中央区", "駐車場あり"],
    recommendedMenu: "なおじろう / 肉そば系",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "公式・現地情報確認推奨。",
    businessHours: "公式サイト掲載の最新営業時間を確認",
    closedDays: "公式サイト掲載の最新情報を確認",
    officialUrl: "https://naoji.jp/shop/souhonten.html",
    mapUrl: map("新潟拉麺なおじ 総本店 新潟市中央区上所上3丁目1-28"),
    officialLinks: [
      { label: "公式サイト", url: "https://naoji.jp/shop/souhonten.html", type: "website" },
      { label: "地図", url: map("新潟拉麺なおじ 総本店 新潟市中央区上所上3丁目1-28"), type: "map" },
    ],
    editorComment: "公式サイトで店舗別ページがあるため、営業時間・限定麺の更新運用をしやすい店舗。ガッツリ系の導線にも使えます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("新潟拉麺なおじ 総本店 公式", "https://naoji.jp/shop/souhonten.html", "official", "住所、店舗概要、公式店舗ページ確認。営業時間は公式最新情報確認前提。"),
      source("なじらぼ 新潟ラーメン なおじ総本店", "https://www.najilabo.net/shop/shop.shtml?s=4387", "local-media", "店舗特徴と営業時間情報の補助確認。"),
    ],
    faqs: [
      { question: "なおじ総本店の営業時間は固定ですか？", answer: "公式サイトや店舗SNS等で変更される可能性があります。訪問前に最新情報の確認を推奨します。" },
      { question: "どんな読者に向いていますか？", answer: "肉そばやガッツリ系、限定麺を楽しみたい読者に向いています。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-parking"],
  },
  {
    slug: "menya-shinobu",
    name: "麺や忍",
    description: "駅南エリアで背脂しょうゆを探す時に候補に入れたい店舗。日祝は昼営業のみのため、訪問時間の確認が重要です。",
    area: "新潟市中央区・駅南",
    address: "新潟県新潟市中央区米山4-1-1 伏見ビル2 1F",
    phone: "025-246-5281",
    genre: "背脂しょうゆ",
    tags: ["背脂", "駅南", "太麺", "昼営業注意", "一人利用"],
    recommendedMenu: "背脂しょうゆ",
    priceRange: "800円〜1,200円目安",
    parking: false,
    parkingNote: "駅南エリアのため周辺駐車場確認推奨。",
    businessHours: "11:00〜14:00、18:00〜19:45（日曜・祝日は昼営業のみ、13:30までの掲載あり）",
    closedDays: "最新情報確認推奨",
    officialUrl: "https://niigata.mypl.net/article/ramen_niigata/7829",
    mapUrl: map("麺や忍 新潟市中央区米山4-1-1"),
    officialLinks: [
      { label: "まいぷれ 店舗紹介", url: "https://niigata.mypl.net/article/ramen_niigata/7829", type: "website" },
      { label: "地図", url: map("麺や忍 新潟市中央区米山4-1-1"), type: "map" },
    ],
    editorComment: "駅南で背脂系を扱える貴重な候補。営業時間の制約も情報価値になるため、店舗詳細で明記しています。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("まいぷれ 新潟市 麺や忍", "https://niigata.mypl.net/article/ramen_niigata/7829", "local-media", "営業時間、店舗特徴、背脂しょうゆの説明確認。"),
      source("新潟ラーメン.com 麺や忍", "https://noodles.bbshin.net/niigata/shinobu.html", "editorial", "背脂しょうゆ、営業時間の補助確認。"),
    ],
    faqs: [
      { question: "夜も営業していますか？", answer: "平日は夜営業の掲載がありますが、日曜・祝日は昼のみとされる情報があります。訪問前に確認してください。" },
      { question: "どんなラーメンですか？", answer: "燕三条系を思わせる背脂しょうゆと太麺の組み合わせとして整理しています。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential"],
  },
  {
    slug: "jikon-matsuzaki",
    name: "らーめん滋魂",
    description: "岩のり中華が看板の東区人気店。燕背脂の流れを感じる濃厚な一杯を、新潟市内で食べたい読者に向いています。",
    area: "新潟市東区・松崎",
    address: "新潟県新潟市東区松崎1-1-28",
    phone: "025-272-9260",
    genre: "燕背脂・岩のり中華",
    tags: ["背脂", "岩のり", "東区", "駐車場あり", "濃厚"],
    recommendedMenu: "岩のり中華",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "駐車場あり。台数・混雑状況は訪問前確認推奨。",
    businessHours: "11:00〜15:00、17:00〜21:00（LO掲載あり）",
    closedDays: "水曜ほか不定休",
    officialUrl: "https://niigata.mypl.net/article/ramen_niigata/80784",
    mapUrl: map("らーめん滋魂 新潟市東区松崎1-1-28"),
    officialLinks: [
      { label: "まいぷれ 店舗紹介", url: "https://niigata.mypl.net/article/ramen_niigata/80784", type: "website" },
      { label: "地図", url: map("らーめん滋魂 新潟市東区松崎1-1-28"), type: "map" },
    ],
    editorComment: "背脂ランキングの中で杭州飯店と比較しやすい新潟市側の候補。岩のりという個性があり、写真・レビュー記事化にも向きます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("まいぷれ 新潟市 らーめん滋魂", "https://niigata.mypl.net/article/ramen_niigata/80784", "local-media", "住所、電話、営業時間、定休日、看板メニュー確認。"),
      source("JAFナビ らーめん滋魂", "https://area.jaf.or.jp/area/2025/10/kanto/niigata/special-benefits/ramen-jikon20251023", "editorial", "岩のり中華と燕背脂系の説明補助。"),
    ],
    faqs: [
      { question: "滋魂の看板メニューは何ですか？", answer: "地域メディアでは岩のり中華が看板として紹介されています。" },
      { question: "背脂が苦手でも食べやすいですか？", answer: "背脂系のため好みは分かれます。岩のりや煮干し感とのバランスを楽しみたい人に向いています。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential", "niigata-parking"],
  },
  {
    slug: "komadori-maki",
    name: "ラーメン こまどり",
    description: "新潟濃厚味噌の代表格として知られる西蒲区の名店。巻エリアや岩室温泉方面の導線でも紹介しやすい店舗です。",
    area: "新潟市西蒲区・巻",
    address: "新潟県新潟市西蒲区竹野町2454-1",
    phone: "0256-72-2827",
    genre: "新潟濃厚味噌",
    tags: ["新潟5大ラーメン", "濃厚味噌", "西蒲区", "餃子", "車移動"],
    recommendedMenu: "味噌ラーメン",
    priceRange: "900円〜1,400円目安",
    parking: true,
    parkingNote: "車訪問向き。駐車場の最新状況は店舗情報確認推奨。",
    businessHours: "平日 11:00〜14:30 / 16:30〜20:00、土日 11:00〜15:00 / 16:30〜20:00目安",
    closedDays: "最新情報確認推奨",
    officialUrl: "https://menlife.jp/shop/396",
    mapUrl: map("ラーメン こまどり 新潟市西蒲区竹野町2454-1"),
    officialLinks: [
      { label: "MEN LIFE 店舗情報", url: "https://menlife.jp/shop/396", type: "website" },
      { label: "地図", url: map("ラーメン こまどり 新潟市西蒲区竹野町2454-1"), type: "map" },
    ],
    editorComment: "新潟濃厚味噌を語るうえで外しにくい店舗。東横と比較して、濃厚味噌のスタイル差を説明する記事へ展開できます。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("MEN LIFE ラーメン こまどり", "https://menlife.jp/shop/396", "editorial", "住所、営業時間、濃厚味噌の背景確認。"),
      source("新潟市ラーメンガイドブック", "https://www.city.niigata.lg.jp/kanko/kanko/oshirase/ramen.files/guidebook.pdf", "government", "新潟5大ラーメン文脈での掲載確認。"),
    ],
    faqs: [
      { question: "こまどりは新潟濃厚味噌の店ですか？", answer: "新潟濃厚味噌の代表格として扱われる店舗です。濃い味噌スープを楽しみたい読者に向いています。" },
      { question: "新潟市中心部から行きやすいですか？", answer: "中心部からは距離があるため、車移動や西蒲区・岩室方面の予定と合わせるのがおすすめです。" },
    ],
    relatedRankingSlugs: ["niigata-miso", "niigata-ramen-essential"],
  },
  {
    slug: "hangzhou-hanten",
    name: "杭州飯店",
    description: "燕背脂ラーメンの象徴的存在。極太麺、煮干し醤油、背脂、玉ねぎという燕三条らしさを体験したい読者向けです。",
    area: "燕市",
    address: "新潟県燕市燕49-4",
    phone: "0256-64-3770",
    genre: "燕背脂ラーメン",
    tags: ["新潟5大ラーメン", "燕背脂", "極太麺", "駐車場あり", "観光協会掲載"],
    recommendedMenu: "中華そば",
    priceRange: "900円〜1,500円目安",
    parking: true,
    parkingNote: "燕市観光協会の燕背脂ラーメンMAPでは駐車場有と掲載。",
    businessHours: "平日 11:00〜14:30 / 17:00〜20:00、土日祝 11:00〜18:30（売り切れ次第終了）",
    closedDays: "月曜（月2回 月火連休）",
    officialUrl: "https://ra-men.tsubame-kankou.jp/stores/entry-27.html",
    mapUrl: map("杭州飯店 燕市燕49-4"),
    officialLinks: [
      { label: "燕背脂ラーメンMAP", url: "https://ra-men.tsubame-kankou.jp/stores/entry-27.html", type: "website" },
      { label: "地図", url: map("杭州飯店 燕市燕49-4"), type: "map" },
    ],
    editorComment: "県内全域のラーメンガイドにするなら必須級。新潟市中心のページから県内ページへ広げる時の柱になります。",
    lastVerifiedAt: collectedAt,
    sources: [
      source("燕背脂ラーメンMAP 杭州飯店", "https://ra-men.tsubame-kankou.jp/stores/entry-27.html", "tourism", "住所、電話、営業時間、定休日、駐車場確認。"),
      source("燕背脂ラーメンMAP", "https://ra-men.tsubame-kankou.jp/", "tourism", "燕背脂ラーメンの地域情報確認。"),
    ],
    faqs: [
      { question: "杭州飯店は何系のラーメンですか？", answer: "燕背脂ラーメンを代表する店舗として整理しています。煮干し醤油、背脂、極太麺、玉ねぎが特徴です。" },
      { question: "売り切れ終了はありますか？", answer: "燕背脂ラーメンMAPでは売り切れ次第終了と掲載されています。遠方から訪問する場合は早めの時間がおすすめです。" },
    ],
    relatedRankingSlugs: ["niigata-ramen-essential"],
  },
];
