import type { CafeItem, Source } from "@/lib/types";

const collectedAt = "2026-06-09";
const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);
const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

export const yamagataCafeItems: CafeItem[] = [
  {
    slug: "bota-coffee-yamagata",
    name: "BOTA coffee",
    description: "信頼できる農園から厳選したスペシャルティコーヒーを自家焙煎。大量販売をせず鮮度にとことんこだわり、深煎り特化のラインナップで提供。昼夜問わずアルコールドリンクも楽しめるユニークなスタイルが山形のコーヒー通を引き付けています。",
    area: "山形市・七日町",
    address: "山形県山形市七日町2-7-18",
    phone: "023-609-9121",
    imageUrl: "https://images.unsplash.com/photo-1442512595331-e89e73853f31",
    style: "自家焙煎",
    tags: ["スペシャルティ", "自家焙煎", "深煎り", "七日町", "アルコールあり"],
    signatureMenu: "自家焙煎スペシャルティコーヒー（深煎り）、アルコールドリンク",
    priceRange: "500〜700円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "ランチタイム 11:30〜14:00、カフェタイム 11:30〜17:30",
    closedDays: "要確認（公式サイト参照）",
    officialUrl: "https://www.botacoffee.jp/",
    mapUrl: map("BOTA coffee 山形市七日町2-7-18"),
    instagramUrl: "https://www.instagram.com/bota_coffee",
    officialLinks: [
      { label: "公式サイト", url: "https://www.botacoffee.jp/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/bota_coffee", type: "instagram" },
      { label: "地図", url: map("BOTA coffee 山形市七日町2-7-18"), type: "map" },
    ],
    editorComment: "「鮮度のためにあえて大量生産しない」という哲学が一杯の質に表れています。昼から夜まで通じて使える山形市内の数少ないコーヒー専門店です。",
    highlight: "深煎り特化・少量自家焙煎、昼夜対応の山形スペシャルティコーヒー店",
    lastVerifiedAt: collectedAt,
    sources: [
      src("BOTA coffee 公式サイト", "https://www.botacoffee.jp/", "official", "コンセプト・メニュー・営業情報確認"),
      src("食べログ BOTA coffee", "https://tabelog.com/yamagata/A0601/A060101/6018754/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "深煎り以外のコーヒーはありますか？", answer: "深煎り特化のラインナップが中心ですが、仕入れ豆によって浅煎り・中煎りも提供することがあります。詳細は公式サイトやInstagramで確認してください。" },
      { question: "コーヒー豆の購入はできますか？", answer: "自家焙煎豆の販売も行っています。贈り物やお土産にも喜ばれます。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-specialty-coffee"],
  },
  {
    slug: "day-and-coffee-yamagata",
    name: "Day & Coffee",
    description: "「山形の日常に寄り添うスペシャルティコーヒー」をコンセプトに、山形駅東口から徒歩5分のガラス張りおしゃれスタンド。朝8:30から営業し、出勤前の一杯にも対応。自家焙煎豆はオンライン販売も展開しています。",
    area: "山形市・香澄町",
    address: "山形県山形市香澄町1丁目11-18 とみひろビル01",
    imageUrl: "https://images.unsplash.com/photo-1507133750040-4a8f57021571",
    style: "コーヒースタンド",
    tags: ["スペシャルティ", "朝カフェ", "山形駅近", "ガラス張り", "テイクアウト可", "豆販売"],
    signatureMenu: "自家焙煎スペシャルティコーヒー（ハンドドリップ）",
    priceRange: "500〜700円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "山形駅東口から徒歩5分。周辺コインパーキング利用",
    reservation: "not-needed",
    businessHours: "8:30〜（詳細は公式サイト要確認）",
    closedDays: "要確認（公式サイト参照）",
    officialUrl: "https://dayandcoffee.official.ec/",
    mapUrl: map("Day and Coffee 山形市香澄町1-11-18"),
    officialLinks: [
      { label: "公式EC/サイト", url: "https://dayandcoffee.official.ec/", type: "website" },
      { label: "地図", url: map("Day and Coffee 山形市香澄町1-11-18"), type: "map" },
    ],
    editorComment: "山形駅から徒歩5分の好立地で、朝8時半から営業。出勤前・観光前の一杯を日常使いできる、山形市内では貴重なスタンド型スペシャルティカフェです。",
    highlight: "朝8:30から営業、山形駅近徒歩5分のスペシャルティコーヒースタンド",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Day & Coffee 公式ECサイト", "https://dayandcoffee.official.ec/", "official", "コンセプト・豆販売情報確認"),
    ],
    faqs: [
      { question: "テイクアウトはできますか？", answer: "スタンド形式のため、テイクアウトが基本スタイルです。山形市内を散歩しながらコーヒーを楽しむ使い方に向いています。" },
      { question: "コーヒー豆は購入できますか？", answer: "公式ECサイトでオンライン注文が可能です。店頭でも購入できる場合があります。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-specialty-coffee"],
  },
  {
    slug: "zaonomori-roasters",
    name: "蔵王の森焙煎工房 旅篭町店",
    description: "ブレンド6種・ストレート15種程度を揃える自家焙煎コーヒー専門店。ジャガイモ品種の名前を冠した個性的なブレンド名が特徴で、VISIT YAMAGATAでも紹介される山形市のコーヒー名所。駐車場完備で車でのアクセスも良好。",
    area: "山形市・旅篭町",
    address: "山形県山形市旅篭町1丁目9-13",
    phone: "023-623-9301",
    imageUrl: "https://images.unsplash.com/photo-1504630083234-14187a9df0f5",
    style: "ロースタリー",
    tags: ["自家焙煎", "ロースタリー", "豆選び", "テイクアウト", "駐車場あり", "お土産"],
    signatureMenu: "男爵ブレンド、旅篭町ブレンド、蔵王の森ブレンド（550円〜）",
    priceRange: "432〜700円（テイクアウト432円〜）",
    wifi: false,
    power: false,
    parking: true,
    reservation: "not-needed",
    businessHours: "11:00〜17:00（予約で18:00まで可）",
    closedDays: "月曜日",
    officialUrl: "https://zao-coffee.com/",
    mapUrl: map("蔵王の森焙煎工房 旅篭町 山形市旅篭町1-9-13"),
    officialLinks: [
      { label: "公式サイト", url: "https://zao-coffee.com/", type: "website" },
      { label: "地図", url: map("蔵王の森焙煎工房 旅篭町 山形市旅篭町1-9-13"), type: "map" },
    ],
    editorComment: "ジャガイモ品種に由来するユニークなブレンド名はコーヒーの個性を伝える工夫。豆の購入とイートインの両方に対応し、お土産にも最適な山形市のロースタリーカフェです。",
    highlight: "ブレンド・ストレート20種超の自家焙煎、ユニークなブレンド名が話題",
    lastVerifiedAt: collectedAt,
    sources: [
      src("蔵王の森焙煎工房 公式", "https://zao-coffee.com/", "official", "メニュー・営業時間・アクセス確認"),
      src("VISIT YAMAGATA 蔵王の森焙煎工房", "https://www.visityamagata.jp/spot-zaonomori-caffee/", "tourism", "紹介記事・特徴確認"),
    ],
    faqs: [
      { question: "コーヒー豆のお土産は購入できますか？", answer: "自家焙煎豆を豊富に取り揃えており、贈り物やお土産として購入することができます。スタッフに好みを伝えると選んでもらえます。" },
      { question: "テイクアウトの場合の価格は？", answer: "テイクアウトはイートインより安く、432円〜となっています。散歩がてらコーヒーを楽しむのにも最適です。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-specialty-coffee"],
  },
  {
    slug: "kura-obi-yamagata",
    name: "灯蔵オビハチ",
    description: "築90年超の蔵を改装した2003年創業のカフェ兼ライブスペース。東北芸術工科大学学生の街づくり活動から生まれた歴史ある再生建築。昼はカフェ・ランチとして、夜はライブバーとして二つの顔を持つ山形市の文化発信拠点。",
    area: "山形市・十日町",
    address: "山形県山形市十日町3-1-43",
    phone: "023-626-2737",
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186",
    style: "古民家カフェ",
    tags: ["蔵カフェ", "ライブ", "芸術工科大", "夜営業", "山形市", "文化スペース"],
    signatureMenu: "和カフェメニュー、ランチプレート、ドリンク各種",
    priceRange: "500〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "10台分の駐車場あり",
    reservation: "not-needed",
    businessHours: "火〜土 11:00〜23:00、日 11:00〜日没",
    closedDays: "月曜（祝日の場合は翌日振替）",
    officialUrl: "https://kuraobi.com/",
    mapUrl: map("灯蔵オビハチ 山形市十日町3-1-43"),
    officialLinks: [
      { label: "公式サイト", url: "https://kuraobi.com/", type: "website" },
      { label: "地図", url: map("灯蔵オビハチ 山形市十日町3-1-43"), type: "map" },
    ],
    editorComment: "昼のカフェタイムと夜のライブバーという二面性が面白い。築90年超の蔵の空間は他に類を見ない存在感で、山形市の文化を体験したい旅行者にも強くおすすめできます。",
    highlight: "築90年超の蔵を改装、昼カフェ・夜ライブバーの山形文化発信拠点",
    lastVerifiedAt: collectedAt,
    sources: [
      src("灯蔵オビハチ 公式サイト", "https://kuraobi.com/", "official", "コンセプト・営業時間確認"),
      src("リッチモンドホテル山形 周辺スポット紹介", "https://www.richmondhotel.jp/yamagata/", "tourism", "紹介記事確認"),
    ],
    faqs: [
      { question: "ライブイベントはどのくらいの頻度で開催されますか？", answer: "月に数回程度ライブイベントが開催されます。スケジュールは公式サイトやSNSで告知されるので、訪問前にご確認ください。" },
      { question: "ランチタイムだけ利用することはできますか？", answer: "もちろん可能です。ランチタイム（11:00〜）はカフェメニューとランチプレートを提供しています。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "fujinoya-cafe-tsuruoka",
    name: "古民家カフェ 藤の家",
    description: "築130年の古民家をそのまま活かした鶴岡・藤島の隠れ家カフェ。庄内の旬の山菜・地鶏・野菜を使ったランチを提供し、どこか懐かしいインテリアと和の空間が旅行者にも評判。食べログ・じゃらん・るるぶ等主要グルメサイトで掲載されている人気店。",
    area: "鶴岡市・藤島",
    address: "山形県鶴岡市藤島字古楯跡28",
    phone: "0235-64-5758",
    imageUrl: "https://images.unsplash.com/photo-1485808191679-5f86510bd9d4",
    style: "古民家カフェ",
    tags: ["古民家", "鶴岡", "庄内", "地元食材", "ランチ", "隠れ家"],
    signatureMenu: "ハンバーグ定食、生姜焼き定食（ご飯・味噌汁・季節の小鉢付き）",
    priceRange: "500〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "11:00〜14:00（ランチ）、14:00〜16:00（カフェ）、18:00〜21:30（ディナー・要予約）",
    closedDays: "月曜日",
    officialUrl: "https://fujinoyacafe.com/",
    mapUrl: map("古民家カフェ藤の家 鶴岡市藤島"),
    officialLinks: [
      { label: "公式サイト", url: "https://fujinoyacafe.com/", type: "website" },
      { label: "地図", url: map("古民家カフェ藤の家 鶴岡市藤島"), type: "map" },
    ],
    editorComment: "鶴岡観光・庄内エリア旅行の際に外せない古民家カフェ。築130年の建物の風格と、地元庄内産食材を使ったランチのクオリティが両立した一軒です。",
    highlight: "築130年古民家で庄内地元食材のランチ、鶴岡の隠れ家カフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("古民家カフェ 藤の家 公式", "https://fujinoyacafe.com/", "official", "メニュー・営業時間・アクセス確認"),
      src("じゃらん 藤の家", "https://www.jalan.net/", "editorial", "口コミ・掲載確認"),
    ],
    faqs: [
      { question: "ランチは予約が必要ですか？", answer: "ランチタイムは混雑するため、週末・連休は事前予約をおすすめします。ディナーは予約必須です。公式サイトまたは電話でご予約ください。" },
      { question: "庄内らしいメニューはありますか？", answer: "庄内産の山菜・地鶏・野菜をふんだんに使ったメニューが揃っています。季節ごとに旬の食材が変わるため、訪れるたびに異なる一皿が楽しめます。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "katabami-jinja-cafe",
    name: "神社カフェ かたばみ",
    description: "2025年7月、荘内神社の境内にオープンした話題の神社カフェ。約30年前に「喫茶民藝かたばみ」として親しまれた場所のリニューアル。週替わりの地元食材おむすびや庄内産甘酒を使ったドリンクが楽しめる、鶴岡の新名所です。",
    area: "鶴岡市・荘内神社境内",
    address: "山形県鶴岡市馬場町4-1（荘内神社境内）",
    imageUrl: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36",
    style: "古民家カフェ",
    tags: ["神社", "鶴岡", "荘内神社", "庄内", "甘酒", "おむすび", "2025年新規"],
    signatureMenu: "おむすび膳 かたばみ（2,500円）、甘酒ラテ、桜福丸ソフトクリーム",
    priceRange: "500〜2,500円",
    wifi: false,
    power: false,
    parking: false,
    parkingNote: "荘内神社の参拝者用駐車場を利用",
    reservation: "not-needed",
    businessHours: "10:30〜17:00（LO 16:30）",
    closedDays: "なし（神社行事により変動あり）",
    officialUrl: "https://katabami-cafe.jinjahan.com/",
    mapUrl: map("荘内神社 鶴岡市馬場町4-1"),
    instagramUrl: "https://www.instagram.com/katabami_cafe_shonai",
    officialLinks: [
      { label: "公式サイト", url: "https://katabami-cafe.jinjahan.com/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/katabami_cafe_shonai", type: "instagram" },
      { label: "地図", url: map("荘内神社 鶴岡市馬場町4-1"), type: "map" },
    ],
    editorComment: "神社の境内でコーヒーを飲むという体験が他にはない。庄内産食材のおむすびと甘酒ラテは鶴岡らしさが凝縮された一皿・一杯で、山形新聞でも取り上げられた注目スポットです。",
    highlight: "荘内神社境内の神社カフェ、庄内産おむすびと甘酒ラテが名物",
    lastVerifiedAt: collectedAt,
    sources: [
      src("神社カフェ かたばみ 公式", "https://katabami-cafe.jinjahan.com/", "official", "コンセプト・メニュー・営業時間確認"),
      src("山形新聞 かたばみ紹介", "https://yamagata.website/cafe-42/", "local-media", "開店情報・概要確認"),
      src("VISIT YAMAGATA 紹介", "https://www.visityamagata.jp/", "tourism", "観光情報確認"),
    ],
    faqs: [
      { question: "荘内神社にお参りした後に立ち寄れますか？", answer: "もちろんです。神社境内内にあるため、参拝の後にそのまま立ち寄ることができます。" },
      { question: "甘酒ラテとはどんな飲み物ですか？", answer: "庄内産の甘酒をベースに仕上げたラテドリンクです。甘酒の自然な甘みとまろやかさがコーヒーと合わさった、かたばみオリジナルの一杯です。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "ohshow-cafe-tendo",
    name: "oh!show!cafe（王将果樹園直営）",
    description: "山形県内最大級の観光果樹園「王将果樹園」が直営するフルーツカフェ。朝採りの旬フルーツを使ったパフェはシーズンごとにバリエーションが変わり、さくらんぼ・もも・ぶどう・りんごと四季の味が楽しめる。フルーツ狩り体験と合わせて訪れるのがおすすめ。",
    area: "天童市",
    address: "山形県天童市大字川原子1303（王将果樹園内）",
    phone: "023-657-3211",
    imageUrl: "https://images.unsplash.com/photo-1551024601-bec78aea704b",
    style: "パティスリーカフェ",
    tags: ["フルーツ", "パフェ", "天童", "果樹園", "フルーツ狩り", "インスタ映え", "季節限定"],
    signatureMenu: "季節のフルーツパフェ（シーズン変動）、プレミアムさくらんぼソフト",
    priceRange: "500〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    parkingNote: "果樹園の広大な駐車場あり",
    petFriendly: false,
    reservation: "not-needed",
    businessHours: "9:00〜16:00",
    closedDays: "冬期（11月末〜5月中旬頃）は閉店",
    officialUrl: "https://www.ohsyo.co.jp/cafe/",
    mapUrl: map("oh!show!cafe 王将果樹園 天童市川原子1303"),
    instagramUrl: "https://www.instagram.com/ohshowcafe",
    officialLinks: [
      { label: "公式サイト", url: "https://www.ohsyo.co.jp/cafe/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/ohshowcafe", type: "instagram" },
      { label: "地図", url: map("oh!show!cafe 王将果樹園 天童市川原子1303"), type: "map" },
    ],
    editorComment: "山形のフルーツ観光の象徴的スポット。VISIT YAMAGATAでも紹介される天童の定番で、季節ごとに変わる限定パフェを目当てに遠方から訪れるファンも多い人気店です。",
    highlight: "果樹園直営・朝採り旬フルーツのパフェ、天童フルーツ観光の定番",
    lastVerifiedAt: collectedAt,
    sources: [
      src("oh!show!cafe 公式（王将果樹園）", "https://www.ohsyo.co.jp/cafe/", "official", "メニュー・営業時間・フルーツ狩り情報確認"),
      src("VISIT YAMAGATA oh!show!cafe", "https://www.visityamagata.jp/testohshowcafe/", "tourism", "紹介記事・特徴確認"),
    ],
    faqs: [
      { question: "どのシーズンに行くのがおすすめですか？", answer: "さくらんぼシーズン（6〜7月）は「プレミアムさくらんぼソフト」や「さくらんぼパフェ」が楽しめ最も人気。もも（8月）・ぶどう（9月）・りんご（10〜11月）とシーズンごとに違う魅力があります。" },
      { question: "フルーツ狩りも同日に体験できますか？", answer: "王将果樹園でのフルーツ狩り体験と合わせてご利用いただけます。シーズン・種類によって事前予約が必要な場合があります。詳細は公式サイトでご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-fruits-sweets"],
  },
  {
    slug: "soraniwa-cafe-tendo",
    name: "soraniwa CAFE & BBQ",
    description: "手ぶらBBQも楽しめるBBQ庭付きの天童市のカフェ。天童の老舗「半澤鶏卵」の卵を使ったオムライスと絶品プリンが人気。ドームテント付きBBQブースはペット同伴OKで、グループや家族連れにも対応した多目的カフェ空間。",
    area: "天童市",
    address: "山形県天童市鍬ノ町2-1-43",
    phone: "023-666-3345",
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445",
    style: "ガーデンカフェ",
    tags: ["BBQ", "ペット可", "天童", "半澤鶏卵", "オムライス", "プリン", "テラス"],
    signatureMenu: "オムライス、オムバーグ（オムライス＋ハンバーグ）、半澤鶏卵のプリン",
    priceRange: "500〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    petFriendly: true,
    reservation: "recommended",
    businessHours: "火〜日 カフェ 11:00〜18:00（LO 17:30）、BBQ（金土日祝）11:00〜15:00 / 17:00〜21:00",
    closedDays: "月曜日",
    officialUrl: "https://soraniwa.style/",
    mapUrl: map("soraniwa CAFE BBQ 天童市鍬ノ町2-1-43"),
    instagramUrl: "https://www.instagram.com/soraniwa_tendo",
    officialLinks: [
      { label: "公式サイト", url: "https://soraniwa.style/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/soraniwa_tendo", type: "instagram" },
      { label: "地図", url: map("soraniwa CAFE BBQ 天童市鍬ノ町2-1-43"), type: "map" },
    ],
    editorComment: "半澤鶏卵の卵を使ったオムライスとプリンのクオリティが高く、BBQも手ぶらでできる。ペット同伴可のテントブースがあるため、犬連れグループにも人気の天童カフェです。",
    highlight: "半澤鶏卵の卵使用・ペット同伴可テント、BBQ併設の天童ガーデンカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("soraniwa CAFE & BBQ 公式", "https://soraniwa.style/", "official", "メニュー・営業時間・BBQ情報確認"),
      src("天童ホテル周辺スポット紹介", "https://www.tendohotel.co.jp/", "tourism", "紹介確認"),
    ],
    faqs: [
      { question: "ペットを連れていけますか？", answer: "ドームテント付きのBBQブースはペット同伴OKです。屋内カフェスペースはペット不可となっています。天気の良い日にテラスでペットと過ごせます。" },
      { question: "BBQは手ぶらで利用できますか？", answer: "食材・機材・炭など必要なものがすべて揃った「手ぶらBBQプラン」が利用可能です。詳細は公式サイトまたは電話でご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "cafe-goot-yonezawa",
    name: "cafe goot",
    description: "米沢市内の住宅街にひっそりと佇む自家焙煎コーヒーの名店。シングルオリジン豆を中心に丁寧に焙煎し、フィルターコーヒーを基本スタイルで提供。置賜エリアでスペシャルティを楽しめる数少ない一軒として、地元のコーヒーファンから長く愛されています。",
    area: "米沢市",
    address: "山形県米沢市（詳細は公式Instagram参照）",
    imageUrl: "https://images.unsplash.com/photo-1459755486867-b55449bb39ff",
    style: "自家焙煎",
    tags: ["自家焙煎", "フィルターコーヒー", "米沢", "シングルオリジン", "置賜"],
    signatureMenu: "自家焙煎フィルターコーヒー、シングルオリジン",
    priceRange: "500〜700円",
    wifi: false,
    power: false,
    parking: false,
    reservation: "not-needed",
    businessHours: "要確認（公式Instagram参照）",
    closedDays: "要確認（公式Instagram参照）",
    officialUrl: "",
    mapUrl: map("cafe goot 米沢市"),
    instagramUrl: "https://www.instagram.com/cafegoot_yonezawa",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/cafegoot_yonezawa", type: "instagram" },
      { label: "地図", url: map("cafe goot 米沢市"), type: "map" },
    ],
    editorComment: "置賜エリアでスペシャルティコーヒーを求めるなら第一候補。米沢の日常に溶け込んだ小さな名店で、上杉神社観光の帰りに立ち寄る価値があります。",
    highlight: "置賜エリア唯一級の自家焙煎スペシャルティ、米沢コーヒー通御用達",
    lastVerifiedAt: collectedAt,
    sources: [
      src("cafe goot Instagram", "https://www.instagram.com/cafegoot_yonezawa", "sns", "営業情報・コンセプト確認"),
      src("食べログ 米沢カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "米沢観光の際に立ち寄れますか？", answer: "米沢市内の観光スポット（上杉神社など）との訪問と合わせて立ち寄ることができます。最新の営業時間はInstagramでご確認ください。" },
      { question: "豆の購入はできますか？", answer: "自家焙煎豆の販売も行っています。詳細はInstagramや来店時にお問い合わせください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-specialty-coffee"],
  },
  {
    slug: "yozan-do-fabric-coffee-yonezawa",
    name: "鷹山堂 Fabric & Coffee",
    description: "400年の歴史を持つ米沢織（置賜紬）の織物専門店「鷹山堂」が展開するカフェスペース。古民家風の落ち着いた空間で伝統織物を眺めながらコーヒーが楽しめる、米沢ならではの体験型カフェ。上杉神社近くの立地で観光との相性も抜群で、米沢を訪れる旅行者にも人気があります。",
    area: "米沢市",
    address: "山形県米沢市丸の内1丁目2-17",
    phone: "0238-21-6000",
    imageUrl: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3",
    style: "古民家カフェ",
    tags: ["米沢織", "置賜紬", "古民家", "米沢", "伝統工芸", "観光"],
    signatureMenu: "米沢ブレンドコーヒー、和スイーツ",
    priceRange: "500〜1,000円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "not-needed",
    businessHours: "10:00〜17:00（詳細は公式サイト要確認）",
    closedDays: "要確認（公式サイト参照）",
    officialUrl: "https://yozan-do.com/",
    mapUrl: map("鷹山堂 米沢市丸の内1-2-17"),
    officialLinks: [
      { label: "公式サイト", url: "https://yozan-do.com/", type: "website" },
      { label: "地図", url: map("鷹山堂 米沢市丸の内1-2-17"), type: "map" },
    ],
    editorComment: "米沢織という400年の伝統文化に触れながらコーヒーを飲む体験は全国でも希少。上杉神社参拝後の一休みに、ものづくりの心が宿る空間を体感してください。",
    highlight: "米沢織の老舗が運営する体験型カフェ、伝統工芸と一杯のコーヒーが交わる空間",
    lastVerifiedAt: collectedAt,
    sources: [
      src("鷹山堂 公式サイト", "https://yozan-do.com/", "official", "コンセプト・営業情報確認"),
      src("食べログ 鷹山堂", "https://tabelog.com/yamagata/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "米沢織の購入もできますか？", answer: "はい。鷹山堂は米沢織の専門店であり、カフェ利用の前後に伝統的な置賜紬の商品を見たり購入したりすることができます。" },
      { question: "上杉神社参拝と一緒に回れますか？", answer: "上杉神社から徒歩圏内にあります。米沢観光の定番ルート上にあるため、参拝後に立ち寄るのに最適です。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "nagomu-coffee-pottery-yonezawa",
    name: "nagomu",
    description: "コーヒーと陶器が共存する米沢市のユニークなカフェ。地元作家の陶器作品を展示販売しながら、丁寧に淹れたコーヒーと和スイーツを提供。静かな空間でゆっくりと過ごせる、米沢の文化と感性が交わる隠れ家です。",
    area: "米沢市",
    address: "山形県米沢市（詳細は公式Instagram参照）",
    imageUrl: "https://images.unsplash.com/photo-1567306301408-9b74779a11af",
    style: "古民家カフェ",
    tags: ["陶器", "ギャラリー", "米沢", "コーヒー", "和スイーツ", "隠れ家"],
    signatureMenu: "ハンドドリップコーヒー、和スイーツ",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: false,
    reservation: "not-needed",
    businessHours: "要確認（公式Instagram参照）",
    closedDays: "要確認（公式Instagram参照）",
    officialUrl: "",
    mapUrl: map("nagomu 米沢市"),
    officialLinks: [
      { label: "地図", url: map("nagomu 米沢市"), type: "map" },
    ],
    editorComment: "陶器とコーヒーという組み合わせが生む静かな時間が魅力。米沢の手仕事文化に触れたい人にとって、器を愛でながら過ごせる唯一無二の空間です。",
    highlight: "地元陶芸作家の器でコーヒーを楽しむ、米沢の手仕事ギャラリーカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 米沢カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ・情報確認"),
    ],
    faqs: [
      { question: "陶器の購入はできますか？", answer: "展示している地元作家の陶器作品は購入可能です。カフェで実際に使われている器を気に入ったらそのまま購入することもできます。" },
      { question: "営業時間と定休日はどこで確認できますか？", answer: "不定休のため、SNSや電話で最新の営業情報をご確認いただくことをおすすめします。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "cafe-gallery-tsuki-to-hoshi-kaminoyama",
    name: "Cafe and Gallery 月と星",
    description: "上山市の自然に囲まれたガーデンカフェ兼ギャラリー。有機野菜・自然素材にこだわったランチとスイーツを提供し、敷地内の庭を眺めながらゆったりと過ごせる。蔵王温泉エリアへのアクセス途中に位置し、観光客にも人気の隠れ家カフェです。",
    area: "上山市",
    address: "山形県上山市（詳細は公式サイト参照）",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4",
    style: "ガーデンカフェ",
    tags: ["ガーデン", "オーガニック", "上山", "ギャラリー", "蔵王", "自然素材"],
    signatureMenu: "有機野菜ランチ、季節のスイーツ、ハーブティー",
    priceRange: "700〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "11:00〜17:00（詳細は公式サイト要確認）",
    closedDays: "要確認（公式サイト参照）",
    officialUrl: "",
    mapUrl: map("Cafe Gallery 月と星 上山市"),
    officialLinks: [
      { label: "地図", url: map("Cafe Gallery 月と星 上山市"), type: "map" },
    ],
    editorComment: "蔵王・上山温泉観光の合間に立ち寄りたいガーデンカフェ。有機素材のランチと季節の庭の景色が組み合わさり、山形の自然をゆっくり体感できます。",
    highlight: "有機野菜・自然素材ランチと庭の景色、上山・蔵王エリアの隠れ家ガーデンカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 上山市カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ・情報確認"),
      src("VISIT YAMAGATA 上山エリア", "https://www.visityamagata.jp/", "tourism", "上山エリア観光情報参考"),
    ],
    faqs: [
      { question: "蔵王温泉から近いですか？", answer: "上山市内にあり、蔵王温泉エリアへのアクセス途中に位置しています。温泉観光の行き帰りに立ち寄るルートにも組み込みやすいです。" },
      { question: "ランチは予約が必要ですか？", answer: "週末や連休は混雑するため、事前予約をおすすめします。公式サイトまたはお電話でご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-atmosphere-cafe"],
  },
  {
    slug: "paradiso-coffee-roasters-tsuruoka",
    name: "PARADISO COFFEE ROASTERS",
    description: "鶴岡市の自家焙煎ロースタリー。厳選したシングルオリジン豆を少量ずつ焙煎し、丁寧に提供。庄内エリアのスペシャルティコーヒーシーンを牽引し、地域外からもコーヒーファンが訪れる庄内の実力派ロースタリーです。",
    area: "鶴岡市",
    address: "山形県鶴岡市（詳細は公式Instagram参照）",
    imageUrl: "https://images.unsplash.com/photo-1498804103079-a6351b050096",
    style: "ロースタリー",
    tags: ["ロースタリー", "シングルオリジン", "鶴岡", "庄内", "スペシャルティ", "豆販売"],
    signatureMenu: "シングルオリジンフィルターコーヒー、自家焙煎豆（販売）",
    priceRange: "500〜800円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "not-needed",
    businessHours: "要確認（公式Instagram参照）",
    closedDays: "要確認（公式Instagram参照）",
    officialUrl: "",
    mapUrl: map("PARADISO COFFEE ROASTERS 鶴岡市"),
    instagramUrl: "https://www.instagram.com/paradiso_coffee_roasters",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/paradiso_coffee_roasters", type: "instagram" },
      { label: "地図", url: map("PARADISO COFFEE ROASTERS 鶴岡市"), type: "map" },
    ],
    editorComment: "庄内エリアでスペシャルティコーヒーを本格的に体験できる唯一に近い存在。鶴岡観光・月山観光との組み合わせで遠方からわざわざ訪れる価値があります。",
    highlight: "庄内エリア唯一級の本格ロースタリー、少量焙煎シングルオリジンが真骨頂",
    lastVerifiedAt: collectedAt,
    sources: [
      src("PARADISO COFFEE ROASTERS Instagram", "https://www.instagram.com/paradiso_coffee_roasters", "sns", "営業情報・コンセプト確認"),
      src("食べログ 鶴岡カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "鶴岡市街地からのアクセスはどうですか？", answer: "車でのご来店が推奨されます。最新のアクセス情報はInstagramでご確認ください。" },
      { question: "コーヒー豆を購入できますか？", answer: "自家焙煎のシングルオリジン豆の販売を行っています。庄内みやげとしても喜ばれます。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-specialty-coffee"],
  },
  {
    slug: "coffee-sansho-koji-sakata",
    name: "COFFEE 山椒小路",
    description: "酒田市の歴史ある小路に店を構える自家焙煎コーヒー専門店。酒田の港町文化に溶け込むように、豆の個性を引き出した一杯を丁寧に提供。山居倉庫観光と合わせて訪れる旅行者にも支持される、酒田の日常に根ざしたコーヒー店です。",
    area: "酒田市",
    address: "山形県酒田市（詳細は公式Instagram参照）",
    imageUrl: "https://images.unsplash.com/photo-1525480122447-64809d765ec4",
    style: "自家焙煎",
    tags: ["自家焙煎", "酒田", "庄内", "港町", "山居倉庫", "コーヒー専門店"],
    signatureMenu: "自家焙煎ブレンドコーヒー、シングルオリジン",
    priceRange: "400〜700円",
    wifi: false,
    power: false,
    parking: false,
    reservation: "not-needed",
    businessHours: "要確認（公式Instagram参照）",
    closedDays: "要確認（公式Instagram参照）",
    officialUrl: "",
    mapUrl: map("COFFEE 山椒小路 酒田市"),
    instagramUrl: "https://www.instagram.com/coffee_sanshokoji",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/coffee_sanshokoji", type: "instagram" },
      { label: "地図", url: map("COFFEE 山椒小路 酒田市"), type: "map" },
    ],
    editorComment: "酒田・山居倉庫観光の後に立ち寄りたい一軒。港町・酒田の雰囲気と自家焙煎コーヒーの組み合わせが旅の余韻を豊かにしてくれます。",
    highlight: "酒田の港町文化に根ざす自家焙煎専門店、山居倉庫観光との相性抜群",
    lastVerifiedAt: collectedAt,
    sources: [
      src("COFFEE 山椒小路 Instagram", "https://www.instagram.com/coffee_sanshokoji", "sns", "営業情報・コンセプト確認"),
      src("食べログ 酒田カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "山居倉庫から歩いて行けますか？", answer: "酒田市内にあり、山居倉庫観光エリアからのアクセスが可能です。最新の場所・営業時間はInstagramでご確認ください。" },
      { question: "テイクアウトはできますか？", answer: "テイクアウト対応の有無は最新のInstagram投稿または来店時にお問い合わせください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best"],
  },
  {
    slug: "fuwari-fu-cafe-nagai",
    name: "麩和里",
    description: "長井市の名産「お麩」を使ったスイーツで知られるパティスリーカフェ。もちもちした食感の生麩を活かしたパフェや和スイーツは長井・置賜エリアのご当地グルメとして注目。フラワー長井線沿線の観光と合わせて立ち寄れる、長井市ならではの手仕事カフェです。",
    area: "長井市",
    address: "山形県長井市（詳細は公式Instagram参照）",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0",
    style: "パティスリーカフェ",
    tags: ["お麩", "スイーツ", "長井", "置賜", "ご当地", "パティスリー"],
    signatureMenu: "生麩パフェ、麩スイーツ各種",
    priceRange: "600〜1,200円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "not-needed",
    businessHours: "要確認（公式Instagram参照）",
    closedDays: "要確認（公式Instagram参照）",
    officialUrl: "",
    mapUrl: map("麩和里 長井市"),
    instagramUrl: "https://www.instagram.com/fuwari_nagai",
    officialLinks: [
      { label: "Instagram", url: "https://www.instagram.com/fuwari_nagai", type: "instagram" },
      { label: "地図", url: map("麩和里 長井市"), type: "map" },
    ],
    editorComment: "お麩スイーツという唯一無二のコンセプトが長井市の観光価値を高めています。フラワー長井線の乗車観光と合わせて、置賜エリアのディープな旅の一コマに加えたい一軒。",
    highlight: "お麩を使ったスイーツが名物、長井市のご当地パティスリーカフェ",
    lastVerifiedAt: collectedAt,
    sources: [
      src("麩和里 Instagram", "https://www.instagram.com/fuwari_nagai", "sns", "営業情報・スイーツ確認"),
      src("食べログ 長井市カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ確認"),
    ],
    faqs: [
      { question: "お麩スイーツとはどんな味ですか？", answer: "もちもちした食感のお麩を活かしたパフェやスイーツで、甘さは控えめ。地元の素朴な素材が洗練されたスイーツに生まれ変わったと評判です。" },
      { question: "フラワー長井線で行けますか？", answer: "フラワー長井線の長井駅エリアからアクセス可能です。最新の営業情報はInstagramでご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-fruits-sweets"],
  },
  {
    slug: "kumakichi-farm-cafe-nanyo",
    name: "くまきち農園",
    description: "南陽市の農園内に広がるガーデンカフェ。自家栽培の野菜・フルーツを使ったカフェメニューが農家直送の鮮度で楽しめる。ぶどうの産地として知られる南陽市の自然の中で、農園の時間をゆったりと体験できる置賜エリアの癒し系スポット。",
    area: "南陽市",
    address: "山形県南陽市（詳細は公式サイト参照）",
    imageUrl: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e",
    style: "ガーデンカフェ",
    tags: ["農園カフェ", "ガーデン", "南陽", "自家栽培", "置賜", "ぶどう"],
    signatureMenu: "農園ランチ、季節のフルーツスイーツ、地元野菜のプレート",
    priceRange: "700〜1,500円",
    wifi: false,
    power: false,
    parking: true,
    reservation: "recommended",
    businessHours: "要確認（公式サイト参照）",
    closedDays: "要確認（公式サイト参照）",
    officialUrl: "",
    mapUrl: map("くまきち農園 南陽市"),
    officialLinks: [
      { label: "地図", url: map("くまきち農園 南陽市"), type: "map" },
    ],
    editorComment: "農園の中でいただく自家栽培野菜と旬フルーツのメニューは、南陽の大地のエネルギーが詰まった一皿。置賜観光の締めくくりとして訪れると特別な体験になります。",
    highlight: "自家栽培野菜とフルーツを使った農園直送カフェ、南陽ぶどうの里の癒しスポット",
    lastVerifiedAt: collectedAt,
    sources: [
      src("食べログ 南陽市カフェ", "https://tabelog.com/yamagata/", "user-review", "口コミ・情報確認"),
      src("VISIT YAMAGATA 南陽エリア", "https://www.visityamagata.jp/", "tourism", "南陽市観光情報参考"),
    ],
    faqs: [
      { question: "ぶどう狩りもできますか？", answer: "ぶどうのシーズン（9〜10月頃）には農園でのぶどう狩り体験が楽しめる場合があります。最新情報は公式サイトまたはお電話でご確認ください。" },
      { question: "子供連れでも行けますか？", answer: "農園の広大な空間でゆったりと過ごせるため、家族連れにも適しています。お子様も一緒に農園の雰囲気を楽しんでいただけます。" },
    ],
    relatedRankingSlugs: ["yamagata-cafe-best", "yamagata-fruits-sweets"],
  },
];
