import type { CafeRegion } from "@/lib/types";

export const cafeRegions: CafeRegion[] = [
  {
    slug: "niigata",
    name: "新潟県",
    shortName: "新潟",
    description: "日本海の恵みと米どころ文化が育んだ新潟のカフェシーン。古町・万代エリアのスペシャルティコーヒー専門店から、古民家を改装したこだわりカフェまで多彩。",
    tagline: "港町・米どころが生んだ、静かに深いコーヒー文化",
    seoTitle: "新潟県のカフェおすすめランキング｜スペシャルティコーヒー・古民家カフェ",
    seoDescription: "新潟県のおすすめカフェを厳選紹介。古町・万代・長岡エリアのスペシャルティコーヒー専門店、自家焙煎カフェ、古民家カフェを口コミ・こだわり・アクセスで比較。",
    seoKeywords: ["新潟 カフェ", "新潟 コーヒー", "新潟市 カフェ", "古町 カフェ", "万代 カフェ", "新潟 スペシャルティコーヒー", "新潟 自家焙煎", "新潟 古民家カフェ"],
    status: "live",
    headline: "新潟のカフェを、\nこだわりとエリアで選ぶ。",
    subtext: "スペシャルティコーヒーから古民家カフェ、地元素材のスイーツまで。新潟ならではの一杯と空間を案内します。",
    heroBadge: "新潟県 カフェガイド",
    heroCtaSlug: "niigata-cafe-best",
    heroCtaLabel: "おすすめランキングを見る",
    statsNote: "編集部調査 2026年6月時点",
    areas: ["新潟市中央区・古町", "新潟市中央区・万代", "新潟市西区", "長岡市", "上越市", "湯沢エリア"],
    featuredSlugs: ["chamonix-niigata", "harumachi-coffee", "mizuya-yuzawa"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93", alt: "新潟のカフェ" },
      { key: "region", url: "https://images.unsplash.com/photo-1554118811-1e0d58224f24", alt: "コーヒーショップ内観" },
    ],
  },
  {
    slug: "yamagata",
    name: "山形県",
    shortName: "山形",
    description: "フルーツ王国として知られる山形は、地元産フルーツを使ったスイーツカフェが充実。山形市中心部のロースタリーから、蔵王や鶴岡の山里カフェまで個性豊か。",
    tagline: "フルーツと自然の恵みで彩る、山形カフェ紀行",
    seoTitle: "山形県のカフェおすすめランキング｜自家焙煎・フルーツカフェ",
    seoDescription: "山形県のおすすめカフェを厳選紹介。山形市・天童・鶴岡エリアの自家焙煎カフェ、フルーツスイーツカフェ、古民家カフェをこだわり・アクセスで比較。",
    seoKeywords: ["山形 カフェ", "山形市 カフェ", "山形 コーヒー", "天童 カフェ", "鶴岡 カフェ", "山形 自家焙煎", "山形 フルーツカフェ", "蔵王 カフェ"],
    status: "live",
    headline: "山形のカフェを、\n地元の恵みと一緒に。",
    subtext: "フルーツ王国山形の旬の素材を使ったスイーツ、自家焙煎の一杯。山形らしいカフェ体験を案内します。",
    heroBadge: "山形県 カフェガイド",
    heroCtaSlug: "yamagata-cafe-best",
    heroCtaLabel: "おすすめランキングを見る",
    statsNote: "編集部調査 2026年6月時点",
    areas: ["山形市", "天童市", "鶴岡市", "米沢市", "蔵王エリア", "上山エリア"],
    featuredSlugs: ["bota-coffee-yamagata", "katabami-jinja-cafe", "ohshow-cafe-tendo"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735", alt: "山形のカフェ" },
      { key: "region", url: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085", alt: "コーヒーラテアート" },
    ],
  },
  {
    slug: "toyama",
    name: "富山県",
    shortName: "富山",
    description: "立山連峰と富山湾に挟まれた富山は、世界遺産の合掌造りから黒部峡谷まで絶景の宝庫。スペシャルティコーヒー専門店から古民家カフェ、高岡の歴史ある街並みのロースタリーまで個性豊か。",
    tagline: "山と海と世界遺産に囲まれた、富山のカフェ旅",
    seoTitle: "富山県のカフェおすすめランキング｜スペシャルティコーヒー・古民家カフェ・合掌造り",
    seoDescription: "富山県のおすすめカフェを厳選紹介。富山市・高岡・黒部・砺波エリアのスペシャルティコーヒー専門店、自家焙煎カフェ、世界遺産五箇山の合掌造りカフェをこだわり・アクセスで比較。",
    seoKeywords: ["富山 カフェ", "富山市 カフェ", "富山 コーヒー", "高岡 カフェ", "黒部 カフェ", "富山 スペシャルティコーヒー", "五箇山 カフェ", "立山 カフェ"],
    status: "live",
    headline: "富山のカフェを、\n山と海と世界遺産とともに。",
    subtext: "立山連峰の伏流水で淹れるコーヒー、世界遺産の合掌造りで飲む一杯。富山ならではのカフェ体験を案内します。",
    heroBadge: "富山県 カフェガイド",
    heroCtaSlug: "toyama-cafe-best",
    heroCtaLabel: "おすすめランキングを見る",
    statsNote: "編集部調査 2026年6月時点",
    areas: ["富山市中央区", "高岡市・金屋町", "黒部・宇奈月", "砺波エリア", "五箇山・南砺", "射水・氷見"],
    featuredSlugs: ["amber-coffee-toyama", "gassho-cafe-nanto", "seikoan-coffee-takaoka"],
    images: [
      { key: "hero", url: "https://images.unsplash.com/photo-1509785307050-d4066910ec1e", alt: "富山のカフェ" },
      { key: "region", url: "https://images.unsplash.com/photo-1544145945-f90425340c7e", alt: "自家焙煎コーヒー" },
    ],
  },
];
