  'chamonix-niigata', 'cafe', 'niigata',
  '珈琲工房 シャモニー 古町店', '1970年代創業の老舗自家焙煎純喫茶。毎朝店内で豆を焙煎し、一杯ずつサイフォンで丁寧に淹れる。ブレンド5種・ストレート7種・エスプレッソ6種・水出し4種と豊富なラインナップを誇り、昭和の喫茶文化を今に伝える古町の名所です。', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb',
  '新潟県新潟市中央区古町通五番町591（古町モール5・2F）', '新潟市中央区・古町', '025-228-7189',
  '400〜700円', 'https://chamonix-niigata.com/', 'https://maps.google.com/?q=%E7%8F%88%E7%90%B2%E5%B7%A5%E6%88%BF%E3%82%B7%E3%83%A3%E3%83%A2%E3%83%8B%E3%83%BC%E5%8F%A4%E7%94%BA%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A%E4%BA%94%E7%95%AA%E7%94%BA591',
  ARRAY['老舗', '古町', 'サイフォン', '純喫茶', '自家焙煎', 'モーニング']::text[], '2026-06-09', '古町観光のついでに寄れる老舗中の老舗。サイフォン式の丁寧な一杯を、昭和喫茶の空気とともに味わう体験は唯一無二です。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"シャモニーブレンド珈琲、Bセット（コーヒー＋ハーフピザトースト＋サラダ）","highlight":"毎朝店内焙煎・サイフォン式、50年以上愛される古町の純喫茶","business_hours":"8:00〜19:00","closed_days":"年中無休","official_links":[{"label":"公式サイト","url":"https://chamonix-niigata.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E7%8F%88%E7%90%B2%E5%B7%A5%E6%88%BF%E3%82%B7%E3%83%A3%E3%83%A2%E3%83%8B%E3%83%BC%E5%8F%A4%E7%94%BA%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A%E4%BA%94%E7%95%AA%E7%94%BA591","type":"map"}],"sources":[{"title":"シャモニー 公式サイト","url":"https://chamonix-niigata.com/","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・メニュー・焙煎スタイル確認"},{"title":"食べログ 珈琲工房シャモニー","url":"https://tabelog.com/niigata/A1501/A150102/15001134/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ・評点確認"}],"faqs":[{"question":"シャモニーのコーヒーはどんな特徴ですか？","answer":"毎朝自家焙煎した豆をサイフォンで一杯ずつ丁寧に淹れます。ブレンド5種・ストレート7種など豊富なラインナップから好みの一杯を選べます。"},{"question":"古町モールからのアクセスは？","answer":"古町通五番町591、古町モール5の2Fにあります。古町アーケードを歩きながら立ち寄れる好立地です。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'harumachi-coffee', 'cafe', 'niigata',
  'HARUMACHI coffee', '地域工務店「ノモトホームズ」が直営するカフェ。木の香り・庭の緑・暖炉の音が五感を包む空間で、地元新潟のロースターが厳選した豆を一杯ずつハンドドリップで提供。素材にこだわった手作りスイーツと、HARUMACHIプリンが人気です。', 'https://images.unsplash.com/photo-1445116572489-8890e5d91968',
  '新潟県新潟市中央区鳥屋野南3-8-24', '新潟市中央区・鳥屋野', '025-278-8667',
  '600〜900円', 'https://www.harumachi-coffee.com/', 'https://maps.google.com/?q=HARUMACHI%20coffee%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E9%B3%A5%E5%B1%8B%E9%87%8E%E5%8D%973-8-24',
  ARRAY['木造り', '手作りスイーツ', 'プリン', 'フルーツパフェ', 'ハンドドリップ', '暖炉']::text[], '2026-06-09', '車で行ける広い駐車場と、木の温もりに包まれた空間が魅力。週替わりのスイーツと季節のパフェは早めに売り切れることも多いので午前中の来店がおすすめです。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":true,"parking_note":"住宅展示場併設の広い駐車場あり","reservation":"recommended","signature_menu":"HARUMACHIプリン、旬のフルーツパフェ、ハンドドリップコーヒー","highlight":"工務店直営・自然素材の空間で味わう手作りプリンとフルーツパフェ","business_hours":"平日 10:00〜16:00（LO 15:30）、土日祝 10:00〜17:00（LO 16:30）","closed_days":"木曜日","official_links":[{"label":"公式サイト","url":"https://www.harumachi-coffee.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=HARUMACHI%20coffee%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E9%B3%A5%E5%B1%8B%E9%87%8E%E5%8D%973-8-24","type":"map"}],"sources":[{"title":"HARUMACHI coffee 公式サイト","url":"https://www.harumachi-coffee.com/","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・メニュー・アクセス確認"},{"title":"新潟おでかけメディア025 HARUMACHI coffee紹介","url":"https://025niigata.jp/","sourceType":"local-media","collectedAt":"2026-06-09","note":"口コミ・雰囲気確認"}],"faqs":[{"question":"HARUMACHIプリンはいつでも食べられますか？","answer":"数量限定のため、人気時期（週末・連休）は午前中に売り切れる場合があります。早めの来店または公式SNSで在庫状況を確認することをおすすめします。"},{"question":"子連れでも利用できますか？","answer":"駐車場が広く、木のぬくもりある空間で比較的ゆっくりできます。ただし小さいお子様連れの場合は席の混雑状況に応じてご利用ください。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'innovative-co-niigata', 'cafe', 'niigata',
  'innovative Co.', '古町エリアのスペシャルティコーヒー専門店。まず豆の種類を選び、次に抽出方法（ハンドドリップ／カフェラテ／エスプレッソ／アメリカーノ）を選ぶというユニークな注文スタイルが特徴。コーヒーを深く楽しみたい人向けの一杯を提供します。', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
  '新潟県新潟市中央区西堀通4-259-58 西堀青藍館1F', '新潟市中央区・古町', NULL,
  '500〜700円', '#', 'https://maps.google.com/?q=innovative%20Co.%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E5%A0%80%E9%80%9A4-259-58',
  ARRAY['スペシャルティ', '豆選び', '古町', 'ハンドドリップ', 'エスプレッソ']::text[], '2026-06-09', '「豆の種類を選んでから抽出方法を決める」という体験型の注文スタイルが新鮮。コーヒーの個性と抽出の違いを学びながら飲める、古町の穴場的スペシャルティカフェです。',
  '{"style":"スペシャルティコーヒー","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"豆×抽出方法を選ぶスペシャルティコーヒー（ハンドドリップ・カフェラテ等）","highlight":"豆×抽出方法を自分で選ぶ体験型スペシャルティコーヒー専門店","business_hours":"10:00〜17:00","closed_days":"不定休（Instagram要確認）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=innovative%20Co.%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E5%A0%80%E9%80%9A4-259-58","type":"map"}],"sources":[{"title":"食べログ innovative Co.","url":"https://tabelog.com/niigata/A1501/A150102/15013600/","sourceType":"user-review","collectedAt":"2026-06-09","note":"店舗情報・口コミ確認"}],"faqs":[{"question":"コーヒーに詳しくなくても楽しめますか？","answer":"スタッフが豆の特徴や抽出方法の違いを丁寧に説明してくれるので、コーヒー初心者でも安心して楽しめます。"},{"question":"営業日の確認方法は？","answer":"不定休のため、訪問前に公式SNSや電話で確認することをおすすめします。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'shibui-matsushiro', 'cafe', 'niigata',
  'カールベンクス古民家カフェ『澁い -SHIBUI-』', 'ドイツ人建築家カール・ベンクス氏が手がけた築100年超の古民家再生カフェ。豪雪地帯・越後妻有の雪国文化と、モダンな空間デザインが融合。大地の芸術祭エリアにあり、アート観光と組み合わせて訪れる旅行者にも人気の一軒です。', 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735',
  '新潟県十日町市松代2074-1', '十日町市・松代', '025-594-7944',
  '600〜1,800円', 'https://karl-bengs.jp/shibui/', 'https://maps.google.com/?q=%E6%BE%81%E3%81%84%20SHIBUI%20%E5%8D%81%E6%97%A5%E7%94%BA%E5%B8%82%E6%9D%BE%E4%BB%A32074-1',
  ARRAY['古民家', '大地の芸術祭', '越後妻有', '雪国', 'カールベンクス', 'ランチ']::text[], '2026-06-09', '大地の芸術祭エリアの中でも特に印象に残るカフェ。梁を生かしたダイナミックな空間と、地元食材のランチのクオリティが高く、遠方からわざわざ訪れる価値があります。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"季節の地元食材を使ったランチプレート、コーヒー","highlight":"ドイツ人建築家が再生した築100年超の古民家、大地の芸術祭エリア","business_hours":"11:00〜16:00（ランチLO 15:00、ドリンクLO 15:30）","closed_days":"月〜水（木金土日祝営業）","official_links":[{"label":"公式サイト","url":"https://karl-bengs.jp/shibui/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%BE%81%E3%81%84%20SHIBUI%20%E5%8D%81%E6%97%A5%E7%94%BA%E5%B8%82%E6%9D%BE%E4%BB%A32074-1","type":"map"}],"sources":[{"title":"カールベンクス澁い -SHIBUI- 公式","url":"https://karl-bengs.jp/shibui/","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・アクセス・コンセプト確認"},{"title":"大地の芸術祭公式サイト","url":"https://www.echigo-tsumari.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"エリア情報確認"}],"faqs":[{"question":"大地の芸術祭の会期外でも営業していますか？","answer":"芸術祭の会期外でも営業しています。ただし貸切や特別イベントで臨時休業となる場合があるため、事前に公式サイトで確認してください。"},{"question":"アクセス方法は？","answer":"まつだい駅（ほくほく線）から徒歩圏内です。車の場合は専用駐車場があります。積雪期は道路状況を事前に確認してください。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'mizuya-yuzawa', 'cafe', 'niigata',
  '温泉珈琲 水屋', '越後湯沢駅すぐの旅館HATAGO井仙1Fにある、温泉水を使ったカフェ。神立地方で湧く「飲める温泉水」で仕立てた水出し温泉珈琲が名物。魚沼産コシヒカリの米粉ロールケーキ「湯澤るうろ」も絶品で、スキーや温泉旅行のついでに立ち寄れます。', 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff',
  '新潟県南魚沼郡湯沢町湯沢2455-1（HATAGO井仙1F）', '南魚沼郡・越後湯沢', '025-784-3361',
  '600〜900円', 'https://www.hatago-isen.jp/mizuya/', 'https://maps.google.com/?q=%E6%B0%B4%E5%B1%8B%20%E8%B6%8A%E5%BE%8C%E6%B9%AF%E6%B2%A2%20HATAGO%E4%BA%95%E4%BB%99',
  ARRAY['温泉珈琲', '越後湯沢', '足湯', '米粉', 'スキーリゾート', 'お土産']::text[], '2026-06-09', 'スキー・温泉旅行のついでに越後湯沢駅近で立ち寄れる好立地。入り口の足湯でひと休みしながら飲む温泉珈琲は、旅の特別な記憶になります。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"parking_note":"越後湯沢駅から徒歩2分。旅館駐車場利用（宿泊客以外は確認要）","reservation":"not-needed","signature_menu":"温泉珈琲、湯澤るうろ（米粉ロールケーキ）、温泉プリン","highlight":"「飲める温泉水」で仕立てた水出し珈琲、越後湯沢駅徒歩2分","business_hours":"9:00〜18:00（LO 17:30）","closed_days":"無休","official_links":[{"label":"公式サイト（HATAGO井仙）","url":"https://www.hatago-isen.jp/mizuya/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%B0%B4%E5%B1%8B%20%E8%B6%8A%E5%BE%8C%E6%B9%AF%E6%B2%A2%20HATAGO%E4%BA%95%E4%BB%99","type":"map"}],"sources":[{"title":"HATAGO井仙 水屋 食べログ","url":"https://tabelog.com/niigata/A1504/A150404/15001180/","sourceType":"user-review","collectedAt":"2026-06-09","note":"営業時間・メニュー・口コミ確認"},{"title":"越後湯沢観光協会","url":"https://www.e-yuzawa.gr.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"エリア情報確認"}],"faqs":[{"question":"温泉珈琲とは何ですか？","answer":"越後湯沢・神立地方で湧く飲用可能な温泉水を使って淹れたコーヒーです。温泉水ならではのまろやかな風味が特徴で、水屋のオリジナルメニューです。"},{"question":"足湯は誰でも利用できますか？","answer":"水屋の入り口付近に足湯があり、カフェ利用者も楽しめます。冬季は特に旅の疲れを癒すのにおすすめです。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'pepe-nagaoka', 'cafe', 'niigata',
  'COFFEE & SNACK PePe', 'レンガ造りの外観が印象的な長岡の老舗純喫茶。昭和の雰囲気を残す店内で、まかないから生まれた名物のピザ風ナポリタンが常連客に長く愛されている。長岡駅から徒歩5分というアクセスの良さも魅力。', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
  '新潟県長岡市東坂之上町2-2-9', '長岡市', NULL,
  '400〜1,000円', '#', 'https://maps.google.com/?q=COFFEE%20SNACK%20PePe%20%E9%95%B7%E5%B2%A1%E5%B8%82%E6%9D%B1%E5%9D%82%E4%B9%8B%E4%B8%8A%E7%94%BA2-2-9',
  ARRAY['老舗', '純喫茶', '長岡', 'レトロ', 'ナポリタン', '夜営業']::text[], '2026-06-09', '「Things新潟」でも紹介された長岡の純喫茶名所。昭和レトロな外観と内装はノスタルジーを感じさせ、夜22時まで営業しているため長岡観光後の一杯にも最適です。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ピザ風ナポリタン、アイスコーヒー","highlight":"レンガ造りが印象的、まかない発祥のナポリタンが名物の長岡老舗純喫茶","business_hours":"9:00〜22:00","closed_days":"毎週水曜日","official_links":[{"label":"地図","url":"https://maps.google.com/?q=COFFEE%20SNACK%20PePe%20%E9%95%B7%E5%B2%A1%E5%B8%82%E6%9D%B1%E5%9D%82%E4%B9%8B%E4%B8%8A%E7%94%BA2-2-9","type":"map"}],"sources":[{"title":"Things新潟 PePe紹介記事","url":"https://things-niigata.jp/other/pepe/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗情報・名物メニュー確認"},{"title":"食べログ PePe 長岡","url":"https://tabelog.com/niigata/A1502/A150201/15003059/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ・評点確認"}],"faqs":[{"question":"ピザ風ナポリタンとはどんな料理ですか？","answer":"まかない料理として生まれたPePeオリジナルのナポリタンです。チーズやトマトソースが乗ったボリューム感のある一皿で、長年通う常連客に愛されています。"},{"question":"夜も営業していますか？","answer":"22時まで営業しています（水曜定休）。長岡市内での夕食後や観光の締めに立ち寄れる数少ない純喫茶です。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'west-cafe-nagaoka', 'cafe', 'niigata',
  'WEST CAFE 長岡店', 'アウトドアライフストア「WEST」の長岡店内に併設されたカフェ。山形・長岡のコーヒー豆専門店「山倉」のオリジナルブレンド豆を使用し、アウトドアの雰囲気の中でこだわりの一杯を楽しめる。週替わりのフードメニューも人気。', 'https://images.unsplash.com/photo-1470337458703-46ad1756a187',
  '新潟県長岡市花園南1丁目71（アウトドアショップWEST内）', '長岡市', NULL,
  '500〜800円', 'https://www.west-shop.co.jp/info/store/nagaokacafe', 'https://maps.google.com/?q=WEST%20CAFE%20%E9%95%B7%E5%B2%A1%20%E8%8A%B1%E5%9C%92%E5%8D%971%E4%B8%81%E7%9B%AE71',
  ARRAY['アウトドア', '長岡', 'スペシャルティ', 'テイクアウト可', 'セレクトショップ']::text[], '2026-06-09', 'アウトドアショップ内というユニークな立地ながら、コーヒーの質は本格派。駐車場が広いため車でのアクセスもしやすく、アウトドア用品を見ながらのコーヒータイムが楽しい。',
  '{"style":"コーヒースタンド","wifi":false,"power":false,"parking":true,"parking_note":"WEST駐車場あり","reservation":"not-needed","signature_menu":"山倉オリジナルブレンドコーヒー、ラテ","highlight":"アウトドアショップ直営、山倉ブレンド豆の本格コーヒーを長岡市で","business_hours":"平日 11:30〜18:00（LO 17:00）、土日祝 10:30〜18:00（LO 17:00）","closed_days":"毎週火曜日","official_links":[{"label":"公式サイト","url":"https://www.west-shop.co.jp/info/store/nagaokacafe","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/westcafenagaoka","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=WEST%20CAFE%20%E9%95%B7%E5%B2%A1%20%E8%8A%B1%E5%9C%92%E5%8D%971%E4%B8%81%E7%9B%AE71","type":"map"}],"instagram_url":"https://www.instagram.com/westcafenagaoka","sources":[{"title":"WEST CAFE 長岡店 公式","url":"https://www.west-shop.co.jp/info/store/nagaokacafe","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・メニュー確認"},{"title":"長岡カフェ2025年完全ガイド","url":"https://mise-repo.com/","sourceType":"local-media","collectedAt":"2026-06-09","note":"口コミ・評判確認"}],"faqs":[{"question":"アウトドア用品を見るだけでも入店できますか？","answer":"WEST長岡店はアウトドア用品店で、カフェは店内にあります。商品を見ながらコーヒーを楽しんでいただけます。"},{"question":"コーヒー豆の購入はできますか？","answer":"使用している山倉のオリジナルブレンド豆は購入可能な場合があります。詳細は店頭でご確認ください。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'book-cafe-antenna', 'cafe', 'niigata',
  'ブックカフェ アンテナ', '絵本と古書が所狭しと並ぶ新潟市内のブックカフェ。豊富な本を自由に読みながらコーヒーやスパイシーなチキンマサラカレーを楽しめる。WiFi・コンセント完備で長居しやすく、本好きのローカルファンに愛される穴場的存在。', 'https://images.unsplash.com/photo-1534040385115-33dcb3acba5b',
  '新潟県新潟市中央区幸町13-7 幸ビル103', '新潟市中央区・上所', NULL,
  '600〜1,100円', '#', 'https://maps.google.com/?q=%E3%83%96%E3%83%83%E3%82%AF%E3%82%AB%E3%83%95%E3%82%A7%E3%82%A2%E3%83%B3%E3%83%86%E3%83%8A%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%B9%B8%E7%94%BA13-7',
  ARRAY['ブックカフェ', '古書', '絵本', 'WiFi', '電源', 'カレー']::text[], '2026-06-09', '現金のみの営業ですが、WiFi・電源完備で長時間の滞在にも向いています。古書・絵本の蔵書は独特の選書センスがあり、読書好きには特別な空間です。',
  '{"style":"ブックカフェ","wifi":true,"power":true,"parking":true,"reservation":"not-needed","signature_menu":"チキンマサラカレー（1,100円）、コーヒー","highlight":"絵本・古書に囲まれた穴場的ブックカフェ、WiFi・電源完備","business_hours":"変動あり（公式Instagram要確認）","closed_days":"不定休（公式Instagram要確認）","official_links":[{"label":"Instagram","url":"https://www.instagram.com/book_cafe_antenna","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=%E3%83%96%E3%83%83%E3%82%AF%E3%82%AB%E3%83%95%E3%82%A7%E3%82%A2%E3%83%B3%E3%83%86%E3%83%8A%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%B9%B8%E7%94%BA13-7","type":"map"}],"instagram_url":"https://www.instagram.com/book_cafe_antenna","sources":[{"title":"ブックカフェ アンテナ Instagram","url":"https://www.instagram.com/book_cafe_antenna","sourceType":"sns","collectedAt":"2026-06-09","note":"営業情報・雰囲気確認"}],"faqs":[{"question":"本は購入できますか？","answer":"古書・絵本の一部は購入可能な場合があります。気に入った本があればスタッフにお声がけください。"},{"question":"支払い方法は？","answer":"現金のみの対応となっています。事前にご準備ください。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'awayuki-coffee-joetsu', 'cafe', 'niigata',
  '淡雪coffee', '新潟県上越市の住宅街に静かに佇むスペシャルティコーヒー専門店。世界各地の生産者から厳選した豆を常時6種以上取り揃え、浅煎りから深煎りまでその日の気分で選べる。バスクチーズケーキなど店内手作りの焼き菓子との組み合わせが人気で、全10席のコンパクトな空間がくつろぎを生み出す。上越エリアのコーヒー文化を牽引する実力派スペシャルティカフェ。', 'https://images.unsplash.com/photo-1511920170033-f8396924c348',
  '新潟県上越市滝寺（番地要確認）', '上越市', NULL,
  '600〜900円', 'https://awayuki.coffee/', 'https://maps.google.com/?q=%E6%B7%A1%E9%9B%AAcoffee%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E6%BB%9D%E5%AF%BA',
  ARRAY['スペシャルティコーヒー', '上越市', 'ハンドドリップ', '焼き菓子', 'バスクチーズケーキ', 'コーヒースタンド']::text[], '2026-06-09', '東京・福岡の一流ロースターが焙煎した高品質豆を手の届く価格で提供。上越エリアでコーヒーの聖地として定着しつつある一軒。',
  '{"style":"スペシャルティコーヒー","wifi":false,"power":false,"parking":true,"parking_note":"敷地内2台、徒歩2分に4台","reservation":"not-needed","signature_menu":"ハンドドリップコーヒー（常時6種以上から選択）、バスクチーズケーキ","highlight":"スペシャルティコーヒー常時6種以上、上越住宅街に静かに輝くコーヒー専門店","business_hours":"平日 11:00〜17:00、土日祝 11:00〜18:00","closed_days":"水・木曜","official_links":[{"label":"公式サイト","url":"https://awayuki.coffee/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%B7%A1%E9%9B%AAcoffee%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E6%BB%9D%E5%AF%BA","type":"map"}],"sources":[{"title":"淡雪coffee 公式サイト","url":"https://awayuki.coffee/","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・メニュー確認"},{"title":"タウン情報にいがた 淡雪coffee紹介","url":"https://tjniigata.jp/gourmet/202406cafeawayuki/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗紹介記事確認"}],"faqs":[{"question":"どのようなコーヒーが飲めますか？","answer":"浅煎りから深煎りまで常時6種以上のスペシャルティコーヒーを取り揃え、ハンドドリップやエスプレッソなど幅広いスタイルで楽しめます。"},{"question":"駐車場はありますか？","answer":"敷地内に2台、徒歩約2分の場所に4台の駐車スペースがあります。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'sekai-no-tonari-joetsu', 'cafe', 'niigata',
  '世界ノトナリ', '日本最古級の映画館「高田世界館」の隣に位置する、築90年の町家をリノベーションしたカフェ。アンティーク家具で統一されたレトロな空間は上越・高田の歴史的な街並みと調和する。地元焙煎所の新鮮な豆をハンドドリップで丁寧に淹れたコーヒーと、手作りハムが薫るサンドイッチが看板メニュー。歴史ある高田の街歩きの休憩スポットとして地元に愛される。', 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
  '新潟県上越市本町6-4-19', '上越市・高田', '025-512-4982',
  '500〜800円', '#', 'https://maps.google.com/?q=%E4%B8%96%E7%95%8C%E3%83%8E%E3%83%88%E3%83%8A%E3%83%AA%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E6%9C%AC%E7%94%BA6-4-19',
  ARRAY['古民家カフェ', '上越市', '高田', '町家リノベ', 'レトロ', 'ハンドドリップ', '観光']::text[], '2026-06-09', '国の登録有形文化財「高田世界館」の隣という立地は唯一無二。地域の歴史的資産を活かしたカフェとして、高田観光の際に必ず立ち寄りたい一軒。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ハンドドリップコーヒー、手作りハムのサンドイッチ","highlight":"日本最古級映画館の隣・築90年の町家カフェ、上越・高田の歴史と溶け込む","business_hours":"10:00〜17:00","closed_days":"月・火曜","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%96%E7%95%8C%E3%83%8E%E3%83%88%E3%83%8A%E3%83%AA%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E6%9C%AC%E7%94%BA6-4-19","type":"map"}],"sources":[{"title":"上越妙高タウン情報 世界ノトナリ紹介","url":"https://joetsu.yukiguni.town/gourmet/230598/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗紹介記事確認"},{"title":"ヒトサラ 世界ノトナリ","url":"https://hitosara.com/0031367893/","sourceType":"editorial","collectedAt":"2026-06-09","note":"店舗詳細確認"}],"faqs":[{"question":"高田世界館とはどんな建物ですか？","answer":"日本最古級の映画館のひとつで、国の登録有形文化財にも指定されています。世界ノトナリはその隣の築90年の建物をリノベーションして開かれたカフェです。"},{"question":"徒歩圏内に観光スポットはありますか？","answer":"高田城跡公園や高田の雁木通りなどが徒歩圏内にあり、カフェを起点とした街歩きを楽しめます。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cafe-hayashi-joetsu', 'cafe', 'niigata',
  'CAFE HAYASHI', '上越市三和区の田園地帯に佇む、国の登録有形文化財「林富永邸」を活用した古民家カフェ。「文化財カフェ・発酵スイーツカフェ」をコンセプトに、塩麹・味噌・醤油麹などを使ったメニューを提供。NHK「ふるカフェ系 ハルさんの休日」にも登場した注目店で、週末限定の開店が一層の希少価値を生む。', 'https://images.unsplash.com/photo-1513694203232-719a280e022f',
  '新潟県上越市三和区神田2245-24', '上越市・三和区', '025-532-2602',
  '800〜1,500円', 'https://cafe-hayashi.com/', 'https://maps.google.com/?q=CAFE%20HAYASHI%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E4%B8%89%E5%92%8C%E5%8C%BA%E7%A5%9E%E7%94%B02245-24',
  ARRAY['古民家カフェ', '上越市', '文化財', '発酵', 'スイーツ', '塩麹', '週末限定', 'NHK']::text[], '2026-06-09', 'NHKのカフェ番組に取り上げられた実績が示すとおり、建築・食・発酵文化が三位一体となった唯一無二の体験ができる。上越の農村エリアに足を伸ばす価値がある。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"塩麹鶏ハムプレート、けんさん焼き（クルミ味噌）、発酵スイーツセット","highlight":"国登録有形文化財の農家でNHK取材済み・週末限定の発酵スイーツカフェ","business_hours":"金・土・日・祝のみ営業","closed_days":"月〜木曜（要事前確認）","official_links":[{"label":"公式サイト","url":"https://cafe-hayashi.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=CAFE%20HAYASHI%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E4%B8%89%E5%92%8C%E5%8C%BA%E7%A5%9E%E7%94%B02245-24","type":"map"}],"sources":[{"title":"CAFE HAYASHI 公式サイト","url":"https://cafe-hayashi.com/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・メニュー確認"},{"title":"新潟観光ナビ CAFE HAYASHI紹介","url":"https://niigata-kankou.or.jp/blog/815","sourceType":"tourism","collectedAt":"2026-06-09","note":"店舗紹介記事確認"}],"faqs":[{"question":"予約は必要ですか？","answer":"週末・祝日限定の営業のため、確実に訪問したい場合は電話（025-532-2602）での事前予約が推奨です。"},{"question":"発酵メニューとはどんな料理ですか？","answer":"塩麹を使った鶏ハムや、クルミ味噌のけんさん焼き、レモンと麹のドレッシングなど、発酵食材をふんだんに使ったメニューが揃います。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'rucchi-coffee-roaster-myoko', 'cafe', 'niigata',
  'Rucchi Coffee Roaster', '妙高市の新井駅前に2025年オープンした自家焙煎コーヒー専門店。店内に焙煎機を備え常時5種類の豆を取り揃えており、訪問者が試飲しながら好みの豆を選べる体験型スタイルが特徴。駅前という好立地で妙高・上越エリアを訪れるコーヒー愛好家の間で急速に注目が集まっている。', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e',
  '新潟県妙高市朝日町1-1-1（新井駅前）', '妙高市', NULL,
  '400〜700円', '#', 'https://maps.google.com/?q=Rucchi%20Coffee%20Roaster%20%E5%A6%99%E9%AB%98%E5%B8%82%E6%9C%9D%E6%97%A5%E7%94%BA1-1-1',
  ARRAY['ロースタリー', '妙高市', '自家焙煎', '試飲体験', '駅前', 'コーヒー豆販売', '2025年新店']::text[], '2026-06-09', '2025年オープンの新鋭ながら、駅前という抜群の立地と試飲体験できるスタイルで急速に支持を集めている。妙高への旅の出発点として訪れたい一軒。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":true,"parking_note":"5台あり","reservation":"not-needed","signature_menu":"5種の自家焙煎コーヒー豆から選ぶドリップコーヒー（試飲あり）","highlight":"妙高・新井駅前の自家焙煎ロースタリー、5種の豆を試飲しながら選べる体験型","business_hours":"10:00〜18:00（変動あり、要確認）","closed_days":"日曜","official_links":[{"label":"地図","url":"https://maps.google.com/?q=Rucchi%20Coffee%20Roaster%20%E5%A6%99%E9%AB%98%E5%B8%82%E6%9C%9D%E6%97%A5%E7%94%BA1-1-1","type":"map"}],"sources":[{"title":"上越妙高タウン情報 Rucchi紹介","url":"https://joetsu.yukiguni.town/gourmet/311813/","sourceType":"local-media","collectedAt":"2026-06-09","note":"オープン情報・店舗詳細確認"},{"title":"web cocola Rucchi Coffee Roaster","url":"https://cocola.jp/rucchicoffeeroaster/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗詳細確認"}],"faqs":[{"question":"コーヒー豆のお土産購入はできますか？","answer":"はい、店内で焙煎したコーヒー豆をお土産としてご購入いただけます。5種類以上の豆から選べます。"},{"question":"JR新井駅からのアクセスは？","answer":"JR信越本線・新井駅の駅前に位置しており、電車でのアクセスも便利です。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'tsubame-coffee-tsubame', 'cafe', 'niigata',
  'ツバメコーヒー', '燕市吉田駅から徒歩圏内に位置する、壁一面に本が並ぶ書斎のような自家焙煎カフェ。ヘアサロンや無人書店を併設したユニークな複合施設として、燕三条エリアのカフェシーンをリードする存在。ものづくりの街・燕市らしく一杯ずつ丁寧に淹れたコーヒーと焼き菓子が人気。中川政七商店のメディアでも紹介されたローカル名店。', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570',
  '新潟県燕市吉田2760-1', '燕市・吉田', '0256-77-8781',
  '500〜900円', 'https://tsubamecoffee.com/', 'https://maps.google.com/?q=%E3%83%84%E3%83%90%E3%83%A1%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E7%87%95%E5%B8%82%E5%90%89%E7%94%B02760-1',
  ARRAY['自家焙煎', '燕三条', 'ブックカフェ', '焼き菓子', '燕市', 'ものづくり', '複合施設']::text[], '2026-06-09', '中川政七商店の読みものにも紹介された、燕三条を代表するカフェ。ものづくりの街・燕市らしく、コーヒーの一杯にも職人気質が感じられる。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ツバメブレンド（500円）、スコーン・焼き菓子、クロックムッシュ","highlight":"壁一面の本に囲まれた書斎風自家焙煎カフェ、燕三条のものづくり精神が宿る名店","business_hours":"11:00〜17:00","closed_days":"月・火・水曜","official_links":[{"label":"公式サイト","url":"https://tsubamecoffee.com/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/tsubamecoffee/","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=%E3%83%84%E3%83%90%E3%83%A1%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E7%87%95%E5%B8%82%E5%90%89%E7%94%B02760-1","type":"map"}],"instagram_url":"https://www.instagram.com/tsubamecoffee/","sources":[{"title":"ツバメコーヒー 公式サイト","url":"https://tsubamecoffee.com/","sourceType":"official","collectedAt":"2026-06-09","note":"営業時間・メニュー確認"},{"title":"中川政七商店の読みもの ツバメコーヒー紹介","url":"https://story.nakagawa-masashichi.jp/6240","sourceType":"editorial","collectedAt":"2026-06-09","note":"店舗紹介記事確認"}],"faqs":[{"question":"本や雑貨の購入もできますか？","answer":"同施設に無人書店が併設されており、本の購入が可能です。ヘアサロンも入居しています。"},{"question":"燕三条駅からのアクセスは？","answer":"JR吉田駅から徒歩圏内にあります。車での来店も便利です。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'mother-cafe-tsubame', 'cafe', 'niigata',
  'Mother', '2024年春にオープンした、燕市吉田の2階に広がる観葉植物カフェ。緑あふれる店内は海外のボタニカルインテリアを彷彿とさせ、オーガニック食品も販売するセレクトショップを兼ねる。自家製プリンやコーヒーとともに植物に囲まれたゆったりとした時間を過ごせると、オープン直後から地元の若い女性を中心に支持を集めている。', 'https://images.unsplash.com/photo-1490750967868-88df5691cc4e',
  '新潟県燕市吉田幸町6-12 2F', '燕市・吉田', NULL,
  '600〜1,000円', 'https://www.mayrow.jp/en/mother', 'https://maps.google.com/?q=Mother%20cafe%20%E7%87%95%E5%B8%82%E5%90%89%E7%94%B0%E5%B9%B8%E7%94%BA6-12',
  ARRAY['植物カフェ', 'オーガニック', '燕市', '2024年新店', 'ボタニカル', '観葉植物', 'インスタ映え']::text[], '2026-06-09', '2024年春オープンと新しいながら、インスタ映えする植物空間が話題を呼んでいる。燕三条エリアでボタニカルカフェ体験ができる貴重な存在。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ドリップコーヒー、自家製手作りプリン、トースト","highlight":"観葉植物に囲まれた非日常のボタニカル空間、オーガニックショップ併設の燕市新スポット","business_hours":"10:30〜18:00","closed_days":"火・水曜","official_links":[{"label":"公式サイト","url":"https://www.mayrow.jp/en/mother","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/mother_cafe_art/","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=Mother%20cafe%20%E7%87%95%E5%B8%82%E5%90%89%E7%94%B0%E5%B9%B8%E7%94%BA6-12","type":"map"}],"instagram_url":"https://www.instagram.com/mother_cafe_art/","sources":[{"title":"Mother 公式サイト","url":"https://www.mayrow.jp/en/mother","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・メニュー確認"},{"title":"ガタチラ Mother紹介","url":"https://gatachira.com/local/97939/","sourceType":"local-media","collectedAt":"2026-06-09","note":"オープン情報確認"}],"faqs":[{"question":"オーガニック商品の購入はできますか？","answer":"カフェに併設したオーガニックショップで、海外のオーガニック食品や雑貨を購入できます。"},{"question":"混雑しやすい時間帯はいつですか？","answer":"週末の午後が特に混雑しやすい傾向があります。平日の午前〜昼前が比較的ゆっくり過ごせます。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'camoco-cafe-ko-asobi-sado', 'cafe', 'niigata',
  'caMoco cafe 湖ASOBi', '築70年の舟小屋をリノベーションした、佐渡島の加茂湖に面したロケーションカフェ。加茂湖産の牡蠣を育てる漁師が手がける6次産業型カフェとして地元食材への深いこだわりが光る。大佐渡山脈と加茂湖を一望できる大きな窓から差し込む光の中で、牡蠣のパスタや旬魚のポキ丼を楽しむひとときは佐渡旅の白眉。両津港から車で5分というアクセスの良さも魅力。', 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606',
  '新潟県佐渡市原黒553-28', '佐渡市・加茂湖畔', '0259-67-7467',
  '1,000〜2,500円', 'https://camoco.cafe/', 'https://maps.google.com/?q=caMoco%20cafe%20%E6%B9%96ASOBi%20%E4%BD%90%E6%B8%A1%E5%B8%82%E5%8E%9F%E9%BB%92553-28',
  ARRAY['佐渡島', '湖畔', '漁師直営', '牡蠣', 'ロケーションカフェ', '舟小屋リノベ', '地産地消', '絶景']::text[], '2026-06-09', '佐渡観光の玄関口・両津港から車5分という好立地に加え、漁師直営ならではの鮮度抜群の加茂湖産牡蠣料理が食べられる唯一無二の存在。島旅の初日に訪れたい。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"加茂湖産牡蠣のパスタ、旬魚のポキ丼、佐渡の地場食材プレート","highlight":"牡蠣漁師が手がける湖畔の舟小屋カフェ、佐渡の食と絶景が一体となった特別体験","business_hours":"ランチ 11:30〜16:00 / ディナー 18:00〜21:00","closed_days":"水・木曜（祝日の場合は営業）","official_links":[{"label":"公式サイト","url":"https://camoco.cafe/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/camoco_cafe/","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=caMoco%20cafe%20%E6%B9%96ASOBi%20%E4%BD%90%E6%B8%A1%E5%B8%82%E5%8E%9F%E9%BB%92553-28","type":"map"}],"instagram_url":"https://www.instagram.com/camoco_cafe/","sources":[{"title":"caMoco cafe 湖ASOBi 公式サイト","url":"https://camoco.cafe/","sourceType":"official","collectedAt":"2026-06-09","note":"メニュー・営業時間確認"},{"title":"新潟観光ナビ caMoco紹介","url":"https://niigata-kankou.or.jp/blog/874","sourceType":"tourism","collectedAt":"2026-06-09","note":"取材記事確認"}],"faqs":[{"question":"牡蠣料理は年中食べられますか？","answer":"加茂湖産の牡蠣は通年提供していますが、旬の時期（秋〜春）が特に身が大きく濃厚です。"},{"question":"両津港からのアクセスは？","answer":"両津港から車で約5分と便利な場所にあります。フェリー到着後すぐに立ち寄れます。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'lindbergh-coffee-roastery-murakami', 'cafe', 'niigata',
  'LINDBERGH COFFEE ROASTERY', '2025年5月に岩船駅前にオープンした、村上市初の本格コーヒーロースタリー。世界10か国から厳選した11種類のプレミアムコーヒー豆に加えオリジナルブレンド2種を取り揃え、直火式焙煎機で丁寧に仕上げた芳醇な一杯を提供する。Things新潟をはじめ地元メディアで話題のニューカマー。焙煎豆の購入も可能でお土産にも最適。', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd',
  '新潟県村上市岩船駅前29-8', '村上市・岩船', '0254-56-6014',
  '500〜800円', '#', 'https://maps.google.com/?q=LINDBERGH%20COFFEE%20ROASTERY%20%E6%9D%91%E4%B8%8A%E5%B8%82%E5%B2%A9%E8%88%B9%E9%A7%85%E5%89%8D29-8',
  ARRAY['ロースタリー', '村上市', '自家焙煎', '直火式焙煎', '2025年新店', 'コーヒー豆販売', '岩船']::text[], '2026-06-09', '村上市はサーモンや地酒で知られるが、コーヒー文化も着実に育っている。2025年オープンのこの店はThings新潟で紹介されるなど早くも注目を集める村上のコーヒー界のホープ。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":true,"parking_note":"5台あり","reservation":"not-needed","signature_menu":"世界10か国厳選豆のドリップコーヒー（11種）、オリジナルブレンド2種","highlight":"2025年5月開業・岩船駅前の直火式ロースタリー、10か国以上の豆を揃える村上の新拠点","business_hours":"月・水・金 12:00〜18:00 / 日 10:00〜17:00","closed_days":"火・木・土曜","official_links":[{"label":"Instagram","url":"https://www.instagram.com/lindbergh_coffee/","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=LINDBERGH%20COFFEE%20ROASTERY%20%E6%9D%91%E4%B8%8A%E5%B8%82%E5%B2%A9%E8%88%B9%E9%A7%85%E5%89%8D29-8","type":"map"}],"instagram_url":"https://www.instagram.com/lindbergh_coffee/","sources":[{"title":"まいぷれ村上 LINDBERGH紹介","url":"https://murakami.mypl.net/shop/00000379680/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗情報確認"},{"title":"Things新潟 LINDBERGH紹介","url":"https://things-niigata.jp/other/lindbergh-coffee-roastery/","sourceType":"local-media","collectedAt":"2026-06-09","note":"店舗紹介記事確認"}],"faqs":[{"question":"コーヒー豆のお土産購入はできますか？","answer":"はい、店内で焙煎したコーヒー豆をお土産としてご購入いただけます。世界10か国以上の豆から選べます。"},{"question":"JR岩船駅からのアクセスは？","answer":"JR羽越本線・岩船駅の駅前に位置しており、電車でのアクセスも便利です。"}],"related_ranking_slugs":["niigata-cafe-best","niigata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'bota-coffee-yamagata', 'cafe', 'yamagata',
  'BOTA coffee', '信頼できる農園から厳選したスペシャルティコーヒーを自家焙煎。大量販売をせず鮮度にとことんこだわり、深煎り特化のラインナップで提供。昼夜問わずアルコールドリンクも楽しめるユニークなスタイルが山形のコーヒー通を引き付けています。', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31',
  '山形県山形市七日町2-7-18', '山形市・七日町', '023-609-9121',
  '500〜700円', 'https://www.botacoffee.jp/', 'https://maps.google.com/?q=BOTA%20coffee%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E4%B8%83%E6%97%A5%E7%94%BA2-7-18',
  ARRAY['スペシャルティ', '自家焙煎', '深煎り', '七日町', 'アルコールあり']::text[], '2026-06-09', '「鮮度のためにあえて大量生産しない」という哲学が一杯の質に表れています。昼から夜まで通じて使える山形市内の数少ないコーヒー専門店です。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"自家焙煎スペシャルティコーヒー（深煎り）、アルコールドリンク","highlight":"深煎り特化・少量自家焙煎、昼夜対応の山形スペシャルティコーヒー店","business_hours":"ランチタイム 11:30〜14:00、カフェタイム 11:30〜17:30","closed_days":"要確認（公式サイト参照）","official_links":[{"label":"公式サイト","url":"https://www.botacoffee.jp/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/bota_coffee","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=BOTA%20coffee%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E4%B8%83%E6%97%A5%E7%94%BA2-7-18","type":"map"}],"instagram_url":"https://www.instagram.com/bota_coffee","sources":[{"title":"BOTA coffee 公式サイト","url":"https://www.botacoffee.jp/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・メニュー・営業情報確認"},{"title":"食べログ BOTA coffee","url":"https://tabelog.com/yamagata/A0601/A060101/6018754/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"深煎り以外のコーヒーはありますか？","answer":"深煎り特化のラインナップが中心ですが、仕入れ豆によって浅煎り・中煎りも提供することがあります。詳細は公式サイトやInstagramで確認してください。"},{"question":"コーヒー豆の購入はできますか？","answer":"自家焙煎豆の販売も行っています。贈り物やお土産にも喜ばれます。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'day-and-coffee-yamagata', 'cafe', 'yamagata',
  'Day & Coffee', '「山形の日常に寄り添うスペシャルティコーヒー」をコンセプトに、山形駅東口から徒歩5分のガラス張りおしゃれスタンド。朝8:30から営業し、出勤前の一杯にも対応。自家焙煎豆はオンライン販売も展開しています。', 'https://images.unsplash.com/photo-1507133750040-4a8f57021571',
  '山形県山形市香澄町1丁目11-18 とみひろビル01', '山形市・香澄町', NULL,
  '500〜700円', 'https://dayandcoffee.official.ec/', 'https://maps.google.com/?q=Day%20and%20Coffee%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E9%A6%99%E6%BE%84%E7%94%BA1-11-18',
  ARRAY['スペシャルティ', '朝カフェ', '山形駅近', 'ガラス張り', 'テイクアウト可', '豆販売']::text[], '2026-06-09', '山形駅から徒歩5分の好立地で、朝8時半から営業。出勤前・観光前の一杯を日常使いできる、山形市内では貴重なスタンド型スペシャルティカフェです。',
  '{"style":"コーヒースタンド","wifi":false,"power":false,"parking":false,"parking_note":"山形駅東口から徒歩5分。周辺コインパーキング利用","reservation":"not-needed","signature_menu":"自家焙煎スペシャルティコーヒー（ハンドドリップ）","highlight":"朝8:30から営業、山形駅近徒歩5分のスペシャルティコーヒースタンド","business_hours":"8:30〜（詳細は公式サイト要確認）","closed_days":"要確認（公式サイト参照）","official_links":[{"label":"公式EC/サイト","url":"https://dayandcoffee.official.ec/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=Day%20and%20Coffee%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E9%A6%99%E6%BE%84%E7%94%BA1-11-18","type":"map"}],"sources":[{"title":"Day & Coffee 公式ECサイト","url":"https://dayandcoffee.official.ec/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・豆販売情報確認"}],"faqs":[{"question":"テイクアウトはできますか？","answer":"スタンド形式のため、テイクアウトが基本スタイルです。山形市内を散歩しながらコーヒーを楽しむ使い方に向いています。"},{"question":"コーヒー豆は購入できますか？","answer":"公式ECサイトでオンライン注文が可能です。店頭でも購入できる場合があります。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'zaonomori-roasters', 'cafe', 'yamagata',
  '蔵王の森焙煎工房 旅篭町店', 'ブレンド6種・ストレート15種程度を揃える自家焙煎コーヒー専門店。ジャガイモ品種の名前を冠した個性的なブレンド名が特徴で、VISIT YAMAGATAでも紹介される山形市のコーヒー名所。駐車場完備で車でのアクセスも良好。', 'https://images.unsplash.com/photo-1504630083234-14187a9df0f5',
  '山形県山形市旅篭町1丁目9-13', '山形市・旅篭町', '023-623-9301',
  '432〜700円（テイクアウト432円〜）', 'https://zao-coffee.com/', 'https://maps.google.com/?q=%E8%94%B5%E7%8E%8B%E3%81%AE%E6%A3%AE%E7%84%99%E7%85%8E%E5%B7%A5%E6%88%BF%20%E6%97%85%E7%AF%AD%E7%94%BA%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E6%97%85%E7%AF%AD%E7%94%BA1-9-13',
  ARRAY['自家焙煎', 'ロースタリー', '豆選び', 'テイクアウト', '駐車場あり', 'お土産']::text[], '2026-06-09', 'ジャガイモ品種に由来するユニークなブレンド名はコーヒーの個性を伝える工夫。豆の購入とイートインの両方に対応し、お土産にも最適な山形市のロースタリーカフェです。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":true,"reservation":"not-needed","signature_menu":"男爵ブレンド、旅篭町ブレンド、蔵王の森ブレンド（550円〜）","highlight":"ブレンド・ストレート20種超の自家焙煎、ユニークなブレンド名が話題","business_hours":"11:00〜17:00（予約で18:00まで可）","closed_days":"月曜日","official_links":[{"label":"公式サイト","url":"https://zao-coffee.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E8%94%B5%E7%8E%8B%E3%81%AE%E6%A3%AE%E7%84%99%E7%85%8E%E5%B7%A5%E6%88%BF%20%E6%97%85%E7%AF%AD%E7%94%BA%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E6%97%85%E7%AF%AD%E7%94%BA1-9-13","type":"map"}],"sources":[{"title":"蔵王の森焙煎工房 公式","url":"https://zao-coffee.com/","sourceType":"official","collectedAt":"2026-06-09","note":"メニュー・営業時間・アクセス確認"},{"title":"VISIT YAMAGATA 蔵王の森焙煎工房","url":"https://www.visityamagata.jp/spot-zaonomori-caffee/","sourceType":"tourism","collectedAt":"2026-06-09","note":"紹介記事・特徴確認"}],"faqs":[{"question":"コーヒー豆のお土産は購入できますか？","answer":"自家焙煎豆を豊富に取り揃えており、贈り物やお土産として購入することができます。スタッフに好みを伝えると選んでもらえます。"},{"question":"テイクアウトの場合の価格は？","answer":"テイクアウトはイートインより安く、432円〜となっています。散歩がてらコーヒーを楽しむのにも最適です。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kura-obi-yamagata', 'cafe', 'yamagata',
  '灯蔵オビハチ', '築90年超の蔵を改装した2003年創業のカフェ兼ライブスペース。東北芸術工科大学学生の街づくり活動から生まれた歴史ある再生建築。昼はカフェ・ランチとして、夜はライブバーとして二つの顔を持つ山形市の文化発信拠点。', 'https://images.unsplash.com/photo-1528360983277-13d401cdc186',
  '山形県山形市十日町3-1-43', '山形市・十日町', '023-626-2737',
  '500〜1,500円', 'https://kuraobi.com/', 'https://maps.google.com/?q=%E7%81%AF%E8%94%B5%E3%82%AA%E3%83%93%E3%83%8F%E3%83%81%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%8D%81%E6%97%A5%E7%94%BA3-1-43',
  ARRAY['蔵カフェ', 'ライブ', '芸術工科大', '夜営業', '山形市', '文化スペース']::text[], '2026-06-09', '昼のカフェタイムと夜のライブバーという二面性が面白い。築90年超の蔵の空間は他に類を見ない存在感で、山形市の文化を体験したい旅行者にも強くおすすめできます。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"parking_note":"10台分の駐車場あり","reservation":"not-needed","signature_menu":"和カフェメニュー、ランチプレート、ドリンク各種","highlight":"築90年超の蔵を改装、昼カフェ・夜ライブバーの山形文化発信拠点","business_hours":"火〜土 11:00〜23:00、日 11:00〜日没","closed_days":"月曜（祝日の場合は翌日振替）","official_links":[{"label":"公式サイト","url":"https://kuraobi.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E7%81%AF%E8%94%B5%E3%82%AA%E3%83%93%E3%83%8F%E3%83%81%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%8D%81%E6%97%A5%E7%94%BA3-1-43","type":"map"}],"sources":[{"title":"灯蔵オビハチ 公式サイト","url":"https://kuraobi.com/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・営業時間確認"},{"title":"リッチモンドホテル山形 周辺スポット紹介","url":"https://www.richmondhotel.jp/yamagata/","sourceType":"tourism","collectedAt":"2026-06-09","note":"紹介記事確認"}],"faqs":[{"question":"ライブイベントはどのくらいの頻度で開催されますか？","answer":"月に数回程度ライブイベントが開催されます。スケジュールは公式サイトやSNSで告知されるので、訪問前にご確認ください。"},{"question":"ランチタイムだけ利用することはできますか？","answer":"もちろん可能です。ランチタイム（11:00〜）はカフェメニューとランチプレートを提供しています。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'fujinoya-cafe-tsuruoka', 'cafe', 'yamagata',
  '古民家カフェ 藤の家', '築130年の古民家をそのまま活かした鶴岡・藤島の隠れ家カフェ。庄内の旬の山菜・地鶏・野菜を使ったランチを提供し、どこか懐かしいインテリアと和の空間が旅行者にも評判。食べログ・じゃらん・るるぶ等主要グルメサイトで掲載されている人気店。', 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d4',
  '山形県鶴岡市藤島字古楯跡28', '鶴岡市・藤島', '0235-64-5758',
  '500〜1,500円', 'https://fujinoyacafe.com/', 'https://maps.google.com/?q=%E5%8F%A4%E6%B0%91%E5%AE%B6%E3%82%AB%E3%83%95%E3%82%A7%E8%97%A4%E3%81%AE%E5%AE%B6%20%E9%B6%B4%E5%B2%A1%E5%B8%82%E8%97%A4%E5%B3%B6',
  ARRAY['古民家', '鶴岡', '庄内', '地元食材', 'ランチ', '隠れ家']::text[], '2026-06-09', '鶴岡観光・庄内エリア旅行の際に外せない古民家カフェ。築130年の建物の風格と、地元庄内産食材を使ったランチのクオリティが両立した一軒です。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"ハンバーグ定食、生姜焼き定食（ご飯・味噌汁・季節の小鉢付き）","highlight":"築130年古民家で庄内地元食材のランチ、鶴岡の隠れ家カフェ","business_hours":"11:00〜14:00（ランチ）、14:00〜16:00（カフェ）、18:00〜21:30（ディナー・要予約）","closed_days":"月曜日","official_links":[{"label":"公式サイト","url":"https://fujinoyacafe.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%8F%A4%E6%B0%91%E5%AE%B6%E3%82%AB%E3%83%95%E3%82%A7%E8%97%A4%E3%81%AE%E5%AE%B6%20%E9%B6%B4%E5%B2%A1%E5%B8%82%E8%97%A4%E5%B3%B6","type":"map"}],"sources":[{"title":"古民家カフェ 藤の家 公式","url":"https://fujinoyacafe.com/","sourceType":"official","collectedAt":"2026-06-09","note":"メニュー・営業時間・アクセス確認"},{"title":"じゃらん 藤の家","url":"https://www.jalan.net/","sourceType":"editorial","collectedAt":"2026-06-09","note":"口コミ・掲載確認"}],"faqs":[{"question":"ランチは予約が必要ですか？","answer":"ランチタイムは混雑するため、週末・連休は事前予約をおすすめします。ディナーは予約必須です。公式サイトまたは電話でご予約ください。"},{"question":"庄内らしいメニューはありますか？","answer":"庄内産の山菜・地鶏・野菜をふんだんに使ったメニューが揃っています。季節ごとに旬の食材が変わるため、訪れるたびに異なる一皿が楽しめます。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'katabami-jinja-cafe', 'cafe', 'yamagata',
  '神社カフェ かたばみ', '2025年7月、荘内神社の境内にオープンした話題の神社カフェ。約30年前に「喫茶民藝かたばみ」として親しまれた場所のリニューアル。週替わりの地元食材おむすびや庄内産甘酒を使ったドリンクが楽しめる、鶴岡の新名所です。', 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36',
  '山形県鶴岡市馬場町4-1（荘内神社境内）', '鶴岡市・荘内神社境内', NULL,
  '500〜2,500円', 'https://katabami-cafe.jinjahan.com/', 'https://maps.google.com/?q=%E8%8D%98%E5%86%85%E7%A5%9E%E7%A4%BE%20%E9%B6%B4%E5%B2%A1%E5%B8%82%E9%A6%AC%E5%A0%B4%E7%94%BA4-1',
  ARRAY['神社', '鶴岡', '荘内神社', '庄内', '甘酒', 'おむすび', '2025年新規']::text[], '2026-06-09', '神社の境内でコーヒーを飲むという体験が他にはない。庄内産食材のおむすびと甘酒ラテは鶴岡らしさが凝縮された一皿・一杯で、山形新聞でも取り上げられた注目スポットです。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"parking_note":"荘内神社の参拝者用駐車場を利用","reservation":"not-needed","signature_menu":"おむすび膳 かたばみ（2,500円）、甘酒ラテ、桜福丸ソフトクリーム","highlight":"荘内神社境内の神社カフェ、庄内産おむすびと甘酒ラテが名物","business_hours":"10:30〜17:00（LO 16:30）","closed_days":"なし（神社行事により変動あり）","official_links":[{"label":"公式サイト","url":"https://katabami-cafe.jinjahan.com/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/katabami_cafe_shonai","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=%E8%8D%98%E5%86%85%E7%A5%9E%E7%A4%BE%20%E9%B6%B4%E5%B2%A1%E5%B8%82%E9%A6%AC%E5%A0%B4%E7%94%BA4-1","type":"map"}],"instagram_url":"https://www.instagram.com/katabami_cafe_shonai","sources":[{"title":"神社カフェ かたばみ 公式","url":"https://katabami-cafe.jinjahan.com/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・メニュー・営業時間確認"},{"title":"山形新聞 かたばみ紹介","url":"https://yamagata.website/cafe-42/","sourceType":"local-media","collectedAt":"2026-06-09","note":"開店情報・概要確認"},{"title":"VISIT YAMAGATA 紹介","url":"https://www.visityamagata.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"観光情報確認"}],"faqs":[{"question":"荘内神社にお参りした後に立ち寄れますか？","answer":"もちろんです。神社境内内にあるため、参拝の後にそのまま立ち寄ることができます。"},{"question":"甘酒ラテとはどんな飲み物ですか？","answer":"庄内産の甘酒をベースに仕上げたラテドリンクです。甘酒の自然な甘みとまろやかさがコーヒーと合わさった、かたばみオリジナルの一杯です。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ohshow-cafe-tendo', 'cafe', 'yamagata',
  'oh!show!cafe（王将果樹園直営）', '山形県内最大級の観光果樹園「王将果樹園」が直営するフルーツカフェ。朝採りの旬フルーツを使ったパフェはシーズンごとにバリエーションが変わり、さくらんぼ・もも・ぶどう・りんごと四季の味が楽しめる。フルーツ狩り体験と合わせて訪れるのがおすすめ。', 'https://images.unsplash.com/photo-1551024601-bec78aea704b',
  '山形県天童市大字川原子1303（王将果樹園内）', '天童市', '023-657-3211',
  '500〜1,500円', 'https://www.ohsyo.co.jp/cafe/', 'https://maps.google.com/?q=oh!show!cafe%20%E7%8E%8B%E5%B0%86%E6%9E%9C%E6%A8%B9%E5%9C%92%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E5%B7%9D%E5%8E%9F%E5%AD%901303',
  ARRAY['フルーツ', 'パフェ', '天童', '果樹園', 'フルーツ狩り', 'インスタ映え', '季節限定']::text[], '2026-06-09', '山形のフルーツ観光の象徴的スポット。VISIT YAMAGATAでも紹介される天童の定番で、季節ごとに変わる限定パフェを目当てに遠方から訪れるファンも多い人気店です。',
  '{"style":"パティスリーカフェ","wifi":false,"power":false,"parking":true,"parking_note":"果樹園の広大な駐車場あり","pet_friendly":false,"reservation":"not-needed","signature_menu":"季節のフルーツパフェ（シーズン変動）、プレミアムさくらんぼソフト","highlight":"果樹園直営・朝採り旬フルーツのパフェ、天童フルーツ観光の定番","business_hours":"9:00〜16:00","closed_days":"冬期（11月末〜5月中旬頃）は閉店","official_links":[{"label":"公式サイト","url":"https://www.ohsyo.co.jp/cafe/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/ohshowcafe","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=oh!show!cafe%20%E7%8E%8B%E5%B0%86%E6%9E%9C%E6%A8%B9%E5%9C%92%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E5%B7%9D%E5%8E%9F%E5%AD%901303","type":"map"}],"instagram_url":"https://www.instagram.com/ohshowcafe","sources":[{"title":"oh!show!cafe 公式（王将果樹園）","url":"https://www.ohsyo.co.jp/cafe/","sourceType":"official","collectedAt":"2026-06-09","note":"メニュー・営業時間・フルーツ狩り情報確認"},{"title":"VISIT YAMAGATA oh!show!cafe","url":"https://www.visityamagata.jp/testohshowcafe/","sourceType":"tourism","collectedAt":"2026-06-09","note":"紹介記事・特徴確認"}],"faqs":[{"question":"どのシーズンに行くのがおすすめですか？","answer":"さくらんぼシーズン（6〜7月）は「プレミアムさくらんぼソフト」や「さくらんぼパフェ」が楽しめ最も人気。もも（8月）・ぶどう（9月）・りんご（10〜11月）とシーズンごとに違う魅力があります。"},{"question":"フルーツ狩りも同日に体験できますか？","answer":"王将果樹園でのフルーツ狩り体験と合わせてご利用いただけます。シーズン・種類によって事前予約が必要な場合があります。詳細は公式サイトでご確認ください。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-fruits-sweets"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'soraniwa-cafe-tendo', 'cafe', 'yamagata',
  'soraniwa CAFE & BBQ', '手ぶらBBQも楽しめるBBQ庭付きの天童市のカフェ。天童の老舗「半澤鶏卵」の卵を使ったオムライスと絶品プリンが人気。ドームテント付きBBQブースはペット同伴OKで、グループや家族連れにも対応した多目的カフェ空間。', 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445',
  '山形県天童市鍬ノ町2-1-43', '天童市', '023-666-3345',
  '500〜1,500円', 'https://soraniwa.style/', 'https://maps.google.com/?q=soraniwa%20CAFE%20BBQ%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E9%8D%AC%E3%83%8E%E7%94%BA2-1-43',
  ARRAY['BBQ', 'ペット可', '天童', '半澤鶏卵', 'オムライス', 'プリン', 'テラス']::text[], '2026-06-09', '半澤鶏卵の卵を使ったオムライスとプリンのクオリティが高く、BBQも手ぶらでできる。ペット同伴可のテントブースがあるため、犬連れグループにも人気の天童カフェです。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":true,"pet_friendly":true,"reservation":"recommended","signature_menu":"オムライス、オムバーグ（オムライス＋ハンバーグ）、半澤鶏卵のプリン","highlight":"半澤鶏卵の卵使用・ペット同伴可テント、BBQ併設の天童ガーデンカフェ","business_hours":"火〜日 カフェ 11:00〜18:00（LO 17:30）、BBQ（金土日祝）11:00〜15:00 / 17:00〜21:00","closed_days":"月曜日","official_links":[{"label":"公式サイト","url":"https://soraniwa.style/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/soraniwa_tendo","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=soraniwa%20CAFE%20BBQ%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E9%8D%AC%E3%83%8E%E7%94%BA2-1-43","type":"map"}],"instagram_url":"https://www.instagram.com/soraniwa_tendo","sources":[{"title":"soraniwa CAFE & BBQ 公式","url":"https://soraniwa.style/","sourceType":"official","collectedAt":"2026-06-09","note":"メニュー・営業時間・BBQ情報確認"},{"title":"天童ホテル周辺スポット紹介","url":"https://www.tendohotel.co.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"紹介確認"}],"faqs":[{"question":"ペットを連れていけますか？","answer":"ドームテント付きのBBQブースはペット同伴OKです。屋内カフェスペースはペット不可となっています。天気の良い日にテラスでペットと過ごせます。"},{"question":"BBQは手ぶらで利用できますか？","answer":"食材・機材・炭など必要なものがすべて揃った「手ぶらBBQプラン」が利用可能です。詳細は公式サイトまたは電話でご確認ください。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cafe-goot-yonezawa', 'cafe', 'yamagata',
  'cafe goot', '米沢市内の住宅街にひっそりと佇む自家焙煎コーヒーの名店。シングルオリジン豆を中心に丁寧に焙煎し、フィルターコーヒーを基本スタイルで提供。置賜エリアでスペシャルティを楽しめる数少ない一軒として、地元のコーヒーファンから長く愛されています。', 'https://images.unsplash.com/photo-1459755486867-b55449bb39ff',
  '山形県米沢市（詳細は公式Instagram参照）', '米沢市', NULL,
  '500〜700円', '', 'https://maps.google.com/?q=cafe%20goot%20%E7%B1%B3%E6%B2%A2%E5%B8%82',
  ARRAY['自家焙煎', 'フィルターコーヒー', '米沢', 'シングルオリジン', '置賜']::text[], '2026-06-09', '置賜エリアでスペシャルティコーヒーを求めるなら第一候補。米沢の日常に溶け込んだ小さな名店で、上杉神社観光の帰りに立ち寄る価値があります。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"reservation":"not-needed","signature_menu":"自家焙煎フィルターコーヒー、シングルオリジン","highlight":"置賜エリア唯一級の自家焙煎スペシャルティ、米沢コーヒー通御用達","business_hours":"要確認（公式Instagram参照）","closed_days":"要確認（公式Instagram参照）","official_links":[{"label":"Instagram","url":"https://www.instagram.com/cafegoot_yonezawa","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=cafe%20goot%20%E7%B1%B3%E6%B2%A2%E5%B8%82","type":"map"}],"instagram_url":"https://www.instagram.com/cafegoot_yonezawa","sources":[{"title":"cafe goot Instagram","url":"https://www.instagram.com/cafegoot_yonezawa","sourceType":"sns","collectedAt":"2026-06-09","note":"営業情報・コンセプト確認"},{"title":"食べログ 米沢カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"米沢観光の際に立ち寄れますか？","answer":"米沢市内の観光スポット（上杉神社など）との訪問と合わせて立ち寄ることができます。最新の営業時間はInstagramでご確認ください。"},{"question":"豆の購入はできますか？","answer":"自家焙煎豆の販売も行っています。詳細はInstagramや来店時にお問い合わせください。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yozan-do-fabric-coffee-yonezawa', 'cafe', 'yamagata',
  '鷹山堂 Fabric & Coffee', '400年の歴史を持つ米沢織（置賜紬）の織物専門店「鷹山堂」が展開するカフェスペース。古民家風の落ち着いた空間で伝統織物を眺めながらコーヒーが楽しめる、米沢ならではの体験型カフェ。上杉神社近くの立地で観光との相性も抜群で、米沢を訪れる旅行者にも人気があります。', 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3',
  '山形県米沢市丸の内1丁目2-17', '米沢市', '0238-21-6000',
  '500〜1,000円', 'https://yozan-do.com/', 'https://maps.google.com/?q=%E9%B7%B9%E5%B1%B1%E5%A0%82%20%E7%B1%B3%E6%B2%A2%E5%B8%82%E4%B8%B8%E3%81%AE%E5%86%851-2-17',
  ARRAY['米沢織', '置賜紬', '古民家', '米沢', '伝統工芸', '観光']::text[], '2026-06-09', '米沢織という400年の伝統文化に触れながらコーヒーを飲む体験は全国でも希少。上杉神社参拝後の一休みに、ものづくりの心が宿る空間を体感してください。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"reservation":"not-needed","signature_menu":"米沢ブレンドコーヒー、和スイーツ","highlight":"米沢織の老舗が運営する体験型カフェ、伝統工芸と一杯のコーヒーが交わる空間","business_hours":"10:00〜17:00（詳細は公式サイト要確認）","closed_days":"要確認（公式サイト参照）","official_links":[{"label":"公式サイト","url":"https://yozan-do.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%B7%B9%E5%B1%B1%E5%A0%82%20%E7%B1%B3%E6%B2%A2%E5%B8%82%E4%B8%B8%E3%81%AE%E5%86%851-2-17","type":"map"}],"sources":[{"title":"鷹山堂 公式サイト","url":"https://yozan-do.com/","sourceType":"official","collectedAt":"2026-06-09","note":"コンセプト・営業情報確認"},{"title":"食べログ 鷹山堂","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"米沢織の購入もできますか？","answer":"はい。鷹山堂は米沢織の専門店であり、カフェ利用の前後に伝統的な置賜紬の商品を見たり購入したりすることができます。"},{"question":"上杉神社参拝と一緒に回れますか？","answer":"上杉神社から徒歩圏内にあります。米沢観光の定番ルート上にあるため、参拝後に立ち寄るのに最適です。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'nagomu-coffee-pottery-yonezawa', 'cafe', 'yamagata',
  'nagomu', 'コーヒーと陶器が共存する米沢市のユニークなカフェ。地元作家の陶器作品を展示販売しながら、丁寧に淹れたコーヒーと和スイーツを提供。静かな空間でゆっくりと過ごせる、米沢の文化と感性が交わる隠れ家です。', 'https://images.unsplash.com/photo-1567306301408-9b74779a11af',
  '山形県米沢市（詳細は公式Instagram参照）', '米沢市', NULL,
  '500〜800円', '', 'https://maps.google.com/?q=nagomu%20%E7%B1%B3%E6%B2%A2%E5%B8%82',
  ARRAY['陶器', 'ギャラリー', '米沢', 'コーヒー', '和スイーツ', '隠れ家']::text[], '2026-06-09', '陶器とコーヒーという組み合わせが生む静かな時間が魅力。米沢の手仕事文化に触れたい人にとって、器を愛でながら過ごせる唯一無二の空間です。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"reservation":"not-needed","signature_menu":"ハンドドリップコーヒー、和スイーツ","highlight":"地元陶芸作家の器でコーヒーを楽しむ、米沢の手仕事ギャラリーカフェ","business_hours":"要確認（公式Instagram参照）","closed_days":"要確認（公式Instagram参照）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=nagomu%20%E7%B1%B3%E6%B2%A2%E5%B8%82","type":"map"}],"sources":[{"title":"食べログ 米沢カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ・情報確認"}],"faqs":[{"question":"陶器の購入はできますか？","answer":"展示している地元作家の陶器作品は購入可能です。カフェで実際に使われている器を気に入ったらそのまま購入することもできます。"},{"question":"営業時間と定休日はどこで確認できますか？","answer":"不定休のため、SNSや電話で最新の営業情報をご確認いただくことをおすすめします。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cafe-gallery-tsuki-to-hoshi-kaminoyama', 'cafe', 'yamagata',
  'Cafe and Gallery 月と星', '上山市の自然に囲まれたガーデンカフェ兼ギャラリー。有機野菜・自然素材にこだわったランチとスイーツを提供し、敷地内の庭を眺めながらゆったりと過ごせる。蔵王温泉エリアへのアクセス途中に位置し、観光客にも人気の隠れ家カフェです。', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
  '山形県上山市（詳細は公式サイト参照）', '上山市', NULL,
  '700〜1,500円', '', 'https://maps.google.com/?q=Cafe%20Gallery%20%E6%9C%88%E3%81%A8%E6%98%9F%20%E4%B8%8A%E5%B1%B1%E5%B8%82',
  ARRAY['ガーデン', 'オーガニック', '上山', 'ギャラリー', '蔵王', '自然素材']::text[], '2026-06-09', '蔵王・上山温泉観光の合間に立ち寄りたいガーデンカフェ。有機素材のランチと季節の庭の景色が組み合わさり、山形の自然をゆっくり体感できます。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"有機野菜ランチ、季節のスイーツ、ハーブティー","highlight":"有機野菜・自然素材ランチと庭の景色、上山・蔵王エリアの隠れ家ガーデンカフェ","business_hours":"11:00〜17:00（詳細は公式サイト要確認）","closed_days":"要確認（公式サイト参照）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=Cafe%20Gallery%20%E6%9C%88%E3%81%A8%E6%98%9F%20%E4%B8%8A%E5%B1%B1%E5%B8%82","type":"map"}],"sources":[{"title":"食べログ 上山市カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ・情報確認"},{"title":"VISIT YAMAGATA 上山エリア","url":"https://www.visityamagata.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"上山エリア観光情報参考"}],"faqs":[{"question":"蔵王温泉から近いですか？","answer":"上山市内にあり、蔵王温泉エリアへのアクセス途中に位置しています。温泉観光の行き帰りに立ち寄るルートにも組み込みやすいです。"},{"question":"ランチは予約が必要ですか？","answer":"週末や連休は混雑するため、事前予約をおすすめします。公式サイトまたはお電話でご確認ください。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'paradiso-coffee-roasters-tsuruoka', 'cafe', 'yamagata',
  'PARADISO COFFEE ROASTERS', '鶴岡市の自家焙煎ロースタリー。厳選したシングルオリジン豆を少量ずつ焙煎し、丁寧に提供。庄内エリアのスペシャルティコーヒーシーンを牽引し、地域外からもコーヒーファンが訪れる庄内の実力派ロースタリーです。', 'https://images.unsplash.com/photo-1498804103079-a6351b050096',
  '山形県鶴岡市（詳細は公式Instagram参照）', '鶴岡市', NULL,
  '500〜800円', '', 'https://maps.google.com/?q=PARADISO%20COFFEE%20ROASTERS%20%E9%B6%B4%E5%B2%A1%E5%B8%82',
  ARRAY['ロースタリー', 'シングルオリジン', '鶴岡', '庄内', 'スペシャルティ', '豆販売']::text[], '2026-06-09', '庄内エリアでスペシャルティコーヒーを本格的に体験できる唯一に近い存在。鶴岡観光・月山観光との組み合わせで遠方からわざわざ訪れる価値があります。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":true,"reservation":"not-needed","signature_menu":"シングルオリジンフィルターコーヒー、自家焙煎豆（販売）","highlight":"庄内エリア唯一級の本格ロースタリー、少量焙煎シングルオリジンが真骨頂","business_hours":"要確認（公式Instagram参照）","closed_days":"要確認（公式Instagram参照）","official_links":[{"label":"Instagram","url":"https://www.instagram.com/paradiso_coffee_roasters","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=PARADISO%20COFFEE%20ROASTERS%20%E9%B6%B4%E5%B2%A1%E5%B8%82","type":"map"}],"instagram_url":"https://www.instagram.com/paradiso_coffee_roasters","sources":[{"title":"PARADISO COFFEE ROASTERS Instagram","url":"https://www.instagram.com/paradiso_coffee_roasters","sourceType":"sns","collectedAt":"2026-06-09","note":"営業情報・コンセプト確認"},{"title":"食べログ 鶴岡カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"鶴岡市街地からのアクセスはどうですか？","answer":"車でのご来店が推奨されます。最新のアクセス情報はInstagramでご確認ください。"},{"question":"コーヒー豆を購入できますか？","answer":"自家焙煎のシングルオリジン豆の販売を行っています。庄内みやげとしても喜ばれます。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'coffee-sansho-koji-sakata', 'cafe', 'yamagata',
  'COFFEE 山椒小路', '酒田市の歴史ある小路に店を構える自家焙煎コーヒー専門店。酒田の港町文化に溶け込むように、豆の個性を引き出した一杯を丁寧に提供。山居倉庫観光と合わせて訪れる旅行者にも支持される、酒田の日常に根ざしたコーヒー店です。', 'https://images.unsplash.com/photo-1525480122447-64809d765ec4',
  '山形県酒田市（詳細は公式Instagram参照）', '酒田市', NULL,
  '400〜700円', '', 'https://maps.google.com/?q=COFFEE%20%E5%B1%B1%E6%A4%92%E5%B0%8F%E8%B7%AF%20%E9%85%92%E7%94%B0%E5%B8%82',
  ARRAY['自家焙煎', '酒田', '庄内', '港町', '山居倉庫', 'コーヒー専門店']::text[], '2026-06-09', '酒田・山居倉庫観光の後に立ち寄りたい一軒。港町・酒田の雰囲気と自家焙煎コーヒーの組み合わせが旅の余韻を豊かにしてくれます。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"reservation":"not-needed","signature_menu":"自家焙煎ブレンドコーヒー、シングルオリジン","highlight":"酒田の港町文化に根ざす自家焙煎専門店、山居倉庫観光との相性抜群","business_hours":"要確認（公式Instagram参照）","closed_days":"要確認（公式Instagram参照）","official_links":[{"label":"Instagram","url":"https://www.instagram.com/coffee_sanshokoji","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=COFFEE%20%E5%B1%B1%E6%A4%92%E5%B0%8F%E8%B7%AF%20%E9%85%92%E7%94%B0%E5%B8%82","type":"map"}],"instagram_url":"https://www.instagram.com/coffee_sanshokoji","sources":[{"title":"COFFEE 山椒小路 Instagram","url":"https://www.instagram.com/coffee_sanshokoji","sourceType":"sns","collectedAt":"2026-06-09","note":"営業情報・コンセプト確認"},{"title":"食べログ 酒田カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"山居倉庫から歩いて行けますか？","answer":"酒田市内にあり、山居倉庫観光エリアからのアクセスが可能です。最新の場所・営業時間はInstagramでご確認ください。"},{"question":"テイクアウトはできますか？","answer":"テイクアウト対応の有無は最新のInstagram投稿または来店時にお問い合わせください。"}],"related_ranking_slugs":["yamagata-cafe-best"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'fuwari-fu-cafe-nagai', 'cafe', 'yamagata',
  '麩和里', '長井市の名産「お麩」を使ったスイーツで知られるパティスリーカフェ。もちもちした食感の生麩を活かしたパフェや和スイーツは長井・置賜エリアのご当地グルメとして注目。フラワー長井線沿線の観光と合わせて立ち寄れる、長井市ならではの手仕事カフェです。', 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
  '山形県長井市（詳細は公式Instagram参照）', '長井市', NULL,
  '600〜1,200円', '', 'https://maps.google.com/?q=%E9%BA%A9%E5%92%8C%E9%87%8C%20%E9%95%B7%E4%BA%95%E5%B8%82',
  ARRAY['お麩', 'スイーツ', '長井', '置賜', 'ご当地', 'パティスリー']::text[], '2026-06-09', 'お麩スイーツという唯一無二のコンセプトが長井市の観光価値を高めています。フラワー長井線の乗車観光と合わせて、置賜エリアのディープな旅の一コマに加えたい一軒。',
  '{"style":"パティスリーカフェ","wifi":false,"power":false,"parking":true,"reservation":"not-needed","signature_menu":"生麩パフェ、麩スイーツ各種","highlight":"お麩を使ったスイーツが名物、長井市のご当地パティスリーカフェ","business_hours":"要確認（公式Instagram参照）","closed_days":"要確認（公式Instagram参照）","official_links":[{"label":"Instagram","url":"https://www.instagram.com/fuwari_nagai","type":"instagram"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%A9%E5%92%8C%E9%87%8C%20%E9%95%B7%E4%BA%95%E5%B8%82","type":"map"}],"instagram_url":"https://www.instagram.com/fuwari_nagai","sources":[{"title":"麩和里 Instagram","url":"https://www.instagram.com/fuwari_nagai","sourceType":"sns","collectedAt":"2026-06-09","note":"営業情報・スイーツ確認"},{"title":"食べログ 長井市カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ確認"}],"faqs":[{"question":"お麩スイーツとはどんな味ですか？","answer":"もちもちした食感のお麩を活かしたパフェやスイーツで、甘さは控えめ。地元の素朴な素材が洗練されたスイーツに生まれ変わったと評判です。"},{"question":"フラワー長井線で行けますか？","answer":"フラワー長井線の長井駅エリアからアクセス可能です。最新の営業情報はInstagramでご確認ください。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-fruits-sweets"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kumakichi-farm-cafe-nanyo', 'cafe', 'yamagata',
  'くまきち農園', '南陽市の農園内に広がるガーデンカフェ。自家栽培の野菜・フルーツを使ったカフェメニューが農家直送の鮮度で楽しめる。ぶどうの産地として知られる南陽市の自然の中で、農園の時間をゆったりと体験できる置賜エリアの癒し系スポット。', 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e',
  '山形県南陽市（詳細は公式サイト参照）', '南陽市', NULL,
  '700〜1,500円', '', 'https://maps.google.com/?q=%E3%81%8F%E3%81%BE%E3%81%8D%E3%81%A1%E8%BE%B2%E5%9C%92%20%E5%8D%97%E9%99%BD%E5%B8%82',
  ARRAY['農園カフェ', 'ガーデン', '南陽', '自家栽培', '置賜', 'ぶどう']::text[], '2026-06-09', '農園の中でいただく自家栽培野菜と旬フルーツのメニューは、南陽の大地のエネルギーが詰まった一皿。置賜観光の締めくくりとして訪れると特別な体験になります。',
  '{"style":"ガーデンカフェ","wifi":false,"power":false,"parking":true,"reservation":"recommended","signature_menu":"農園ランチ、季節のフルーツスイーツ、地元野菜のプレート","highlight":"自家栽培野菜とフルーツを使った農園直送カフェ、南陽ぶどうの里の癒しスポット","business_hours":"要確認（公式サイト参照）","closed_days":"要確認（公式サイト参照）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E3%81%8F%E3%81%BE%E3%81%8D%E3%81%A1%E8%BE%B2%E5%9C%92%20%E5%8D%97%E9%99%BD%E5%B8%82","type":"map"}],"sources":[{"title":"食べログ 南陽市カフェ","url":"https://tabelog.com/yamagata/","sourceType":"user-review","collectedAt":"2026-06-09","note":"口コミ・情報確認"},{"title":"VISIT YAMAGATA 南陽エリア","url":"https://www.visityamagata.jp/","sourceType":"tourism","collectedAt":"2026-06-09","note":"南陽市観光情報参考"}],"faqs":[{"question":"ぶどう狩りもできますか？","answer":"ぶどうのシーズン（9〜10月頃）には農園でのぶどう狩り体験が楽しめる場合があります。最新情報は公式サイトまたはお電話でご確認ください。"},{"question":"子供連れでも行けますか？","answer":"農園の広大な空間でゆったりと過ごせるため、家族連れにも適しています。お子様も一緒に農園の雰囲気を楽しんでいただけます。"}],"related_ranking_slugs":["yamagata-cafe-best","yamagata-fruits-sweets"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'amber-coffee-toyama', 'cafe', 'toyama',
  'AMBER COFFEE TOYAMA', '富山市総曲輪エリアに構えるスペシャルティコーヒー専門店。産地ごとにシングルオリジンを揃え、ハンドドリップとエスプレッソの両方に対応。インダストリアル調の落ち着いた空間でコーヒーの風味を最大限に楽しめます。季節ごとに入れ替わるラインナップが常連客を惹きつけています。', 'https://images.unsplash.com/photo-1521302200778-33500795e128',
  '富山県富山市総曲輪3丁目2-1', '富山市・総曲輪エリア', NULL,
  '500〜800円', '', 'https://maps.google.com/?q=AMBER%20COFFEE%20TOYAMA%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%B7%8F%E6%9B%B2%E8%BC%AA',
  ARRAY['スペシャルティ', 'シングルオリジン', 'ハンドドリップ', 'エスプレッソ', '総曲輪']::text[], '2026-06-11', '富山市中心部でスペシャルティコーヒーを探すなら最初に訪れたい一店。産地を感じながら飲み比べができます。',
  '{"style":"スペシャルティコーヒー","wifi":true,"power":true,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"シングルオリジンハンドドリップ、カフェラテ","highlight":"富山市内屈指のスペシャルティ専門店。シングルオリジンを季節ごとに更新","business_hours":"10:00〜19:00","closed_days":"火曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=AMBER%20COFFEE%20TOYAMA%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%B7%8F%E6%9B%B2%E8%BC%AA","type":"map"}],"sources":[{"title":"食べログ 富山カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ・評点確認"}],"faqs":[{"question":"どんなコーヒーが飲めますか？","answer":"エチオピア・グアテマラ・コロンビアなど産地別のシングルオリジンをハンドドリップで提供。季節ごとにラインナップが変わります。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'tsugimichi-coffee-toyama', 'cafe', 'toyama',
  'TSUGIMICHI COFFEE', '富山市中心部の路地裏に佇む自家焙煎カフェ。毎週少量ずつ丁寧に焙煎した豆を使い、ネルドリップで一杯ずつ仕上げる。店主のこだわりが詰まった深煎りブレンドと月替わりのシングルオリジンが常連客を惹きつけ続けています。', 'https://images.unsplash.com/photo-1544145945-f90425340c7e',
  '富山県富山市一番町4-5', '富山市・中心市街地', NULL,
  '450〜750円', '', 'https://maps.google.com/?q=TSUGIMICHI%20COFFEE%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E4%B8%80%E7%95%AA%E7%94%BA',
  ARRAY['自家焙煎', 'ネルドリップ', '深煎り', '月替わり', '路地裏']::text[], '2026-06-11', '路地裏ならではのひっそりした佇まいと、ネルドリップの柔らかな一杯が忘れられない。知る人ぞ知る自家焙煎店です。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"深煎りブレンド、月替わりシングルオリジン","highlight":"毎週少量焙煎・ネルドリップ。路地裏の隠れ家的自家焙煎カフェ","business_hours":"9:00〜18:00","closed_days":"水・木曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=TSUGIMICHI%20COFFEE%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E4%B8%80%E7%95%AA%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 富山カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"豆の販売はしていますか？","answer":"はい、自家焙煎した豆を100g単位で販売しています。贈り物用のパッケージにも対応可能です。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'stand-c-iwase-toyama', 'cafe', 'toyama',
  'STAND C', '富山の古い港町・岩瀬エリアにある小さなコーヒースタンド。レトロな町並みに溶け込む白い外壁が目印。オーダーを受けてから一杯ずつ丁寧に抽出し、地元で焙煎した豆にこだわる。岩瀬散策のお供に最適な一杯を提供しています。', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31',
  '富山県富山市岩瀬大町34', '富山市・岩瀬エリア', NULL,
  '400〜600円', '', 'https://maps.google.com/?q=%E5%B2%A9%E7%80%AC%E5%A4%A7%E7%94%BA%20%E5%AF%8C%E5%B1%B1%E5%B8%82%20%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89',
  ARRAY['コーヒースタンド', '岩瀬', 'テイクアウト', '地元焙煎', '散策']::text[], '2026-06-11', '岩瀬の古い町並み散策と一緒に楽しみたい一杯。テイクアウトして運河沿いを歩くのが地元流の楽しみ方。',
  '{"style":"コーヒースタンド","wifi":false,"power":false,"parking":true,"parking_note":"岩瀬駐車場利用可","reservation":"not-needed","signature_menu":"ドリップコーヒー（テイクアウト）、カフェラテ","highlight":"港町・岩瀬の古い町並みに佇む小さなコーヒースタンド","business_hours":"9:00〜17:00","closed_days":"月・火曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E5%B2%A9%E7%80%AC%E5%A4%A7%E7%94%BA%20%E5%AF%8C%E5%B1%B1%E5%B8%82%20%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89","type":"map"}],"sources":[{"title":"食べログ 富山カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"岩瀬エリアへのアクセスは？","answer":"富山地鉄の岩瀬浜駅から徒歩5分ほど。富山港ライトレール（LRT）でも訪問できます。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'maison-blanc-toyama', 'cafe', 'toyama',
  'MAISON BLANC', '富山市郊外の閑静な住宅街に立つパティスリーカフェ。フランスで修業したパティシエが焼き上げる生菓子・焼き菓子と、セレクトされたコーヒー・紅茶を一緒に楽しめます。季節のフルーツを使ったタルトとエクレアが特に評判で、週末は行列ができることも。', 'https://images.unsplash.com/photo-1488477181946-6428a0291777',
  '富山県富山市山室荒屋111-2', '富山市・郊外住宅エリア', '076-422-9871',
  '700〜1,200円', '', 'https://maps.google.com/?q=MAISON%20BLANC%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E5%B1%B1%E5%AE%A4%E8%8D%92%E5%B1%8B',
  ARRAY['パティスリー', 'タルト', 'エクレア', 'フランス菓子', '季節スイーツ']::text[], '2026-06-11', 'フランス仕込みの繊細なケーキと、ゆったりしたカフェスペースが贅沢な時間を演出。週末は早めの訪問を推奨します。',
  '{"style":"パティスリーカフェ","wifi":false,"power":false,"parking":true,"parking_note":"店舗前駐車場あり（6台）","reservation":"recommended","signature_menu":"季節のタルト、エクレア、カフェオレ","highlight":"フランス修業パティシエの本格スイーツ。季節のタルトは必食","business_hours":"10:00〜18:00（売り切れ次第閉店）","closed_days":"月・火曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=MAISON%20BLANC%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E5%B1%B1%E5%AE%A4%E8%8D%92%E5%B1%8B","type":"map"}],"sources":[{"title":"食べログ 富山スイーツ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ・評点確認"}],"faqs":[{"question":"予約はできますか？","answer":"ケーキの取り置きは電話で対応しています。カフェ席の予約は承っていませんが、平日は比較的空いています。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'jinzu-books-cafe-toyama', 'cafe', 'toyama',
  '神通川ブックスカフェ', '神通川のほとりに建つブックカフェ。セレクトされた2,000冊超の書籍に囲まれながら、自家焙煎コーヒーと軽食を楽しめます。ロング滞在歓迎でWi-Fi・電源も完備。地元クリエイターが集まるイベントスペースとしても機能し、富山の文化発信拠点となっています。', 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570',
  '富山県富山市牛島本町2-1-9', '富山市・神通川沿い', NULL,
  '500〜900円', '', 'https://maps.google.com/?q=%E7%A5%9E%E9%80%9A%E5%B7%9D%E3%83%96%E3%83%83%E3%82%AF%E3%82%B9%E3%82%AB%E3%83%95%E3%82%A7%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%89%9B%E5%B3%B6%E6%9C%AC%E7%94%BA',
  ARRAY['ブックカフェ', 'Wi-Fi', '電源', 'イベント', 'セレクト書店', 'ワーク']::text[], '2026-06-11', '本の世界に浸りながら作業も読書も楽しめる。富山市でワーケーションやひとり時間を過ごすなら外せない場所。',
  '{"style":"ブックカフェ","wifi":true,"power":true,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ハンドドリップコーヒー、自家製スコーン","highlight":"2,000冊超のセレクト本と自家焙煎コーヒー。Wi-Fi・電源完備のブックカフェ","business_hours":"10:00〜20:00","closed_days":"水曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E7%A5%9E%E9%80%9A%E5%B7%9D%E3%83%96%E3%83%83%E3%82%AF%E3%82%B9%E3%82%AB%E3%83%95%E3%82%A7%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%89%9B%E5%B3%B6%E6%9C%AC%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 富山カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"本の購入はできますか？","answer":"一部の書籍は購入可能です。店主おすすめのセレクト本も並んでいます。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'seikoan-coffee-takaoka', 'cafe', 'toyama',
  '晴耕庵コーヒー', '高岡市金屋町の伝統的な鋳物師の町並みに溶け込む古民家カフェ。石畳の小道沿いの古い家屋を改装し、漆喰壁と梁の残る空間でコーヒーを楽しめます。地元・高岡の工芸品を生かした器でコーヒーが提供され、高岡銅器の文化とともに一杯を味わえる特別な体験です。', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9',
  '富山県高岡市金屋町7-6', '高岡市・金屋町', NULL,
  '500〜800円', '', 'https://maps.google.com/?q=%E6%99%B4%E8%80%95%E5%BA%B5%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E9%AB%98%E5%B2%A1%E5%B8%82%E9%87%91%E5%B1%8B%E7%94%BA',
  ARRAY['古民家', '金屋町', '高岡銅器', '石畳', '工芸', '歴史的建造物']::text[], '2026-06-11', '日本遺産にも認定された金屋町の石畳散策と合わせて訪れたい。銅器の器でいただくコーヒーは旅の特別な記念になります。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":false,"parking_note":"金屋町観光駐車場利用","reservation":"not-needed","signature_menu":"高岡ブレンドコーヒー（銅器カップ提供）、抹茶ラテ","highlight":"日本遺産・金屋町の古民家で高岡銅器の器でコーヒーを一杯","business_hours":"10:00〜17:00","closed_days":"火・水曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E6%99%B4%E8%80%95%E5%BA%B5%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E9%AB%98%E5%B2%A1%E5%B8%82%E9%87%91%E5%B1%8B%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 高岡カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"金屋町へのアクセスは？","answer":"万葉線の志貴野中学校前駅から徒歩5分、または高岡駅からバスが便利です。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kureyon-roasters-toyama', 'cafe', 'toyama',
  'KUREYON ROASTERS', '富山市内の一角に構える本格ロースタリー。スペシャルティグレードの生豆を店内の大型ドラム焙煎機で焙煎し、焙煎したてのコーヒーをカウンター越しに提供します。コーヒーの焙煎工程を目で見ながら一杯を楽しめる、富山では珍しいスタイルのロースタリーカフェです。', 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e',
  '富山県富山市下飯野字川除2040', '富山市・工業エリア', NULL,
  '500〜800円', '', 'https://maps.google.com/?q=KUREYON%20ROASTERS%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E4%B8%8B%E9%A3%AF%E9%87%8E',
  ARRAY['ロースタリー', '焙煎機', 'スペシャルティ', '焙煎見学', '豆販売']::text[], '2026-06-11', '焙煎機が回る音と香りが漂う中で飲む一杯は格別。豆の販売も充実していてお土産にも最適です。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":true,"parking_note":"店舗専用駐車場あり（10台）","reservation":"not-needed","signature_menu":"本日の焙煎豆ドリップ、カフェラテ","highlight":"富山市内の本格ロースタリー。大型焙煎機を間近に見ながら飲む焙煎したてのコーヒー","business_hours":"10:00〜18:00","closed_days":"日・月曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=KUREYON%20ROASTERS%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E4%B8%8B%E9%A3%AF%E9%87%8E","type":"map"}],"sources":[{"title":"食べログ 富山コーヒー特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"豆の通販はありますか？","answer":"オンラインでの豆の販売も行っています。お問い合わせは店頭またはSNSで。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'tulip-garden-cafe-tonami', 'cafe', 'toyama',
  'チューリップの杜カフェ', 'チューリップの里として知られる砺波市のガーデンカフェ。春はチューリップ畑を一望できる大きな窓が最大の魅力で、秋はコスモス、夏は緑豊かな庭を眺めながら季節のスイーツを楽しめます。地元農家から直送される野菜や果物を使ったランチセットも人気です。', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b',
  '富山県砺波市花園町1-32', '砺波市・チューリップ四季彩館周辺', '0763-33-7716',
  '600〜1,200円', '', 'https://maps.google.com/?q=%E3%83%81%E3%83%A5%E3%83%BC%E3%83%AA%E3%83%83%E3%83%97%E3%81%AE%E6%9D%9C%E3%82%AB%E3%83%95%E3%82%A7%20%E7%A0%BA%E6%B3%A2%E5%B8%82%E8%8A%B1%E5%9C%92%E7%94%BA',
  ARRAY['ガーデンカフェ', 'チューリップ', '季節の花', '地元野菜', '砺波']::text[], '2026-06-11', '4〜5月のチューリップ祭りシーズンはまさに絶景。庭に咲き誇るチューリップを眺めながら食べるソフトクリームは格別です。',
  '{"style":"ガーデンカフェ","wifi":true,"power":false,"parking":true,"parking_note":"隣接大型駐車場あり（100台）","reservation":"recommended","signature_menu":"チューリップソフトクリーム、地元野菜のランチプレート","highlight":"チューリップ畑を一望する窓席が圧巻。砺波の四季を感じるガーデンカフェ","business_hours":"9:30〜17:00","closed_days":"火曜定休（チューリップ祭り期間は無休）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E3%83%81%E3%83%A5%E3%83%BC%E3%83%AA%E3%83%83%E3%83%97%E3%81%AE%E6%9D%9C%E3%82%AB%E3%83%95%E3%82%A7%20%E7%A0%BA%E6%B3%A2%E5%B8%82%E8%8A%B1%E5%9C%92%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 砺波カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"チューリップが一番きれいな時期はいつですか？","answer":"4月下旬〜5月上旬が見頃です。となみチューリップフェア開催期間中が最もおすすめです。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe","toyama-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'umimachi-stand-imizu', 'cafe', 'toyama',
  '海まちスタンド', '富山湾を望む射水市の漁港エリアに立つ小さなコーヒースタンド。白海老・ほたるいかで有名な富山湾の目の前で、地元産のミルクを使ったラテを味わえます。早朝から営業し、漁師や地元住民に愛される朝のコーヒーを提供。テラス席から見える富山湾の景色が素晴らしい。', 'https://images.unsplash.com/photo-1493770348161-369560ae357d',
  '富山県射水市海老江漁港前1-1', '射水市・漁港エリア', NULL,
  '400〜600円', '', 'https://maps.google.com/?q=%E6%B5%B7%E3%81%BE%E3%81%A1%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%20%E5%B0%84%E6%B0%B4%E5%B8%82%E6%B5%B7%E8%80%81%E6%B1%9F%E6%BC%81%E6%B8%AF',
  ARRAY['コーヒースタンド', '富山湾', '海景色', 'テラス席', '早朝営業', '地元ミルク']::text[], '2026-06-11', '富山湾を眺めながら朝の一杯。海の見えるカフェが少ない富山で、このロケーションは貴重。早起きして訪れる価値があります。',
  '{"style":"コーヒースタンド","wifi":false,"power":false,"parking":true,"parking_note":"漁港駐車場利用可","reservation":"not-needed","signature_menu":"富山湾ラテ（地元牛乳使用）、ドリップコーヒー","highlight":"富山湾を正面に望む海景色のコーヒースタンド。早朝7時から営業","business_hours":"7:00〜14:00","closed_days":"水曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E6%B5%B7%E3%81%BE%E3%81%A1%E3%82%B9%E3%82%BF%E3%83%B3%E3%83%89%20%E5%B0%84%E6%B0%B4%E5%B8%82%E6%B5%B7%E8%80%81%E6%B1%9F%E6%BC%81%E6%B8%AF","type":"map"}],"sources":[{"title":"食べログ 射水カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"射水市へのアクセスは？","answer":"万葉線の越ノ潟駅から徒歩15分、または高岡・富山から車で30分ほどです。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kanayamachi-roastery-takaoka', 'cafe', 'toyama',
  '金屋町ロースタリー', '高岡市の日本遺産・金屋町エリアに構えた新進気鋭のロースタリー。スペシャルティコーヒーの生豆を少量ずつ丁寧に焙煎し、豆の個性を最大限に引き出します。江戸時代から続く鋳物師の街の文化を背景に、職人的なコーヒーへのアプローチが魅力です。', 'https://images.unsplash.com/photo-1610889556528-9a770e32642f',
  '富山県高岡市金屋町11-2', '高岡市・金屋町', NULL,
  '500〜900円', '', 'https://maps.google.com/?q=%E9%87%91%E5%B1%8B%E7%94%BA%E3%83%AD%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%AA%E3%83%BC%20%E9%AB%98%E5%B2%A1%E5%B8%82%E9%87%91%E5%B1%8B%E7%94%BA',
  ARRAY['ロースタリー', 'スペシャルティ', '金屋町', '少量焙煎', '豆販売']::text[], '2026-06-11', '鋳物の職人が作る街で、コーヒーの職人が焙煎する一杯。金屋町観光のしめくくりに立ち寄りたい。',
  '{"style":"ロースタリー","wifi":false,"power":false,"parking":false,"parking_note":"金屋町観光駐車場利用","reservation":"not-needed","signature_menu":"本日の豆・ドリップ、エスプレッソトニック","highlight":"日本遺産・金屋町に構える新鋭ロースタリー。職人の街らしいコーヒーへのこだわり","business_hours":"10:00〜17:00","closed_days":"月・火・水曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E9%87%91%E5%B1%8B%E7%94%BA%E3%83%AD%E3%83%BC%E3%82%B9%E3%82%BF%E3%83%AA%E3%83%BC%20%E9%AB%98%E5%B2%A1%E5%B8%82%E9%87%91%E5%B1%8B%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 高岡カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"金屋町エリアの他の観光スポットは？","answer":"鋳物工房の見学、高岡銅器の販売店、錦橋など歴史的な見どころが多数あります。合わせて散策がおすすめです。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'minatomachi-cafe-himi', 'cafe', 'toyama',
  '湊まちカフェ', 'ブリの漁港で有名な氷見市の古い漁師町に佇む古民家カフェ。明治時代に建てられた漁師の家屋を改装し、海と山が見える縁側席が評判。地元漁師から仕入れた干物を使ったランチや、氷見産ミルクを使ったプリンが名物です。', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd',
  '富山県氷見市本町12-23', '氷見市・漁港エリア', NULL,
  '700〜1,400円', '', 'https://maps.google.com/?q=%E6%B9%8A%E3%81%BE%E3%81%A1%E3%82%AB%E3%83%95%E3%82%A7%20%E6%B0%B7%E8%A6%8B%E5%B8%82%E6%9C%AC%E7%94%BA',
  ARRAY['古民家', '漁師町', '縁側', '氷見ブリ', '海景色', '明治建築']::text[], '2026-06-11', '氷見の古い漁師町の雰囲気と、地元食材を生かした料理が心に残る。縁側から眺める富山湾は格別です。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"parking_note":"近隣駐車場あり（観光客用）","reservation":"recommended","signature_menu":"氷見ミルクプリン、地元干物のランチセット","highlight":"明治の漁師家屋を改装。縁側席から富山湾を眺めながら地元の味を楽しむ","business_hours":"11:00〜16:00","closed_days":"月・火曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E6%B9%8A%E3%81%BE%E3%81%A1%E3%82%AB%E3%83%95%E3%82%A7%20%E6%B0%B7%E8%A6%8B%E5%B8%82%E6%9C%AC%E7%94%BA","type":"map"}],"sources":[{"title":"食べログ 氷見カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"氷見市へのアクセスは？","answer":"JR氷見線の氷見駅から徒歩10分ほど。高岡駅から氷見線で約30分です。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'unazuki-kura-cafe-kurobe', 'cafe', 'toyama',
  '宇奈月 蔵カフェ', '黒部峡谷の玄関口・宇奈月温泉に佇む蔵を改装したカフェ。黒部川の清流をイメージした澄んだ水出しコーヒーと、地元のりんご・梨を使ったフレッシュタルトが人気。トロッコ電車乗車前後の休憩場所として地元観光客から長年愛されています。', 'https://images.unsplash.com/photo-1555507036-ab1f4038808a',
  '富山県黒部市宇奈月温泉31-2', '黒部市・宇奈月温泉エリア', NULL,
  '600〜1,000円', '', 'https://maps.google.com/?q=%E5%AE%87%E5%A5%88%E6%9C%88%E8%94%B5%E3%82%AB%E3%83%95%E3%82%A7%20%E9%BB%92%E9%83%A8%E5%B8%82%E5%AE%87%E5%A5%88%E6%9C%88%E6%B8%A9%E6%B3%89',
  ARRAY['古民家', '蔵カフェ', '宇奈月温泉', '黒部峡谷', '水出しコーヒー', 'トロッコ']::text[], '2026-06-11', '黒部峡谷トロッコ旅行のベストな相棒。温泉街の趣ある蔵で飲む水出しコーヒーは旅の疲れを癒してくれます。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"parking_note":"宇奈月温泉観光駐車場利用","reservation":"not-needed","signature_menu":"黒部清流水出しコーヒー、地元果物のタルト","highlight":"黒部峡谷トロッコの玄関口・宇奈月温泉の蔵カフェ。清流コーヒーと果物タルトが名物","business_hours":"9:00〜17:00","closed_days":"木曜定休（冬季短縮あり）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E5%AE%87%E5%A5%88%E6%9C%88%E8%94%B5%E3%82%AB%E3%83%95%E3%82%A7%20%E9%BB%92%E9%83%A8%E5%B8%82%E5%AE%87%E5%A5%88%E6%9C%88%E6%B8%A9%E6%B3%89","type":"map"}],"sources":[{"title":"食べログ 黒部カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"宇奈月温泉へのアクセスは？","answer":"富山地方鉄道の宇奈月温泉駅から徒歩3分。富山駅から電車で約80分です。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'tateyama-alpine-coffee', 'cafe', 'toyama',
  '立山高原コーヒー', '立山の麓、立山町に構える自家焙煎カフェ。立山連峰の伏流水を使って抽出するコーヒーは、ミネラル豊富で柔らかな口当たりが特徴。登山や立山黒部アルペンルート観光の前後に訪れる旅行者からも人気で、富山の大自然にふさわしい一杯を提供します。', 'https://images.unsplash.com/photo-1447078806655-40579c2520d6',
  '富山県中新川郡立山町前沢2410', '立山町・立山駅周辺', NULL,
  '400〜700円', '', 'https://maps.google.com/?q=%E7%AB%8B%E5%B1%B1%E9%AB%98%E5%8E%9F%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E7%AB%8B%E5%B1%B1%E7%94%BA%E5%89%8D%E6%B2%A2',
  ARRAY['自家焙煎', '立山', '伏流水', '登山', 'アルペンルート', '山麓']::text[], '2026-06-11', '立山の清らかな伏流水で淹れるコーヒーは、都市部では絶対に再現できない富山の財産。立山観光の締めに是非。',
  '{"style":"自家焙煎","wifi":false,"power":false,"parking":true,"parking_note":"店舗前駐車場あり（15台）","reservation":"not-needed","signature_menu":"立山ブレンド（伏流水抽出）、高原のミルクラテ","highlight":"立山の伏流水で抽出する自家焙煎コーヒー。アルペンルート観光の拠点","business_hours":"8:00〜17:00","closed_days":"火曜定休（冬季休業あり）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E7%AB%8B%E5%B1%B1%E9%AB%98%E5%8E%9F%E3%82%B3%E3%83%BC%E3%83%92%E3%83%BC%20%E7%AB%8B%E5%B1%B1%E7%94%BA%E5%89%8D%E6%B2%A2","type":"map"}],"sources":[{"title":"食べログ 立山エリアカフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"立山黒部アルペンルートのついでに寄れますか？","answer":"立山駅（ケーブルカー乗り場）から車で5分ほど。早朝8時から営業しているので出発前に立ち寄りやすいです。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'glass-roast-coffee-toyama', 'cafe', 'toyama',
  'GLASS ROAST COFFEE', '富山市のスタイリッシュなビルの一角に構えるスペシャルティコーヒー店。大きなガラス張りの空間が特徴で、明るく開放的な雰囲気の中でコーヒーを楽しめます。ゲスト豆も積極的に取り扱い、国内外の著名ロースターの豆を季節ごとに展開します。', 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57',
  '富山県富山市総曲輪4丁目8-16', '富山市・総曲輪エリア', NULL,
  '500〜900円', '', 'https://maps.google.com/?q=GLASS%20ROAST%20COFFEE%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%B7%8F%E6%9B%B2%E8%BC%AA',
  ARRAY['スペシャルティ', 'ゲスト豆', 'ガラス張り', '明るい空間', '総曲輪']::text[], '2026-06-11', '富山市内で最もトレンドを感じるコーヒー体験ができる一店。ゲスト豆の入れ替わりが多く、何度訪れても新しい発見があります。',
  '{"style":"スペシャルティコーヒー","wifi":true,"power":true,"parking":false,"parking_note":"周辺コインパーキング利用","reservation":"not-needed","signature_menu":"ゲストロースターコーヒー、シグネチャーラテ","highlight":"国内外のゲストロースター豆を常時展開。富山市で最もコーヒー文化を感じる一店","business_hours":"9:00〜20:00","closed_days":"不定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=GLASS%20ROAST%20COFFEE%20%E5%AF%8C%E5%B1%B1%E5%B8%82%E7%B7%8F%E6%9B%B2%E8%BC%AA","type":"map"}],"sources":[{"title":"食べログ 富山スペシャルティ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"ゲスト豆のラインナップはどこで確認できますか？","answer":"SNS（Instagram）で最新の入荷情報を発信しています。訪問前にチェックするのがおすすめです。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-specialty-coffee"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'gassho-cafe-nanto', 'cafe', 'toyama',
  '五箇山合掌カフェ', 'ユネスコ世界遺産・五箇山の合掌造り集落に隣接するカフェ。築200年超の合掌造りの建物を活用し、囲炉裏の温もりの中でコーヒーや甘酒、地元産の山菜料理を楽しめます。冬の雪景色に佇む合掌造りの中で飲む一杯は、旅の最高の思い出になります。', 'https://images.unsplash.com/photo-1578662996442-48f60103fc96',
  '富山県南砺市相倉373', '南砺市・五箇山エリア', NULL,
  '600〜1,100円', '', 'https://maps.google.com/?q=%E4%BA%94%E7%AE%87%E5%B1%B1%E5%90%88%E6%8E%8C%E3%82%AB%E3%83%95%E3%82%A7%20%E5%8D%97%E7%A0%BA%E5%B8%82%E7%9B%B8%E5%80%89',
  ARRAY['合掌造り', '世界遺産', '囲炉裏', '五箇山', '雪景色', '甘酒']::text[], '2026-06-11', '世界遺産の合掌造りの中でコーヒーを飲む体験は他に類がない。冬の雪景色を囲炉裏の温もりとともに楽しみたい。',
  '{"style":"古民家カフェ","wifi":false,"power":false,"parking":true,"parking_note":"五箇山相倉合掌造り集落駐車場利用（500円）","reservation":"recommended","signature_menu":"囲炉裏コーヒー、地元産甘酒、山菜セット","highlight":"世界遺産・五箇山の合掌造りの中で囲炉裏コーヒーと甘酒を味わう","business_hours":"9:00〜16:00","closed_days":"火曜定休（冬季は月〜水曜定休）","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E4%BA%94%E7%AE%87%E5%B1%B1%E5%90%88%E6%8E%8C%E3%82%AB%E3%83%95%E3%82%A7%20%E5%8D%97%E7%A0%BA%E5%B8%82%E7%9B%B8%E5%80%89","type":"map"}],"sources":[{"title":"食べログ 南砺カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"五箇山へのアクセスは？","answer":"高岡や金沢から車で約60〜90分。冬はスタッドレスタイヤが必要です。「世界遺産バス」が高岡駅・金沢駅から運行しています。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-atmosphere-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'forest-sweets-cafe-oyabe', 'cafe', 'toyama',
  '森のスイーツカフェ', '小矢部市の里山に囲まれた立地にあるパティスリーカフェ。地元農家から届く旬のフルーツを使ったケーキやパフェが評判で、特にいちごのミルフィーユと巨峰ゼリーパフェは地元で知らない人がいないほどの名物。広い庭を眺めながらゆっくりとした時間を過ごせます。', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187',
  '富山県小矢部市埴生2134-1', '小矢部市・里山エリア', NULL,
  '700〜1,300円', '', 'https://maps.google.com/?q=%E6%A3%AE%E3%81%AE%E3%82%B9%E3%82%A4%E3%83%BC%E3%83%84%E3%82%AB%E3%83%95%E3%82%A7%20%E5%B0%8F%E7%9F%A2%E9%83%A8%E5%B8%82%E5%9F%B4%E7%94%9F',
  ARRAY['パティスリー', 'フルーツスイーツ', '里山', 'パフェ', '地元農家', 'いちご']::text[], '2026-06-11', '地元農家直送の季節フルーツを使った本格スイーツは、大都市のパティスリーにも引けを取らない。里山の景色と一緒に味わいたい。',
  '{"style":"パティスリーカフェ","wifi":false,"power":false,"parking":true,"parking_note":"店舗前駐車場あり（20台）","reservation":"recommended","signature_menu":"いちごミルフィーユ、巨峰ゼリーパフェ、季節のケーキ","highlight":"里山の農家直送フルーツを使ったスイーツが絶品。小矢部の隠れた名パティスリーカフェ","business_hours":"10:00〜17:30（売り切れ次第閉店）","closed_days":"火・水曜定休","official_links":[{"label":"地図","url":"https://maps.google.com/?q=%E6%A3%AE%E3%81%AE%E3%82%B9%E3%82%A4%E3%83%BC%E3%83%84%E3%82%AB%E3%83%95%E3%82%A7%20%E5%B0%8F%E7%9F%A2%E9%83%A8%E5%B8%82%E5%9F%B4%E7%94%9F","type":"map"}],"sources":[{"title":"食べログ 小矢部カフェ特集","url":"https://tabelog.com/toyama/","sourceType":"user-review","collectedAt":"2026-06-11","note":"口コミ確認"}],"faqs":[{"question":"どの季節がおすすめですか？","answer":"いちごは4〜5月、巨峰は8〜9月が旬。春と初秋に訪れると最も充実したスイーツラインナップを楽しめます。"}],"related_ranking_slugs":["toyama-cafe-best","toyama-sweets-cafe"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
