  'kiyotsu-gorge-tunnel', 'leisure_spot', 'niigata',
  '清津峡渓谷トンネル', '日本三大峡谷の一つとして知られる清津峡を、全長のあるトンネルとアート空間「Tunnel of Light」から楽しめる十日町の定番スポットです。', NULL,
  '新潟県十日町市小出癸2119-2', '十日町市', '025-763-4800',
  '一般1,200円、小中学生500円目安', 'https://nakasato-kiyotsu.com/', 'https://maps.google.com/?q=%E6%B8%85%E6%B4%A5%E5%B3%A1%E6%B8%93%E8%B0%B7%E3%83%88%E3%83%B3%E3%83%8D%E3%83%AB%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E5%8D%81%E6%97%A5%E7%94%BA%E5%B8%82%E5%B0%8F%E5%87%BA%E7%99%B82119-2',
  ARRAY['絶景', '自然', 'アート', '写真', '予約日あり']::text[], '2026-06-08', '新潟レジャーの象徴として最初に置きたいスポット。混雑・予約日・冬季条件の確認導線を強く出すと実用性が上がります。',
  '{"kind":"outdoor","genre":"渓谷・アート","best_for":["カップル","写真目的","県外観光"],"highlight":"渓谷美とトンネル内の現代アートを同時に見られる。","parking":true,"parking_note":"周辺駐車場は混雑期に制限される場合があるため公式案内確認推奨。","business_hours":"8:30〜17:00（最終受付16:30）","closed_days":"通常は定休日なし。予約購入限定営業日などは公式確認。","official_links":[{"label":"公式サイト","url":"https://nakasato-kiyotsu.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%B8%85%E6%B4%A5%E5%B3%A1%E6%B8%93%E8%B0%B7%E3%83%88%E3%83%B3%E3%83%8D%E3%83%AB%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E5%8D%81%E6%97%A5%E7%94%BA%E5%B8%82%E5%B0%8F%E5%87%BA%E7%99%B82119-2","type":"map"}],"sources":[{"title":"清津峡 公式サイト","url":"https://nakasato-kiyotsu.com/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、営業時間、最終受付、入坑料、予約購入限定営業日の注意確認。"}],"faqs":[{"question":"清津峡は雨の日でも行けますか？","answer":"トンネル内から鑑賞できますが、現地までの移動や混雑、予約対象日は公式サイトで確認してください。"},{"question":"写真目的で行くなら何に注意すべきですか？","answer":"人気スポットのため、混雑時間帯を避ける計画が必要です。予約購入限定営業日もあります。"}],"related_ranking_slugs":["niigata-leisure-best","niigata-outdoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yuzawa-kogen-panorama-park', 'leisure_spot', 'niigata',
  '湯沢高原パノラマパーク', '湯沢高原ロープウェイで山上へ上がり、アルプの里や展望、カフェを組み合わせて過ごせる越後湯沢の山岳レジャーです。', NULL,
  '新潟県南魚沼郡湯沢町大字湯沢490', '湯沢町', '025-784-3326',
  'ロープウェイ往復込み大人3,500円目安', 'https://www.yuzawakogen.com/green/tickets/', 'https://maps.google.com/?q=%E6%B9%AF%E6%B2%A2%E9%AB%98%E5%8E%9F%E3%83%AD%E3%83%BC%E3%83%97%E3%82%A6%E3%82%A7%E3%82%A4%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E5%8D%97%E9%AD%9A%E6%B2%BC%E9%83%A1%E6%B9%AF%E6%B2%A2%E7%94%BA%E6%B9%AF%E6%B2%A2490',
  ARRAY['ロープウェイ', '展望', '高原', '季節営業', '駅近']::text[], '2026-06-08', '新幹線旅行と相性が良い。天候・整備休業・季節営業の影響を受けるため、行程作成ページでは公式確認を前提にします。',
  '{"kind":"outdoor","genre":"ロープウェイ・高原","best_for":["家族","カップル","越後湯沢旅行"],"highlight":"ロープウェイ、山上散策、カフェを一つの行程にしやすい。","parking":true,"parking_note":"湯沢高原公式のアクセス・駐車案内確認推奨。","business_hours":"夏期の山麓駅舎 8:20〜17:00、ロープウェイ 8:40〜16:40目安","closed_days":"整備休業期間あり。営業日は公式確認。","official_links":[{"label":"料金・営業時間","url":"https://www.yuzawakogen.com/green/tickets/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%B9%AF%E6%B2%A2%E9%AB%98%E5%8E%9F%E3%83%AD%E3%83%BC%E3%83%97%E3%82%A6%E3%82%A7%E3%82%A4%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E5%8D%97%E9%AD%9A%E6%B2%BC%E9%83%A1%E6%B9%AF%E6%B2%A2%E7%94%BA%E6%B9%AF%E6%B2%A2490","type":"map"}],"sources":[{"title":"湯沢高原 料金・営業時間","url":"https://www.yuzawakogen.com/green/tickets/","sourceType":"official","collectedAt":"2026-06-08","note":"営業期間、ロープウェイ運行時間、料金、整備休業注意確認。"}],"faqs":[{"question":"湯沢高原は通年で同じように遊べますか？","answer":"季節営業と整備休業があります。訪問前に営業日と運行状況を確認してください。"},{"question":"車なし旅行にも向きますか？","answer":"越後湯沢駅周辺から組み込みやすく、車なし旅の候補にしやすいスポットです。"}],"related_ranking_slugs":["niigata-leisure-best","niigata-outdoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yahiko-ropeway', 'leisure_spot', 'niigata',
  '弥彦山ロープウェイ', '弥彦山の山麓と山頂側を結ぶロープウェイ。彌彦神社や弥彦公園と合わせて、半日観光に組み込みやすいスポットです。', NULL,
  '新潟県西蒲原郡弥彦村弥彦2898', '弥彦村', '0256-94-4141',
  '料金は公式確認', 'https://www.vill.yahiko.niigata.jp/culture/?content=469', 'https://maps.google.com/?q=%E5%BC%A5%E5%BD%A6%E5%B1%B1%E3%83%AD%E3%83%BC%E3%83%97%E3%82%A6%E3%82%A7%E3%82%A4%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E8%A5%BF%E8%92%B2%E5%8E%9F%E9%83%A1%E5%BC%A5%E5%BD%A6%E6%9D%91%E5%BC%A5%E5%BD%A62898',
  ARRAY['展望', 'ロープウェイ', '神社周辺', '半日観光', '弥彦']::text[], '2026-06-08', '弥彦エリア全体の回遊導線を作る中心。紅葉、神社参拝、温泉を合わせた記事に展開しやすいです。',
  '{"kind":"outdoor","genre":"ロープウェイ・展望","best_for":["カップル","家族","日帰り観光"],"highlight":"彌彦神社周辺とセットで計画しやすい山上展望。","parking":true,"parking_note":"弥彦公園・彌彦神社周辺の駐車場計画と合わせて確認推奨。","business_hours":"9:00〜17:00目安","closed_days":"無休掲載あり。運休・整備日は公式確認。","official_links":[{"label":"弥彦村 観光案内","url":"https://www.vill.yahiko.niigata.jp/culture/?content=469","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%BC%A5%E5%BD%A6%E5%B1%B1%E3%83%AD%E3%83%BC%E3%83%97%E3%82%A6%E3%82%A7%E3%82%A4%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E8%A5%BF%E8%92%B2%E5%8E%9F%E9%83%A1%E5%BC%A5%E5%BD%A6%E6%9D%91%E5%BC%A5%E5%BD%A62898","type":"map"}],"sources":[{"title":"弥彦村 弥彦山ロープウェイ","url":"https://www.vill.yahiko.niigata.jp/culture/?content=469","sourceType":"government","collectedAt":"2026-06-08","note":"弥彦村の観光ページでスポット確認。"},{"title":"トクトククーポン 弥彦山ロープウェイ","url":"https://tokutoku-coupon.jp/stores/473/detail","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所、電話、営業時間、無休掲載の補助確認。"}],"faqs":[{"question":"弥彦山ロープウェイは何と組み合わせると良いですか？","answer":"彌彦神社、弥彦公園、温泉街と合わせると半日から1日行程にしやすいです。"},{"question":"天候の影響はありますか？","answer":"ロープウェイは気象条件や整備で変更される可能性があります。訪問前に運行状況を確認してください。"}],"related_ranking_slugs":["niigata-leisure-best","niigata-outdoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'echigo-hillside-park', 'leisure_spot', 'niigata',
  '国営越後丘陵公園', '長岡市の国営公園。花、芝生広場、遊具、季節イベントを組み合わせやすく、家族の外遊び候補として強いスポットです。', NULL,
  '新潟県長岡市宮本東方町字三ツ又1950-1', '長岡市', '0258-47-8001',
  '入園料・駐車料金は公式確認', 'https://echigo-park.jp/', 'https://maps.google.com/?q=%E5%9B%BD%E5%96%B6%E8%B6%8A%E5%BE%8C%E4%B8%98%E9%99%B5%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AE%AE%E6%9C%AC%E6%9D%B1%E6%96%B9%E7%94%BA%E4%B8%89%E3%83%84%E5%8F%881950-1',
  ARRAY['公園', '花', '遊具', '家族', '季節イベント']::text[], '2026-06-08', '家族向けランキングの軸になる大型公園。イベント時期ごとの記事化に向いています。',
  '{"kind":"outdoor","genre":"公園・花・遊具","best_for":["家族","ピクニック","外遊び"],"highlight":"広い公園で、花の季節イベントと外遊びをまとめられる。","parking":true,"parking_note":"公式サイトで駐車場・イベント時の案内確認推奨。","business_hours":"時期により変動。公式開園情報を確認。","closed_days":"時期により変動。公式開園情報を確認。","official_links":[{"label":"公式サイト","url":"https://echigo-park.jp/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%9B%BD%E5%96%B6%E8%B6%8A%E5%BE%8C%E4%B8%98%E9%99%B5%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AE%AE%E6%9C%AC%E6%9D%B1%E6%96%B9%E7%94%BA%E4%B8%89%E3%83%84%E5%8F%881950-1","type":"map"}],"sources":[{"title":"国営越後丘陵公園 公式","url":"https://echigo-park.jp/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、公式開園情報、季節イベントの確認元。"},{"title":"にいがた観光ナビ 国営越後丘陵公園","url":"https://niigata-kankou.or.jp/spot/5957","sourceType":"tourism","collectedAt":"2026-06-08","note":"観光スポットとしての掲載確認。"}],"faqs":[{"question":"国営越後丘陵公園は子ども連れ向きですか？","answer":"広い公園、遊具、季節イベントを組み合わせやすく、家族向け候補として整理しています。"},{"question":"営業時間は固定ですか？","answer":"開園時間や休園日は季節・イベントで変動するため、公式サイトの開園情報を確認してください。"}],"related_ranking_slugs":["niigata-outdoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'shinano-river-water-shuttle', 'leisure_spot', 'niigata',
  '信濃川ウォーターシャトル', 'みなとぴあ、朱鷺メッセ、萬代橋、新潟ふるさと村などを結ぶ水上バス。新潟市中心部の移動と観光を同時に楽しめます。', NULL,
  '新潟市内各乗船場', '新潟市中央区', '025-227-5200',
  'シャトル便 大人500円〜1,200円、周遊便 大人1,400円〜1,800円目安', 'https://www.nvcb.or.jp/spot/detail_1158.html', 'https://maps.google.com/?q=%E4%BF%A1%E6%BF%83%E5%B7%9D%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%88%E3%83%AB%20%E4%B8%87%E4%BB%A3%E3%82%B7%E3%83%86%E3%82%A4',
  ARRAY['乗り物', '信濃川', '市内観光', '周遊', '車なし']::text[], '2026-06-08', '移動そのものを体験化できるため、車なし観光や市内半日コースの記事で強い導線になります。',
  '{"kind":"outdoor","genre":"水上バス・クルーズ","best_for":["車なし旅行","カップル","親子"],"highlight":"水上移動で萬代橋や信濃川沿いの景観を楽しめる。","parking":false,"parking_note":"乗船場ごとに周辺駐車場・公共交通を確認。","business_hours":"運航日・時刻は公式確認","closed_days":"運航日程は公式確認","official_links":[{"label":"新潟市観光ガイド","url":"https://www.nvcb.or.jp/spot/detail_1158.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%BF%A1%E6%BF%83%E5%B7%9D%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BF%E3%83%BC%E3%82%B7%E3%83%A3%E3%83%88%E3%83%AB%20%E4%B8%87%E4%BB%A3%E3%82%B7%E3%83%86%E3%82%A4","type":"map"}],"sources":[{"title":"新潟市観光ガイド 信濃川ウォーターシャトル","url":"https://www.nvcb.or.jp/spot/detail_1158.html","sourceType":"tourism","collectedAt":"2026-06-08","note":"乗船場、電話、料金、ルート概要確認。"}],"faqs":[{"question":"信濃川ウォーターシャトルは移動手段として使えますか？","answer":"みなとぴあ、朱鷺メッセ、萬代橋、新潟ふるさと村などを結ぶため、観光移動にも使いやすいです。"},{"question":"運航時刻は固定ですか？","answer":"運航日や便は変わるため、公式サイトで最新時刻を確認してください。"}],"related_ranking_slugs":["niigata-leisure-best","niigata-outdoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'marinepia-nihonkai', 'leisure_spot', 'niigata',
  '新潟市水族館 マリンピア日本海', '日本海沿いにある新潟市の水族館。屋内展示と屋外エリアを組み合わせられ、雨の日や家族のおでかけ候補として使いやすい施設です。', NULL,
  '新潟県新潟市中央区西船見町5932-445', '新潟市中央区', '025-222-7500',
  '大人1,500円、小中学生600円、幼児200円、3歳まで無料', 'https://www.marinepia.or.jp/info/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E5%B8%82%E6%B0%B4%E6%97%8F%E9%A4%A8%20%E3%83%9E%E3%83%AA%E3%83%B3%E3%83%94%E3%82%A2%E6%97%A5%E6%9C%AC%E6%B5%B7%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E8%88%B9%E8%A6%8B%E7%94%BA5932-445',
  ARRAY['屋内', '水族館', '家族', '雨の日', '駐車場無料']::text[], '2026-06-08', '雨の日・家族向けの中心施設。新潟市内観光の定番として検索導線を厚くしたいスポットです。',
  '{"kind":"indoor","genre":"水族館","best_for":["家族","雨の日","新潟市観光"],"highlight":"水族館展示、ショー・解説、海沿い散策を組み合わせられる。","parking":true,"parking_note":"公式アクセスでは無料駐車場670台と掲載。","business_hours":"9:00〜17:00（券売16:30まで）","closed_days":"12月29日〜1月1日、3月の第1木曜と翌日","official_links":[{"label":"利用案内","url":"https://www.marinepia.or.jp/info/","type":"website"},{"label":"アクセス","url":"https://www.marinepia.or.jp/access/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E5%B8%82%E6%B0%B4%E6%97%8F%E9%A4%A8%20%E3%83%9E%E3%83%AA%E3%83%B3%E3%83%94%E3%82%A2%E6%97%A5%E6%9C%AC%E6%B5%B7%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E8%88%B9%E8%A6%8B%E7%94%BA5932-445","type":"map"}],"sources":[{"title":"マリンピア日本海 ご利用案内","url":"https://www.marinepia.or.jp/info/","sourceType":"official","collectedAt":"2026-06-08","note":"開館時間、休館日、料金確認。"},{"title":"マリンピア日本海 アクセス","url":"https://www.marinepia.or.jp/access/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、無料駐車場台数確認。"}],"faqs":[{"question":"マリンピア日本海は雨の日でも楽しめますか？","answer":"屋内展示が中心のため、雨の日候補として使いやすい施設です。屋外エリアもあるため天候に合わせて回り方を調整してください。"},{"question":"駐車場はありますか？","answer":"公式アクセスでは無料駐車場670台と掲載されています。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'niigata-science-museum', 'leisure_spot', 'niigata',
  '新潟県立自然科学館', '自然科学、生活科学、プラネタリウムなどを扱う参加・体験型の科学館。雨の日や子どもの学習系レジャーに向きます。', NULL,
  '新潟県新潟市中央区女池南3丁目1番1号', '新潟市中央区', '025-283-3331',
  '大人580円、小中学生100円、未就学児無料。プラネタリウム別料金あり', 'https://www.sciencemuseum.jp/guide/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6%E9%A4%A8%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%A5%B3%E6%B1%A0%E5%8D%973%E4%B8%81%E7%9B%AE1%E7%95%AA1%E5%8F%B7',
  ARRAY['屋内', '科学館', 'プラネタリウム', '学習', '駐車場無料']::text[], '2026-06-08', '雨の日・学習・プラネタリウムの検索意図を拾えるスポット。新潟市中央区の屋内回遊で使いやすいです。',
  '{"kind":"indoor","genre":"科学館・プラネタリウム","best_for":["家族","雨の日","小学生"],"highlight":"展示とプラネタリウムを組み合わせて半日過ごしやすい。","parking":true,"parking_note":"公式では無料駐車場250台完備と掲載。","business_hours":"平日9:30〜16:30、土日祝・夏期9:30〜17:00","closed_days":"毎週火曜、年末年始ほか","official_links":[{"label":"ご利用案内","url":"https://www.sciencemuseum.jp/guide/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6%E9%A4%A8%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%A5%B3%E6%B1%A0%E5%8D%973%E4%B8%81%E7%9B%AE1%E7%95%AA1%E5%8F%B7","type":"map"}],"sources":[{"title":"新潟県立自然科学館 ご利用案内","url":"https://www.sciencemuseum.jp/guide/","sourceType":"official","collectedAt":"2026-06-08","note":"開館時間、休館日、料金、住所、電話、駐車場確認。"}],"faqs":[{"question":"自然科学館は小学生向けですか？","answer":"参加・体験型展示やプラネタリウムがあり、小学生の学習系レジャー候補として扱いやすい施設です。"},{"question":"プラネタリウムは入館料に含まれますか？","answer":"公式案内では入館料に加えてプラネタリウム観覧料が設定されています。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'niitsu-railway-museum', 'leisure_spot', 'niigata',
  '新潟市新津鉄道資料館', '鉄道の街として栄えた新津の鉄道文化を保存・公開する資料館。屋外車両展示もあり、鉄道好きの親子に向くスポットです。', NULL,
  '新潟県新潟市秋葉区新津東町2-5-6', '新潟市秋葉区', '0250-24-5700',
  '一般390円、高校・大学生260円、小中学生130円目安', 'https://niigata-kankou.or.jp/spot/5615', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E5%B8%82%E6%96%B0%E6%B4%A5%E9%89%84%E9%81%93%E8%B3%87%E6%96%99%E9%A4%A8%20%E6%96%B0%E6%BD%9F%E5%B8%82%E7%A7%8B%E8%91%89%E5%8C%BA%E6%96%B0%E6%B4%A5%E6%9D%B1%E7%94%BA2-5-6',
  ARRAY['屋内', '鉄道', '資料館', '親子', '駐車場無料']::text[], '2026-06-08', '水族館・科学館とは違う屋内軸として有効。秋葉区の地域導線も作れます。',
  '{"kind":"indoor","genre":"鉄道資料館","best_for":["鉄道好き","親子","雨の日"],"highlight":"新津の鉄道文化と屋外車両展示を見られる。","parking":true,"parking_note":"にいがた観光ナビでは普通車30台無料と掲載。","business_hours":"9:30〜17:00（入館16:30まで）","closed_days":"火曜、12月28日〜1月3日ほか","official_links":[{"label":"にいがた観光ナビ","url":"https://niigata-kankou.or.jp/spot/5615","type":"website"},{"label":"公式サイト","url":"https://www.ncnrm.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E5%B8%82%E6%96%B0%E6%B4%A5%E9%89%84%E9%81%93%E8%B3%87%E6%96%99%E9%A4%A8%20%E6%96%B0%E6%BD%9F%E5%B8%82%E7%A7%8B%E8%91%89%E5%8C%BA%E6%96%B0%E6%B4%A5%E6%9D%B1%E7%94%BA2-5-6","type":"map"}],"sources":[{"title":"にいがた観光ナビ 新潟市新津鉄道資料館","url":"https://niigata-kankou.or.jp/spot/5615","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、アクセス、駐車場、営業時間、休館日、料金、電話確認。"},{"title":"新津鉄道資料館 公式","url":"https://www.ncnrm.com/","sourceType":"official","collectedAt":"2026-06-08","note":"公式サイト確認。"}],"faqs":[{"question":"新津鉄道資料館は鉄道好き以外でも楽しめますか？","answer":"鉄道文化や屋外車両展示を見られるため、親子のおでかけや地域学習の候補として使いやすいです。"},{"question":"週末の子ども料金に注意点はありますか？","answer":"にいがた観光ナビでは土日祝は中学生以下無料と掲載されていますが、最新条件は公式案内を確認してください。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'niigata-furusato-mura', 'leisure_spot', 'niigata',
  '新潟ふるさと村', '新潟の観光情報、歴史文化展示、特産品、飲食をまとめて楽しめる複合施設。雨の日やお土産探しにも使いやすいスポットです。', NULL,
  '新潟県新潟市西区山田2307', '新潟市西区', '025-230-3030',
  '入館無料', 'https://www.city.niigata.lg.jp/nishi/shisetsu/yoka/furusatomura.html', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E3%81%B5%E3%82%8B%E3%81%95%E3%81%A8%E6%9D%91%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%B1%B1%E7%94%B02307',
  ARRAY['屋内', '物産', '観光情報', 'お土産', '駐車場無料']::text[], '2026-06-08', '観光情報と物産が揃うため、旅の初日・最終日どちらにも置きやすい。ウォーターシャトルとの接続も記事化しやすいです。',
  '{"kind":"hybrid","genre":"観光情報・物産・展示","best_for":["家族","雨の日","お土産"],"highlight":"観光情報、展示、物産、飲食を一か所で回れる。","parking":true,"parking_note":"新潟市公式では大駐車場400台と掲載。","business_hours":"アピール館9:00〜17:00、バザール館9:30〜17:30目安","closed_days":"無休","official_links":[{"label":"新潟市 施設案内","url":"https://www.city.niigata.lg.jp/nishi/shisetsu/yoka/furusatomura.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E3%81%B5%E3%82%8B%E3%81%95%E3%81%A8%E6%9D%91%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%B1%B1%E7%94%B02307","type":"map"}],"sources":[{"title":"新潟市 新潟ふるさと村","url":"https://www.city.niigata.lg.jp/nishi/shisetsu/yoka/furusatomura.html","sourceType":"government","collectedAt":"2026-06-08","note":"所在地、電話、開館時間、休館日、駐車場、料金、施設概要確認。"}],"faqs":[{"question":"新潟ふるさと村は無料で入れますか？","answer":"新潟市公式では料金無料と掲載されています。飲食や買い物は別途費用がかかります。"},{"question":"雨の日の観光に向きますか？","answer":"屋内の展示、観光情報、物産、飲食を組み合わせられるため、雨の日候補として使いやすいです。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ikutopia-shoku-hana', 'leisure_spot', 'niigata',
  'いくとぴあ食花', '食育・花育センター、こども創造センター、動物ふれあいセンター、キラキラガーデンなどを含む複合型の体験施設です。', NULL,
  '新潟県新潟市中央区清五郎401', '新潟市中央区', '025-282-4181',
  '施設・体験により異なる', 'https://www.ikutopia.com/', 'https://maps.google.com/?q=%E3%81%84%E3%81%8F%E3%81%A8%E3%81%B4%E3%81%82%E9%A3%9F%E8%8A%B1%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B8%85%E4%BA%94%E9%83%8E401',
  ARRAY['複合施設', '子ども', '花', '動物ふれあい', '屋内外']::text[], '2026-06-08', '家族向け・子ども向けカテゴリを拡張する時の柱。施設ごとに営業時間が違うため、詳細ページで確認導線を強く出します。',
  '{"kind":"hybrid","genre":"食育・花育・体験","best_for":["家族","未就学児","雨の日"],"highlight":"屋内外の複数施設を、子どもの年齢や天候に合わせて選べる。","parking":true,"parking_note":"公式では90分まで無料、以降有料の駐車場案内あり。","business_hours":"主な施設は9:00〜17:00目安。施設により異なる。","closed_days":"不定休。施設により異なる。","official_links":[{"label":"公式サイト","url":"https://www.ikutopia.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%84%E3%81%8F%E3%81%A8%E3%81%B4%E3%81%82%E9%A3%9F%E8%8A%B1%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B8%85%E4%BA%94%E9%83%8E401","type":"map"}],"sources":[{"title":"いくとぴあ食花 公式","url":"https://www.ikutopia.com/","sourceType":"official","collectedAt":"2026-06-08","note":"施設一覧、主な営業時間、不定休、駐車場料金確認。"}],"faqs":[{"question":"いくとぴあ食花は屋内施設ですか？","answer":"屋内施設と屋外施設が混在しています。天候や年齢に合わせて施設を選びやすい複合施設です。"},{"question":"営業時間は全施設共通ですか？","answer":"施設により休業日・営業時間が異なります。公式サイトの施設一覧を確認してください。"}],"related_ranking_slugs":["niigata-family-rainyday","niigata-indoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'view-fukushimagata', 'leisure_spot', 'niigata',
  '水の駅 ビュー福島潟', '福島潟を一望できる展望施設。潟の自然、野鳥、地域文化を学べる展示があり、北区の自然観察と屋内学習をつなげやすい公共系スポットです。', NULL,
  '新潟県新潟市北区前新田乙493', '新潟市北区', '025-387-1491',
  '1〜3階無料、有料ゾーンあり', 'https://view-fukushimagata.niigata.jp/visit/', 'https://maps.google.com/?q=%E6%B0%B4%E3%81%AE%E9%A7%85%20%E3%83%93%E3%83%A5%E3%83%BC%E7%A6%8F%E5%B3%B6%E6%BD%9F%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8C%97%E5%8C%BA%E5%89%8D%E6%96%B0%E7%94%B0%E4%B9%99493',
  ARRAY['公共系', '展望', '自然観察', '野鳥', '雨の日']::text[], '2026-06-08', '自然観察と屋内展示をまたぐため、雨の日・自由研究・野鳥観察の導線に使えます。新潟市北区の公共スポットとして厚みを作れます。',
  '{"kind":"hybrid","genre":"自然観察・展望","best_for":["親子","自然観察","雨の日"],"highlight":"展望室と映像展示で、福島潟の自然を屋内から学べる。","parking":true,"parking_note":"公式では普通車120台、大型車5台、思いやり駐車場2台と掲載。","business_hours":"9:00〜17:00（入館は閉館30分前まで）","closed_days":"月曜（休日の場合は翌日）、年末年始12月28日〜1月4日","official_links":[{"label":"公式 ご利用案内","url":"https://view-fukushimagata.niigata.jp/visit/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%B0%B4%E3%81%AE%E9%A7%85%20%E3%83%93%E3%83%A5%E3%83%BC%E7%A6%8F%E5%B3%B6%E6%BD%9F%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8C%97%E5%8C%BA%E5%89%8D%E6%96%B0%E7%94%B0%E4%B9%99493","type":"map"}],"sources":[{"title":"ビュー福島潟 ご利用案内","url":"https://view-fukushimagata.niigata.jp/visit/","sourceType":"official","collectedAt":"2026-06-08","note":"開館時間、休館日、駐車場、住所、電話、施設概要確認。"}],"faqs":[{"question":"ビュー福島潟は屋内施設ですか？","answer":"展望・展示は屋内で楽しめます。福島潟周辺の自然観察と組み合わせる場合は天候に合わせて計画してください。"},{"question":"無料で利用できますか？","answer":"公式案内では1階から3階は無料ゾーン、4階から7階は有料ゾーンとされています。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'niigata-botanical-garden', 'leisure_spot', 'niigata',
  '新潟県立植物園', '国内最大級の熱帯植物ドームや企画展示を備える県立植物園。屋外園地と観賞温室を組み合わせて、季節を問わず植物に触れられます。', NULL,
  '新潟県新潟市秋葉区金津186', '新潟市秋葉区', '0250-24-6465',
  '屋外園地無料、観賞温室 大人700円・高校生/学生300円・小中学生100円目安', 'https://niigata-kankou.or.jp/spot/5621', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E6%A4%8D%E7%89%A9%E5%9C%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E7%A7%8B%E8%91%89%E5%8C%BA%E9%87%91%E6%B4%A5186',
  ARRAY['公共系', '植物園', '温室', '自由研究', '駐車場無料']::text[], '2026-06-08', '屋内温室と屋外園地を両方持つため、雨の日と晴天の両方に展開できます。秋葉区の自然・学習系スポットとして有効です。',
  '{"kind":"hybrid","genre":"植物園・温室","best_for":["親子","雨の日","植物好き"],"highlight":"熱帯植物ドームと企画展示で、屋内でも植物観察ができる。","parking":true,"parking_note":"にいがた観光ナビでは普通車340台無料、大型車ありと掲載。","business_hours":"9:30〜16:30（入館締切16:00）","closed_days":"火曜（祝日の場合は水曜）、年末年始、展示替え臨時休館あり","official_links":[{"label":"にいがた観光ナビ","url":"https://niigata-kankou.or.jp/spot/5621","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E6%A4%8D%E7%89%A9%E5%9C%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E7%A7%8B%E8%91%89%E5%8C%BA%E9%87%91%E6%B4%A5186","type":"map"}],"sources":[{"title":"にいがた観光ナビ 新潟県立植物園","url":"https://niigata-kankou.or.jp/spot/5621","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、営業時間、休館日、料金、駐車場、施設特徴確認。"}],"faqs":[{"question":"新潟県立植物園は雨の日でも楽しめますか？","answer":"観賞温室や展示があるため雨の日候補にできます。屋外園地を回る場合は天候に合わせて調整してください。"},{"question":"屋外園地も有料ですか？","answer":"にいがた観光ナビでは屋外園地は無料、観賞温室は入館料が必要と掲載されています。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yahiko-park', 'leisure_spot', 'niigata',
  '弥彦公園', '弥彦駅近くの公園。桜、ホタル、紅葉など季節ごとの見どころがあり、弥彦山ロープウェイや彌彦神社と合わせて回りやすい公共系スポットです。', NULL,
  '新潟県西蒲原郡弥彦村弥彦667-1', '弥彦村', NULL,
  '入園無料目安', 'https://niigata-kankou.or.jp/spot/7482', 'https://maps.google.com/?q=%E5%BC%A5%E5%BD%A6%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E8%A5%BF%E8%92%B2%E5%8E%9F%E9%83%A1%E5%BC%A5%E5%BD%A6%E6%9D%91%E5%BC%A5%E5%BD%A6667-1',
  ARRAY['公共系', '公園', '紅葉', '桜', '駅近']::text[], '2026-06-08', '既存の弥彦山ロープウェイと相互導線にしやすいスポット。季節イベント・紅葉記事の核になります。',
  '{"kind":"outdoor","genre":"公園・紅葉・桜","best_for":["散策","カップル","半日観光"],"highlight":"弥彦駅徒歩圏で、季節の花や紅葉を見ながら散策できる。","parking":true,"parking_note":"にいがた観光ナビでは普通車2,000台掲載。紅葉期などは有料・混雑あり。","business_hours":"終日開放","closed_days":"なし","official_links":[{"label":"にいがた観光ナビ","url":"https://niigata-kankou.or.jp/spot/7482","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%BC%A5%E5%BD%A6%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E7%9C%8C%E8%A5%BF%E8%92%B2%E5%8E%9F%E9%83%A1%E5%BC%A5%E5%BD%A6%E6%9D%91%E5%BC%A5%E5%BD%A6667-1","type":"map"}],"sources":[{"title":"にいがた観光ナビ 弥彦公園","url":"https://niigata-kankou.or.jp/spot/7482","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、アクセス、駐車場、終日開放、桜・ホタル・紅葉情報確認。"}],"faqs":[{"question":"弥彦公園は駅から近いですか？","answer":"にいがた観光ナビではJR弥彦線 弥彦駅より徒歩1分と掲載されています。"},{"question":"紅葉時期は駐車場に注意が必要ですか？","answer":"10月下旬から11月下旬は公園周辺駐車場が有料になる掲載があります。混雑も想定して計画してください。"}],"related_ranking_slugs":["niigata-outdoor-leisure","niigata-leisure-best"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kodomo-shizen-okoku', 'leisure_spot', 'niigata',
  '新潟県立こども自然王国', '柏崎市高柳町にある県立の子ども向け自然体験施設。キャンプ、工作、カヌー、自然観察など、里山での体験メニューを組み合わせられます。', NULL,
  '新潟県柏崎市高柳町高尾30-33', '柏崎市', '0257-41-3355',
  '入館無料、体験・宿泊・入浴は別料金', 'https://niigata-kankou.or.jp/spot/6047', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E3%81%93%E3%81%A9%E3%82%82%E8%87%AA%E7%84%B6%E7%8E%8B%E5%9B%BD%20%E6%9F%8F%E5%B4%8E%E5%B8%82%E9%AB%98%E6%9F%B3%E7%94%BA%E9%AB%98%E5%B0%BE30-33',
  ARRAY['公共系', '子ども', '自然体験', 'キャンプ', '工作']::text[], '2026-06-08', '子ども向けの体験コンテンツを増やす時の強い軸。将来はキャンプ・夏休み・自由研究記事に広げやすいです。',
  '{"kind":"hybrid","genre":"自然体験・キャンプ","best_for":["子連れ","自然体験","宿泊"],"highlight":"自然体験、工作、キャンプ、日帰り入浴まで子ども向け体験が広い。","parking":true,"parking_note":"にいがた観光ナビでは普通車200台と掲載。","business_hours":"9:00〜17:00（最終入場16:30）目安。施設により異なる","closed_days":"月曜（月曜が祝日の場合は翌日）","official_links":[{"label":"にいがた観光ナビ","url":"https://niigata-kankou.or.jp/spot/6047","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E7%AB%8B%E3%81%93%E3%81%A9%E3%82%82%E8%87%AA%E7%84%B6%E7%8E%8B%E5%9B%BD%20%E6%9F%8F%E5%B4%8E%E5%B8%82%E9%AB%98%E6%9F%B3%E7%94%BA%E9%AB%98%E5%B0%BE30-33","type":"map"}],"sources":[{"title":"にいがた観光ナビ 新潟県立こども自然王国","url":"https://niigata-kankou.or.jp/spot/6047","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、営業時間、休館日、駐車場、体験メニュー、料金確認。"}],"faqs":[{"question":"こども自然王国は日帰りでも使えますか？","answer":"入館無料で体験メニューや日帰り入浴の掲載があります。内容や営業日は施設により異なるため公式確認が必要です。"},{"question":"キャンプや宿泊もできますか？","answer":"にいがた観光ナビではキャンプや本館宿泊の料金掲載があります。予約条件は公式情報を確認してください。"}],"related_ranking_slugs":["niigata-family-rainyday","niigata-outdoor-leisure"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'aqua-park-niigata', 'leisure_spot', 'niigata',
  'アクアパークにいがた', '新潟市西区の温水施設。清掃センターの余熱を利用したプール・浴室系施設として、天候を問わず体を動かしたい日に使いやすいスポットです。', NULL,
  '新潟県新潟市西区笠木3629番地1', '新潟市西区', '025-264-6400',
  '料金は公式確認', 'https://niigata-kankou.or.jp/spot/11337', 'https://maps.google.com/?q=%E3%82%A2%E3%82%AF%E3%82%A2%E3%83%91%E3%83%BC%E3%82%AF%E3%81%AB%E3%81%84%E3%81%8C%E3%81%9F%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E7%AC%A0%E6%9C%A83629%E7%95%AA%E5%9C%B01',
  ARRAY['公共系', '屋内', 'プール', '温水施設', '駐車場あり']::text[], '2026-06-08', '観光というより日常レジャー寄りですが、雨の日・健康・親子プールの検索意図を拾えます。地元利用の記事に向きます。',
  '{"kind":"indoor","genre":"温水プール・健康施設","best_for":["親子","雨の日","運動"],"highlight":"屋内温水施設として、雨の日や冬場でも体を動かしやすい。","parking":true,"parking_note":"にいがた観光ナビでは普通車200台、大型車利用可と掲載。","business_hours":"10:00〜22:00（5〜9月の土日祝・7月25日〜8月31日は9:00〜22:00）","closed_days":"水曜、年末年始（GWと7月25日〜8月31日は無休）","official_links":[{"label":"にいがた観光ナビ","url":"https://niigata-kankou.or.jp/spot/11337","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%82%A2%E3%82%AF%E3%82%A2%E3%83%91%E3%83%BC%E3%82%AF%E3%81%AB%E3%81%84%E3%81%8C%E3%81%9F%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E7%AC%A0%E6%9C%A83629%E7%95%AA%E5%9C%B01","type":"map"}],"sources":[{"title":"にいがた観光ナビ アクアパークにいがた","url":"https://niigata-kankou.or.jp/spot/11337","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、交通、駐車場、営業時間、定休日、電話確認。"}],"faqs":[{"question":"アクアパークにいがたは雨の日向きですか？","answer":"屋内温水施設のため、雨の日や冬場に体を動かす候補として整理しています。"},{"question":"夏休み期間は営業時間が変わりますか？","answer":"にいがた観光ナビでは、7月25日から8月31日は9時から22時と掲載されています。最新情報は公式確認してください。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'toyano-sports-park', 'leisure_spot', 'niigata',
  '鳥屋野潟公園（新潟県スポーツ公園）', 'デンカビッグスワンスタジアムやHARD OFF ECOスタジアム新潟周辺に広がる県立公園。芝生広場、遊具、自然生態園、スケートパークなどを備えます。', NULL,
  '新潟県新潟市中央区清五郎及び長潟地内', '新潟市中央区', '025-286-1080',
  '公園利用は無料目安。施設利用は別途確認', 'https://www.pref.niigata.lg.jp/sec/toshiseibi/1220551354997.html', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B8%85%E4%BA%94%E9%83%8E',
  ARRAY['公共系', '公園', 'スポーツ', '遊具', 'スケートパーク']::text[], '2026-06-08', '新潟市中心部で日常的に使える公共公園。スポーツイベント、散歩、親子遊びなど複数導線に展開できます。',
  '{"kind":"outdoor","genre":"公園・スポーツ","best_for":["親子","散歩","スポーツ"],"highlight":"大型スタジアム周辺で、芝生・遊具・自然観察・スポーツを組み合わせられる。","parking":true,"parking_note":"新潟県資料では第1約540台、第2約400台、第3約270台の駐車場掲載あり。閉鎖期間あり。","business_hours":"終日開園。施設により利用時間あり","closed_days":"公園は原則常時利用。施設・駐車場は公式確認","official_links":[{"label":"新潟県 施設案内","url":"https://www.pref.niigata.lg.jp/sec/toshiseibi/1220551354997.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E5%85%AC%E5%9C%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B8%85%E4%BA%94%E9%83%8E","type":"map"}],"sources":[{"title":"新潟県 鳥屋野潟公園（スポーツ公園）","url":"https://www.pref.niigata.lg.jp/sec/toshiseibi/1220551354997.html","sourceType":"government","collectedAt":"2026-06-08","note":"施設概要、主な施設、スケートパーク情報確認。"},{"title":"新潟県 鳥屋野潟公園資料","url":"https://www.pref.niigata.lg.jp/uploaded/attachment/347429.pdf","sourceType":"government","collectedAt":"2026-06-08","note":"所在地、駐車場、終日開園、問い合わせ先確認。"}],"faqs":[{"question":"鳥屋野潟公園は子ども連れで使えますか？","answer":"芝生広場、遊具、自然生態園などがあり、親子の外遊び候補として整理しています。"},{"question":"駐車場はいつでも使えますか？","answer":"新潟県資料では駐車場閉鎖期間ありとされているため、イベント時や冬期などは公式確認を推奨します。"}],"related_ranking_slugs":["niigata-outdoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'teradomari-aquarium', 'leisure_spot', 'niigata',
  '長岡市寺泊水族博物館', '長岡市寺泊にある水族博物館。日本海側のドライブや寺泊観光と合わせやすく、屋内展示中心で家族のおでかけ候補にもなります。', NULL,
  '新潟県長岡市寺泊花立9353-158', '長岡市寺泊', '0258-75-4936',
  '大人700円、中学生450円、小学生350円、幼児200円目安', 'https://aquarium-teradomari.jp/guide', 'https://maps.google.com/?q=%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AF%BA%E6%B3%8A%E6%B0%B4%E6%97%8F%E5%8D%9A%E7%89%A9%E9%A4%A8%20%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AF%BA%E6%B3%8A%E8%8A%B1%E7%AB%8B9353-158',
  ARRAY['公共系', '水族館', '屋内', '寺泊', '家族']::text[], '2026-06-08', '寺泊方面の観光導線を補強できる屋内スポット。既存の新潟市内中心から中越・海沿いへ広げられます。',
  '{"kind":"indoor","genre":"水族博物館","best_for":["親子","雨の日","寺泊観光"],"highlight":"寺泊観光と組み合わせやすい、公共系の水族博物館。","parking":true,"parking_note":"駐車場の詳細は公式・現地案内確認推奨。","business_hours":"9:00〜16:30（最終入館16:00）","closed_days":"年度ごとに休館日掲載あり。公式確認","official_links":[{"label":"公式 ご利用案内","url":"https://aquarium-teradomari.jp/guide","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AF%BA%E6%B3%8A%E6%B0%B4%E6%97%8F%E5%8D%9A%E7%89%A9%E9%A4%A8%20%E9%95%B7%E5%B2%A1%E5%B8%82%E5%AF%BA%E6%B3%8A%E8%8A%B1%E7%AB%8B9353-158","type":"map"}],"sources":[{"title":"長岡市寺泊水族博物館 ご利用案内","url":"https://aquarium-teradomari.jp/guide","sourceType":"official","collectedAt":"2026-06-08","note":"開館時間、最終入館、休館日、料金、住所、電話確認。"}],"faqs":[{"question":"寺泊水族博物館は雨の日でも使えますか？","answer":"屋内展示中心の水族博物館として、寺泊観光の雨の日候補にできます。"},{"question":"休館日は固定ですか？","answer":"公式では年度ごとの休館日が掲載されています。訪問前に最新の休館日を確認してください。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'umigatari-joetsu', 'leisure_spot', 'niigata',
  '上越市立水族博物館 うみがたり', '日本海をテーマにした上越市の水族博物館。大水槽、海中トンネル、マゼランペンギン展示などがあり、上越方面の屋内レジャーの核になります。', NULL,
  '新潟県上越市五智2-15-15', '上越市', '025-543-2449',
  '大人2,000円、高校生1,200円、小中学生1,000円、幼児600円目安', 'https://www.umigatari.jp/joetsu/', 'https://maps.google.com/?q=%E4%B8%8A%E8%B6%8A%E5%B8%82%E7%AB%8B%E6%B0%B4%E6%97%8F%E5%8D%9A%E7%89%A9%E9%A4%A8%20%E3%81%86%E3%81%BF%E3%81%8C%E3%81%9F%E3%82%8A%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E4%BA%94%E6%99%BA2-15-15',
  ARRAY['公共系', '水族館', '屋内', '上越', 'ペンギン']::text[], '2026-06-08', '上越方面のレジャー軸を強化できる大型屋内施設。マリンピア日本海との比較記事にも展開できます。',
  '{"kind":"indoor","genre":"水族博物館","best_for":["親子","雨の日","上越観光"],"highlight":"日本海テーマの展示とマゼランペンギン展示を一度に楽しめる。","parking":true,"parking_note":"公式アクセスでは無料駐車場 一般約580台・大型バス20台と掲載。","business_hours":"通常10:00〜17:00（最終入館16:30）。時期により変動","closed_days":"設備点検休館日あり。公式確認","official_links":[{"label":"公式サイト","url":"https://www.umigatari.jp/joetsu/","type":"website"},{"label":"アクセス","url":"https://www.umigatari.jp/ko/joetsu/access/index.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%8A%E8%B6%8A%E5%B8%82%E7%AB%8B%E6%B0%B4%E6%97%8F%E5%8D%9A%E7%89%A9%E9%A4%A8%20%E3%81%86%E3%81%BF%E3%81%8C%E3%81%9F%E3%82%8A%20%E4%B8%8A%E8%B6%8A%E5%B8%82%E4%BA%94%E6%99%BA2-15-15","type":"map"}],"sources":[{"title":"うみがたり 公式サイト","url":"https://www.umigatari.jp/joetsu/","sourceType":"official","collectedAt":"2026-06-08","note":"施設概要、本日の開館時間、日本海テーマ展示、マゼランペンギン確認。"},{"title":"うみがたり 開館時間・料金","url":"https://www.umigatari.jp/en/joetsu/info/","sourceType":"official","collectedAt":"2026-06-08","note":"通常開館時間、料金、設備点検休館日確認。"},{"title":"うみがたり アクセス","url":"https://www.umigatari.jp/ko/joetsu/access/index.html","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、駐車場確認。"}],"faqs":[{"question":"うみがたりはマリンピア日本海とどう使い分けますか？","answer":"新潟市内ならマリンピア日本海、上越方面の旅行や直江津周辺観光ならうみがたりを候補にしやすいです。"},{"question":"開館時間は固定ですか？","answer":"通常は10時から17時ですが、夏期や連休など時期により変動します。公式サイトで最新情報を確認してください。"}],"related_ranking_slugs":["niigata-indoor-leisure","niigata-family-rainyday"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
