  'sea-luvism-bandai', 'beauty_salon', 'niigata',
  'Sea by LUVISM 万代店', '新潟万代ビル8Fに構えるLUVISMグループのプレミアムライン。イルミナカラー・ブリーチ・ダブルカラーを得意とし、20〜30代のカラー重視層から高い支持を集める。新潟駅万代口から徒歩約10分とアクセスも良好。年中無休で夜22時まで営業しており、仕事帰りや週末でも通いやすい環境が整っている。', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
  '新潟県新潟市中央区万代1-3-10 新潟万代ビル8F', '新潟市中央区・万代', '025-278-8332',
  'カット+カラーセット ¥7,950〜', 'https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%B8%87%E4%BB%A31-3-10%20%E6%96%B0%E6%BD%9F%E4%B8%87%E4%BB%A3%E3%83%93%E3%83%AB%20Sea%20by%20LUVISM',
  ARRAY[]::text[], '2026-06-08', '万代エリアでイルミナカラー・ダブルカラーを得意とするLUVISMグループの上位ライン。20〜30代でカラー重視の読者への最有力候補のひとつ。',
  '{"tagline":"イルミナカラー・ブリーチ・ダブルカラーが得意な万代の実力サロン","access":"新潟駅（万代口）徒歩約10分","treatments":["cut","color","highlight","hairQuality","straightening"],"age_groups":["twenties","thirties"],"cut_price":"要確認（公式サイト・予約サイトで確認）","color_price":"カット+カラーセット ¥7,950〜","parking":false,"parking_note":"万代エリア周辺コインパーキング利用","children_welcome":false,"men_welcome":true,"business_hours":"9:00〜22:00","closed_days":"年中無休","official_links":[{"label":"公式サイト","url":"https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000624907/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%B8%87%E4%BB%A31-3-10%20%E6%96%B0%E6%BD%9F%E4%B8%87%E4%BB%A3%E3%83%93%E3%83%AB%20Sea%20by%20LUVISM","type":"map"}],"sources":[{"title":"Sea by LUVISM 万代店 公式サイト","url":"https://seabyluvism.jp/salon/sea-by-luvism-%E4%B8%87%E4%BB%A3%E5%BA%97/","sourceType":"official","collectedAt":"2026-06-08","note":"店舗名・住所・電話・営業時間・得意施術を確認。"},{"title":"Sea by LUVISM 万代店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000624907/","sourceType":"local-media","collectedAt":"2026-06-08","note":"料金・メニュー・口コミを確認。"}],"faqs":[{"question":"Sea by LUVISMはどんな人に向いていますか？","answer":"イルミナカラー・ブリーチを使ったハイライトやダブルカラーなど透明感のあるカラーを求める20〜30代の方に向いています。予約はホットペッパービューティーまたは公式サイトから可能です。"},{"question":"万代店の場所はどこですか？","answer":"新潟万代ビル8Fにあります。新潟駅万代口から徒歩約10分です。電話番号は025-278-8332です。"}],"related_ranking_slugs":["niigata-beauty-color","niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cloe-luvism-furumachi', 'beauty_salon', 'niigata',
  'CLOE by LUVISM 古町6番店', '古町通六番町に位置するLUVISMグループのサロン。デザインカラー・オーガニックカラー・髪質改善を中心にメニューを展開し、20〜40代の幅広い層に対応。年中無休で夜22時まで営業と仕事帰りの利用にも便利。カット¥2,500〜とコスパも良好で、古町エリアでの定番サロンとして定着している。', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
  '新潟県新潟市中央区古町通六番町982-1 ロンドベル古町6番町', '新潟市中央区・古町', '025-201-9922',
  'カット¥2,500〜 / カット+オーガニックフルカラー¥5,400〜', 'https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A%E5%85%AD%E7%95%AA%E7%94%BA982-1%20CLOE%20by%20LUVISM',
  ARRAY[]::text[], '2026-06-08', '古町エリアでオーガニックカラーを試したい方への第一候補。コスパと立地の良さが20〜40代から支持される。',
  '{"tagline":"オーガニックカラーとデザインカラーを得意とする古町のサロン","access":"古町モール6番町入口・国際調理製菓専門学校向かい","treatments":["cut","color","highlight","hairQuality","treatment"],"age_groups":["twenties","thirties","forties"],"cut_price":"¥2,500〜","color_price":"カット+オーガニックフルカラー ¥5,400〜","parking":false,"parking_note":"古町エリア周辺コインパーキング利用","children_welcome":false,"men_welcome":true,"business_hours":"9:00〜22:00","closed_days":"年中無休","instagram":"https://www.instagram.com/cloebyluvism/","official_links":[{"label":"公式サイト","url":"https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000577647/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/cloebyluvism/","type":"instagram"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A%E5%85%AD%E7%95%AA%E7%94%BA982-1%20CLOE%20by%20LUVISM","type":"map"}],"sources":[{"title":"CLOE by LUVISM 古町6番店 公式サイト","url":"https://cloebyluvism.jp/salon/cloe-by-luvism-%E5%8F%A4%E7%94%BA6%E7%95%AA%E5%BA%97/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・料金を確認。"},{"title":"クロエ バイ ラヴィズム 古町6番店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000577647/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・料金・口コミを確認。"}],"faqs":[{"question":"古町6番店のカラー料金はどのくらいですか？","answer":"カット+オーガニックフルカラーが¥5,400〜です。詳細メニューはホットペッパービューティーの公式ページでご確認ください。"},{"question":"オーガニックカラーとは何ですか？","answer":"天然由来成分を配合したカラー剤を使用する施術です。頭皮への刺激が少なく、敏感肌の方や薬剤が気になる方に向いています。"}],"related_ranking_slugs":["niigata-beauty-color","niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cloe-luvism-niigataeki', 'beauty_salon', 'niigata',
  'CLOE by LUVISM 新潟駅前店', '新潟駅万代口から徒歩2分のアルファビル2Fに構えるCLOEの駅前店。デザインカラー・オーガニックカラー・縮毛矯正を中心に、10〜30代の学生から社会人まで幅広く対応。カット¥2,400〜と価格の入りやすさも強み。夜22時まで年中無休で営業しており、新潟駅を利用する通勤・通学者の定番サロンとして定着している。', 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80',
  '新潟県新潟市中央区花園1-3-23 アルファビル2階', '新潟市中央区・新潟駅前', '025-282-7335',
  'デザインカット¥2,400〜 / カット+オーガニックフルカラー¥4,900〜', 'https://cloebyluvism.jp/salon/niigata_ekimae/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%8A%B1%E5%9C%921-3-23%20%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%93%E3%83%AB%20CLOE%20by%20LUVISM',
  ARRAY[]::text[], '2026-06-08', '新潟駅徒歩2分という立地と入りやすい価格帯が10〜20代への強み。初めてデザインカラーや縮毛矯正を試す読者への提案先として使いやすい。',
  '{"tagline":"新潟駅徒歩2分・デザインカラーと縮毛矯正が得意な駅前サロン","access":"新潟駅（万代口）徒歩2分","treatments":["cut","color","highlight","hairQuality","straightening"],"age_groups":["teens","twenties","thirties"],"cut_price":"¥2,400〜","color_price":"カット+オーガニックフルカラー ¥4,900〜","parking":false,"parking_note":"駅近のため公共交通機関利用推奨","children_welcome":false,"men_welcome":true,"business_hours":"9:00〜22:00","closed_days":"年中無休","instagram":"https://www.instagram.com/cloebyluvism/","official_links":[{"label":"公式サイト","url":"https://cloebyluvism.jp/salon/niigata_ekimae/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000316018/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/cloebyluvism/","type":"instagram"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%8A%B1%E5%9C%921-3-23%20%E3%82%A2%E3%83%AB%E3%83%95%E3%82%A1%E3%83%93%E3%83%AB%20CLOE%20by%20LUVISM","type":"map"}],"sources":[{"title":"CLOE by LUVISM 新潟駅前店 公式サイト","url":"https://cloebyluvism.jp/salon/niigata_ekimae/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・料金を確認。"},{"title":"クロエ バイ ラヴィズム 新潟駅前店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000316018/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・口コミを確認。"}],"faqs":[{"question":"新潟駅前店は駅からどのくらいですか？","answer":"新潟駅万代口から徒歩2分、アルファビル2Fです。電話番号は025-282-7335です。"},{"question":"学生でも利用できますか？","answer":"はい。各種クーポンや割引メニューをホットペッパービューティーで確認できます。最新情報は予約サイトまたは電話でご確認ください。"}],"related_ranking_slugs":["niigata-beauty-color","niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'delight-designers-works', 'beauty_salon', 'niigata',
  'Delight Designer''s Works', '新潟市中央区東大通の東陽ビル2Fに構えるメンズ専門ヘアサロン。フェードカット・ツーブロック・メンズパーマなどメンズスタイリング全般を高い技術力で提供。新潟駅（花園・沼垂方面出口）から徒歩2分のアクセスも良好。旧東区店から移転後も固定客が多く、新潟市内のメンズサロンとして定評がある。', 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80',
  '新潟県新潟市中央区東大通1丁目5番2号 東陽ビル2F', '新潟市中央区・新潟駅前', '025-384-4559',
  '要確認（公式サイト・予約サイトで確認）', 'https://delightdesignersworks.com/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%9D%B1%E5%A4%A7%E9%80%9A1%E4%B8%81%E7%9B%AE5%E7%95%AA2%E5%8F%B7%20%E6%9D%B1%E9%99%BD%E3%83%93%E3%83%AB%20Delight%20Designers%20Works',
  ARRAY[]::text[], '2026-06-08', '新潟市内でメンズ専門の技術力に定評があるサロン。料金は公式サイトまたはInstagram（@delightdesignersworks）で要確認。',
  '{"tagline":"新潟駅前に構えるメンズ専門ヘアサロン","access":"新潟駅（花園・沼垂方面出口）徒歩2分","treatments":["cut","color","perm"],"age_groups":["teens","twenties","thirties","forties"],"cut_price":"要確認（公式サイトで確認）","parking":false,"parking_note":"駅近のため公共交通機関利用推奨","children_welcome":false,"men_welcome":true,"business_hours":"11:00〜20:00（最終受付19:00）","closed_days":"毎週月曜日（臨時休業あり）","instagram":"https://www.instagram.com/delightdesignersworks/","official_links":[{"label":"公式サイト","url":"https://delightdesignersworks.com/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000563316/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/delightdesignersworks/","type":"instagram"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%9D%B1%E5%A4%A7%E9%80%9A1%E4%B8%81%E7%9B%AE5%E7%95%AA2%E5%8F%B7%20%E6%9D%B1%E9%99%BD%E3%83%93%E3%83%AB%20Delight%20Designers%20Works","type":"map"}],"sources":[{"title":"Delight Designer''s Works 公式サイト","url":"https://delightdesignersworks.com/","sourceType":"official","collectedAt":"2026-06-08","note":"移転後の店舗情報・営業時間を確認。"},{"title":"ディライト ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000563316/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・口コミを確認。"}],"faqs":[{"question":"女性も利用できますか？","answer":"メンズ専門サロンです。詳細は公式サイト（delightdesignersworks.com）またはInstagramでご確認ください。"},{"question":"場所はどこですか？","answer":"新潟市中央区東大通1丁目5番2号 東陽ビル2Fです。新潟駅（花園・沼垂方面出口）から徒歩2分です。電話番号は025-384-4559です。"}],"related_ranking_slugs":["niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ursus-headlight-sakaihi', 'beauty_salon', 'niigata',
  'Ursus hair Design by HEADLIGHT 坂井東店', '新潟市西区坂井東に立地するHEADLIGHTグループのサロン。髪質改善・ヘッドスパ・縮毛矯正・デジタルパーマなど幅広いメニューを提供し、車移動が多い西区・西蒲区の利用者に支持されている。専用駐車場5台完備で、郊外在住者でも通いやすい。カット¥2,700〜とリーズナブルな価格帯も魅力で、年中無休夜21時まで営業。', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80',
  '新潟県新潟市西区坂井東1-3-15', '新潟市西区', '025-378-3447',
  'カット¥2,700〜', 'https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%9D%82%E4%BA%95%E6%9D%B11-3-15%20Ursus%20hair%20Design%20HEADLIGHT',
  ARRAY[]::text[], '2026-06-08', '新潟市西区で髪質改善・ヘッドスパを求める読者への最有力候補。駐車場完備で車移動派にも使いやすく、豊富なメニューで幅広い悩みに対応できる。',
  '{"tagline":"髪質改善・ヘッドスパ・縮毛矯正が揃う駐車場完備の西区サロン","access":"JR小針駅から車約10分 / 大堀幹線沿い・ブックオフ斜め前","treatments":["cut","color","hairQuality","straightening","treatment","headSpa","perm"],"age_groups":["thirties","forties","fifties"],"cut_price":"¥2,700〜","parking":true,"parking_note":"専用駐車場5台あり","children_welcome":false,"men_welcome":true,"business_hours":"9:00〜21:00","closed_days":"年中無休","official_links":[{"label":"公式サイト（HEADLIGHT）","url":"https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000362060/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%9D%82%E4%BA%95%E6%9D%B11-3-15%20Ursus%20hair%20Design%20HEADLIGHT","type":"map"}],"sources":[{"title":"Ursus hair Design by HEADLIGHT 坂井東店 HEADLIGHT公式","url":"https://headlight-inc.com/salon/area04/nigata/ursus-hair-design-niigatasakaihigashi/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・駐車場・得意施術を確認。"},{"title":"アーサス ヘアー デザイン 坂井東店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000362060/","sourceType":"local-media","collectedAt":"2026-06-08","note":"料金・メニュー・口コミを確認。"}],"faqs":[{"question":"ヘッドスパの予約はできますか？","answer":"はい。ホットペッパービューティーまたは電話（025-378-3447）でご予約いただけます。"},{"question":"駐車場はありますか？","answer":"専用駐車場が5台あります。大堀幹線沿い、ブックオフ斜め前が目印です。"}],"related_ranking_slugs":["niigata-beauty-headspa","niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'cloe-luvism-nagaoka', 'beauty_salon', 'niigata',
  'CLOE by LUVISM 長岡古正寺店', '長岡市古正寺に立地するCLOE by LUVISMの長岡店。15台の広い駐車場とキッズスペースを完備し、子連れ家族でも安心して利用できる。イルミナカラー・インナーカラー・ブリーチ・ハイライトなどカラーメニューも充実しており、長岡市内では数少ない「カラー技術とファミリー対応を両立」するサロン。年中無休で夜22時まで営業。', 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80',
  '新潟県長岡市古正寺2-57', '長岡市', '0258-86-8755',
  'カット¥2,800〜 / イルミナフルカラー+カット¥7,400〜', 'https://cloebyluvism.jp/salon/kosyoji/', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E9%95%B7%E5%B2%A1%E5%B8%82%E5%8F%A4%E6%AD%A3%E5%AF%BA2-57%20CLOE%20by%20LUVISM',
  ARRAY[]::text[], '2026-06-08', '長岡市内で「子連れOK」かつ「カラー技術も妥協したくない」読者への最優先提案先。駐車場15台は長岡郊外での利便性として大きな強み。',
  '{"tagline":"キッズスペースあり・駐車場15台完備の長岡ファミリーサロン","access":"JR長岡駅から車約10分 / 国道351号・新潟トヨペット左隣","treatments":["cut","color","highlight","hairQuality","perm"],"age_groups":["teens","twenties","thirties","forties"],"cut_price":"¥2,800〜（メンズカット¥2,400〜）","color_price":"イルミナフルカラー+カット ¥7,400〜 / カット+フルカラー ¥5,400〜","parking":true,"parking_note":"専用駐車場15台完備","children_welcome":true,"men_welcome":true,"business_hours":"9:00〜22:00","closed_days":"年中無休","instagram":"https://www.instagram.com/cloebyluvism/","official_links":[{"label":"公式サイト","url":"https://cloebyluvism.jp/salon/kosyoji/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000375435/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/cloebyluvism/","type":"instagram"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E7%9C%8C%E9%95%B7%E5%B2%A1%E5%B8%82%E5%8F%A4%E6%AD%A3%E5%AF%BA2-57%20CLOE%20by%20LUVISM","type":"map"}],"sources":[{"title":"CLOE by LUVISM 長岡古正寺店 公式サイト","url":"https://cloebyluvism.jp/salon/kosyoji/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・駐車場・キッズスペース・料金を確認。"},{"title":"クロエ バイ ラヴィズム 長岡古正寺店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000375435/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・口コミ・子連れ対応を確認。"}],"faqs":[{"question":"子連れで利用できますか？","answer":"はい。キッズスペースを完備しています。専用駐車場も15台あるため、お子様連れでも安心してご来店いただけます。"},{"question":"長岡駅からのアクセスは？","answer":"JR長岡駅から車約10分です。国道351号沿い、新潟トヨペットの左隣が目印です。電話番号は0258-86-8755です。"}],"related_ranking_slugs":["niigata-beauty-color","niigata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'rem-yamagata-2', 'beauty_salon', 'yamagata',
  'REM 山形2号店', '山形市飯田西のLa Saison Claire 101に構えるヘアサロン。イルミナカラー・アディクシーカラー・TOKIOトリートメント・酸熱トリートメントなど充実したメニューを展開し、20〜30代を中心に支持される。バス停「大学病院」から徒歩1分とアクセスも良好。ホットペッパービューティーではランキング上位に掲載される人気サロン。', 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
  '山形県山形市飯田西4-5-33 La Saison Claire 101', '山形市・飯田西', '023-626-5133',
  '要確認（ホットペッパービューティーで確認）', 'https://beauty.hotpepper.jp/slnH000477049/', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E9%A3%AF%E7%94%B0%E8%A5%BF4-5-33%20La%20Saison%20Claire%20REM',
  ARRAY[]::text[], '2026-06-08', '山形市内でイルミナカラーと酸熱トリートメントを組み合わせたいカラー重視の読者への有力候補。ホットペッパービューティーのランキング常連店。',
  '{"tagline":"イルミナカラー・アディクシー・酸熱トリートメントが揃う山形市のサロン","access":"バス停「大学病院」徒歩1分 / 「飯田アパート前」徒歩2分 / 蔵王駅から車7分","treatments":["cut","color","highlight","hairQuality","treatment"],"age_groups":["twenties","thirties"],"cut_price":"要確認（公式サイト・予約サイトで確認）","parking":false,"parking_note":"詳細は店舗に要確認","children_welcome":false,"men_welcome":false,"business_hours":"9:00〜20:00","closed_days":"基本なし（年末年始・臨時休業あり）","instagram":"https://www.instagram.com/rem.hairsalon/","official_links":[{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000477049/","type":"website"},{"label":"Instagram","url":"https://www.instagram.com/rem.hairsalon/","type":"instagram"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E9%A3%AF%E7%94%B0%E8%A5%BF4-5-33%20La%20Saison%20Claire%20REM","type":"map"}],"sources":[{"title":"REM 山形2号店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000477049/","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・得意施術・口コミを確認。"},{"title":"山形市 ランキング 美容室 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/keyword/%E5%B1%B1%E5%BD%A2%E5%B8%82%E3%80%80%E3%83%A9%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0%E3%80%80%E7%BE%8E%E5%AE%B9%E5%AE%A4/","sourceType":"local-media","collectedAt":"2026-06-08","note":"山形市ランキング上位サロンとして掲載確認。"}],"faqs":[{"question":"REMの場所はどこですか？","answer":"山形市飯田西4-5-33 La Saison Claire 101です。バス停「大学病院」から徒歩1分が最寄りです。電話番号は023-626-5133です。"},{"question":"TOKIOトリートメントはカラーと同日にできますか？","answer":"多くの場合、同日施術が可能です。施術時間が長くなるため、予約時に希望をお伝えください。"}],"related_ranking_slugs":["yamagata-beauty-color","yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'hair-design-buco', 'beauty_salon', 'yamagata',
  'HAIR DESIGN BUCO', '山形市荒楯町の国道286号沿いに立地する実力派ヘアサロン。イルミナカラーによる透明感スタイルとドライカット技術を組み合わせた柔らかなテクスチャーが特徴。ショートスタイル・ボブの再現性が高く、白髪染めにも丁寧に対応するため、30〜50代女性からの支持が厚い。店舗前に広い駐車場完備で車移動派にも便利。', 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80',
  '山形県山形市荒楯町1-1-8', '山形市・荒楯町', '023-666-7487',
  'カット¥4,950〜 / カット+イルミナカラー¥12,650〜', 'https://hairdesign-buco.com/', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E8%8D%92%E6%A5%AF%E7%94%BA1-1-8%20HAIR%20DESIGN%20BUCO',
  ARRAY[]::text[], '2026-06-08', '山形市でイルミナカラーと質感のあるカット技術を求める30〜50代女性への第一候補。駐車場完備で車移動でも通いやすい。',
  '{"tagline":"イルミナカラーとドライカットで柔らかな質感を得意とする山形市の実力店","access":"山形駅から車5分 / 国道286号沿い・店舗前広い駐車場あり","treatments":["cut","color","treatment"],"age_groups":["thirties","forties","fifties"],"cut_price":"¥4,950〜（学割あり）","color_price":"カット+イルミナカラー ¥12,650〜","parking":true,"parking_note":"店舗前に広い駐車場あり","children_welcome":false,"men_welcome":false,"business_hours":"9:30〜19:00（最終受付）","closed_days":"毎週月曜日","official_links":[{"label":"公式サイト","url":"https://hairdesign-buco.com/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000285830/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E8%8D%92%E6%A5%AF%E7%94%BA1-1-8%20HAIR%20DESIGN%20BUCO","type":"map"}],"sources":[{"title":"HAIR DESIGN BUCO 公式サイト","url":"https://hairdesign-buco.com/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・料金・駐車場を確認。"},{"title":"ヘアー デザイン ブーコ ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000285830/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・料金・口コミを確認。"}],"faqs":[{"question":"BUCOのカット料金はどのくらいですか？","answer":"¥4,950〜（学割あり）です。カット+イルミナカラーは¥12,650〜です。詳細メニューは公式サイト（hairdesign-buco.com）でご確認ください。"},{"question":"白髪が気になりますが相談できますか？","answer":"はい。白髪染めのほか、白髪を活かすイルミナカラーの提案も行っています。まずはカウンセリングでご相談ください。"}],"related_ranking_slugs":["yamagata-beauty-color","yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'baker-street-yamagata', 'beauty_salon', 'yamagata',
  'Baker Street', '山形市七日町2丁目に構える完全予約制のプライベートサロン。カウンセリングを徹底的に重視し、骨格・ライフスタイルに合わせた似合わせカットに特化。専用駐車場3台完備。新規様は¥3,000〜と比較的入りやすい価格設定で、七日町という中心地の立地も相まって山形市内での口コミ評価が高いサロン。', 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80',
  '山形県山形市七日町2丁目7-23', '山形市・七日町', '023-665-5215',
  'メンテナンスカット¥2,000〜 / 新規限定カット¥3,000〜', 'https://beauty.hotpepper.jp/slnH000679203/', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E4%B8%83%E6%97%A5%E7%94%BA2%E4%B8%81%E7%9B%AE7-23%20Baker%20Street',
  ARRAY[]::text[], '2026-06-08', '「カット技術と似合わせ提案を重視したい」山形市内の30〜50代女性への提案先として有効。完全予約制のプライベート感が評価されている。',
  '{"tagline":"完全予約制・カウンセリング重視の似合わせカット専門プライベートサロン","access":"山形駅・北山形駅から車6分 / 専用駐車場3台あり","treatments":["cut","color"],"age_groups":["thirties","forties","fifties"],"cut_price":"¥2,000〜（メンテナンス） / ¥3,000〜（新規）","parking":true,"parking_note":"専用駐車場3台あり","children_welcome":false,"men_welcome":false,"business_hours":"9:00〜20:00","closed_days":"要確認（ホットペッパービューティーで確認）","official_links":[{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000679203/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%B1%B1%E5%BD%A2%E5%B8%82%E4%B8%83%E6%97%A5%E7%94%BA2%E4%B8%81%E7%9B%AE7-23%20Baker%20Street","type":"map"}],"sources":[{"title":"ベイカーストリート(Baker Street) ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000679203/","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・料金・口コミを確認。"}],"faqs":[{"question":"Baker Streetは予約が必要ですか？","answer":"完全予約制です。ホットペッパービューティーまたは電話（023-665-5215）でご予約ください。"},{"question":"初めて行く場合の料金はどのくらいですか？","answer":"新規様限定カットが¥3,000〜です。詳細はホットペッパービューティーのページでご確認ください。"}],"related_ranking_slugs":["yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'agu-navy-tsuruoka', 'beauty_salon', 'yamagata',
  'Agu hair navy 鶴岡東原店', '鶴岡市東原町の羽黒街道沿いに立地するAguヘアーネイビーの鶴岡店。カット¥2,500〜・カット+カラー¥3,900〜と庄内エリアでも入りやすい価格帯が魅力。7〜8台の駐車場完備で年中無休、夜21時まで営業しており、仕事帰りや週末でも立ち寄りやすい。10〜40代まで幅広い年代に対応し、鶴岡市内での定番サロンとして定着している。', 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80',
  '山形県鶴岡市東原町17-28', '鶴岡市・東原', '0235-33-9743',
  'カット¥2,500〜 / カット+カラー¥3,900〜', 'https://agu-hair.com/salon/2047/', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E6%9D%B1%E5%8E%9F%E7%94%BA17-28%20Agu%20hair%20navy',
  ARRAY[]::text[], '2026-06-08', '鶴岡・庄内エリアでコスパを重視する読者への最初の提案先として使いやすい。駐車場・年中無休・夜21時まで営業の三拍子が揃っている。',
  '{"tagline":"コスパと技術を両立した鶴岡市の年中無休サロン","access":"羽黒街道（県道47号線）沿い / グランドエル・サン近く / 食彩居酒屋「赤のれん」隣","treatments":["cut","color","perm"],"age_groups":["teens","twenties","thirties","forties"],"cut_price":"¥2,500〜","color_price":"カット+カラー ¥3,900〜","parking":true,"parking_note":"専用駐車場7〜8台あり","children_welcome":false,"men_welcome":true,"business_hours":"9:00〜21:00（カット最終受付20:00）","closed_days":"年中無休","official_links":[{"label":"Agu公式サイト","url":"https://agu-hair.com/salon/2047/","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000457001/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E6%9D%B1%E5%8E%9F%E7%94%BA17-28%20Agu%20hair%20navy","type":"map"}],"sources":[{"title":"Agu hair navy 鶴岡東原店 Agu公式サイト","url":"https://agu-hair.com/salon/2047/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・駐車場・料金を確認。"},{"title":"アグ ヘアー ネイビー 鶴岡東原店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000457001/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・口コミを確認。"}],"faqs":[{"question":"Agu鶴岡店のカラー料金はどのくらいですか？","answer":"カット+カラーで¥3,900〜です。詳細メニューはホットペッパービューティーまたは電話（0235-33-9743）でご確認ください。"},{"question":"駐車場はありますか？","answer":"専用駐車場が7〜8台あります。羽黒街道沿い、食彩居酒屋「赤のれん」隣が目印です。"}],"related_ranking_slugs":["yamagata-beauty-color","yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'earth-tsuruoka', 'beauty_salon', 'yamagata',
  'HAIR & MAKE EARTH 鶴岡店', '鶴岡市美咲町に立地するHAIR & MAKE EARTHの鶴岡店。全国に400店舗以上を展開するEARTHグループの一店として、カラー・パーマ・トリートメントなど幅広いメニューを提供。統一されたマニュアルと技術研修による安定した品質が特徴で、初めて行くサロンとして安心感がある。年中無休で営業。', 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80',
  '山形県鶴岡市美咲町3-11', '鶴岡市・美咲町', '050-8884-1558',
  '要確認（公式サイト・予約サイトで確認）', 'https://map.hairmake-earth.com/salon/227', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E7%BE%8E%E5%92%B2%E7%94%BA3-11%20HAIR%20MAKE%20EARTH',
  ARRAY[]::text[], '2026-06-08', '全国チェーンの安定した品質と年中無休の利便性が強み。「初めて行くサロンで失敗したくない」読者への鶴岡エリアの安心候補。',
  '{"tagline":"全国展開の実力チェーン・鶴岡市の年中無休サロン","access":"JR鶴岡駅から車10分（徒歩46分）","treatments":["cut","color","perm","treatment"],"age_groups":["twenties","thirties","forties"],"cut_price":"要確認（公式サイトで確認）","parking":false,"parking_note":"詳細は店舗に要確認","children_welcome":false,"men_welcome":true,"business_hours":"日〜木・祝: 9:00〜17:00 / 金・土: 9:00〜18:00","closed_days":"年中無休","official_links":[{"label":"EARTH公式サイト","url":"https://map.hairmake-earth.com/salon/227","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E7%BE%8E%E5%92%B2%E7%94%BA3-11%20HAIR%20MAKE%20EARTH","type":"map"}],"sources":[{"title":"HAIR & MAKE EARTH 鶴岡店 EARTH公式サイト","url":"https://map.hairmake-earth.com/salon/227","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間を確認。"},{"title":"楽天ビューティ 酒田・鶴岡 美容室","url":"https://beauty.rakuten.co.jp/area0605/sort15/","sourceType":"local-media","collectedAt":"2026-06-08","note":"庄内エリアの注目サロンとして掲載確認。"}],"faqs":[{"question":"EARTHは初めてでも安心ですか？","answer":"はい。全国チェーンのため統一された施術基準があり、初めての方でも安心して利用いただけます。詳細メニューと料金はEARTH公式サイトまたは電話でご確認ください。"},{"question":"鶴岡駅からのアクセスは？","answer":"JR鶴岡駅から車で約10分です。電話番号は050-8884-1558です。"}],"related_ranking_slugs":["yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'earth-sakata', 'beauty_salon', 'yamagata',
  'HAIR & MAKE EARTH 酒田店', '酒田市松原南に立地するHAIR & MAKE EARTHの酒田店。全国チェーンの安定した技術とメニューの豊富さが魅力。カラー・パーマ・カット全般に対応し、庄内エリアの酒田在住者に利用しやすい年中無休営業。電話番号は0234-25-6171で、メニューや料金の詳細は公式サイトまたは楽天ビューティーで確認できる。', 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80',
  '山形県酒田市松原南1-5', '酒田市・松原南', '0234-25-6171',
  '要確認（公式サイト・予約サイトで確認）', 'https://map.hairmake-earth.com/salon/175', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%85%92%E7%94%B0%E5%B8%82%E6%9D%BE%E5%8E%9F%E5%8D%971-5%20HAIR%20MAKE%20EARTH',
  ARRAY[]::text[], '2026-06-08', '酒田市で安定したサービスを年中無休で受けられるチェーンサロン。庄内エリア在住で「まず試してみたい」読者への入門候補として紹介しやすい。',
  '{"tagline":"酒田市の年中無休サロン・カラーとパーマが揃うEARTHグループ","access":"要確認（公式サイトで確認）","treatments":["cut","color","perm","treatment"],"age_groups":["twenties","thirties","forties"],"cut_price":"要確認（公式サイトで確認）","parking":false,"parking_note":"詳細は店舗に要確認","children_welcome":false,"men_welcome":true,"business_hours":"日〜木: 9:00〜17:00（カラー・パーマ）/ 9:00〜18:00（カット） / 金・土: 9:00〜17:00（カラー・パーマ）/ 9:00〜18:00（カット）","closed_days":"年中無休","official_links":[{"label":"EARTH公式サイト","url":"https://map.hairmake-earth.com/salon/175","type":"website"},{"label":"ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000232955/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%85%92%E7%94%B0%E5%B8%82%E6%9D%BE%E5%8E%9F%E5%8D%971-5%20HAIR%20MAKE%20EARTH","type":"map"}],"sources":[{"title":"HAIR & MAKE EARTH 酒田店 EARTH公式サイト","url":"https://map.hairmake-earth.com/salon/175","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間を確認。"},{"title":"アース 酒田店 ホットペッパービューティー","url":"https://beauty.hotpepper.jp/slnH000232955/","sourceType":"local-media","collectedAt":"2026-06-08","note":"メニュー・口コミを確認。"}],"faqs":[{"question":"酒田店の場所はどこですか？","answer":"山形県酒田市松原南1-5です。電話番号は0234-25-6171です。詳細なアクセスは公式サイトまたは電話でご確認ください。"},{"question":"料金はどのくらいですか？","answer":"EARTH公式サイト（map.hairmake-earth.com/salon/175）またはホットペッパービューティーで最新の料金をご確認ください。"}],"related_ranking_slugs":["yamagata-beauty-color","yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'lafucona-tendo', 'beauty_salon', 'yamagata',
  'LAFUCONA', '山形県天童市芳賀タウン南に立地するヘアサロン。天童市内のサロンとして地域住民に利用されている。営業時間は9:30〜18:00、定休日は毎週月曜・第3日曜。詳細メニューや料金については公式サイト（lafucona.com）でご確認ください。', 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80',
  '山形県天童市芳賀タウン南2丁目11番23号', '天童市・芳賀タウン南', '023-674-9447',
  '要確認（公式サイトで確認）', 'https://lafucona.com/', 'https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%A4%A9%E7%AB%A5%E5%B8%82%E8%8A%B3%E8%B3%80%E3%82%BF%E3%82%A6%E3%83%B3%E5%8D%972%E4%B8%81%E7%9B%AE11%E7%95%AA23%E5%8F%B7%20LAFUCONA',
  ARRAY[]::text[], '2026-06-08', '天童市在住者向けの地域密着サロン。詳細メニュー・料金・特色は公式サイト（lafucona.com）または電話（023-674-9447）でご確認ください。',
  '{"tagline":"天童市の芳賀タウン南エリアに構えるヘアサロン","access":"要確認（公式サイトで確認）","treatments":["cut","color","treatment"],"age_groups":["twenties","thirties","forties"],"cut_price":"要確認（公式サイトで確認）","parking":false,"parking_note":"詳細は店舗に要確認","children_welcome":false,"men_welcome":false,"business_hours":"9:30〜18:00","closed_days":"毎週月曜日・第3日曜日","official_links":[{"label":"公式サイト","url":"https://lafucona.com/","type":"website"},{"label":"Google マップ","url":"https://maps.google.com/?q=%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%A4%A9%E7%AB%A5%E5%B8%82%E8%8A%B3%E8%B3%80%E3%82%BF%E3%82%A6%E3%83%B3%E5%8D%972%E4%B8%81%E7%9B%AE11%E7%95%AA23%E5%8F%B7%20LAFUCONA","type":"map"}],"sources":[{"title":"LAFUCONA 公式サイト","url":"https://lafucona.com/","sourceType":"official","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日を確認。"}],"faqs":[{"question":"LAFUCONAの場所はどこですか？","answer":"山形県天童市芳賀タウン南2丁目11番23号です。電話番号は023-674-9447です。"},{"question":"どのようなメニューがありますか？","answer":"詳細メニューは公式サイト（lafucona.com）でご確認ください。不明な点は電話でお問い合わせいただくのが確実です。"}],"related_ranking_slugs":["yamagata-beauty-by-age"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
