-- ========== ITEMS ==========
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'sankichiya-nishibori', 'ramen_item', 'niigata',
  '三吉屋 西堀本店', '昭和32年創業の老舗。新潟あっさり醤油ラーメンの代表格として、細麺と淡麗スープを目当てに訪れる読者へ紹介したい一店です。', NULL,
  '新潟県新潟市中央区西堀通5番町829', '新潟市中央区・古町', '025-222-8227',
  '600円〜1,000円目安', 'https://niigata.mypl.net/article/ramen_niigata/30547', 'https://maps.google.com/?q=%E4%B8%89%E5%90%89%E5%B1%8B%20%E8%A5%BF%E5%A0%80%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E5%A0%80%E9%80%9A5%E7%95%AA%E7%94%BA829',
  ARRAY['新潟5大ラーメン', '老舗', '古町', '細麺', '昼営業']::text[], '2026-06-08', '新潟ラーメンの入口記事や観光向け導線に最適。濃厚系が苦手な読者にも提案しやすく、古町散策との相性も良いです。',
  '{"genre":"新潟あっさり醤油","parking":false,"parking_note":"専用駐車場は確認できないため、周辺コインパーキング利用を想定。","recommended_menu":"中華そば","business_hours":"11:00〜16:00、17:00〜19:00（スープ・麺がなくなり次第終了）","closed_days":"火曜","official_links":[{"label":"店舗紹介","url":"https://niigata.mypl.net/article/ramen_niigata/30547","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%89%E5%90%89%E5%B1%8B%20%E8%A5%BF%E5%A0%80%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E8%A5%BF%E5%A0%80%E9%80%9A5%E7%95%AA%E7%94%BA829","type":"map"}],"sources":[{"title":"まいぷれ 新潟市 三吉屋 西堀本店","url":"https://niigata.mypl.net/article/ramen_niigata/30547","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、看板メニュー確認。"},{"title":"新潟市ラーメンガイドブック","url":"https://www.city.niigata.lg.jp/kanko/kanko/oshirase/ramen.files/guidebook.pdf","sourceType":"government","collectedAt":"2026-06-08","note":"新潟5大ラーメンと掲載店舗の確認。"}],"faqs":[{"question":"三吉屋 西堀本店はどんなラーメンですか？","answer":"細麺と淡麗スープの新潟あっさり醤油系です。濃厚さよりも昔ながらの中華そばらしさを重視する人に向いています。"},{"question":"訪問前に確認すべきことはありますか？","answer":"スープや麺がなくなり次第終了とされるため、遅い時間の訪問前は営業状況を確認してください。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-assari-shoyu"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'touyoko-shichikuyama', 'ramen_item', 'niigata',
  '元祖新潟濃厚味噌 東横 紫竹山本店', '割りスープ付きの濃厚味噌で知られる新潟5大ラーメンの代表格。太麺と味噌の強さを楽しみたい読者向けです。', NULL,
  '新潟県新潟市中央区紫竹山1-8-20', '新潟市中央区・紫竹山', '025-290-4770',
  '700円〜1,200円目安', 'https://www.touyoko.jp/stores', 'https://maps.google.com/?q=%E6%9D%B1%E6%A8%AA%20%E7%B4%AB%E7%AB%B9%E5%B1%B1%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B4%AB%E7%AB%B9%E5%B1%B11-8-20',
  ARRAY['新潟5大ラーメン', '濃厚味噌', '割りスープ', '太麺', '駐車場あり']::text[], '2026-06-08', '県外読者に新潟濃厚味噌を説明する時の軸になる店舗。味噌の濃さ、割りスープ、太麺という体験要素が明確です。',
  '{"genre":"新潟濃厚味噌","parking":true,"parking_note":"車利用しやすい郊外型店舗。","recommended_menu":"元祖新潟濃厚味噌","business_hours":"平日 11:00〜15:00 / 17:00〜21:00、土日祝 11:00〜21:00","closed_days":"不定休","official_links":[{"label":"公式サイト","url":"https://www.touyoko.jp/stores","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%9D%B1%E6%A8%AA%20%E7%B4%AB%E7%AB%B9%E5%B1%B1%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B4%AB%E7%AB%B9%E5%B1%B11-8-20","type":"map"}],"sources":[{"title":"東横 公式 店舗情報","url":"https://www.touyoko.jp/stores","sourceType":"official","collectedAt":"2026-06-08","note":"店舗展開と紫竹山本店の確認。"},{"title":"GOOD LUCK TRIP 東横 紫竹山本店","url":"https://www.gltjp.com/ja/directory/item/11508/","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所、電話、営業時間、濃厚味噌の説明確認。"}],"faqs":[{"question":"割りスープとは何ですか？","answer":"濃厚な味噌スープを好みの濃さに調整するためのスープです。まずはそのまま、途中で調整する流れが分かりやすいです。"},{"question":"観光客にも向いていますか？","answer":"新潟5大ラーメンの一つを分かりやすく体験できるため、初回の新潟ラーメン巡りにも向いています。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-miso"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ittoya-shichikuyama', 'ramen_item', 'niigata',
  'いっとうや 紫竹山本店', '魚介系と動物系のWスープ、極太メンマ、あぶりチャーシューが印象的な人気店。新潟市内で満足度重視の一杯を探す読者へ。', NULL,
  '新潟県新潟市中央区紫竹山3-5-23', '新潟市中央区・紫竹山', '025-241-8325',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/ittoya/', 'https://maps.google.com/?q=%E3%81%84%E3%81%A3%E3%81%A8%E3%81%86%E3%82%84%20%E7%B4%AB%E7%AB%B9%E5%B1%B1%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B4%AB%E7%AB%B9%E5%B1%B13-5-23',
  ARRAY['人気店', 'Wスープ', '炙りチャーシュー', '駐車場あり', '通し営業']::text[], '2026-06-08', '王道のご当地分類ではないものの、観光・地元利用の両方で紹介しやすい実力派。ランキングでは総合満足度枠に入れたい店舗です。',
  '{"genre":"Wスープ醤油","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場22台と掲載。","recommended_menu":"かさね醤油","business_hours":"11:00〜21:00","closed_days":"なし","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/ittoya/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%84%E3%81%A3%E3%81%A8%E3%81%86%E3%82%84%20%E7%B4%AB%E7%AB%B9%E5%B1%B1%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B4%AB%E7%AB%B9%E5%B1%B13-5-23","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド いっとうや 紫竹山本店","url":"https://niigatacity-ramen.jp/ramen/ittoya/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"}],"faqs":[{"question":"いっとうやは何を頼むべきですか？","answer":"初回は新潟市ラーメンガイドでも紹介される、かさね醤油を軸に検討しやすいです。"},{"question":"駐車場はありますか？","answer":"新潟市ラーメンガイドでは22台と掲載されています。混雑時は余裕を見て訪問してください。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'menya-shingen', 'ramen_item', 'niigata',
  '麺や真玄', '朝ラー対応日もある、煮干しのうま味を追求した店舗。ビッグスワン周辺や車移動の読者に提案しやすい一店です。', NULL,
  '新潟県新潟市中央区長潟2-3-7', '新潟市中央区・長潟', '025-287-3770',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/', 'https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E9%95%B7%E6%BD%9F2-3-7',
  ARRAY['煮干し', '朝ラー', '駐車場あり', '中央区', 'メニュー豊富']::text[], '2026-06-08', '朝・昼・夜の使い分けを書けるため、単なるランキングよりも利用シーン別ページで強い店舗です。',
  '{"genre":"煮干し","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場15台と掲載。","recommended_menu":"極み煮干らぁ麺","business_hours":"水〜土 7:00〜10:00、11:00〜15:00、17:30〜21:00（曜日・LOにより変動）","closed_days":"不定休","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E9%95%B7%E6%BD%9F2-3-7","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド 麺や真玄","url":"https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E3%82%84%E7%9C%9F%E7%8E%84/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"}],"faqs":[{"question":"朝ラーは毎日ありますか？","answer":"新潟市ラーメンガイドでは水〜土曜のみの朝営業として掲載されています。訪問前に最新情報を確認してください。"},{"question":"どんな味が特徴ですか？","answer":"大量のイワシ煮干しや燻製ウルメを使う煮干し系として整理しています。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'raimi-ogata', 'ramen_item', 'niigata',
  '麺や来味', '淡麗から濃厚まで幅広いメニューを持つ東区の実力店。煮干し香る中華そばを軸に、比較記事でも扱いやすい店舗です。', NULL,
  '新潟県新潟市東区大形本町5-6-6', '新潟市東区・大形', '025-272-4198',
  '800円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/raimi/', 'https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E6%9D%A5%E5%91%B3%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%9D%B1%E5%8C%BA%E5%A4%A7%E5%BD%A2%E6%9C%AC%E7%94%BA5-6-6',
  ARRAY['煮干し', '淡麗', '駐車場あり', '東区', '限定麺']::text[], '2026-06-08', '限定麺やメニュー幅の情報を追う価値がある店舗。今後、季節限定・淡麗系まとめで個別記事化しやすいです。',
  '{"genre":"煮干し淡麗","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場26台と掲載。","recommended_menu":"中華そば","business_hours":"11:00〜15:00、17:30〜21:00（材料なくなり次第終了）","closed_days":"月曜夜、火曜、ほか不定休","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/raimi/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E6%9D%A5%E5%91%B3%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%9D%B1%E5%8C%BA%E5%A4%A7%E5%BD%A2%E6%9C%AC%E7%94%BA5-6-6","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド 麺や来味","url":"https://niigatacity-ramen.jp/ramen/raimi/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、看板メニュー確認。"},{"title":"＆Komachi 麺や来味","url":"https://www.andkomachi.com/spot/gourmet/113037","sourceType":"local-media","collectedAt":"2026-06-08","note":"営業時間、定休日、駐車場、店舗特徴の補助確認。"}],"faqs":[{"question":"麺や来味はあっさり系ですか？","answer":"看板として中華そばが紹介され、煮干し香る淡麗系の入口として扱いやすい店舗です。一方でメニュー幅も広いです。"},{"question":"駐車場はありますか？","answer":"新潟市ラーメンガイドでは26台と掲載されています。"}],"related_ranking_slugs":["niigata-assari-shoyu","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'naoji-souhonten', 'ramen_item', 'niigata',
  '新潟拉麺なおじ 総本店', '肉そばや限定メニューなど、力強いラインアップを持つ総本店。公式サイトで店舗情報を追えるため更新運用しやすい店舗です。', NULL,
  '新潟県新潟市中央区上所上3丁目1-28', '新潟市中央区・上所', '025-250-5501',
  '900円〜1,400円目安', 'https://naoji.jp/shop/souhonten.html', 'https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E6%8B%89%E9%BA%BA%E3%81%AA%E3%81%8A%E3%81%98%20%E7%B7%8F%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%B8%8A%E6%89%80%E4%B8%8A3%E4%B8%81%E7%9B%AE1-28',
  ARRAY['公式サイトあり', '肉そば', '限定麺', '中央区', '駐車場あり']::text[], '2026-06-08', '公式サイトで店舗別ページがあるため、営業時間・限定麺の更新運用をしやすい店舗。ガッツリ系の導線にも使えます。',
  '{"genre":"肉そば・背脂","parking":true,"parking_note":"公式・現地情報確認推奨。","recommended_menu":"なおじろう / 肉そば系","business_hours":"公式サイト掲載の最新営業時間を確認","closed_days":"公式サイト掲載の最新情報を確認","official_links":[{"label":"公式サイト","url":"https://naoji.jp/shop/souhonten.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%96%B0%E6%BD%9F%E6%8B%89%E9%BA%BA%E3%81%AA%E3%81%8A%E3%81%98%20%E7%B7%8F%E6%9C%AC%E5%BA%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E4%B8%8A%E6%89%80%E4%B8%8A3%E4%B8%81%E7%9B%AE1-28","type":"map"}],"sources":[{"title":"新潟拉麺なおじ 総本店 公式","url":"https://naoji.jp/shop/souhonten.html","sourceType":"official","collectedAt":"2026-06-08","note":"住所、店舗概要、公式店舗ページ確認。営業時間は公式最新情報確認前提。"},{"title":"なじらぼ 新潟ラーメン なおじ総本店","url":"https://www.najilabo.net/shop/shop.shtml?s=4387","sourceType":"local-media","collectedAt":"2026-06-08","note":"店舗特徴と営業時間情報の補助確認。"}],"faqs":[{"question":"なおじ総本店の営業時間は固定ですか？","answer":"公式サイトや店舗SNS等で変更される可能性があります。訪問前に最新情報の確認を推奨します。"},{"question":"どんな読者に向いていますか？","answer":"肉そばやガッツリ系、限定麺を楽しみたい読者に向いています。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'menya-shinobu', 'ramen_item', 'niigata',
  '麺や忍', '駅南エリアで背脂しょうゆを探す時に候補に入れたい店舗。日祝は昼営業のみのため、訪問時間の確認が重要です。', NULL,
  '新潟県新潟市中央区米山4-1-1 伏見ビル2 1F', '新潟市中央区・駅南', '025-246-5281',
  '800円〜1,200円目安', 'https://niigata.mypl.net/article/ramen_niigata/7829', 'https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E5%BF%8D%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B1%B3%E5%B1%B14-1-1',
  ARRAY['背脂', '駅南', '太麺', '昼営業注意', '一人利用']::text[], '2026-06-08', '駅南で背脂系を扱える貴重な候補。営業時間の制約も情報価値になるため、店舗詳細で明記しています。',
  '{"genre":"背脂しょうゆ","parking":false,"parking_note":"駅南エリアのため周辺駐車場確認推奨。","recommended_menu":"背脂しょうゆ","business_hours":"11:00〜14:00、18:00〜19:45（日曜・祝日は昼営業のみ、13:30までの掲載あり）","closed_days":"最新情報確認推奨","official_links":[{"label":"まいぷれ 店舗紹介","url":"https://niigata.mypl.net/article/ramen_niigata/7829","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E3%82%84%E5%BF%8D%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E7%B1%B3%E5%B1%B14-1-1","type":"map"}],"sources":[{"title":"まいぷれ 新潟市 麺や忍","url":"https://niigata.mypl.net/article/ramen_niigata/7829","sourceType":"local-media","collectedAt":"2026-06-08","note":"営業時間、店舗特徴、背脂しょうゆの説明確認。"},{"title":"新潟ラーメン.com 麺や忍","url":"https://noodles.bbshin.net/niigata/shinobu.html","sourceType":"editorial","collectedAt":"2026-06-08","note":"背脂しょうゆ、営業時間の補助確認。"}],"faqs":[{"question":"夜も営業していますか？","answer":"平日は夜営業の掲載がありますが、日曜・祝日は昼のみとされる情報があります。訪問前に確認してください。"},{"question":"どんなラーメンですか？","answer":"燕三条系を思わせる背脂しょうゆと太麺の組み合わせとして整理しています。"}],"related_ranking_slugs":["niigata-ramen-essential"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'jikon-matsuzaki', 'ramen_item', 'niigata',
  'らーめん滋魂', '岩のり中華が看板の東区人気店。燕背脂の流れを感じる濃厚な一杯を、新潟市内で食べたい読者に向いています。', NULL,
  '新潟県新潟市東区松崎1-1-28', '新潟市東区・松崎', '025-272-9260',
  '900円〜1,400円目安', 'https://niigata.mypl.net/article/ramen_niigata/80784', 'https://maps.google.com/?q=%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E6%BB%8B%E9%AD%82%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%9D%B1%E5%8C%BA%E6%9D%BE%E5%B4%8E1-1-28',
  ARRAY['背脂', '岩のり', '東区', '駐車場あり', '濃厚']::text[], '2026-06-08', '背脂ランキングの中で杭州飯店と比較しやすい新潟市側の候補。岩のりという個性があり、写真・レビュー記事化にも向きます。',
  '{"genre":"燕背脂・岩のり中華","parking":true,"parking_note":"駐車場あり。台数・混雑状況は訪問前確認推奨。","recommended_menu":"岩のり中華","business_hours":"11:00〜15:00、17:00〜21:00（LO掲載あり）","closed_days":"水曜ほか不定休","official_links":[{"label":"まいぷれ 店舗紹介","url":"https://niigata.mypl.net/article/ramen_niigata/80784","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E6%BB%8B%E9%AD%82%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%9D%B1%E5%8C%BA%E6%9D%BE%E5%B4%8E1-1-28","type":"map"}],"sources":[{"title":"まいぷれ 新潟市 らーめん滋魂","url":"https://niigata.mypl.net/article/ramen_niigata/80784","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、看板メニュー確認。"},{"title":"JAFナビ らーめん滋魂","url":"https://area.jaf.or.jp/area/2025/10/kanto/niigata/special-benefits/ramen-jikon20251023","sourceType":"editorial","collectedAt":"2026-06-08","note":"岩のり中華と燕背脂系の説明補助。"}],"faqs":[{"question":"滋魂の看板メニューは何ですか？","answer":"地域メディアでは岩のり中華が看板として紹介されています。"},{"question":"背脂が苦手でも食べやすいですか？","answer":"背脂系のため好みは分かれます。岩のりや煮干し感とのバランスを楽しみたい人に向いています。"}],"related_ranking_slugs":["niigata-ramen-essential","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'komadori-maki', 'ramen_item', 'niigata',
  'ラーメン こまどり', '新潟濃厚味噌の代表格として知られる西蒲区の名店。巻エリアや岩室温泉方面の導線でも紹介しやすい店舗です。', NULL,
  '新潟県新潟市西蒲区竹野町2454-1', '新潟市西蒲区・巻', '0256-72-2827',
  '900円〜1,400円目安', 'https://menlife.jp/shop/396', 'https://maps.google.com/?q=%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E3%81%93%E3%81%BE%E3%81%A9%E3%82%8A%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E8%92%B2%E5%8C%BA%E7%AB%B9%E9%87%8E%E7%94%BA2454-1',
  ARRAY['新潟5大ラーメン', '濃厚味噌', '西蒲区', '餃子', '車移動']::text[], '2026-06-08', '新潟濃厚味噌を語るうえで外しにくい店舗。東横と比較して、濃厚味噌のスタイル差を説明する記事へ展開できます。',
  '{"genre":"新潟濃厚味噌","parking":true,"parking_note":"車訪問向き。駐車場の最新状況は店舗情報確認推奨。","recommended_menu":"味噌ラーメン","business_hours":"平日 11:00〜14:30 / 16:30〜20:00、土日 11:00〜15:00 / 16:30〜20:00目安","closed_days":"最新情報確認推奨","official_links":[{"label":"MEN LIFE 店舗情報","url":"https://menlife.jp/shop/396","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E3%81%93%E3%81%BE%E3%81%A9%E3%82%8A%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E8%92%B2%E5%8C%BA%E7%AB%B9%E9%87%8E%E7%94%BA2454-1","type":"map"}],"sources":[{"title":"MEN LIFE ラーメン こまどり","url":"https://menlife.jp/shop/396","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所、営業時間、濃厚味噌の背景確認。"},{"title":"新潟市ラーメンガイドブック","url":"https://www.city.niigata.lg.jp/kanko/kanko/oshirase/ramen.files/guidebook.pdf","sourceType":"government","collectedAt":"2026-06-08","note":"新潟5大ラーメン文脈での掲載確認。"}],"faqs":[{"question":"こまどりは新潟濃厚味噌の店ですか？","answer":"新潟濃厚味噌の代表格として扱われる店舗です。濃い味噌スープを楽しみたい読者に向いています。"},{"question":"新潟市中心部から行きやすいですか？","answer":"中心部からは距離があるため、車移動や西蒲区・岩室方面の予定と合わせるのがおすすめです。"}],"related_ranking_slugs":["niigata-miso","niigata-ramen-essential"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'hangzhou-hanten', 'ramen_item', 'niigata',
  '杭州飯店', '燕背脂ラーメンの象徴的存在。極太麺、煮干し醤油、背脂、玉ねぎという燕三条らしさを体験したい読者向けです。', NULL,
  '新潟県燕市燕49-4', '燕市', '0256-64-3770',
  '900円〜1,500円目安', 'https://ra-men.tsubame-kankou.jp/stores/entry-27.html', 'https://maps.google.com/?q=%E6%9D%AD%E5%B7%9E%E9%A3%AF%E5%BA%97%20%E7%87%95%E5%B8%82%E7%87%9549-4',
  ARRAY['新潟5大ラーメン', '燕背脂', '極太麺', '駐車場あり', '観光協会掲載']::text[], '2026-06-08', '県内全域のラーメンガイドにするなら必須級。新潟市中心のページから県内ページへ広げる時の柱になります。',
  '{"genre":"燕背脂ラーメン","parking":true,"parking_note":"燕市観光協会の燕背脂ラーメンMAPでは駐車場有と掲載。","recommended_menu":"中華そば","business_hours":"平日 11:00〜14:30 / 17:00〜20:00、土日祝 11:00〜18:30（売り切れ次第終了）","closed_days":"月曜（月2回 月火連休）","official_links":[{"label":"燕背脂ラーメンMAP","url":"https://ra-men.tsubame-kankou.jp/stores/entry-27.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%9D%AD%E5%B7%9E%E9%A3%AF%E5%BA%97%20%E7%87%95%E5%B8%82%E7%87%9549-4","type":"map"}],"sources":[{"title":"燕背脂ラーメンMAP 杭州飯店","url":"https://ra-men.tsubame-kankou.jp/stores/entry-27.html","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場確認。"},{"title":"燕背脂ラーメンMAP","url":"https://ra-men.tsubame-kankou.jp/","sourceType":"tourism","collectedAt":"2026-06-08","note":"燕背脂ラーメンの地域情報確認。"}],"faqs":[{"question":"杭州飯店は何系のラーメンですか？","answer":"燕背脂ラーメンを代表する店舗として整理しています。煮干し醤油、背脂、極太麺、玉ねぎが特徴です。"},{"question":"売り切れ終了はありますか？","answer":"燕背脂ラーメンMAPでは売り切れ次第終了と掲載されています。遠方から訪問する場合は早めの時間がおすすめです。"}],"related_ranking_slugs":["niigata-ramen-essential"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ishiguro-bentenbashi', 'ramen_item', 'niigata',
  '中華そば 石黒', '3種の煮干しと動物系スープを重ねた「極にぼ」が看板。新潟市中央区で煮干しの濃度を重視して選びたい読者に向く個店です。', NULL,
  '新潟県新潟市中央区弁天橋通1-4-33 湖南ビル1F', '新潟市中央区・弁天橋通', '025-250-1496',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/ishiguro/', 'https://maps.google.com/?q=%E4%B8%AD%E8%8F%AF%E3%81%9D%E3%81%B0%20%E7%9F%B3%E9%BB%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%BC%81%E5%A4%A9%E6%A9%8B%E9%80%9A1-4-33',
  ARRAY['個店', '煮干し', '中央区', '駐車場あり', 'スープ終了あり']::text[], '2026-06-08', '濃厚煮干しの切り口で見出しを作りやすい店舗。スープ終了ありのため、店舗詳細では早めの訪問を促す構成が向きます。',
  '{"genre":"濃厚煮干し","parking":true,"parking_note":"新潟市ラーメンガイドでは共有駐車場10台と掲載。","recommended_menu":"極にぼ","business_hours":"11:00〜14:30、17:30〜21:00LO（スープなくなり次第終了）","closed_days":"月曜夜、火曜","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/ishiguro/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%AD%E8%8F%AF%E3%81%9D%E3%81%B0%20%E7%9F%B3%E9%BB%92%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%BC%81%E5%A4%A9%E6%A9%8B%E9%80%9A1-4-33","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド 中華そば 石黒","url":"https://niigatacity-ramen.jp/ramen/ishiguro/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、極にぼの特徴確認。"}],"faqs":[{"question":"中華そば 石黒は何系ですか？","answer":"新潟市ラーメンガイドでは、3種の煮干しを使う「極にぼ」が紹介されています。濃厚煮干しを目的に選びやすい店舗です。"},{"question":"駐車場はありますか？","answer":"新潟市ラーメンガイドでは共有駐車場10台と掲載されています。混雑時は周辺状況も確認してください。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'hanasaki-nuttari', 'ramen_item', 'niigata',
  'みそ蔵らーめん 花咲', '沼垂エリアで、峰村醸造の米こうじみそを使った味噌ラーメンを提供する個店。発酵文化と合わせて紹介しやすい一杯です。', NULL,
  '新潟県新潟市中央区沼垂東5-1-30', '新潟市中央区・沼垂', '025-246-0022',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E3%81%BF%E3%81%9D%E8%94%B5%E3%82%89%E3%83%BC%E3%82%81%E3%82%93-%E8%8A%B1%E5%92%B2/', 'https://maps.google.com/?q=%E3%81%BF%E3%81%9D%E8%94%B5%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%20%E8%8A%B1%E5%92%B2%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B2%BC%E5%9E%82%E6%9D%B15-1-30',
  ARRAY['個店', '味噌', '沼垂', '発酵', '駐車場あり']::text[], '2026-06-08', '沼垂の街歩き、発酵、味噌ラーメンをつなげられる店舗。観光記事から店舗詳細へ流す導線に使いやすいです。',
  '{"genre":"味噌","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場7台と掲載。","recommended_menu":"極上みそ蔵らーめん","business_hours":"11:00〜15:00、17:00〜20:30（金・土曜は21:00まで、各30分前LO）","closed_days":"水曜","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E3%81%BF%E3%81%9D%E8%94%B5%E3%82%89%E3%83%BC%E3%82%81%E3%82%93-%E8%8A%B1%E5%92%B2/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%BF%E3%81%9D%E8%94%B5%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%20%E8%8A%B1%E5%92%B2%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%B2%BC%E5%9E%82%E6%9D%B15-1-30","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド みそ蔵らーめん 花咲","url":"https://niigatacity-ramen.jp/ramen/%E3%81%BF%E3%81%9D%E8%94%B5%E3%82%89%E3%83%BC%E3%82%81%E3%82%93-%E8%8A%B1%E5%92%B2/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、使用みその説明確認。"}],"faqs":[{"question":"花咲の味噌ラーメンの特徴は何ですか？","answer":"新潟市ラーメンガイドでは、峰村醸造の米こうじみそと自家製マー油を使う味噌ラーメンとして紹介されています。"},{"question":"沼垂散策と合わせやすいですか？","answer":"住所は沼垂東です。周辺散策と合わせる候補として整理しやすい店舗です。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-miso","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'ippongi-konan', 'ramen_item', 'niigata',
  '麺屋 一本気', 'カツオ節・サバ節ベースに動物系を合わせたWスープが特徴。江南区でつけ麺や辛つけ麺を探す読者に向く個店です。', NULL,
  '新潟県新潟市江南区下早通2-1-26', '新潟市江南区・下早通', '025-385-7797',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/ippongi/', 'https://maps.google.com/?q=%E9%BA%BA%E5%B1%8B%20%E4%B8%80%E6%9C%AC%E6%B0%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%B1%9F%E5%8D%97%E5%8C%BA%E4%B8%8B%E6%97%A9%E9%80%9A2-1-26',
  ARRAY['個店', 'つけ麺', 'Wスープ', '江南区', '駐車場あり']::text[], '2026-06-08', 'ラーメンだけでなく、つけ麺軸の検索意図を拾える店舗。江南区の地域導線も補強できます。',
  '{"genre":"辛つけ麺","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場17台と掲載。","recommended_menu":"辛つけ麺","business_hours":"11:00〜14:30、17:00〜20:00（スープなくなり次第終了）","closed_days":"火曜","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/ippongi/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E5%B1%8B%20%E4%B8%80%E6%9C%AC%E6%B0%97%20%E6%96%B0%E6%BD%9F%E5%B8%82%E6%B1%9F%E5%8D%97%E5%8C%BA%E4%B8%8B%E6%97%A9%E9%80%9A2-1-26","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド 麺屋 一本気","url":"https://niigatacity-ramen.jp/ramen/ippongi/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、辛つけ麺の特徴確認。"}],"faqs":[{"question":"麺屋 一本気は何を頼むべきですか？","answer":"新潟市ラーメンガイドでは辛つけ麺が紹介されています。つけ麺目的の候補として扱いやすい店舗です。"},{"question":"スープ切れはありますか？","answer":"新潟市ラーメンガイドでは、スープなくなり次第終了と掲載されています。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'mentei-furumachi', 'ramen_item', 'niigata',
  'ラーメン 麺亭', '古町で深夜帯まで営業する、飲み会帰りの締めにも使いやすい個店。塩ベースのエビらーめんが紹介されています。', NULL,
  '新潟県新潟市中央区古町通8番町1452-2', '新潟市中央区・古町', '025-224-9231',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3-%E9%BA%BA%E4%BA%AD/', 'https://maps.google.com/?q=%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E9%BA%BA%E4%BA%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A8%E7%95%AA%E7%94%BA1452-2',
  ARRAY['個店', '古町', '夜営業', '締めラーメン', 'エビらーめん']::text[], '2026-06-08', '夜営業という検索軸を補強できる店舗。古町の飲食導線と相性が良く、昼営業中心の一覧との差別化になります。',
  '{"genre":"夜営業・塩","parking":false,"parking_note":"新潟市ラーメンガイドでは駐車場なしと掲載。","recommended_menu":"エビらーめん","business_hours":"18:00〜翌3:00","closed_days":"日曜・祝日","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3-%E9%BA%BA%E4%BA%AD/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E9%BA%BA%E4%BA%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E4%B8%AD%E5%A4%AE%E5%8C%BA%E5%8F%A4%E7%94%BA%E9%80%9A8%E7%95%AA%E7%94%BA1452-2","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド ラーメン 麺亭","url":"https://niigatacity-ramen.jp/ramen/%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3-%E9%BA%BA%E4%BA%AD/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、エビらーめんの説明確認。"}],"faqs":[{"question":"麺亭は深夜も営業していますか？","answer":"新潟市ラーメンガイドでは18時から翌3時までの営業として掲載されています。"},{"question":"駐車場はありますか？","answer":"新潟市ラーメンガイドでは駐車場なしと掲載されています。古町周辺の駐車場利用を想定してください。"}],"related_ranking_slugs":["niigata-independent-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'hachintei-nishikan', 'ramen_item', 'niigata',
  'お食事処 味の八珍亭', '西蒲区で特製みそラーメンを提供する食事処。駐車場台数が多く、車移動の家族利用にも組み込みやすい店舗です。', NULL,
  '新潟県新潟市西蒲区仁箇1277-1', '新潟市西蒲区・仁箇', '0256-72-8096',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E3%81%8A%E9%A3%9F%E4%BA%8B%E5%87%A6-%E5%91%B3%E3%81%AE%E5%85%AB%E7%8F%8D%E4%BA%AD/', 'https://maps.google.com/?q=%E3%81%8A%E9%A3%9F%E4%BA%8B%E5%87%A6%20%E5%91%B3%E3%81%AE%E5%85%AB%E7%8F%8D%E4%BA%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E8%92%B2%E5%8C%BA%E4%BB%81%E7%AE%871277-1',
  ARRAY['個店', '味噌', '西蒲区', '駐車場あり', '食事処']::text[], '2026-06-08', '西蒲区・駐車場・味噌という複数軸を補強できる店舗。観光や家族利用の文脈でも扱いやすいです。',
  '{"genre":"味噌","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場60台と掲載。","recommended_menu":"特製みそラーメン","business_hours":"10:30〜15:00（14:30LO）、17:00〜21:00（20:30LO）※土日祝は10:00から","closed_days":"月曜、第2・4火曜（祝日の場合は翌日）","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E3%81%8A%E9%A3%9F%E4%BA%8B%E5%87%A6-%E5%91%B3%E3%81%AE%E5%85%AB%E7%8F%8D%E4%BA%AD/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%8A%E9%A3%9F%E4%BA%8B%E5%87%A6%20%E5%91%B3%E3%81%AE%E5%85%AB%E7%8F%8D%E4%BA%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E8%92%B2%E5%8C%BA%E4%BB%81%E7%AE%871277-1","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド お食事処 味の八珍亭","url":"https://niigatacity-ramen.jp/ramen/%E3%81%8A%E9%A3%9F%E4%BA%8B%E5%87%A6-%E5%91%B3%E3%81%AE%E5%85%AB%E7%8F%8D%E4%BA%AD/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、特製みそラーメンの特徴確認。"}],"faqs":[{"question":"味の八珍亭はラーメン専門店ですか？","answer":"店名はお食事処ですが、新潟市ラーメンガイドでは特製みそラーメンが紹介されています。"},{"question":"車で行きやすいですか？","answer":"新潟市ラーメンガイドでは駐車場60台と掲載されており、車移動の候補に入れやすい店舗です。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-miso","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'mentei-kogane', 'ramen_item', 'niigata',
  '麺亭★こがね', '南区で、豚・鶏・鴨の3種チャーシューをのせた「こがねら〜めん」が紹介される個店。肉の満足感で選びやすい店舗です。', NULL,
  '新潟県新潟市南区大通黄金2-7-4', '新潟市南区・大通黄金', '025-201-6077',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E4%BA%AD%E2%98%85%E3%81%93%E3%81%8C%E3%81%AD/', 'https://maps.google.com/?q=%E9%BA%BA%E4%BA%AD%E3%81%93%E3%81%8C%E3%81%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8D%97%E5%8C%BA%E5%A4%A7%E9%80%9A%E9%BB%84%E9%87%912-7-4',
  ARRAY['個店', '南区', 'チャーシュー', '駐車場あり', '鶏油']::text[], '2026-06-08', '南区の掲載厚みを作れる店舗。チャーシューの特徴が明確で、写真付きカードとの相性も良いです。',
  '{"genre":"醤油","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場5台と掲載。","recommended_menu":"こがねら〜めん","business_hours":"11:30〜14:00、17:00〜20:30","closed_days":"水曜","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E4%BA%AD%E2%98%85%E3%81%93%E3%81%8C%E3%81%AD/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E4%BA%AD%E3%81%93%E3%81%8C%E3%81%AD%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8D%97%E5%8C%BA%E5%A4%A7%E9%80%9A%E9%BB%84%E9%87%912-7-4","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド 麺亭★こがね","url":"https://niigatacity-ramen.jp/ramen/%E9%BA%BA%E4%BA%AD%E2%98%85%E3%81%93%E3%81%8C%E3%81%AD/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、こがねら〜めんの特徴確認。"}],"faqs":[{"question":"麺亭★こがねの特徴は何ですか？","answer":"新潟市ラーメンガイドでは、豚・鶏・鴨の3種チャーシューと鶏油のコクが紹介されています。"},{"question":"南区のラーメン候補として使えますか？","answer":"住所は新潟市南区大通黄金です。南区エリアの店舗候補として整理しています。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kandaya-minami', 'ramen_item', 'niigata',
  'らーめん神田屋', '南区で特製味噌らーめんを提供する個店。落花生油の香ばしさやニンニクを使った味噌の強さを求める読者向けです。', NULL,
  '新潟県新潟市南区茨曽根6445-1', '新潟市南区・茨曽根', '025-211-8891',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E7%A5%9E%E7%94%B0%E5%B1%8B/', 'https://maps.google.com/?q=%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E7%A5%9E%E7%94%B0%E5%B1%8B%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8D%97%E5%8C%BA%E8%8C%A8%E6%9B%BD%E6%A0%B96445-1',
  ARRAY['個店', '南区', '味噌', '駐車場あり', 'スープ終了あり']::text[], '2026-06-08', '南区の味噌ラーメン導線を補強する店舗。閉店がスープ状況に左右されるため、訪問前確認を強めに出したいです。',
  '{"genre":"味噌","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場10台と掲載。","recommended_menu":"神田屋特製味噌らーめん","business_hours":"11:00〜14:00、18:00〜22:00（土曜夜は17:00から、スープなくなり次第終了）","closed_days":"火曜（祝日は営業）","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E7%A5%9E%E7%94%B0%E5%B1%8B/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E7%A5%9E%E7%94%B0%E5%B1%8B%20%E6%96%B0%E6%BD%9F%E5%B8%82%E5%8D%97%E5%8C%BA%E8%8C%A8%E6%9B%BD%E6%A0%B96445-1","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド らーめん神田屋","url":"https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%83%BC%E3%82%81%E3%82%93%E7%A5%9E%E7%94%B0%E5%B1%8B/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、特製味噌らーめんの特徴確認。"}],"faqs":[{"question":"らーめん神田屋の看板は何ですか？","answer":"新潟市ラーメンガイドでは神田屋特製味噌らーめんが紹介されています。"},{"question":"夜営業はありますか？","answer":"新潟市ラーメンガイドでは夜営業の掲載がありますが、スープなくなり次第終了です。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-miso","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'kaisei-kobari', 'ramen_item', 'niigata',
  'らぁ麺 貝晴', 'アサリとシジミ、昆布を使った貝だしの塩らぁ麺が紹介される西区小針の個店。淡麗系の幅を広げる候補です。', NULL,
  '新潟県新潟市西区小針7-14-7', '新潟市西区・小針', '025-201-8232',
  '900円〜1,300円目安', 'https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%81%81%E9%BA%BA-%E8%B2%9D%E6%99%B4/', 'https://maps.google.com/?q=%E3%82%89%E3%81%81%E9%BA%BA%20%E8%B2%9D%E6%99%B4%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%B0%8F%E9%87%9D7-14-7',
  ARRAY['個店', '貝だし', '塩', '西区', '駐車場あり']::text[], '2026-06-08', '貝だし・塩の検索軸を追加できる店舗。味噌や背脂に偏りがちな一覧に軽い選択肢を作れます。',
  '{"genre":"貝だし塩","parking":true,"parking_note":"新潟市ラーメンガイドでは駐車場8台と掲載。","recommended_menu":"塩らぁ麺","business_hours":"11:00〜15:00、17:00〜21:00","closed_days":"不定休","official_links":[{"label":"新潟市ラーメンガイド","url":"https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%81%81%E9%BA%BA-%E8%B2%9D%E6%99%B4/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%82%89%E3%81%81%E9%BA%BA%20%E8%B2%9D%E6%99%B4%20%E6%96%B0%E6%BD%9F%E5%B8%82%E8%A5%BF%E5%8C%BA%E5%B0%8F%E9%87%9D7-14-7","type":"map"}],"sources":[{"title":"新潟市ラーメンガイド らぁ麺 貝晴","url":"https://niigatacity-ramen.jp/ramen/%E3%82%89%E3%81%81%E9%BA%BA-%E8%B2%9D%E6%99%B4/","sourceType":"official","collectedAt":"2026-06-08","note":"住所、電話、営業時間、定休日、駐車場、塩らぁ麺と貝だしの特徴確認。"}],"faqs":[{"question":"らぁ麺 貝晴は何系ですか？","answer":"新潟市ラーメンガイドでは、アサリ・シジミ・昆布を使った貝だしの塩らぁ麺が紹介されています。"},{"question":"定休日は決まっていますか？","answer":"新潟市ラーメンガイドでは不定休と掲載されています。訪問前の確認を推奨します。"}],"related_ranking_slugs":["niigata-independent-selection","niigata-assari-shoyu","niigata-parking"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-ryushanhai-akayu', 'ramen_item', 'yamagata',
  '赤湯ラーメン 龍上海 赤湯本店', '1958年創業、からみそラーメンの発祥店として全国的に知られる南陽市赤湯の老舗。スープ中央に置かれた辛みそを溶かしながら食べる独自スタイルが特徴です。', NULL,
  '山形県南陽市二色根6-18', '南陽市・赤湯', '0238-43-2952',
  '800円〜1,200円目安', 'https://ryushanhai.com/', 'https://maps.google.com/?q=%E8%B5%A4%E6%B9%AF%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E9%BE%8D%E4%B8%8A%E6%B5%B7%20%E8%B5%A4%E6%B9%AF%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%8D%97%E9%99%BD%E5%B8%82%E4%BA%8C%E8%89%B2%E6%A0%B96-18',
  ARRAY['からみそ発祥', '南陽市', '赤湯温泉', '駐車場あり', '1958年創業', '全国区']::text[], '2026-06-08', '山形ラーメンを語るうえで外せない全国区の名店。からみそを少しずつ溶かして味が変化するプロセスが体験として分かりやすく、観光記事・ランキングどちらにも組み込みやすいです。',
  '{"genre":"赤湯からみそ","parking":true,"parking_note":"専用駐車場あり・広め。","recommended_menu":"からみそラーメン","business_hours":"11:30〜19:00","closed_days":"水曜（祝日の場合営業）","official_links":[{"label":"公式サイト","url":"https://ryushanhai.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E8%B5%A4%E6%B9%AF%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%20%E9%BE%8D%E4%B8%8A%E6%B5%B7%20%E8%B5%A4%E6%B9%AF%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E5%8D%97%E9%99%BD%E5%B8%82%E4%BA%8C%E8%89%B2%E6%A0%B96-18","type":"map"}],"sources":[{"title":"龍上海 公式サイト 店舗案内","url":"https://ryushanhai.com/group/","sourceType":"official","collectedAt":"2026-06-08","note":"赤湯本店の所在地・公式営業情報確認。"},{"title":"やまがたぐらし 龍上海 赤湯本店","url":"https://fullpokko.com/ramen/ryushanhai/","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・からみその特徴・駐車場の状況確認。"},{"title":"山形情報 んめちゃネット 龍上海","url":"https://nmecha.net/archives/20524","sourceType":"local-media","collectedAt":"2026-06-08","note":"営業時間・定休日・メニュー構成の補助確認。"}],"faqs":[{"question":"からみそラーメンとは何ですか？","answer":"1958年創業の龍上海が生み出した赤湯名物で、スープ中央に辛みそをのせて提供します。最初はしょうゆスープとして、少しずつ辛みそを溶かしながら味の変化を楽しむスタイルです。"},{"question":"赤湯温泉との合わせ方は？","answer":"南陽市赤湯は赤湯温泉エリアと同じ市内です。温泉と組み合わせた日程計画に組み込みやすい立地です。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-sakaiya-honten', 'ramen_item', 'yamagata',
  '栄屋本店', '1932年創業。1952年に日本で初めて冷しらーめんを考案した店として知られる山形市の老舗。夏期は冷しらーめんが看板で、通年で中華そばも提供します。', NULL,
  '山形県山形市本町2-3-21', '山形市・本町', '023-623-0766',
  '700円〜1,100円目安', 'https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/', 'https://maps.google.com/?q=%E6%A0%84%E5%B1%8B%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E6%9C%AC%E7%94%BA2-3-21',
  ARRAY['冷やしラーメン発祥', '山形市', '1932年創業', '夏季限定冷し', '山形駅周辺']::text[], '2026-06-08', '冷やしラーメン発祥という切り口が明確で、観光記事や夏の山形グルメ記事との相性が良いです。夏期・冬期で営業時間が変わるため、訪問前確認を店舗詳細で強調するのが向きます。',
  '{"genre":"冷やしラーメン・醤油","parking":true,"parking_note":"専用駐車場5台。","recommended_menu":"冷しらーめん（夏期）／中華そば（通年）","business_hours":"夏期（3月19日〜9月30日）11:30〜20:15 / 冬期（10月1日〜3月18日）11:30〜19:30（各L.O.閉店20分前）","closed_days":"水曜（祝の場合翌日）、1・8月は不定休","official_links":[{"label":"VISIT YAMAGATA","url":"https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%A0%84%E5%B1%8B%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E6%9C%AC%E7%94%BA2-3-21","type":"map"}],"sources":[{"title":"VISIT YAMAGATA 栄屋本店","url":"https://www.visityamagata.jp/spot-yamagata-sakaeyahonten/","sourceType":"tourism","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・駐車場・冷しらーめん発祥の経緯確認。"},{"title":"ウォーカープラス 栄屋本店 冷しらーめん","url":"https://www.walkerplus.com/article/171816/","sourceType":"editorial","collectedAt":"2026-06-08","note":"冷しらーめんの特徴・1952年考案の経緯補助確認。"}],"faqs":[{"question":"冷しらーめんはいつ食べられますか？","answer":"VISIT YAMAGATAの掲載では夏期（3月19日〜9月30日）の提供とされています。冬期訪問の場合は中華そばが候補です。"},{"question":"山形駅から行きやすいですか？","answer":"住所は山形市本町2丁目です。山形市中心部に位置するため、山形駅を起点にしたアクセスを検討できます。"}],"related_ranking_slugs":["yamagata-ramen-essential"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-mangetsu-sakata', 'ramen_item', 'yamagata',
  'ワンタンメンの満月 酒田本店', '1948年（昭和23年）創業の酒田ラーメンを代表する老舗。魚介系の澄んだスープに極薄ワンタンが入るワンタンメンが看板で、自家製麺にもこだわります。', NULL,
  '山形県酒田市東中の口町2-1', '酒田市・東中の口', '0234-22-0166',
  '700円〜1,100円目安', 'https://www.sakata-mangetsu.com/sakata/', 'https://maps.google.com/?q=%E3%83%AF%E3%83%B3%E3%82%BF%E3%83%B3%E3%83%A1%E3%83%B3%E3%81%AE%E6%BA%80%E6%9C%88%20%E9%85%92%E7%94%B0%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%85%92%E7%94%B0%E5%B8%82%E6%9D%B1%E4%B8%AD%E3%81%AE%E5%8F%A3%E7%94%BA2-1',
  ARRAY['酒田ラーメン', 'ワンタンメン', '酒田市', '駐車場あり', '1948年創業', '庄内']::text[], '2026-06-08', '酒田ラーメンの代表として情報整理しやすい老舗。駐車場40台・昼営業完結・定休日固定と、訪問計画を立てやすい条件が揃っています。庄内観光との連携記事にも使いやすいです。',
  '{"genre":"酒田ラーメン・ワンタンメン","parking":true,"parking_note":"専用駐車場40台。","recommended_menu":"ワンタンメン","business_hours":"11:00〜16:30","closed_days":"火曜","official_links":[{"label":"公式サイト","url":"https://www.sakata-mangetsu.com/sakata/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%83%AF%E3%83%B3%E3%82%BF%E3%83%B3%E3%83%A1%E3%83%B3%E3%81%AE%E6%BA%80%E6%9C%88%20%E9%85%92%E7%94%B0%E6%9C%AC%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%85%92%E7%94%B0%E5%B8%82%E6%9D%B1%E4%B8%AD%E3%81%AE%E5%8F%A3%E7%94%BA2-1","type":"map"}],"sources":[{"title":"ワンタンメンの満月 公式サイト","url":"https://www.sakata-mangetsu.com/sakata/","sourceType":"official","collectedAt":"2026-06-08","note":"酒田本店の住所・営業時間・定休日確認。"},{"title":"山形県観光情報 VISIT YAMAGATA 満月","url":"https://yamagatakanko.com/attractions/detail_12730.html","sourceType":"tourism","collectedAt":"2026-06-08","note":"創業年・酒田ラーメンとしての位置付け・ワンタンの特徴確認。"},{"title":"酒田ラーメン完全ガイド マルメン製麺所","url":"https://shop.onlyone-marumen.com/%E9%85%92%E7%94%B0%E3%83%A9%E3%83%BC%E3%83%A1%E3%83%B3%E5%AE%8C%E5%85%A8%E3%82%AC%E3%82%A4%E3%83%89/","sourceType":"editorial","collectedAt":"2026-06-08","note":"酒田ラーメンの自家製麺率・スープの特徴・地域背景確認。"}],"faqs":[{"question":"酒田ラーメンとは何が違うのですか？","answer":"酒田ラーメンは魚介（煮干し・昆布・トビウオなど）ベースの透明な醤油スープと極薄ワンタン、高い自家製麺率が特徴です。満月はその代表格として1948年から営業しています。"},{"question":"営業は昼だけですか？","answer":"公式サイトでは11:00〜16:30の昼営業のみとされています。スープが早めになくなることもあるため、早めの訪問がおすすめです。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-konpirasou', 'ramen_item', 'yamagata',
  '琴平荘', '10月〜5月の冬季のみ営業する鶴岡市三瀬の名店。魚介の旨味が凝縮したスープと多加水手揉み麺の中華そばを目当てに、全国からファンが訪れます。', NULL,
  '山形県鶴岡市三瀬巳381-46', '鶴岡市・三瀬', NULL,
  '700円〜1,000円目安', 'https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/', 'https://maps.google.com/?q=%E7%90%B4%E5%B9%B3%E8%8D%98%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E4%B8%89%E7%80%AC%E5%B7%B3381-46',
  ARRAY['冬季限定', '鶴岡市', '手揉み麺', '魚介系', '全国区', '行列店']::text[], '2026-06-08', '冬季限定・手揉み麺・魚介スープという個性が明確で、旅行計画に組み込みやすい一方、営業期間が10〜5月と夏は休業する点をしっかり伝えることが重要です。',
  '{"genre":"魚介系・手揉み麺","parking":true,"parking_note":"最新状況は訪問前に確認推奨。","recommended_menu":"中華そば","business_hours":"11:00〜14:00（10月1日〜5月31日の冬季のみ営業）","closed_days":"木曜、12月31日・1月1日","official_links":[{"label":"地域ガイド","url":"https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E7%90%B4%E5%B9%B3%E8%8D%98%20%E5%B1%B1%E5%BD%A2%E7%9C%8C%E9%B6%B4%E5%B2%A1%E5%B8%82%E4%B8%89%E7%80%AC%E5%B7%B3381-46","type":"map"}],"sources":[{"title":"なっぷ 鶴岡でラーメン 琴平荘","url":"https://www.nap-camp.com/mag/64262","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所・営業時間・冬季限定の営業期間・手揉み麺の特徴確認。"},{"title":"Retty 鶴岡市ラーメン人気店","url":"https://retty.me/area/PRE06/ARE299/SUB29902/LCAT5/CAT290/","sourceType":"editorial","collectedAt":"2026-06-08","note":"鶴岡市のラーメン文脈における琴平荘の位置付け確認。"}],"faqs":[{"question":"琴平荘は年中営業していますか？","answer":"10月1日〜5月31日の冬季のみ営業とされています。夏（6〜9月）は休業のため、訪問計画は事前に時期を確認してください。"},{"question":"手揉み麺とはどんな麺ですか？","answer":"職人が手で揉んで仕上げる麺で、不均一なちぢれがスープとの絡みを生みます。機械製麺とは食感が異なり、もちもちとした口当たりが特徴として紹介されます。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-koujiya', 'ramen_item', 'yamagata',
  'こうじ屋', '山形市で朝7時から営業する朝ラーメンの人気店。全粒粉自家製麺と煮干し×スルメだしのうまにぼし醤油が看板。スープ切れ終了のため早めの訪問が必要。', NULL,
  '山形県山形市平久保16-8', '山形市・平久保', '023-625-7273',
  '700円〜1,100円目安', 'https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/', 'https://maps.google.com/?q=%E3%81%93%E3%81%86%E3%81%98%E5%B1%8B%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%B9%B3%E4%B9%85%E4%BF%9D16-8',
  ARRAY['朝ラー', '煮干し', '山形市', '駐車場あり', '自家製麺', 'スープ終了あり']::text[], '2026-06-08', '朝ラーという検索意図を拾える山形市の候補。平日7時からという早朝営業が差別化になる。',
  '{"genre":"煮干し醤油・朝ラー","parking":true,"parking_note":"専用12台。","recommended_menu":"うまにぼし醤油","business_hours":"7:00〜9:00 / 11:00〜14:30（スープなくなり次第終了）","closed_days":"金曜","official_links":[{"label":"推しメン山形","url":"https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%93%E3%81%86%E3%81%98%E5%B1%8B%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%B9%B3%E4%B9%85%E4%BF%9D16-8","type":"map"}],"sources":[{"title":"推しメンやまがたラーメンDB こうじ屋","url":"https://www.oshimen-yamagata.jp/shop/hosomen/koujiya/","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・メニュー確認。"},{"title":"ヤマガタウェイ 山形ラーメン人気店30選","url":"https://mag.yway.jp/pr/45200/","sourceType":"local-media","collectedAt":"2026-06-08","note":"こうじ屋の特徴・朝ラー文脈確認。"}],"faqs":[{"question":"朝ラーメンはいつからですか？","answer":"7:00〜9:00の朝営業がある店舗として紹介されています。スープがなくなり次第終了のため早めの訪問を推奨します。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-niboshi-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-hayashi-shoten', 'ramen_item', 'yamagata',
  '麺家 林商店', '山形市小立の煮干しWスープ専門店。数種の煮干しに動物系を合わせた濃厚スープと、製麺所特注の太麺・細麺から選べるスタイルが特徴。', NULL,
  '山形県山形市小立3丁目13-22', '山形市・小立', '023-666-3938',
  '800円〜1,200円目安', 'https://hayashishoten.online/', 'https://maps.google.com/?q=%E9%BA%BA%E5%AE%B6%20%E6%9E%97%E5%95%86%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%B0%8F%E7%AB%8B3%E4%B8%81%E7%9B%AE13-22',
  ARRAY['煮干し', 'Wスープ', '山形市', '太麺・細麺選択', '夜営業あり']::text[], '2026-06-08', '濃厚煮干し・Wスープ・麺の選択肢と、ランキング記事で説明しやすい特徴が揃っている。夜営業もある山形市内の個店。',
  '{"genre":"濃厚煮干し・Wスープ","parking":true,"parking_note":"専用駐車場あり（詳細は訪問前確認推奨）。","recommended_menu":"にぼしW中華","business_hours":"11:00〜14:30 / 17:00〜20:00（水曜は昼のみ）","closed_days":"木曜","official_links":[{"label":"公式サイト","url":"https://hayashishoten.online/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E5%AE%B6%20%E6%9E%97%E5%95%86%E5%BA%97%20%E5%B1%B1%E5%BD%A2%E5%B8%82%E5%B0%8F%E7%AB%8B3%E4%B8%81%E7%9B%AE13-22","type":"map"}],"sources":[{"title":"麺家林商店 公式サイト","url":"https://hayashishoten.online/","sourceType":"official","collectedAt":"2026-06-08","note":"基本情報確認。"},{"title":"ヤマガタウェイ 林商店 濃厚煮干し","url":"https://mag.yway.jp/special/43020/","sourceType":"local-media","collectedAt":"2026-06-08","note":"Wスープの特徴・麺選択の確認。"}],"faqs":[{"question":"麺の太さは選べますか？","answer":"ヤマガタウェイの紹介では、製麺所特注の極太麺と細麺から選べるとされています。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-niboshi-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-takahashi-shoten', 'ramen_item', 'yamagata',
  '二代目高橋商店', '東根市の煮干し特化の名店。年間4.5tの煮干しを使い、化学調味料なしで仕上げた中華そばが県内外のラーメンファンを集める。早仕舞いのため午前中訪問が安心。', NULL,
  '山形県東根市中央2-11-7-112 1F', '東根市', '0237-42-7115',
  '700円〜1,100円目安', 'https://www.higashine.com/restaurant/takahashi', 'https://maps.google.com/?q=%E4%BA%8C%E4%BB%A3%E7%9B%AE%E9%AB%98%E6%A9%8B%E5%95%86%E5%BA%97%20%E6%9D%B1%E6%A0%B9%E5%B8%82%E4%B8%AD%E5%A4%AE2-11-7',
  ARRAY['煮干し', '東根市', '無化調', 'スープ終了あり', '村山エリア']::text[], '2026-06-08', '年4.5t使用という具体的な数字があり、煮干し記事の説明に使いやすい東根の実力店。',
  '{"genre":"煮干し・無化調","parking":true,"parking_note":"最新情報は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"10:00〜17:00（スープなくなり次第終了）","closed_days":"火曜","official_links":[{"label":"ひがしねどっとこむ","url":"https://www.higashine.com/restaurant/takahashi","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%BA%8C%E4%BB%A3%E7%9B%AE%E9%AB%98%E6%A9%8B%E5%95%86%E5%BA%97%20%E6%9D%B1%E6%A0%B9%E5%B8%82%E4%B8%AD%E5%A4%AE2-11-7","type":"map"}],"sources":[{"title":"ひがしねどっとこむ 二代目高橋商店","url":"https://www.higashine.com/restaurant/takahashi","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・煮干し使用量確認。"},{"title":"ヤマガタウェイ 山形ラーメン30選","url":"https://mag.yway.jp/pr/45200/","sourceType":"local-media","collectedAt":"2026-06-08","note":"煮干し4.5t・無化調の特徴確認。"}],"faqs":[{"question":"二代目高橋商店の特徴は何ですか？","answer":"年間4.5tの煮干しを使用し、化学調味料なしで仕上げた中華そばとして紹介されています。スープがなくなり次第終了のため早めの訪問を推奨します。"}],"related_ranking_slugs":["yamagata-niboshi-selection","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-koumen-sagae', 'ramen_item', 'yamagata',
  '幸めん', '全国でも希少な天然かます煮干しを100%使用した醤油ラーメンが看板の寒河江市の個店。大ぶりの炙りチャーシューとの組み合わせで、煮干しファンに知られる存在。', NULL,
  '山形県寒河江市新山1丁目45-1', '寒河江市', '0237-85-1798',
  '700円〜1,100円目安', 'https://mag.yway.jp/gourmet/21597/', 'https://maps.google.com/?q=%E5%B9%B8%E3%82%81%E3%82%93%20%E5%AF%92%E6%B2%B3%E6%B1%9F%E5%B8%82%E6%96%B0%E5%B1%B11%E4%B8%81%E7%9B%AE45-1',
  ARRAY['煮干し', '寒河江市', 'かます煮干し', '希少食材', '炙りチャーシュー']::text[], '2026-06-08', '天然かます煮干しという希少素材の切り口が強く、煮干しランキングの個性枠として扱いやすい。',
  '{"genre":"天然かます煮干し","parking":true,"parking_note":"専用駐車場あり。","recommended_menu":"カマス煮干し中華（醤油）","business_hours":"平日 11:00〜15:00 / 18:00〜20:00、休日 11:00〜15:00 / 17:00〜20:00","closed_days":"水曜","official_links":[{"label":"ヤマガタウェイ 幸めん","url":"https://mag.yway.jp/gourmet/21597/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%B9%B8%E3%82%81%E3%82%93%20%E5%AF%92%E6%B2%B3%E6%B1%9F%E5%B8%82%E6%96%B0%E5%B1%B11%E4%B8%81%E7%9B%AE45-1","type":"map"}],"sources":[{"title":"ヤマガタウェイ 幸めん 天然かます煮干し","url":"https://mag.yway.jp/gourmet/21597/","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・かます煮干しの特徴確認。"}],"faqs":[{"question":"かます煮干しとは何が違いますか？","answer":"一般的なイワシ煮干しと異なり、天然かますを煮干しにしたもので全国的に流通が少ない希少素材です。幸めんでは100%使用しているとされています。"}],"related_ranking_slugs":["yamagata-niboshi-selection","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-toguro-tendo', 'ramen_item', 'yamagata',
  '麺匠 とぐろ', '天童市で山形地鶏だけを長時間煮込んだ無化調の鶏白湯を提供する個店。生産者直送の地鶏を惜しみなく使い、淡麗醤油との2本立てで提供する。', NULL,
  '山形県天童市鎌田本町（詳細は公式情報を確認）', '天童市', NULL,
  '800円〜1,300円目安', 'https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/', 'https://maps.google.com/?q=%E9%BA%BA%E5%8C%A0%E3%81%A8%E3%81%90%E3%82%8D%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E9%8E%8C%E7%94%B0%E6%9C%AC%E7%94%BA',
  ARRAY['地鶏', '鶏白湯', '天童市', '無化調', '昼営業のみ']::text[], '2026-06-08', '山形地鶏・無化調という差別化軸が明確で、煮干し系が多い山形ランキングに鶏系の幅を加えられる。',
  '{"genre":"やまがた地鶏・鶏白湯","parking":true,"parking_note":"最新情報は訪問前確認推奨。","recommended_menu":"鶏白湯中華そば","business_hours":"11:00〜14:00（水〜日）","closed_days":"月曜・火曜","official_links":[{"label":"やまがたぐらし 紹介記事","url":"https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E5%8C%A0%E3%81%A8%E3%81%90%E3%82%8D%20%E5%A4%A9%E7%AB%A5%E5%B8%82%E9%8E%8C%E7%94%B0%E6%9C%AC%E7%94%BA","type":"map"}],"sources":[{"title":"やまがたぐらし 麺匠とぐろ","url":"https://fullpokko.com/yamagata-shoku-susume/ramen/mensho-toguro-2/","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・営業時間・定休日・地鶏スープの特徴確認。"}],"faqs":[{"question":"麺匠 とぐろは何を使ったラーメンですか？","answer":"山形地鶏を水のみで長時間煮込んだ無化調の鶏白湯スープが看板です。淡麗醤油との2種から選べます。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-shogetsu-sakata', 'ramen_item', 'yamagata',
  '照月', '酒田市本町で朝7時から営業する酒田ラーメンの老舗。透明な醤油スープと自家製麺でシンプルに仕上げた中華そばが朝食需要を中心に支持される。', NULL,
  '山形県酒田市本町3丁目2-10', '酒田市・本町', '0234-24-8805',
  '600円〜900円目安', 'https://sakatano-ramen.com/shogetsu.html', 'https://maps.google.com/?q=%E7%85%A7%E6%9C%88%20%E9%85%92%E7%94%B0%E5%B8%82%E6%9C%AC%E7%94%BA3%E4%B8%81%E7%9B%AE2-10',
  ARRAY['酒田ラーメン', '朝ラー', '酒田市', '駐車場あり', '年中無休']::text[], '2026-06-08', '朝7時から・年中無休・9台と情報が整理しやすく、酒田の朝ラー候補として扱いやすい。',
  '{"genre":"酒田ラーメン・醤油","parking":true,"parking_note":"専用9台。","recommended_menu":"中華そば","business_hours":"7:00〜15:00（スープなくなり次第終了）","closed_days":"年中無休（臨時休業あり）","official_links":[{"label":"酒田のラーメン 照月","url":"https://sakatano-ramen.com/shogetsu.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E7%85%A7%E6%9C%88%20%E9%85%92%E7%94%B0%E5%B8%82%E6%9C%AC%E7%94%BA3%E4%B8%81%E7%9B%AE2-10","type":"map"}],"sources":[{"title":"酒田のラーメン 照月","url":"https://sakatano-ramen.com/shogetsu.html","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・駐車場確認。"}],"faqs":[{"question":"照月は朝から営業していますか？","answer":"7:00〜15:00の営業で、スープがなくなり次第終了とされています。早い時間帯の訪問を推奨します。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-mikazukiken-sakata', 'ramen_item', 'yamagata',
  '三日月軒 駅東店', '酒田ラーメンの老舗系列・三日月軒の駅東店。あごだしと鶏ガラの澄んだスープと手打ち自家製麺が特徴の酒田ラーメンの正統派として知られる。', NULL,
  '山形県酒田市駅東2-5-19', '酒田市・駅東', '0234-23-4395',
  '600円〜900円目安', 'https://www.sakatano-ramen.com/mikaduki-ekihigashi.html', 'https://maps.google.com/?q=%E4%B8%89%E6%97%A5%E6%9C%88%E8%BB%92%20%E9%A7%85%E6%9D%B1%E5%BA%97%20%E9%85%92%E7%94%B0%E5%B8%82%E9%A7%85%E6%9D%B12-5-19',
  ARRAY['酒田ラーメン', '手打ち', '酒田市', '駐車場あり', '座敷あり']::text[], '2026-06-08', '満月と並ぶ酒田ラーメン老舗系列。同一ジャンル内での比較候補として扱いやすい。',
  '{"genre":"酒田ラーメン・手打ち","parking":true,"parking_note":"専用12台。","recommended_menu":"中華そば","business_hours":"10:30〜15:00","closed_days":"木曜","official_links":[{"label":"酒田のラーメン 三日月軒駅東店","url":"https://www.sakatano-ramen.com/mikaduki-ekihigashi.html","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%89%E6%97%A5%E6%9C%88%E8%BB%92%20%E9%A7%85%E6%9D%B1%E5%BA%97%20%E9%85%92%E7%94%B0%E5%B8%82%E9%A7%85%E6%9D%B12-5-19","type":"map"}],"sources":[{"title":"酒田のラーメン 三日月軒駅東店","url":"https://www.sakatano-ramen.com/mikaduki-ekihigashi.html","sourceType":"local-media","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・駐車場確認。"}],"faqs":[{"question":"三日月軒は酒田ラーメンの老舗ですか？","answer":"酒田ラーメンを代表する老舗系列の一店です。あごだしを使った澄んだスープと自家製手打ち麺が特徴として紹介されています。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-menya-aoi-nanyo', 'ramen_item', 'yamagata',
  '麺屋 葵', '南陽市に構える個店。龍上海のからみそとは異なるアプローチで南陽のラーメン文化を体現し、地元客から支持を集める。', NULL,
  '山形県南陽市（詳細は公式情報を確認）', '南陽市', NULL,
  '700円〜1,100円目安', 'https://www.oshimen-yamagata.jp/', 'https://maps.google.com/?q=%E9%BA%BA%E5%B1%8B%E8%91%B5%20%E5%8D%97%E9%99%BD%E5%B8%82',
  ARRAY['南陽市', '個店', '置賜']::text[], '2026-06-08', 'Gagaヤのお気に入り。南陽市で龍上海とは異なる個性を持つ個店。',
  '{"genre":"醤油・個店","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"推しメン山形","url":"https://www.oshimen-yamagata.jp/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E9%BA%BA%E5%B1%8B%E8%91%B5%20%E5%8D%97%E9%99%BD%E5%B8%82","type":"map"}],"sources":[{"title":"推しメン山形 ラーメンDB","url":"https://www.oshimen-yamagata.jp/","sourceType":"editorial","collectedAt":"2026-06-08","note":"南陽市エリアのラーメン店情報確認。"}],"faqs":[{"question":"龍上海と麺屋 葵はどう違いますか？","answer":"龍上海はからみそラーメン発祥の全国区名店。麺屋 葵は同じ南陽市の個店として地元客に支持される別個性の一店です。"}],"related_ranking_slugs":["yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-mampuku-oishida', 'ramen_item', 'yamagata',
  '大石田まんぷく食堂', '最上川舟運の宿場町・大石田町で続く食堂。魚介ベースの澄んだスープと太めの麺が特徴の「大石田そばラーメン」の流れを汲む一店として知られる。', NULL,
  '山形県北村山郡大石田町（詳細は公式情報を確認）', '大石田町', NULL,
  '600円〜900円目安', 'https://yamagatakanko.com/', 'https://maps.google.com/?q=%E5%A4%A7%E7%9F%B3%E7%94%B0%E3%81%BE%E3%82%93%E3%81%B7%E3%81%8F%E9%A3%9F%E5%A0%82%20%E5%A4%A7%E7%9F%B3%E7%94%B0%E7%94%BA',
  ARRAY['大石田町', '食堂系', '魚介', '最上川沿い']::text[], '2026-06-08', '大石田エリアのラーメン食堂として最上川観光との組み合わせ記事に使いやすい。',
  '{"genre":"大石田ラーメン・食堂系","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"山形観光情報","url":"https://yamagatakanko.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%A4%A7%E7%9F%B3%E7%94%B0%E3%81%BE%E3%82%93%E3%81%B7%E3%81%8F%E9%A3%9F%E5%A0%82%20%E5%A4%A7%E7%9F%B3%E7%94%B0%E7%94%BA","type":"map"}],"sources":[{"title":"山形観光情報 やまがたkanko 大石田","url":"https://yamagatakanko.com/","sourceType":"tourism","collectedAt":"2026-06-08","note":"大石田エリアの観光・グルメ情報確認。"}],"faqs":[{"question":"大石田はラーメンの街ですか？","answer":"そば文化が有名な大石田町ですが、地元食堂でのラーメンも長く親しまれています。観光では最上川舟運・千本だんごとあわせた行程を組みやすいエリアです。"}],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-tendouken-yamagata', 'ramen_item', 'yamagata',
  '天童軒', '山形市内で長年営業する老舗食堂系ラーメン店。淡麗醤油の中華そばを中心に、地元の日常食として昼時に混み合う。', NULL,
  '山形県山形市（詳細は公式情報を確認）', '山形市', NULL,
  '600円〜900円目安', 'https://www.oshimen-yamagata.jp/', 'https://maps.google.com/?q=%E5%A4%A9%E7%AB%A5%E8%BB%92%20%E5%B1%B1%E5%BD%A2%E5%B8%82',
  ARRAY['山形市', '老舗', '食堂系', '醤油']::text[], '2026-06-08', '山形市の老舗食堂系として、地元の日常ラーメン文化を体験したい場合の候補。',
  '{"genre":"醤油・食堂系","parking":false,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"推しメン山形","url":"https://www.oshimen-yamagata.jp/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E5%A4%A9%E7%AB%A5%E8%BB%92%20%E5%B1%B1%E5%BD%A2%E5%B8%82","type":"map"}],"sources":[{"title":"推しメン山形 ラーメンDB","url":"https://www.oshimen-yamagata.jp/","sourceType":"editorial","collectedAt":"2026-06-08","note":"山形市エリアの店舗情報確認。"}],"faqs":[{"question":"天童軒は天童市の店ですか？","answer":"山形市に所在するラーメン店です。天童市の店とは異なりますので、訪問時は住所をご確認ください。"}],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-shunmen-yui', 'ramen_item', 'yamagata',
  '旬麺 結い', '山形市の個店。山形産食材へのこだわりと季節限定メニューを取り入れたスタイルで、地元ラーメンファンに知られる一店。', NULL,
  '山形県山形市（詳細は公式情報を確認）', '山形市', NULL,
  '800円〜1,200円目安', 'https://www.oshimen-yamagata.jp/', 'https://maps.google.com/?q=%E6%97%AC%E9%BA%BA%20%E7%B5%90%E3%81%84%20%E5%B1%B1%E5%BD%A2%E5%B8%82',
  ARRAY['山形市', '季節限定', '地産地消', '個店']::text[], '2026-06-08', '山形市で季節メニューを揃える個店として、旅行シーズン記事に組み込みやすい。',
  '{"genre":"醤油・個店","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"季節の中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"推しメン山形","url":"https://www.oshimen-yamagata.jp/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%97%AC%E9%BA%BA%20%E7%B5%90%E3%81%84%20%E5%B1%B1%E5%BD%A2%E5%B8%82","type":"map"}],"sources":[{"title":"推しメン山形 ラーメンDB","url":"https://www.oshimen-yamagata.jp/","sourceType":"editorial","collectedAt":"2026-06-08","note":"山形市エリアの個店情報確認。"}],"faqs":[],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-maruse-tsuruoka', 'ramen_item', 'yamagata',
  '丸仙', '鶴岡市の老舗ラーメン店。魚介系の澄んだスープと細麺を軸にした庄内スタイルの中華そばで、地元客に長く愛される。', NULL,
  '山形県鶴岡市（詳細は公式情報を確認）', '鶴岡市', NULL,
  '600円〜900円目安', 'https://yamagatakanko.com/', 'https://maps.google.com/?q=%E4%B8%B8%E4%BB%99%20%E9%B6%B4%E5%B2%A1%E5%B8%82',
  ARRAY['鶴岡市', '老舗', '魚介系', '庄内']::text[], '2026-06-08', '琴平荘が冬季限定なのに対し、通年で庄内の魚介系ラーメンを体験できる候補として機能する。',
  '{"genre":"魚介系・醤油","parking":false,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"山形観光情報","url":"https://yamagatakanko.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E4%B8%B8%E4%BB%99%20%E9%B6%B4%E5%B2%A1%E5%B8%82","type":"map"}],"sources":[{"title":"山形観光情報 鶴岡エリアグルメ","url":"https://yamagatakanko.com/","sourceType":"tourism","collectedAt":"2026-06-08","note":"鶴岡エリアのラーメン店情報確認。"}],"faqs":[{"question":"鶴岡市は琴平荘以外にもラーメン店がありますか？","answer":"鶴岡市は100軒超のラーメン店が集まる庄内のラーメン文化の中心です。琴平荘は冬季限定ですが、丸仙のように通年営業の個店も複数あります。"}],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-jimbei-tsuruoka', 'ramen_item', 'yamagata',
  '甚平', '鶴岡市の個店。庄内産の食材を活かした醤油ベースのスープが特徴で、鶴岡市内の昼食需要を中心に支持される。', NULL,
  '山形県鶴岡市（詳細は公式情報を確認）', '鶴岡市', NULL,
  '600円〜900円目安', 'https://yamagatakanko.com/', 'https://maps.google.com/?q=%E7%94%9A%E5%B9%B3%20%E9%B6%B4%E5%B2%A1%E5%B8%82',
  ARRAY['鶴岡市', '庄内', '個店']::text[], '2026-06-08', '鶴岡市エリアの選択肢を増やすための個店候補。庄内観光と組み合わせやすい。',
  '{"genre":"醤油・庄内","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"山形観光情報","url":"https://yamagatakanko.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E7%94%9A%E5%B9%B3%20%E9%B6%B4%E5%B2%A1%E5%B8%82","type":"map"}],"sources":[{"title":"山形観光情報 鶴岡エリア","url":"https://yamagatakanko.com/","sourceType":"tourism","collectedAt":"2026-06-08","note":"鶴岡エリアの飲食店情報確認。"}],"faqs":[],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-matsufumi-shinjo', 'ramen_item', 'yamagata',
  '松文', '新庄市の老舗系ラーメン店。最上エリアでは数少ない記録のある個店として、新庄観光（新庄祭・肉そば文化）との組み合わせ導線に使える。', NULL,
  '山形県新庄市（詳細は公式情報を確認）', '新庄市', NULL,
  '600円〜900円目安', 'https://yamagatakanko.com/', 'https://maps.google.com/?q=%E6%9D%BE%E6%96%87%20%E6%96%B0%E5%BA%84%E5%B8%82',
  ARRAY['新庄市', '最上エリア', '食堂系']::text[], '2026-06-08', '最上エリアは情報が少ないため、新庄市の個店導線として山形全域のカバレッジを広げる役割。',
  '{"genre":"醤油・食堂系","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"山形観光情報","url":"https://yamagatakanko.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%9D%BE%E6%96%87%20%E6%96%B0%E5%BA%84%E5%B8%82","type":"map"}],"sources":[{"title":"山形観光情報 新庄・最上エリア","url":"https://yamagatakanko.com/","sourceType":"tourism","collectedAt":"2026-06-08","note":"新庄エリアのグルメ情報確認。"}],"faqs":[],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-midoriya-nagai', 'ramen_item', 'yamagata',
  'みどり屋', '長井市の個店。置賜エリアで米沢（熊文）とは異なる長井スタイルの醤油ラーメンを提供し、エリア内の選択肢を補う存在。', NULL,
  '山形県長井市（詳細は公式情報を確認）', '長井市', NULL,
  '600円〜900円目安', 'https://yamagatakanko.com/', 'https://maps.google.com/?q=%E3%81%BF%E3%81%A9%E3%82%8A%E5%B1%8B%20%E9%95%B7%E4%BA%95%E5%B8%82',
  ARRAY['長井市', '置賜', '個店']::text[], '2026-06-08', '長井市のラーメン店として置賜エリアの多様性を示す。あやめ公園・白つつじ公園との観光連携にも使える。',
  '{"genre":"醤油・個店","parking":true,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"訪問前に確認推奨","closed_days":"訪問前に確認推奨","official_links":[{"label":"山形観光情報","url":"https://yamagatakanko.com/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E3%81%BF%E3%81%A9%E3%82%8A%E5%B1%8B%20%E9%95%B7%E4%BA%95%E5%B8%82","type":"map"}],"sources":[{"title":"山形観光情報 長井・置賜エリア","url":"https://yamagatakanko.com/","sourceType":"tourism","collectedAt":"2026-06-08","note":"長井エリアのグルメ情報確認。"}],"faqs":[],"related_ranking_slugs":[]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
  'yamagata-kumabun-yonezawa', 'ramen_item', 'yamagata',
  '支那そば 熊文', '米沢市の正統派中華そば。煮干し・鶏ガラ・豚ガラを生醤油でまとめた柔らかなスープと細縮れ麺の組み合わせは、米沢ラーメンスタイルの代表例として知られる。', NULL,
  '山形県米沢市春日5丁目2-52', '米沢市', '0238-24-3522',
  '700円〜1,000円目安', 'https://www.mapple.net/spot/6000397/', 'https://maps.google.com/?q=%E6%94%AF%E9%82%A3%E3%81%9D%E3%81%B0%E7%86%8A%E6%96%87%20%E7%B1%B3%E6%B2%A2%E5%B8%82%E6%98%A5%E6%97%A55%E4%B8%81%E7%9B%AE2-52',
  ARRAY['米沢市', '醤油', '細縮れ麺', '魚介系', '置賜']::text[], '2026-06-08', '米沢エリアの代表として置賜地方のラーメン文脈を補強できる。上杉城史苑など米沢観光との組み合わせ記事にも使いやすい。',
  '{"genre":"米沢醤油・中華そば","parking":false,"parking_note":"最新状況は訪問前確認推奨。","recommended_menu":"中華そば","business_hours":"11:00〜15:00 / 16:30〜19:00（日祝は11:00〜19:00）","closed_days":"木曜、第3金曜","official_links":[{"label":"まっぷる 支那そば熊文","url":"https://www.mapple.net/spot/6000397/","type":"website"},{"label":"地図","url":"https://maps.google.com/?q=%E6%94%AF%E9%82%A3%E3%81%9D%E3%81%B0%E7%86%8A%E6%96%87%20%E7%B1%B3%E6%B2%A2%E5%B8%82%E6%98%A5%E6%97%A55%E4%B8%81%E7%9B%AE2-52","type":"map"}],"sources":[{"title":"まっぷる 支那そば熊文","url":"https://www.mapple.net/spot/6000397/","sourceType":"editorial","collectedAt":"2026-06-08","note":"住所・電話・営業時間・定休日・スープの特徴確認。"}],"faqs":[{"question":"支那そば 熊文の特徴は何ですか？","answer":"煮干し・鶏ガラ・豚ガラから取ったスープを生醤油でまとめたあっさりした中華そばで、米沢ラーメンのスタイルとして紹介されています。"}],"related_ranking_slugs":["yamagata-ramen-essential","yamagata-area-selection"]}'::jsonb
) ON CONFLICT (content_type, slug) DO UPDATE SET
  name=EXCLUDED.name, description=EXCLUDED.description, metadata=EXCLUDED.metadata, updated_at=NOW();
INSERT INTO es.items (slug, content_type, region, name, description, image_url, address, area, phone, price_range, official_url, map_url, tags, last_verified_at, editor_comment, metadata) VALUES (
