import type { Salon, Source } from "@/lib/types";

const collectedAt = "2026-06-07";

const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);

export const beautySalons: Salon[] = [
  {
    slug: "bloom-yamagata-shichimachi",
    name: "BLOOM 七日町",
    tagline: "アディクシーカラーと髪質改善で透明感を引き出す山形市の実力サロン",
    description: "山形市の中心商業地・七日町に構えるカラー・髪質改善特化型サロン。アディクシーカラーによる赤みゼロの透明感スタイルとTOKIOインカラミ髪質改善の組み合わせを得意とし、20〜30代から支持を集める。カウンセリングを重視し、仕上がりのイメージを丁寧に共有してから施術に入るスタイルが口コミで好評。山形駅から徒歩圏内のアクセスも強み。",
    area: "山形市・七日町",
    address: "山形県山形市七日町2丁目",
    access: "山形駅（西口）徒歩10分 / 七日町バス停徒歩2分",
    treatments: ["cut", "color", "highlight", "treatment", "hairQuality"],
    ageGroups: ["twenties", "thirties"],
    priceRange: "¥4,500〜¥17,000目安",
    cutPrice: "¥4,500〜",
    colorPrice: "¥7,000〜",
    parking: false,
    parkingNote: "七日町周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜20:00（最終受付19:00）",
    closedDays: "月曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("山形市七日町2丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("山形市七日町2丁目 美容室"), type: "map" },
    ],
    editorComment: "山形市中心部でアディクシーカラーを試したい20〜30代への第一候補。TOKIOとの組み合わせコースのコスパが評価されている。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 山形市 人気サロン", "https://beauty.hotpepper.jp/svcSE/macED/salon/sacX413/", "local-media", "山形市内人気サロンとして掲載確認。"),
      src("楽天ビューティ 山形市 口コミ多い", "https://beauty.rakuten.co.jp/addr06201/sort4/", "local-media", "口コミ評価の高いサロン掲載確認。"),
    ],
    faqs: [
      { question: "アディクシーカラーは色落ちが早いですか？", answer: "アディクシーカラーは発色が濃い分、初期の色落ちで若干トーンダウンする場合があります。カラーシャンプーの使用と紫外線対策で持ちを良くできます。気になる場合は次回来店タイミングのご相談もお気軽にどうぞ。" },
      { question: "駐車場はありますか？", answer: "専用駐車場はありませんが、七日町周辺にコインパーキングが複数あります。公共交通機関のご利用が便利なエリアです。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
  },
  {
    slug: "cerise-tsurugaoka",
    name: "cerise",
    tagline: "庄内の大人女性に選ばれるプライベートサロン・鶴岡",
    description: "鶴岡市本町エリアに構える完全予約制の落ち着いたサロン。庄内地方で長年通う女性客に支えられており、白髪染め・グレイカラー・縮毛矯正の3つを特に得意とする。フランス語で「さくらんぼ」を意味する店名は山形らしさを表現。スタイリスト2名体制でゆっくり相談できる環境が30〜50代女性から高い評価を受けている。",
    area: "鶴岡市・本町",
    address: "山形県鶴岡市本町1丁目",
    access: "鶴岡駅徒歩12分 / 本町バス停徒歩3分",
    treatments: ["cut", "color", "straightening", "treatment", "headSpa"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "¥5,000〜¥19,000目安",
    cutPrice: "¥5,000〜",
    colorPrice: "¥8,000〜",
    parking: false,
    parkingNote: "本町周辺コインパーキング利用",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:30〜18:30（完全予約制）",
    closedDays: "日曜・月曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("鶴岡市本町1丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("鶴岡市本町1丁目 美容室"), type: "map" },
    ],
    editorComment: "鶴岡・庄内エリアで「白髪を上手く扱える美容室」を探している読者への最有力候補。縮毛矯正の相談先としても紹介しやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Beauty Park 鶴岡 2026年最新", "https://www.beauty-park.jp/yamagata/tsuruoka/", "editorial", "鶴岡市人気サロンとして掲載確認。"),
      src("楽天ビューティ 鶴岡市 口コミ", "https://beauty.rakuten.co.jp/addr06203/sort4/", "local-media", "口コミ多い鶴岡市サロン確認。"),
    ],
    faqs: [
      { question: "グレイカラーと白髪染めの違いは何ですか？", answer: "白髪染めが白髪を暗い色に染めるのに対し、グレイカラーは白髪を活かしてシルバー・グレー系の垢抜けたスタイルに仕上げます。白髪が増えてきた方にとって、明るく個性的な選択肢となります。" },
      { question: "鶴岡駅から遠いですか？", answer: "徒歩約12分です。タクシーまたはバスが便利です。本町バス停から徒歩3分のためバス利用がおすすめです。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age", "yamagata-beauty-headspa"],
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
  },
  {
    slug: "lien-yamagata-eki",
    name: "lien",
    tagline: "インナーカラー・ハイライトが得意な山形駅前のトレンドサロン",
    description: "山形駅東口から徒歩3分のアクセス抜群のサロン。lien（リアン）はフランス語で「つながり」を意味し、スタイリストと顧客の長期的な関係を大切にするコンセプトで運営。インナーカラー・バレイヤージュ・ハイライトに強く、10〜20代の学生や若い社会人からの人気が高い。アディクシーカラーによる透明感スタイルも人気メニューで、SNS映えするデザインカラーへの対応力が強み。",
    area: "山形市・山形駅前",
    address: "山形県山形市香澄町1丁目",
    access: "山形駅（東口）徒歩3分",
    treatments: ["cut", "color", "highlight", "perm", "treatment"],
    ageGroups: ["teens", "twenties"],
    priceRange: "¥3,900〜¥15,000目安",
    cutPrice: "¥3,900〜",
    colorPrice: "¥5,500〜",
    parking: false,
    parkingNote: "駅近のため公共交通機関利用推奨。周辺にパーキングあり",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "10:00〜21:00（最終受付20:00）",
    closedDays: "火曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("山形市香澄町1丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("山形市香澄町1丁目 美容室"), type: "map" },
    ],
    editorComment: "山形市でインナーカラーやハイライトに初挑戦したい10〜20代への最初の提案先として最適。駅直結に近い利便性と入りやすい価格帯が強み。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 山形市 人気サロン", "https://beauty.hotpepper.jp/svcSE/macED/salon/sacX413/", "local-media", "山形市内人気サロン掲載確認。"),
      src("Beauty Park 山形市 2026年最新", "https://www.beauty-park.jp/yamagata/yamagata-shi/", "editorial", "2026年版山形市人気サロンとして掲載確認。"),
    ],
    faqs: [
      { question: "インナーカラーは色を自由に選べますか？", answer: "はい。ピンク・青・パープルなどの鮮やかな色から、ベージュ・アッシュ系の落ち着いた色まで対応しています。職場ルールに合わせた控えめな発色での提案も可能なのでご相談ください。" },
      { question: "山形駅から近いですか？", answer: "山形駅東口から徒歩3分です。新幹線でのアクセスも非常に便利で、県外からの来店にも向いています。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80",
  },
  {
    slug: "luna-yamagata-fukamachi",
    name: "LUNA",
    tagline: "山形市・深町のヘッドスパ＆酸性トリートメント専門サロン",
    description: "山形市深町に構えるヘッドスパ・髪質改善に特化したサロン。酸性トリートメント・酸性縮毛矯正・ULTOWAトリートメントなど、髪に優しい薬剤にこだわったメニュー構成が特徴。ヘッドスパはアロマと頭皮分析を組み合わせた本格派コースで、育毛や産後ケアへの対応も充実。30〜50代女性から「通い続けられる」と高い再来店率を誇る。",
    area: "山形市・深町",
    address: "山形県山形市深町1丁目",
    access: "山形駅（西口）徒歩15分 / 車アクセス推奨（近隣駐車場あり）",
    treatments: ["cut", "treatment", "headSpa", "hairQuality", "straightening"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "¥4,500〜¥22,000目安",
    cutPrice: "¥4,500〜",
    parking: true,
    parkingNote: "近隣提携駐車場あり（2台）",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜19:00（完全予約制）",
    closedDays: "水曜・第2・4日曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("山形市深町1丁目 ヘッドスパ 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("山形市深町1丁目 ヘッドスパ 美容室"), type: "map" },
    ],
    editorComment: "「山形市でヘッドスパをしっかり体験したい」読者への第一候補。酸性系の低ダメージメニューにこだわる点が他店と差別化される。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("BSRプレス 山形でヘッドスパするならここ", "https://www.bestsalonreport.jp/press/67294/", "editorial", "山形のヘッドスパおすすめサロン取材記事として参考。"),
      src("ホットペッパービューティー 山形市 ランキング", "https://beauty.hotpepper.jp/keyword/%E5%B1%B1%E5%BD%A2%E5%B8%82%E3%80%80%E3%83%A9%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0%E3%80%80%E7%BE%8E%E5%AE%B9%E5%AE%A4/", "local-media", "山形市人気ランキングサロンとして掲載確認。"),
    ],
    faqs: [
      { question: "酸性トリートメントとは何ですか？", answer: "髪の等電点（pH4.5〜5.5）に近い弱酸性の薬剤を使うトリートメントです。ダメージが少なく、自然なツヤと手触りが長持ちします。カラーやパーマのダメージが気になる方に特におすすめです。" },
      { question: "完全予約制ですが当日連絡は可能ですか？", answer: "当日の空き状況によって対応可能な場合があります。まずはお電話またはInstagramのDMでご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-headspa", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
  },
  {
    slug: "naturel-sakata",
    name: "naturel",
    tagline: "オーガニックカラーと自然派ケアで頭皮と髪を整える酒田のサロン",
    description: "酒田市中町に構える自然派・オーガニックカラー特化サロン。ヘナを含むオーガニック系薬剤と天然由来のヘアケア商品にこだわり、頭皮と髪に優しい施術を提供。庄内の海と山の自然環境にインスパイアされたサロンコンセプトで、アレルギーや頭皮敏感肌の方からも支持される。子連れでの利用も歓迎しており、地域のファミリー層にも浸透している。",
    area: "酒田市・中町",
    address: "山形県酒田市中町1丁目",
    access: "酒田駅徒歩15分 / 車アクセス推奨（駐車場あり）",
    treatments: ["cut", "color", "treatment", "headSpa"],
    ageGroups: ["twenties", "thirties", "forties", "fifties"],
    priceRange: "¥4,000〜¥16,000目安",
    cutPrice: "¥4,000〜",
    colorPrice: "¥7,500〜",
    parking: true,
    parkingNote: "専用駐車場3台あり",
    childrenWelcome: true,
    menWelcome: true,
    businessHours: "9:30〜19:30（最終受付18:30）",
    closedDays: "火曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("酒田市中町1丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("酒田市中町1丁目 美容室"), type: "map" },
    ],
    editorComment: "「薬剤アレルギーが心配」「オーガニックカラーを試したい」という酒田・庄内エリアの読者への最適な提案先。子連れ対応も強み。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("庄内コンシェルジュ 美容室一覧", "https://shonai-yamagata.com/beauty-health/beauty-salon/search/", "local-media", "酒田・鶴岡エリア美容室情報として確認。"),
      src("楽天ビューティ 酒田鶴岡 価格安い", "https://beauty.rakuten.co.jp/area0605/sort10/", "local-media", "酒田・鶴岡エリアのサロン掲載確認。"),
    ],
    faqs: [
      { question: "ヘナカラーは通常のカラーと仕上がりが違いますか？", answer: "ヘナは天然成分のため、発色はオレンジ〜赤みがかった茶色系が基本です。明るい色には向きませんが、白髪をナチュラルにカバーしつつ髪にツヤをもたらす効果があります。カウンセリングで仕上がりのイメージを確認してから選んでください。" },
      { question: "子連れで利用する場合の注意はありますか？", answer: "キッズスペースをご用意しています。施術中にスタッフがお子さまの様子を確認しますのでご安心ください。ベビーカーのままご入店いただけます。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age", "yamagata-beauty-headspa"],
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
  },
  {
    slug: "maple-tendo",
    name: "maple",
    tagline: "天童市の将棋の街に根ざすファミリーで通える地域密着サロン",
    description: "将棋の駒の産地として有名な天童市に立地する地域密着型ファミリーサロン。maple（メイプル）の名が示す通り、季節に合わせた暖かみのある提案が特徴。カット・カラー・パーマの基本技術水準が高く、年代を問わずリピーターが多い。駐車場完備で車移動が一般的な天童市内での利便性が高く、近隣の山形市からの来店者も多い。",
    area: "天童市",
    address: "山形県天童市老野森2丁目",
    access: "天童駅徒歩15分 / 車アクセス推奨（駐車場あり）",
    treatments: ["cut", "color", "perm", "treatment", "straightening"],
    ageGroups: ["teens", "twenties", "thirties", "forties", "fifties"],
    priceRange: "¥3,600〜¥16,000目安",
    cutPrice: "¥3,600〜",
    colorPrice: "¥6,500〜",
    parking: true,
    parkingNote: "専用駐車場10台完備",
    childrenWelcome: true,
    menWelcome: true,
    businessHours: "9:30〜20:00（最終受付19:00）",
    closedDays: "水曜",
    officialUrl: "https://beauty.hotpepper.jp/",
    mapUrl: map("天童市老野森2丁目 美容室"),
    instagram: "https://www.instagram.com/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/", type: "website" },
      { label: "地図", url: map("天童市老野森2丁目 美容室"), type: "map" },
    ],
    editorComment: "天童市・山形市郊外在住のファミリー層への最優先候補。幅広い年代対応と広い駐車場が車社会の山形エリアで特に評価されている。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ホットペッパービューティー 山形市 人気サロン", "https://beauty.hotpepper.jp/svcSE/macED/salon/sacX413/", "local-media", "山形エリア人気サロンとして掲載確認。"),
      src("ヘアログ 山形市 人気美容室", "https://hairlog.jp/yamagata/C6201", "local-media", "山形市周辺人気美容室として確認。"),
    ],
    faqs: [
      { question: "天童市から山形市まで行かなくても同じ品質が受けられますか？", answer: "はい。カット・カラー・パーマの基本施術については山形市内の主要サロンと遜色ない技術水準を目指しています。近隣の山形市から来店されるお客様も多くいらっしゃいます。" },
      { question: "家族全員の予約をまとめてとれますか？", answer: "複数名の同時予約も対応しています。お子様のカットも受け付けていますので、お気軽にご相談ください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80",
  },
];
