import type { Salon, Source } from "@/lib/types";

const collectedAt = "2026-06-08";

const src = (title: string, url: string, sourceType: Source["sourceType"], note: string): Source => ({
  title, url, sourceType, collectedAt, note,
});

const map = (q: string) => "https://maps.google.com/?q=" + encodeURIComponent(q);

export const beautySalons: Salon[] = [
  {
    slug: "rem-yamagata-2",
    name: "REM 山形2号店",
    tagline: "イルミナカラー・アディクシー・酸熱トリートメントが揃う山形市のサロン",
    description: "山形市飯田西のLa Saison Claire 101に構えるヘアサロン。イルミナカラー・アディクシーカラー・TOKIOトリートメント・酸熱トリートメントなど充実したメニューを展開し、20〜30代を中心に支持される。バス停「大学病院」から徒歩1分とアクセスも良好。ホットペッパービューティーではランキング上位に掲載される人気サロン。",
    area: "山形市・飯田西",
    address: "山形県山形市飯田西4-5-33 La Saison Claire 101",
    phone: "023-626-5133",
    access: "バス停「大学病院」徒歩1分 / 「飯田アパート前」徒歩2分 / 蔵王駅から車7分",
    treatments: ["cut", "color", "highlight", "hairQuality", "treatment"],
    ageGroups: ["twenties", "thirties"],
    priceRange: "要確認（ホットペッパービューティーで確認）",
    cutPrice: "要確認（公式サイト・予約サイトで確認）",
    parking: false,
    parkingNote: "詳細は店舗に要確認",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:00〜20:00",
    closedDays: "基本なし（年末年始・臨時休業あり）",
    officialUrl: "https://beauty.hotpepper.jp/slnH000477049/",
    mapUrl: map("山形県山形市飯田西4-5-33 La Saison Claire REM"),
    instagram: "https://www.instagram.com/rem.hairsalon/",
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000477049/", type: "website" },
      { label: "Instagram", url: "https://www.instagram.com/rem.hairsalon/", type: "instagram" },
      { label: "Google マップ", url: map("山形県山形市飯田西4-5-33 La Saison Claire REM"), type: "map" },
    ],
    editorComment: "山形市内でイルミナカラーと酸熱トリートメントを組み合わせたいカラー重視の読者への有力候補。ホットペッパービューティーのランキング常連店。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("REM 山形2号店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000477049/", "local-media", "住所・電話・営業時間・得意施術・口コミを確認。"),
      src("山形市 ランキング 美容室 ホットペッパービューティー", "https://beauty.hotpepper.jp/keyword/%E5%B1%B1%E5%BD%A2%E5%B8%82%E3%80%80%E3%83%A9%E3%83%B3%E3%82%AD%E3%83%B3%E3%82%B0%E3%80%80%E7%BE%8E%E5%AE%B9%E5%AE%A4/", "local-media", "山形市ランキング上位サロンとして掲載確認。"),
    ],
    faqs: [
      { question: "REMの場所はどこですか？", answer: "山形市飯田西4-5-33 La Saison Claire 101です。バス停「大学病院」から徒歩1分が最寄りです。電話番号は023-626-5133です。" },
      { question: "TOKIOトリートメントはカラーと同日にできますか？", answer: "多くの場合、同日施術が可能です。施術時間が長くなるため、予約時に希望をお伝えください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
  },
  {
    slug: "hair-design-buco",
    name: "HAIR DESIGN BUCO",
    tagline: "イルミナカラーとドライカットで柔らかな質感を得意とする山形市の実力店",
    description: "山形市荒楯町の国道286号沿いに立地する実力派ヘアサロン。イルミナカラーによる透明感スタイルとドライカット技術を組み合わせた柔らかなテクスチャーが特徴。ショートスタイル・ボブの再現性が高く、白髪染めにも丁寧に対応するため、30〜50代女性からの支持が厚い。店舗前に広い駐車場完備で車移動派にも便利。",
    area: "山形市・荒楯町",
    address: "山形県山形市荒楯町1-1-8",
    phone: "023-666-7487",
    access: "山形駅から車5分 / 国道286号沿い・店舗前広い駐車場あり",
    treatments: ["cut", "color", "treatment"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "カット¥4,950〜 / カット+イルミナカラー¥12,650〜",
    cutPrice: "¥4,950〜（学割あり）",
    colorPrice: "カット+イルミナカラー ¥12,650〜",
    parking: true,
    parkingNote: "店舗前に広い駐車場あり",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:30〜19:00（最終受付）",
    closedDays: "毎週月曜日",
    officialUrl: "https://hairdesign-buco.com/",
    mapUrl: map("山形県山形市荒楯町1-1-8 HAIR DESIGN BUCO"),
    officialLinks: [
      { label: "公式サイト", url: "https://hairdesign-buco.com/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000285830/", type: "website" },
      { label: "Google マップ", url: map("山形県山形市荒楯町1-1-8 HAIR DESIGN BUCO"), type: "map" },
    ],
    editorComment: "山形市でイルミナカラーと質感のあるカット技術を求める30〜50代女性への第一候補。駐車場完備で車移動でも通いやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("HAIR DESIGN BUCO 公式サイト", "https://hairdesign-buco.com/", "official", "住所・電話・営業時間・定休日・料金・駐車場を確認。"),
      src("ヘアー デザイン ブーコ ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000285830/", "local-media", "メニュー・料金・口コミを確認。"),
    ],
    faqs: [
      { question: "BUCOのカット料金はどのくらいですか？", answer: "¥4,950〜（学割あり）です。カット+イルミナカラーは¥12,650〜です。詳細メニューは公式サイト（hairdesign-buco.com）でご確認ください。" },
      { question: "白髪が気になりますが相談できますか？", answer: "はい。白髪染めのほか、白髪を活かすイルミナカラーの提案も行っています。まずはカウンセリングでご相談ください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
  },
  {
    slug: "baker-street-yamagata",
    name: "Baker Street",
    tagline: "完全予約制・カウンセリング重視の似合わせカット専門プライベートサロン",
    description: "山形市七日町2丁目に構える完全予約制のプライベートサロン。カウンセリングを徹底的に重視し、骨格・ライフスタイルに合わせた似合わせカットに特化。専用駐車場3台完備。新規様は¥3,000〜と比較的入りやすい価格設定で、七日町という中心地の立地も相まって山形市内での口コミ評価が高いサロン。",
    area: "山形市・七日町",
    address: "山形県山形市七日町2丁目7-23",
    phone: "023-665-5215",
    access: "山形駅・北山形駅から車6分 / 専用駐車場3台あり",
    treatments: ["cut", "color"],
    ageGroups: ["thirties", "forties", "fifties"],
    priceRange: "メンテナンスカット¥2,000〜 / 新規限定カット¥3,000〜",
    cutPrice: "¥2,000〜（メンテナンス） / ¥3,000〜（新規）",
    parking: true,
    parkingNote: "専用駐車場3台あり",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:00〜20:00",
    closedDays: "要確認（ホットペッパービューティーで確認）",
    officialUrl: "https://beauty.hotpepper.jp/slnH000679203/",
    mapUrl: map("山形県山形市七日町2丁目7-23 Baker Street"),
    officialLinks: [
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000679203/", type: "website" },
      { label: "Google マップ", url: map("山形県山形市七日町2丁目7-23 Baker Street"), type: "map" },
    ],
    editorComment: "「カット技術と似合わせ提案を重視したい」山形市内の30〜50代女性への提案先として有効。完全予約制のプライベート感が評価されている。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("ベイカーストリート(Baker Street) ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000679203/", "local-media", "住所・電話・営業時間・料金・口コミを確認。"),
    ],
    faqs: [
      { question: "Baker Streetは予約が必要ですか？", answer: "完全予約制です。ホットペッパービューティーまたは電話（023-665-5215）でご予約ください。" },
      { question: "初めて行く場合の料金はどのくらいですか？", answer: "新規様限定カットが¥3,000〜です。詳細はホットペッパービューティーのページでご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
  },
  {
    slug: "agu-navy-tsuruoka",
    name: "Agu hair navy 鶴岡東原店",
    tagline: "コスパと技術を両立した鶴岡市の年中無休サロン",
    description: "鶴岡市東原町の羽黒街道沿いに立地するAguヘアーネイビーの鶴岡店。カット¥2,500〜・カット+カラー¥3,900〜と庄内エリアでも入りやすい価格帯が魅力。7〜8台の駐車場完備で年中無休、夜21時まで営業しており、仕事帰りや週末でも立ち寄りやすい。10〜40代まで幅広い年代に対応し、鶴岡市内での定番サロンとして定着している。",
    area: "鶴岡市・東原",
    address: "山形県鶴岡市東原町17-28",
    phone: "0235-33-9743",
    access: "羽黒街道（県道47号線）沿い / グランドエル・サン近く / 食彩居酒屋「赤のれん」隣",
    treatments: ["cut", "color", "perm"],
    ageGroups: ["teens", "twenties", "thirties", "forties"],
    priceRange: "カット¥2,500〜 / カット+カラー¥3,900〜",
    cutPrice: "¥2,500〜",
    colorPrice: "カット+カラー ¥3,900〜",
    parking: true,
    parkingNote: "専用駐車場7〜8台あり",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "9:00〜21:00（カット最終受付20:00）",
    closedDays: "年中無休",
    officialUrl: "https://agu-hair.com/salon/2047/",
    mapUrl: map("山形県鶴岡市東原町17-28 Agu hair navy"),
    officialLinks: [
      { label: "Agu公式サイト", url: "https://agu-hair.com/salon/2047/", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000457001/", type: "website" },
      { label: "Google マップ", url: map("山形県鶴岡市東原町17-28 Agu hair navy"), type: "map" },
    ],
    editorComment: "鶴岡・庄内エリアでコスパを重視する読者への最初の提案先として使いやすい。駐車場・年中無休・夜21時まで営業の三拍子が揃っている。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("Agu hair navy 鶴岡東原店 Agu公式サイト", "https://agu-hair.com/salon/2047/", "official", "住所・電話・営業時間・駐車場・料金を確認。"),
      src("アグ ヘアー ネイビー 鶴岡東原店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000457001/", "local-media", "メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "Agu鶴岡店のカラー料金はどのくらいですか？", answer: "カット+カラーで¥3,900〜です。詳細メニューはホットペッパービューティーまたは電話（0235-33-9743）でご確認ください。" },
      { question: "駐車場はありますか？", answer: "専用駐車場が7〜8台あります。羽黒街道沿い、食彩居酒屋「赤のれん」隣が目印です。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80",
  },
  {
    slug: "earth-tsuruoka",
    name: "HAIR & MAKE EARTH 鶴岡店",
    tagline: "全国展開の実力チェーン・鶴岡市の年中無休サロン",
    description: "鶴岡市美咲町に立地するHAIR & MAKE EARTHの鶴岡店。全国に400店舗以上を展開するEARTHグループの一店として、カラー・パーマ・トリートメントなど幅広いメニューを提供。統一されたマニュアルと技術研修による安定した品質が特徴で、初めて行くサロンとして安心感がある。年中無休で営業。",
    area: "鶴岡市・美咲町",
    address: "山形県鶴岡市美咲町3-11",
    phone: "050-8884-1558",
    access: "JR鶴岡駅から車10分（徒歩46分）",
    treatments: ["cut", "color", "perm", "treatment"],
    ageGroups: ["twenties", "thirties", "forties"],
    priceRange: "要確認（公式サイト・予約サイトで確認）",
    cutPrice: "要確認（公式サイトで確認）",
    parking: false,
    parkingNote: "詳細は店舗に要確認",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "日〜木・祝: 9:00〜17:00 / 金・土: 9:00〜18:00",
    closedDays: "年中無休",
    officialUrl: "https://map.hairmake-earth.com/salon/227",
    mapUrl: map("山形県鶴岡市美咲町3-11 HAIR MAKE EARTH"),
    officialLinks: [
      { label: "EARTH公式サイト", url: "https://map.hairmake-earth.com/salon/227", type: "website" },
      { label: "Google マップ", url: map("山形県鶴岡市美咲町3-11 HAIR MAKE EARTH"), type: "map" },
    ],
    editorComment: "全国チェーンの安定した品質と年中無休の利便性が強み。「初めて行くサロンで失敗したくない」読者への鶴岡エリアの安心候補。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("HAIR & MAKE EARTH 鶴岡店 EARTH公式サイト", "https://map.hairmake-earth.com/salon/227", "official", "住所・電話・営業時間を確認。"),
      src("楽天ビューティ 酒田・鶴岡 美容室", "https://beauty.rakuten.co.jp/area0605/sort15/", "local-media", "庄内エリアの注目サロンとして掲載確認。"),
    ],
    faqs: [
      { question: "EARTHは初めてでも安心ですか？", answer: "はい。全国チェーンのため統一された施術基準があり、初めての方でも安心して利用いただけます。詳細メニューと料金はEARTH公式サイトまたは電話でご確認ください。" },
      { question: "鶴岡駅からのアクセスは？", answer: "JR鶴岡駅から車で約10分です。電話番号は050-8884-1558です。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800&q=80",
  },
  {
    slug: "earth-sakata",
    name: "HAIR & MAKE EARTH 酒田店",
    tagline: "酒田市の年中無休サロン・カラーとパーマが揃うEARTHグループ",
    description: "酒田市松原南に立地するHAIR & MAKE EARTHの酒田店。全国チェーンの安定した技術とメニューの豊富さが魅力。カラー・パーマ・カット全般に対応し、庄内エリアの酒田在住者に利用しやすい年中無休営業。電話番号は0234-25-6171で、メニューや料金の詳細は公式サイトまたは楽天ビューティーで確認できる。",
    area: "酒田市・松原南",
    address: "山形県酒田市松原南1-5",
    phone: "0234-25-6171",
    access: "要確認（公式サイトで確認）",
    treatments: ["cut", "color", "perm", "treatment"],
    ageGroups: ["twenties", "thirties", "forties"],
    priceRange: "要確認（公式サイト・予約サイトで確認）",
    cutPrice: "要確認（公式サイトで確認）",
    parking: false,
    parkingNote: "詳細は店舗に要確認",
    childrenWelcome: false,
    menWelcome: true,
    businessHours: "日〜木: 9:00〜17:00（カラー・パーマ）/ 9:00〜18:00（カット） / 金・土: 9:00〜17:00（カラー・パーマ）/ 9:00〜18:00（カット）",
    closedDays: "年中無休",
    officialUrl: "https://map.hairmake-earth.com/salon/175",
    mapUrl: map("山形県酒田市松原南1-5 HAIR MAKE EARTH"),
    officialLinks: [
      { label: "EARTH公式サイト", url: "https://map.hairmake-earth.com/salon/175", type: "website" },
      { label: "ホットペッパービューティー", url: "https://beauty.hotpepper.jp/slnH000232955/", type: "website" },
      { label: "Google マップ", url: map("山形県酒田市松原南1-5 HAIR MAKE EARTH"), type: "map" },
    ],
    editorComment: "酒田市で安定したサービスを年中無休で受けられるチェーンサロン。庄内エリア在住で「まず試してみたい」読者への入門候補として紹介しやすい。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("HAIR & MAKE EARTH 酒田店 EARTH公式サイト", "https://map.hairmake-earth.com/salon/175", "official", "住所・電話・営業時間を確認。"),
      src("アース 酒田店 ホットペッパービューティー", "https://beauty.hotpepper.jp/slnH000232955/", "local-media", "メニュー・口コミを確認。"),
    ],
    faqs: [
      { question: "酒田店の場所はどこですか？", answer: "山形県酒田市松原南1-5です。電話番号は0234-25-6171です。詳細なアクセスは公式サイトまたは電話でご確認ください。" },
      { question: "料金はどのくらいですか？", answer: "EARTH公式サイト（map.hairmake-earth.com/salon/175）またはホットペッパービューティーで最新の料金をご確認ください。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-color", "yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80",
  },
  {
    slug: "lafucona-tendo",
    name: "LAFUCONA",
    tagline: "天童市の芳賀タウン南エリアに構えるヘアサロン",
    description: "山形県天童市芳賀タウン南に立地するヘアサロン。天童市内のサロンとして地域住民に利用されている。営業時間は9:30〜18:00、定休日は毎週月曜・第3日曜。詳細メニューや料金については公式サイト（lafucona.com）でご確認ください。",
    area: "天童市・芳賀タウン南",
    address: "山形県天童市芳賀タウン南2丁目11番23号",
    phone: "023-674-9447",
    access: "要確認（公式サイトで確認）",
    treatments: ["cut", "color", "treatment"],
    ageGroups: ["twenties", "thirties", "forties"],
    priceRange: "要確認（公式サイトで確認）",
    cutPrice: "要確認（公式サイトで確認）",
    parking: false,
    parkingNote: "詳細は店舗に要確認",
    childrenWelcome: false,
    menWelcome: false,
    businessHours: "9:30〜18:00",
    closedDays: "毎週月曜日・第3日曜日",
    officialUrl: "https://lafucona.com/",
    mapUrl: map("山形県天童市芳賀タウン南2丁目11番23号 LAFUCONA"),
    officialLinks: [
      { label: "公式サイト", url: "https://lafucona.com/", type: "website" },
      { label: "Google マップ", url: map("山形県天童市芳賀タウン南2丁目11番23号 LAFUCONA"), type: "map" },
    ],
    editorComment: "天童市在住者向けの地域密着サロン。詳細メニュー・料金・特色は公式サイト（lafucona.com）または電話（023-674-9447）でご確認ください。",
    lastVerifiedAt: collectedAt,
    sources: [
      src("LAFUCONA 公式サイト", "https://lafucona.com/", "official", "住所・電話・営業時間・定休日を確認。"),
    ],
    faqs: [
      { question: "LAFUCONAの場所はどこですか？", answer: "山形県天童市芳賀タウン南2丁目11番23号です。電話番号は023-674-9447です。" },
      { question: "どのようなメニューがありますか？", answer: "詳細メニューは公式サイト（lafucona.com）でご確認ください。不明な点は電話でお問い合わせいただくのが確実です。" },
    ],
    relatedRankingSlugs: ["yamagata-beauty-by-age"],
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=800&q=80",
  },
];
